cowprotocol/cowswap

- .github/workflows/vercel.yml
I set the ENV in the project, but is not reaching to vercel. 
I don't think this will change anything, since its already an env, but let me try just in case
i need to test in staging so i will just merge
> fix: pass env to vercel

- apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts
- apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
Remove permit related feature flags
Permit is already enabled in prod, no longer need the feature flags.
Even for gnosis chain - which is currently not enabled - there's [at least one token identified as permittable](https://github.com/cowprotocol/token-lists/blob/eb1454efa1f26eecbe7d35aa1d075901c276463a/src/public/PermitInfo.100.json)
So it should be safe to enable it there as well.
Further work is still needed to fix it for other tokens, but it should be fine.
1. Permit should work as usual
> feat(permit): remove permit related feature flags

- apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
- libs/ui/src/pure/Tooltip/index.tsx
Based on suggestion from [here](https://cowservices.slack.com/archives/C0361CDG8GP/p1699018201722129?thread_ts=1699015859.603799&cid=C0361CDG8GP)
1. Open token selector
2. Look for a token with `gas-free approval` flag
3. Hover the mouse over it
> feat(permit): update gas-free flag tooltip

- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/embedDialog/utils/vanillaNoDepsExample.ts
- libs/widget-lib/docs/README.md
- libs/widget-lib/src/cowSwapWidget.ts
Fixes a small issue in the HTML vanilla example:
Also adds some style
Before:
After:
> Fix and style vanilla html

- libs/widget-lib/package.json
- libs/widget-lib/src/consts.ts
- libs/widget-react/package.json
While trying to integrate the widget in Next.js project (cow.fi) I got an error: `ReferenceError: window is not defined`.
It's because Next.js renders the code not in browser environment.
Hence, I changed code to not break when it is running on server side.
> fix(widget-lib): adjust code for server-side rendering

- apps/cowswap-frontend/src/common/pure/CurrencyArrowSeparator/index.tsx
- Hides the cow nose picker loading image when in widget mode
https://github.com/cowprotocol/cowswap/assets/31534717/a45db1cb-1276-4890-b8ea-3be68811c27b
> feat: hide nose picker loader

- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
This is very annoying bug. See the scenario bellow.
1. Open cowswap and connect to a wallet (I tested with Metamask)
2. Change network in Metamask to Mainnet
3. Copy the tab URL and close the tab
4. Open a new tab with the copied URL but replace chainId  from 1 to 100 (Gnosis chain)
5. Click to other widget menu item (Limit orders for example)
> fix: update chainId in trade state

- apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
Since the trezor is already battle-tested on prod we can remove the feature-flag for it
> chore: remove feature-flag from trezor

- apps/cowswap-frontend-e2e/src/e2e/swapMod.test.ts
- apps/cowswap-frontend/src/common/pure/ConfirmedButton/ConfirmedButton.tsx
`swapMod.ts` was enabled recently in #3189 and it's a little outdated
> test: fix failed e2e tests

- .github/workflows/ci.yml
- .github/workflows/ipfs.yml
- .github/workflows/publish.yml
- .github/workflows/vercel.yml
- .nvmrc
Just a quick test, since locally worked and v16 will be deprecated soon.
We want to get rid of this warning, and build using a more modern Node version:
It looks like it worked, the 3 apps were build correctly! 🎉
Actually, the widget and cosmos were already migrated.
Test this doesn't break anything
```bash
nvm install
nvm use
yarn 
yarn build
yarn start
```
> feat: change from node v16 to v18

- libs/common-const/src/networks.ts
DEV still uses infura despite us adding the RPC envs:
I believe the issue is related to Vite not knowing at compile time the envs that will be there because I used a dynamic env: `REACT_APP_NETWORK_URL_${chainId}`
The solution is to save the RPC values in a const:
```
const RPC_URL_ENVS: Record<SupportedChainId, string | undefined> = {
[SupportedChainId.MAINNET]: process.env.REACT_APP_NETWORK_URL_1 || undefined,
[SupportedChainId.GNOSIS_CHAIN]: process.env.REACT_APP_NETWORK_URL_100 || undefined,
[SupportedChainId.GOERLI]: process.env.REACT_APP_NETWORK_URL_5 || undefined,
}
```
Now vite can tell if `process.env.REACT_APP_NETWORK_URL_1` is in the env or not, and will replace it in the bundle
The good test will be when I merge this into develop and see if it works
> fix: fix issue with RPC env

- apps/cowswap-frontend/src/modules/orders/hooks/useSWRProdOrders.ts
While testing I noticed that my M2 Max processor sometimes freezes.
By stopping the main thread periodically I noticed that I almost always get into `CreatedInOrderBookOrdersUpdater`.
After adding a `console.log` here I saw that it gets tons of recalculations for `partOrdersFromProd`.
After some bisection on `useAsyncMemo` deps I got into `useSWRProdOrders` and here I found the cause of the problem.
So, the main problem in the fact that we always return a new array and it makes `useAsyncMemo()` recalculate everything many times.
https://github.com/cowprotocol/cowswap/assets/7122625/419e2e7f-0b7b-4372-9670-861ffdfb6624
1. I just add a `console.log` like:
```
const partOrdersFromProd = useAsyncMemo(
async () => {
console.log('TRIGGER')
...
```
Before the fix I got tons of console logs. …
> fix(twap): fix infinite loop in orders hook

- libs/tokens/src/migrations/tokensLegacyStateMigration.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1699355067687489
The old redux state of user-added tokens might be not full, so we need to add default values for all networks for it.
1. locally checkout previous release (1.48.17)
2. Open localhost and clean localStorage
3. Reload the page
4. Add a custom token only to one network (for example Mainnet)
5. Close the tab
6. Switch to 1.49 release branch
7. Open localhost again
> fix(tokens): use default value for user-added tokens migration

- apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts
There's currently a race condition that makes us to loose the `appData` passed by the host app.
The reason is, that a hook is re-rendering. Each re-render triggers an update. The update is a promise. There's no guarantee on the order in which the updates are performed.
the solution is to chain the tasks using a mutable reference to the latest promise.
One way is to try before this change (check 1 commit before). 
Load the configurator. Enable debug logs in your browser. 
Then filter for `useAppData`. you should see this:
In this PR shouldn't happen
> fix: fix race condition with widget

- apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetPalette.ts
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/embedDialog/const.ts
- libs/widget-lib/src/types.ts
- libs/widget-lib/src/urlUtils.ts
> This PR is just a proposal. I like it more, but I want to get the temperature of the squad.
I feel that in order to control the theme, is easier if we just have a single `theme` parameter.
In this PR I propose to:
- 🔪 kill `palette` parameter
- 🤩 Enhance `theme` to allow more control
Basically you would use it like this:
```ts
// Dark theme
{ theme: 'dark' }
// Light theme
{ theme: 'light' }
// Full control, based on a theme, you override some colors
{
theme: {
baseTheme: 'light',
primaryColor: '#d9258e',
screenBackground: '#ee00cd',
widgetBackground: '#b900ff',
textColor: '#b348cc',
}
}
```
it should work as before, its just, we don't have 2 properties. Just one theme
You can uncomment this to see the new colors: https://github.com/cowprotocol/cowswap/blob/simplify-theme/apps/widget-con …
> feat: simplify theme config

- apps/widget-configurator/src/app/configurator/hooks/useSyncWidgetNetwork.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1699458252970569
2. Connect a wallet
3. Changed network on the wallet side
4. Change network in the configurator UI
5. Accept network switching in the wallet
> fix(widget-configurator): switch network only when user changed in the configurator

- apps/cowswap-frontend/src/common/pure/Modal/index.tsx
- Adds rounded borders (border-radius) to the connect wallet modal. This prevents the modal from showing with hard edges.
> feat: connect wallet rounded modal

- apps/widget-configurator/src/app/analytics.ts
- apps/widget-configurator/src/app/configurator/hooks/useEmbedDialogState.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/embedDialog/index.tsx
- apps/widget-configurator/src/main.tsx
- apps/widget-configurator/src/theme/commonTypography.ts
- Adds a snackbar on click to copy embed code
https://github.com/cowprotocol/cowswap/assets/31534717/fe9da4de-a40e-4f8f-bfc9-b53d8e07a4fb
> feat: add snackbar click to copy

- apps/widget-configurator/src/app/analytics.ts
- apps/widget-configurator/src/app/configurator/hooks/useEmbedDialogState.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/styled.ts
- apps/widget-configurator/src/app/embedDialog/index.tsx
- apps/widget-configurator/src/main.tsx
- apps/widget-configurator/src/theme/commonTypography.ts
- General reiterations configurator
https://github.com/cowprotocol/cowswap/assets/31534717/0c10c06f-c7a3-4d72-910c-a94eb7615fc5
> feat: iterate on configurator

- libs/widget-lib/src/cowSwapWidget.ts
Reference: https://cowservices.slack.com/archives/C0361CDG8GP/p1699558059623669
In some cases `IframeResizer` sends a hight value that a little less than real height and it cause displaying a scrollbar for the widget. To avoid this I added a small threshold (20px) to the widget height.
2. Navigate between different pages in the widget (swap, limit, advanced, account modal, etc)
> fix(widget): add a threshold for the widget height

- .github/workflows/npm.yml
This PR removes a `yarn add nx` which was adding it "again" into our dependencies (we have it in the devDependencies)
The problems are:
- This adds another version (latest, instead of the one we have)
- This command brings also all the other dependencies does a normal `yarn install` implicitly), however it doesn't use the node_modules cache
Lastly, i took this opportunity to rename the workflow to NPM since its easier to find it. `publish` is too generic, and can be confused with our `deploy` workflow which deploys CoW Swap
CTX:
https://cowservices.slack.com/archives/C0361CDG8GP/p1699624696566869?thread_ts=1699623116.624319&cid=C0361CDG8GP
> chore: use cache when building library

- apps/cowswap-frontend/src/legacy/state/multicall.tsx
- libs/common-hooks/src/useContract.ts
- libs/widget-lib/src/urlUtils.spec.ts
In this PR I switched all multicalls to networkConnection providers. It means that we don't use a wallet provider and make requests through RPC_URLS. Ideally, we should do it only when user is connected to MevBlocker. Otherwise, we will get significant load on RPC nodes we use.
1. Open cowswap
2. Connect to a wallet with MevBlocker
> fix(balances): always use network provider for multicalls

- apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
- apps/cowswap-frontend/src/modules/permit/state/permitCacheAtom.ts
- libs/permit-utils/src/const.ts
- libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
Multiple users reported permits failing due to low insufficient fees
Also, Waymont wallet (Safe based) reported users getting permit related issues, although permit should be disabled for SC wallets
See the full investigation on https://github.com/cowprotocol/cowswap/issues/3400
Turns out a bug was introduced on 1.49.0 where pre-generated permits were added.
It did not check whether permit is enabled before returning the pre-generated info.
Thus, SC wallets were having permit hook data added to their orders.
Because of that, permits for the quote account were being executed, making the permits cheaper gas wise while quoting.
That results in real users having the insufficient fee error, given that their real order permit cost more than what was quoted.
This is in no way a 100% fix for some …
> fix(permit): disable permit for sc wallets

- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
Minor fix
Before
After
1. Load the Safe app
2. Pick as sell token one that you have balance and has no approval
3. Pick a buy token
* SWAP text should have a space after the token name
> fix: add space on approve & swap text for Safe

- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
Reported on Discord
Before
After
1. Connect wallet
2. Select native token as sell, anything other than wrapped native as buy tokens
3. Click on the `wrap` banner at the bottom
* It should not have the typo
> fix: typo on classic eth flow banner

- apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
- apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
- apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
- apps/cowswap-frontend/src/modules/permit/permit-state.drawio.svg
- apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
- libs/permit-utils/src/index.ts
This PR is a continuation of Leandro's https://github.com/cowprotocol/cowswap/pull/3411
I went through multiple rabbit holes to debug this one. 
Basically, making the story short, there was 3 issues:
- One ciclic dependency making an infinite loop
- Too many re-renders! (even if you remove the infinite loop)
- Not clearing the hooks
- Hooks is required for the quote
- Therefore: If you change the hooks, it will re-calculate the quote
- When the quote is recalculated, the "v2Trade" becomes null. This is a critical entity used to calculate the actual `sellAmount` after slippage
- Because we don't know the `sellAmount` during the quote re-calculation, we... BECOME UNSURE if our allowance is enough
- The previous code, would assume that, if we are not sure, we will add hooks (just in case!)
- …
> fix: do not send permit to quote when enough allowance

- apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
Fixes #3486
Fiat amount loader is displayed when no tokens selected in the form.
We should not display it when there is no amount.
See #3486
> fix(trade): don't display fiat value when there is no amount

- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1701858407051049
Just changed `Fees` to `Est. fees` in swap form and swap confirmation modal.
> chore: change fee label

- libs/wallet/src/constants.ts
- libs/wallet/src/web3-react/connection/walletConnectV2.tsx
- libs/wallet/src/web3-react/connectors/LedgerConnector.tsx
- package.json
- yarn.lock
Fixes #3464 
Upgrade ledger live support to WCv2 according to their migration guide https://developers.ledger.com/docs/connectivity/connect-kit/implementation#walletconnect-v2-migration-guide
1. Open the app
2. Connect with ledger
3. Select Ledger Live
* Should connect
* Should be able to trade
**Note**: I was not able to test the order placement as I don't have a ledger with me right now
> fix(wallet): fix ledger live

- package.json
- yarn.lock
There was still a dependency that might use the ledger lib.
It was only ever loaded in the Widget, though, did not affect CoW Swap UI.
https://github.com/wevm/wagmi/releases/tag/wagmi%401.4.12
1. Widget should not have the ledger connector
2. CoW Swap should not have the ledger connector
> fix(deps): upgrade wagmi version to remove ledger lib

- apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/WrappingPreview/WrapCard.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts
Fix #3421
Classic eth flow works again!
1. Select native as sell and another token as buy
2. Input the sell amount less than what you have in wrapped native
3. Click on `wrap` button at the bottom of the SWAP form 
4. Click on `wrap and swap` button at the bottom 
5. Wrap
* Should wrap
6. After wrapped, approve (if needed)
* Should approve if needed
7. Swap
* Should swap with wrapped native
> fix(classic-eth-flow): wrap no longer clears input amounts

- libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
Fixes #3466 
1. Open app, select to connect via WC
2. On iOS, open Safe app and connect to it
3. Place tx
* Should be recognized as a Safe tx and the usual stuff
> fix(wallet): recognize Safe iOS wallet name

- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
Tiny change, fixing the labels that have been bothering me forever
The label for this column used 2 verbs in different tenses.
Not that of a big deal when creation date is always in the past (limit orders), but it doesn't make sense when it can be in the future (TWAP orders)
| Before | Now |
|-|-|
| ![image](https://github.com/cowprotocol/cowswap/assets/43217/93e1eaf4-3b8b-4b7e-a76b-ed98f658d3b1) | ![image](https://github.com/cowprotocol/cowswap/assets/43217/e11b3c86-3cb3-4f0e-8402-1cf8d00fa010) |
1. Open an active Limit or TWAP order
2. Label should be updated
No other changes, that's all
> feat: replace time column labels with nouns

- libs/ui/src/pure/Button/index.tsx
Fix text color for error button
|light|dark|
|-|-|
| ![image](https://github.com/cowprotocol/cowswap/assets/43217/c39b0d10-d353-4aa7-ba7f-c0659dd8d6b3) | ![image](https://github.com/cowprotocol/cowswap/assets/43217/01c72fcc-d91e-49db-8d5f-c1e772a61e9f) |
1. Open the setting and click on expert mode
2. Fill in `confirm`
* The button text should be legible
> fix: use button text color for error button

- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx
Eth flow stepper border colors were missing.
Before
Now
1. Place and eth-flow order
* Pending steps border should be shown
> fix: eth-flow stepper missing border

- apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx
- apps/cowswap-frontend/src/legacy/theme/styled.d.ts
Before
After
1. Select unsupported token (such as AST on gchain)
* Unsupported token button should be visible with the correct text color
> fix: unsupported token button text color

- apps/cowswap-frontend/src/legacy/components/Card/index.tsx
- apps/cowswap-frontend/src/legacy/theme/components.tsx
Before
After
1. Change wallet
2. Hover over t&c
* Link is visible
> fix: terms and conditions link hover color

- apps/cowswap-frontend/src/legacy/components/Card/index.tsx
- apps/cowswap-frontend/src/legacy/theme/components.tsx
This reverts commit f91aabb1573c3e9fc514efe4bb28169a4febe922.
Revert https://github.com/cowprotocol/cowswap/pull/3538
Before:
After:
> Revert "fix: terms and conditions link hover color (#3538)"

- libs/wallet/src/web3-react/connection/injected.tsx
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1703180798915089?thread_ts=1703151865.359929&cid=C0361CDG8GP
After [the fix](https://github.com/cowprotocol/cowswap/pull/3544) we lost an ability to change network using Metamask.
1. Disconnect wallet
2. Select mainnet in CoW Swap UI
3. Select Gnosis chain in Metamask
4. Try to connect to Metamask
5. Switch network to Goerli in CoW Swap ui
> fix(wallets): send request to switch network

- apps/cowswap-frontend/src/cowSdk.ts
- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
- apps/cowswap-frontend/src/utils/orderUtils/getIsComposableCowOrder.ts
Fixes #3549 
Each order type on its own table.
Only load LIMIT on LIMIT table, only load TWAP on TWAP table.
It's tricky to identify TWAP orders not created on the same device, as the TWAP part order type is LIMIT.
This PR adds a work around relying on the appData `orderClass`.
Not 100% reliable as this is not guaranteed to be filled in.
⚠️ This PR uses PROD backend so the behaviour can be tested ⚠️ 
⚠️ dd2bb3c7ef053a1a617c551c31dc86aed9cd4534 SHOULD BE REVERTED BEFORE MERGING ⚠️ 
1. Open [this safe](https://app.safe.global/apps/open?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37)
2. Add this PR's url as a custom Safe app: https://swap-dev-git-fix-3549filter-out-twap-orders-from-limit-cowswap.vercel.app/
3. Check the limit orders tab
* It should be empty 
4. For comparison, on the …
> fix: filter out twap orders from limit

- apps/cowswap-frontend/src/common/hooks/useApproveCallback.ts
- apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
- apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
- apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/useApproveCallbackMod.ts
- apps/cowswap-frontend/src/legacy/state/enhancedTransactions/reducer.test.ts
- apps/cowswap-frontend/src/legacy/state/enhancedTransactions/reducer.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/transactionsMocks.ts
- libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts
- libs/balances-and-allowances/src/hooks/useNativeCurrencyAmount.ts
- libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
- libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
- libs/balances-and-allowances/src/hooks/useTokensAllowances.ts
- libs/balances-and-allowances/src/index.ts
- libs/balances-and-allowances/src/state/allowancesAtom.ts
- libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.ts
Fixes #3533
Once a notification with approval success appears, the trade form state should changes from "Allow CoW Swap to use your..." to "Swap/Place order"
Only for trade widgets (Swap/Limit/Twap)!
The improvement doesn't affect eth-flow.
1. Approve a token
2. Wait for green "Approve" notification
> fix(trade): update allowance immediately after approval tx mined

- apps/cowswap-frontend/src/common/hooks/featureFlags/useFeatureFlags.ts
- apps/cowswap-frontend/src/legacy/hooks/useRefetchPriceCallback.tsx
- apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
- apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
- apps/cowswap-frontend/src/modules/swap/helpers/logSwapParams.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1703156515196189
This is a follow up of fee=zero feature.
The amount from Quote API already took into account the fee amount, so we don't need to substract it again.
The only this we should do is adding/substracting slippage.
In console you can find logs with prefix '[SWAP PARAMS]'.
`[SWAP PARAMS] quote` - displays what we got from quote
`[SWAP PARAMS] amounts to sign` - displays what we are going to sign
The simpliest way how to test:
1. Set slippage to 0
2. What you sign in your wallet must be the same what you got from Quote API
3. Set slippage to 50%
4. What you sign in your wallet must be 50% from what you got from Quote API
> fix(swap): don't add/sub fee for swap orders

- apps/cowswap-frontend/src/utils/orderUtils/getOrderSurplus.ts
Matching Explorer's https://github.com/cowprotocol/explorer/pull/709
1. Check the surplus % on limit/TWAP orders
* Should match the calculation done on explorer https://github.com/cowprotocol/explorer/pull/709
> feat: update surplus percentage calculation

- apps/cowswap-frontend/src/common/hooks/useCategorizeRecentActivity.ts
- apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
- apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
- apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts
- apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
- apps/cowswap-frontend/src/legacy/state/orders/actions.ts
- apps/cowswap-frontend/src/legacy/state/orders/hooks.ts
- apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.ts
- apps/cowswap-frontend/src/legacy/state/orders/utils.ts
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/appData/types.ts
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/usePriorityTokenAddresses.ts
- apps/cowswap-frontend/src/modules/twap/hooks/useAllEmulatedOrders.ts
- apps/cowswap-frontend/src/pages/LimitOrders/index.tsx
- apps/cowswap-frontend/src/utils/orderUtils/getUiOrderType.ts
- libs/analytics/src/types.ts
Refactoring how we classify orders in the app
Introduced a new type: `UiOrderType` that's a combination of `order.orderClass` and `appData.metada.orderClass.orderClass`.
Added an utils fn that takes and order and returns the type.
Applied it to everywhere in the app where it makes sense to.
Changed a lot of things, so rather than steps I'll list what needs to be tested
1. Fee=0 SWAP orders should be displayed in Activity details (even past orders)
2. LIMIT and TWAP should be displayed in their respective sections
3. Pending SWAP, LIMIT and TWAP should be updated in the background
4. Appzi should trigger for all order types as before (different rules for SWAP than LIMIT and TWAP)
5. Market price should NOT be fetched/updated for SWAPs
6. Unfillable SWAPs should still work as before
> feat(fee=0): classify order types

- libs/permit-utils/src/const.ts
HOTFIX!!
No functional changes.
Only replacing signer PK with one without approvals to prevent users from placing orders with permit.
1. On mainnet, make sure you have no approvals for one of/all of: wstETH, USDC or DAI
2. Place a sell order of any/all of the above
* Should ask to sign the permit
* Should place successfully
* Should execute the permit once successfully traded (check the approval on revoke.cash for example)
See [this thread](https://cowservices.slack.com/archives/C036G0J90BU/p1703764369248749)
> fix(permit): replace permit signer used for quoting

- apps/cowswap-frontend/src/common/constants/common.ts
- apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
- apps/cowswap-frontend/src/modules/twap/const.ts
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/BigPartTimeWarning.tsx
- apps/cowswap-frontend/src/modules/twap/pure/CustomDeadlineSelector/index.tsx
- apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/getTwapFormState.tsx
- apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/index.tsx
- apps/cowswap-frontend/src/modules/twap/utils/deadlinePartsDisplay.ts
- apps/cowswap-frontend/src/modules/twap/utils/isPartTimeIntervalTooLong.ts
Follow up to and waterfalls into https://github.com/cowprotocol/cowswap/pull/3567
Another low hanging fruit from 2024 roadmap
TWAP orders in theory have no duration limit.
The only restriction is that each individual part can not be longer than 6 months.
This change:
1. Removes the 6 months limit for TWAP duration
2. Adds the limit for individual part duration
3. Also adds human friendly display for time in years and months (albeit not very precise...)
1. Open the app as a Safe App
2. Go to TWAP tab
3. Fill in the form and pick a custom order duration
4. Insert 9000 hours (rounding 1y up) and 2 parts
* You should be allowed to pick more than 4400 hours (rounding up 6 months)
* You should see a warning about the part time being too long
* You should not be able to place the TWAP
5. …
> feat(twap): unlimited twap deadline

- libs/permit-utils/package.json
The package must be published with Sepolia updates
> chore: bump @cowprotocol/permit-utils version

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
Fix #3060 
Warning wasn't displayed when doing a Limit order with approval bundled.
1. Open as Safe app
2. Go to limit order
3. Pick a token that needs approval as sell
4. Pick a pair, set price below market (> 5%)
* Warning should be displayed
5. Proceed to confirm screen
* Warning should require confirmation to proceed 
6. Repeat steps with non-safe wallet
* Warnings should work as usual
> fix(limit): show price impact warning for Safe App when bundling

- libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
- libs/wallet/src/web3-react/updater.ts
Initially part of https://github.com/cowprotocol/cowswap/pull/3372
Extracted only the improved Safe wallet detection as it's valuable on its own.
With this change, we rely on the existence of Safe info to detect when the wallet is a Safe.
And we detect whether the app is loaded within an iframe to tell when it's loaded as Safe App.
In the previous way, we were detecting based on wallet names, which varies by platform and was easily broken.
1. Load the app as Safe app
* Should be loaded and detected as usual
* TWAP should be enabled
2. Connect with a Safe via WC
* Should detect it's a Safe via WC
* TWAP should not be enabled
3. Do a wrap/unwrap
* Should detect the proper Safe signing phases (signers, execution, etc)
4. Repeat steps 2 and 3 with iOS app
* Should have the same result as via …
> feat(safe): rely on safeInfo and iframe detection to identify Safe wallets

- apps/cowswap-frontend/src/legacy/state/swap/reducer.ts
Fix #3523 
It was possible to create a buy order selling ETH, which is not supported at protocol level.
1. Pick any pair
2. Create a buy order
3. Replace the sell token with ETH
* The amounts should be cleared
* The buy input should not be editable
4. Play around with different combinations of buy and sell orders, buying and selling ETH and regular tokens
* Everything should work as usual
Nenad [left a note about this](https://github.com/cowprotocol/cowswap/blob/1cdfa24c6448e3ebf2c6e3c986cb5d7bfd269aa4/apps/cowswap-frontend/src/modules/trade/hooks/useSwitchTokensPlaces.ts#L16C1-L17) :)
> fix(swap): disable eth flow selling on buy orders

- libs/common-const/src/common.ts
This reverts commit c71929057442bade1684423cb01f81fb05c04143.
This change is breaking sepolia as it uses a different address than the other networks. See https://github.com/cowprotocol/cowswap/pull/3587#issuecomment-1883348974
In case there are issues locally when running, try clearing the local yarn cache and installing again:
`yarn cache clean && rm -rf node_modules && yarn`
See https://github.com/cowprotocol/cowswap/pull/3587#issuecomment-1883348974
1. Eth flow should work on all networks, including sepolia
> chore: revert "fix: hard code eth-flow contract addresses (#3587)"

- package.json
- yarn.lock
New version https://github.com/cowprotocol/ethflowcontract/releases/tag/v1.1.1-artifacts
Only change from 1.1.0 is the package.json version bump from 1.0.0 to 1.1.1
1. Ethflow should work on all networks, including sepolia
> chore: bump ethflowcontract to 1.1.1

- apps/cowswap-frontend/src/modules/permit/hooks/useGetPermitInfo.ts
- apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
- apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1704892417024459?thread_ts=1704724619.995319&cid=C0361CDG8GP
1. Changed type to `PermittableTokens | undefined` to be safe from undefined values
2. Added optional operators for atom
> fix: don't crash when permittable tokens atom doesn't contain new network

- apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts
- apps/cowswap-frontend/src/legacy/state/orders/hooks.ts
Fixes #3561 
Swap orders should show out of the market again.
Check the instructions on #3561
> fix(swap): fix swap out of market

- apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx
- libs/tokens/src/utils/tokenMapToListWithLogo.ts
Fixes #3599 
There were 2 issues with token search
1. Sorting inconsistency
Due to default browsers' sorting behaviour, the results were different when the symbols were identical.
This is the case for [StaFi](https://etherscan.io/token/0x9559Aaa82d9649C7A7b220E7c461d2E74c9a3593) and [Rocket Poll Eth](https://etherscan.io/token/0xae78736Cd615f374D3085123A210448E74Fc6393).
2. Only last match was picked
In the displayed list of matches, we picked the one matching exactly the search terms, by address or symbol.
Turns out symbol is not unique, so we were silently dropping everything but the last match.
This is the case for both tokens above, as well as [COW Protocol Token](https://etherscan.io/token/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB) and …
> fix(token-search): fix token search results

- apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
- libs/core/src/jotaiStore.ts
- libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
- libs/tokens/src/state/tokens/unsupportedTokensAtom.ts
- libs/tokens/src/state/tokens/userAddedTokensAtom.ts
- libs/tokens/src/updaters/TokensListsUpdater/index.ts
There has been a couple of app crashes since the refactor to add Sepolia, due to missing data coming from localStorage
- https://github.com/cowprotocol/cowswap/pull/3603
- https://github.com/cowprotocol/cowswap/pull/3594
- https://github.com/cowprotocol/cowswap/pull/3589
This is an attempt to prevent this from happening on any atom that depends on multiple networks and might face the same issue.
The fix is to use a new jotai storage as proposed on https://github.com/pmndrs/jotai/discussions/1357
1. Load app
* Should work as usual, no crashes
3. Insert local storage from an env without Sepolia
4. Refresh
* Should work as usual, no crashes
* Stored state should remain
One more PR exclusive feature (should be removed) is a log entry starting with `jotaiStore`
1. Filter by `jotaiStore` in the …
> fix: merge localStorage state with initial state to prevent empty states

- apps/cowswap-frontend/src/common/pure/InlineBanner/banners.tsx
- apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
- apps/cowswap-frontend/src/modules/trade/containers/SellNativeWarningBanner/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/useNavigateOnCurrencySelection.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useTradeNavigate.ts
- apps/cowswap-frontend/src/modules/trade/utils/parameterizeTradeSearch.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
Part of 2024 roadmap.
Improve sell ETH UX for limit orders.
While UX wise the ethflow contract is not usable IMO for Limit orders, the current UX is also not optimal.
When the user tries to sell ETH for anything other than WETH (a wrap), the UI silently switches it to WETH.
This PR makes it so:
1. ETH is selectable both on limit and twap
2. The trade button is disabled
3. A warning with a short explanation and the options available are displayed
Think of it as a poor's man version of the classic eth flow.
**1:** While Safe Apps could in theory do the wrap + order placement as it's available now for SWAPs on LIMIT and TWAP, it's out of the scope of this PR, mainly for a similar reason as for the ethflow contract.
While on LIMIT and TWAP the funds are NOT locked in the ethflow contract, …
> feat: sell eth warning for limit/twap

- libs/tokens/src/hooks/tokens/useSearchToken.ts
Fixes #3613 
The loading state of the token search was not case insensitive
https://github.com/cowprotocol/cowswap/assets/43217/92302fba-3c95-4cae-92fc-ca0af60b9bef
1. Open the token dropdown and enter a search string
2. Change the case of any letter
* Search should remain same as before
> fix(token-search): ignore search input case when triggering the search

- apps/explorer/src/state/network/NetworkUpdater.tsx
Fixes #3621 
Properly identify gchain network id and use the correct rpc provider (not infura).
1. Open a gchain order such as `0xf8def1173a59451d5d2d5db2f57cfabe5cfa3ad0cd6d8d63e602dc66bb1e76d35b0abe214ab7875562adee331deff0fe1912fe4265aa8bdd`
* Should load
* Other networks should load too
The code was ignoring TS and casting the SupportedChainId enum value (number) to the type itself.
In the end, this check was failing because `'100' !== 100` 
https://github.com/cowprotocol/cowswap/blob/d744c4adc595b93b55310fd5d4e57594f45d9b26/apps/explorer/src/api/web3/index.ts#L93
> fix(explorer): cast string SupportedChainId to number

- libs/tokens/src/state/tokens/favouriteTokensAtom.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1705320476117909?thread_ts=1705320166.113969&cid=C0361CDG8GP
The actual fix: #3604
The app shouldn't crash on Sepolia
> fix: don't crash when there is no fav tokens in new network

- apps/explorer/src/components/layout/GenericLayout/Footer/config.ts
Context: https://github.com/cowprotocol/cowswap/pull/3580#issuecomment-1884382996
Since Explorer migrated to monorepo we should update the link
The link should open a release page of the latest version
> fix(explorer): change link to explorer version

- apps/cowswap-frontend/src/common/containers/WalletUnsupportedNetworkBanner/index.tsx
- apps/cowswap-frontend/src/common/hooks/useUnsupportedNetworksText.tsx
- apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1705320722004659
1. Open Cowswap when Sepolia feature flag is off
2. Connect wallet and switch network to Sepolia
> fix: don't display Sepolia in supported list when it is off

- package.json
- yarn.lock
Fixing issue reported internally [here](https://cowservices.slack.com/archives/C036G0J90BU/p1705083817684659)
Essentially, [this order](https://explorer.cow.fi/orders/0xdedb65b51a6f81493f8e6e1d811b56a57297dbb6fb11716d85e646a66a5d041f85cc3c8da85612013acabe9b5d954d578860b3c165a22c43?tab=overview) displays 0 fee although the value is filled.
It was fixed in https://github.com/cowprotocol/cow-sdk/pull/197
This change simply uses cow-sdk version released with that fix.
1. Open the order `0xdedb65b51a6f81493f8e6e1d811b56a57297dbb6fb11716d85e646a66a5d041f85cc3c8da85612013acabe9b5d954d578860b3c165a22c43` in the explorer
* Fee should not be `0`
2. Play around with different orders
* Fee should be displayed as usual
> feat: update cow-sdk to 4.1.0

- apps/cowswap-frontend/src/legacy/components/swap/ConfirmSwapModal/index.tsx
- apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/index.tsx
- apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
- apps/cowswap-frontend/src/legacy/utils/prices.ts
- apps/cowswap-frontend/src/legacy/utils/trade.ts
- apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeSummary/index.tsx
- apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
- apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.tsx
- apps/cowswap-frontend/src/modules/twap/hooks/useCreateTwapOrder.ts
While testing fee=0 on staging, we realized buy order amounts were being sent without the estimated fee in the sell amount, leading to un-matchable orders due to unrealistic limit prices.
This PR addresses that and somewhat reverts https://github.com/cowprotocol/cowswap/pull/3657, as the calculation is done at another level.
I believe this was not caught as I tested it:
1. On chains where the fee is very small (gchain and goerli)
2. With high slippage to help visualize the amounts (10%)
The combination of high slippage and low fees compensated for the lack of fee in the sell amounts.
1. On mainnet, place a buy order with fee=0
* Check the max sell amount in the modal matches the signing
* Should include the fee and slippage in the sell amount
* Should show that value in the tooltip …
> fix(fee=0): buy order amounts again

- apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
- apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.test.ts
- apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.ts
- libs/common-utils/src/appzi.ts
Triggering Appzi for limit orders when:
- Order is placed (EOA)
- Order is presigned (SC)
- Order is cancelled
No changes to existing behaviour
Plus a small clean up on Appzi code which was using deprecated stuff.
Before each action, remember to remove the appzi localStorage key starting with `azat-` and refresh the page
1. Using EOA, place LIMIT order
* NPS pops up
2. Remove appzi localStorage key, refresh the page
3. Cancel order
* NPS pops up
4. Using SC wallet, place LIMIT order but don't sign it yet
* No NPS pops up
5. Sign the order
* NPS pops up
6. Remove appzi localStorage key, refresh the page
7. Cancel order
* NPS pops up
8. Existing behaviour should still work
* Placing SWAP/TWAP should not trigger NPS
* Trading SWAP (and LIMIT within 5min) should trigger NPS
* Having a SWAP …
> feat(appzi): add appzi triggers for limit orders

- libs/permit-utils/src/const.ts
HOTFIX!!
Once again, the permit signer got an approval.
This is bad because it breaks users' permit flow, if they had no approval for given token before.
This is a temporary measure.
After this I'll investigate the root cause of how the permit signer is getting approvals.
1. Make sure you have no approvals on mainnet for USDC and DAI
2. Sell USDC and DAI on mainnet
* Should be able to place the orders and get the approvals executed as usual
> fix(permit): replace permit signer account

- apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
To launch the fee=0 feature, we already have a feature flag, but we want to delivery it progressively to be able to monitor it
This PR adds a const that allows us to select the % of users we want to see affected by the feature. 
It just decides based on the wallet address
This have a effect which is, unless the user is connected, we won't show if the fee=zero is activated
We have to try it out. In principle, i don't think is a big problem, but we have to see if this becomes a bit weird UX
to test it we need to find a wallet that its "selected" to receive the feature.
You can check which of your wallets fits the criteria by running this in the console:
```js
parseInt('add-here-your-address', 16) % 100 < 10
```
If you have a wallet that matches the criteria, you can verify that once …
> feat(feeZero): deliver fee zero only to 10% of users

- apps/cowswap-frontend/src/modules/permit/state/permitCacheAtom.ts
We saw an issue with USDC quote permit approvals being too cheap, causing user permit being too expensive and prevent users from placing orders.
The puzzling part was that, the permit signer account had no USDC approvals, and it was still cheap to approve it again.
Check [the simulation](https://www.tdly.co/shared/simulation/aa95f665-2e2e-4d75-9eb9-b25c0de760cc) of one of the quote permit approvals.
Turns out, the permit was using the first account used for permit, which [had indeed USDC approvals](https://revoke.cash/address/0x9eF31A6BB1A80e58cb73A906bddFaE308978095C?chainId=1).
Reason being, even though the account was replaced because of that very problem, the localStorage cache was not cleared.
Thus anyone who used CoW Swap when that key was used can still face this issue today.
Not …
> fix(permit): invalidate static and user permit cache

- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
This issue solves the issue with fee=0 in the AB testing.
When the flag is enabled, it enables fee=0 only for 10% of users.
More concretely to users whose address return true to:
`parseInt('add-here-your-address', 16) % 100 < 10`
The AB selection works, it only delivers the feature  to 10%, however for the users that it doesn't deliver the feature, they still will see some change in the UI: the will see the `Est. fee` instead of just `Fee`
This PR fixes it.
- Enable flag
- Use a wallet that returns `true` to `parseInt('add-here-your-address', 16) % 100 < 10`, make sure the label is correct (`Est. fee`), and the fee is zero when you sign the order
- Use a wallet that returns `false` to `parseInt('add-here-your-address', 16) % 100 < 10`, make sure the label is correct (`Est. fee`), and the …
> fix: fix label for fee0

- apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/styled.ts
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/styled.ts
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/styled.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/styled.ts
- libs/tokens/src/pure/TokenLogo/index.tsx
- package.json
- yarn.lock
- Addresses https://github.com/cowprotocol/cowswap/issues/3498 
The current height of each Tokenitem is not re-calculated after the given estimated height (`const estimateSize = () => 56`)
for the Virtual list. @alfetopito @shoom3301 if possible review this PR and see if we can re-calculate the actual height of each token item container. Also on resize of the viewport (https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) would be good to detect if height changes.
As you see above the Token item for USDC stays at 56px height whereas it should be higher.
**This is what the expected result should have been:**
> feat: add tag styling for tokenlist

- apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
- apps/cowswap-frontend/src/modules/permit/hooks/usePreGeneratedPermitInfo.ts
- apps/cowswap-frontend/src/modules/permit/hooks/usePreGeneratedPermitInfoForToken.ts
- libs/permit-utils/package.json
- libs/permit-utils/src/abi/erc20.json
- libs/permit-utils/src/const.ts
- libs/permit-utils/src/index.ts
- libs/permit-utils/src/lib/checkIsCallDataAValidPermit.ts
- libs/permit-utils/src/lib/getTokenPermitInfo.ts
- libs/permit-utils/src/types.ts
- libs/permit-utils/src/utils/buildPermitCallData.ts
- libs/permit-utils/src/utils/fixTokenName.ts
- libs/permit-utils/src/utils/getEip712Domain.ts
Use [EIP-5267](https://eips.ethereum.org/EIPS/eip-5267) when available for fetching token permit info.
Revert https://github.com/cowprotocol/cowswap/commit/8f601ec5e318515337d728447b7000877199d2da before merging!!
Pre-generated permit has been disabled for testing, just so AAVE can be calculated locally.
It'll later be updated in the pre-generated doc.
1. On mainnet, pick AAVE as sell and something else as buy token
2. Clear any cached approvals by removing the localStorage key `userPermitCache:v0`
3. Proceed with the order
* Should prompt to sign
* Should place order successfully
4. Open order on explorer
* AppData should contain the prehook data
5. Sell another permittable token like DAI, USDC, COW etc
* Should work as usual
> fix(permit-utils): aave permit

- apps/cowswap-frontend/src/modules/fortune/containers/FortuneWidget/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/OrderContextMenu.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
- Solves for a scenario where the fortune cookie overlays the orders table. Preventing a user from clicking on the 3 dot ellipsis context menu. Current situation:
---
- The solution provided in this PR:
- Relocates the fortune cookie
- Adds padding so that you always have space to scroll down and see the table unobstructed
- Forces the fortune cookie to the mobile/table footer bar
https://github.com/cowprotocol/cowswap/assets/31534717/38c0149e-6c27-475b-bbef-a5cc8655d7aa
https://github.com/cowprotocol/cowswap/assets/31534717/699e566e-91d2-4586-9de2-e408bbe0789b
Tablet (960px viewport width and lower):
Mobile:
https://github.com/cowprotocol/cowswap/assets/31534717/31444190-529c-4bb7-ad4c-78ed81ec5a45
> feat: fortune cookie position fix

- apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts
- apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
- apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
- apps/cowswap-frontend/src/modules/permit/utils/appDataContainsHooks.ts
- apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useIsEoaEthFlow.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
- apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
- apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
- apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
- libs/common-utils/src/sentry.ts
- libs/wallet/src/api/types.ts
- libs/wallet/src/api/utils/getWalletType.ts
- libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
Orders that did not need permit hooks included it in their appData.
The hook included was however for the permit signer account rather than the user account.
This is bad in 2 ways:
1. User is paying for the approval unnecessarily.
2. It break the gas estimation for users trying to approve the same token later on
For a full picture of how often and how many times it happened, check [this dune query](https://dune.com/queries/3376950?category=abstraction&namespace=cow_protocol&table=trades&blockchains=ethereum)
Analyzing only the most recent cases, there are [2 approvals](https://etherscan.io/tokenapprovalchecker?search=0xce69d355dfdf13c3ead95ec1c437df5d4bac05e4)
The [first](https://etherscan.io/tx/0x5e8464cccf089aa85b6ac4a03ea53f45c31092631a305108911baa0df399c97d) approves DAI in [this …
> fix(permit): presign

- libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
Safe is integrating the Widget.
The button was not working, the reason is because we detect that the flow is `SAFE_BUNDLE_APPROVAL`, however we never get an instance of an SDK 
We don't get the SDK because the app is native! we don't have the safe provider injected.
This PR makes sure that, if we don't have the SDK, we don't enable bundling.
> Disable bundling for non safe apps

- .github/workflows/deployment.yml
- .github/workflows/vercel.yml
Currently, cannot deploy single app. 
Got this on last attempt: https://github.com/cowprotocol/cowswap/actions/runs/7641838388
Also, when both apps are published at the same time, there are race conditions causing unexpected deployment order and random failures:
The [cowswap version deployment](https://github.com/cowprotocol/cowswap/actions/runs/7742412931) deployed **barn explorer** and **staging cowswap**.
The [explorer version deployment](https://github.com/cowprotocol/cowswap/actions/runs/7742413236) deployed **barn** and **staging explorer**.
No one deployed **barn cowswap**
1. Must merge to develop in order to test it.
> ci: deploy single app per tag

- apps/cowswap-frontend/src/legacy/components/AddressInputPanel/index.tsx
- Fixes the custom recipient input field (part of issue https://github.com/cowprotocol/cowswap/issues/3522)
- It also crashed the app with broken CSS styles
> Fix custom recipient style

- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
- libs/ens/src/hooks/useENSResolver.ts
Fixes #3757
There are two fixes:
1. On the first app load, if wallet connected and wallet network doesn't match url network we should request network switching in the wallet
2. Before the fix we reset the recipient value always. But we should not do that when it set in the URL
1. All cases with network switching
- wallet connected
- wallet not connected
- change network from UI
- change network from URL
- change network from Wallet
- navigation between pages
2. Recipient value should be set if it presents in URL
3. Recipient value should be reset after page reload if it is not presented in URL
> fix: network setup and recipient resetting

- apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
continuation on #3614
Increase AB testing to 30%
to test it we need to find a wallet that its "selected" to receive the feature.
You can check which of your wallets fits the criteria by running this in the console:
```js
parseInt('add-here-your-address', 16) % 100 < 30
```
If you have a wallet that matches the criteria, you can verify that once connected, you will have the feature on.
If you struggle to find one, I can help to make a script so you get an account that fits the criteria.
> feat: increase AB testing for fee 0 to 30% of users

- apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/calculateUniqueOrderId.ts
- apps/cowswap-frontend/src/modules/swap/services/types.ts
HOTFIX!
Addresses (not very likely, but if it does might not be good) edge case for ethflow orders with order id collision.
1. EthFlow orders should work the same with and without fee=0 enabled accounts
> fix(fee=0): do not touch fee=0 ethflow fees

- apps/cowswap-frontend/src/api/gnosisProtocol/api.ts
- apps/cowswap-frontend/src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap
There is a race condition where the appDataHash can be set in a quote call without having the fullAppData.
That is a problem as backend doesn't can't tell what's the appData content unless we pass it as part of the request.
([Internal link to logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/YfMNN))
This PR makes sure that, if the fullAppData is not present, we ignore the appDataHash and use the fallback values instead.
1. Observe the quote requests in the network console
* All of them should have both `appData` with the JSON doc and `appDataHash` with its hash
> fix: do not set appDataHash unless appData is also set when quoting

- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
- apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrdersAuthMulticall.ts
Fixes #3530 #3809
#3530 issue was introduced since the last multicall refactoring (#3416), the multicall in `useTwapOrdersAuthMulticall` returns a tuple of boolean, not just boolean.
#3809 issue also came from the multicall refactoring, the `useSWR` result shouldn't be used in hook dependencies, because it causes re-rendering issues.
I also found another rerendering issue in `TwapFormWidget`, there were two callbacks not wrapped in `useCallback`.
1. See #3530
2. For developers: add a console log into `TwapOrdersUpdater` body and check that there is no tons of calls
> fix(twap): orders auth updating and rerending issues

- libs/widget-lib/src/types.ts
This PR adds a bunch of parametrization in the widget param.
They are all optional fields, and they will default to our current behaviour if not specified.
Note all settings are optional and nullable! this is to model:
- `undefined`: We use the default we had until now
- `null`: We disable it. For example, for images and sounds, would mean we need to remove the image or sound
- `actual value`: We override our default
They include:
- Define your own sounds! silly someone might want to remove or change the moooo. I would think this will only be used to make the mooooooo even louder
- Define your own images! You don't like yoga cow, you can replace it, we welcome people with no-taste for images.
- A bunch of disable or hide …
> [Widget enhancement] 03 - Param enhancement: sounds, images, and mooooore

- apps/cowswap-frontend/src/common/hooks/useCowEventEmitter.ts
- apps/cowswap-frontend/src/cow-react/index.tsx
- libs/events/src/CowEventEmitter.ts
- libs/events/src/CowEventEmitterProvider.ts
- libs/events/src/index.ts
Any component will be able to use a `CowEventEmitter` instance to send a message.
More particularly, they need to use `cowEventEmitterContext.emit(...)` function
Good question! Glad you ask. As the emitter needs to be created only once, one good way to have an instance is to expose it using a provider.
This PR adds a provider `CowEventEmitterContext` and creates a convenient hook to get the instance `useCowEventEmitter()` 
this way code is as simple as:
```ts
const eventEmitter = useCowEventEmitter()
// somewhere in your component
eventEmitter.emit(youEvent, yourPayload)
```
> [Widget enhancement] 06 - Context for eventEmitter

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
- apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
- apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useHandleSwap.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
- apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
- apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
- apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
- libs/events/src/types/events.ts
- libs/events/src/types/orders.ts
- libs/events/src/types/toastMessages.ts
- libs/widget-lib/src/types.ts
This PR start to use the `eventEmitter` in the app.
It triggers an event for when we post an order to the API.
Note that in the case of Safe flow, we want to make sure we get the transaction hash from the safe, before we post the event, just because for technical reasons we post the order to the API before the user signs/approve the order.
> [Widget enhancement] 07 - Emit post order events

- libs/widget-lib/src/IframeCowEventEmitter.ts
This PR creates `IframeCowEventEmitter` in our widget library.
This component will facilitate the bridging of events on the widget side. 
It has a local instance of the event emitter. It will be used to register all the listeners. 
This way, this component can listen to the events arriving to the window, and forward them into the listeners (with the help of the event emitter)
> [Widget enhancement] 09 - Create an iframe event emitter

- apps/widget-configurator/src/app/configurator/index.tsx
- libs/events/src/CowEventEmitter.ts
- libs/events/src/types/toastMessages.ts
- libs/widget-lib/src/cowSwapWidget.ts
- libs/widget-lib/src/index.ts
- libs/widget-react/src/lib/CowSwapWidget.tsx
So this PR is the first one I could test if all this inter-iFrame event communication was working. 
And it did!! it did too well! I was receiving every message TWICE! 👯
I saw that the cause is because the widget is redrawn at least TWICE.
One reason is because, it depends on the `provider` and the `params`. A react hook will update first with the params, and then again once the provider is ready.
As the method to create a widget (`cowSwapWidget`) returns only one `update` function which:
- deletes all content in the iFrame parent container
- creates the iFrame again
- Create all listeners and bridging logics  👈 here is where I was registering twice, once per re-draw of the widget
This is when I decided to:
- Make the …
> [Widget enhancement] 10 - Optimise widget updates

- apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
Deletes the fee-zero AB testing.
It will leave the activation decision to the feature flag, so no more checking if the wallet has it or not activated.
> fix: disable ab-testing for fee-zero. Enable flag for all users

- apps/cowswap-frontend/src/legacy/components/Header/URLWarning/URLWarningMod.tsx
- apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
- apps/widget-configurator/src/app/configurator/controls/PaletteControl.tsx
- apps/widget-configurator/src/app/configurator/index.tsx
- libs/tokens/src/hooks/tokens/useAreThereTokensWithSameSymbol.ts
1. When wallet is not connected in the widget configurator, the widget itself is not displayed
2. By clicking on "More options" the panel looks broken
3. Token selection widget looks broken
4. The top header banner appearance improvement
| Header | Header |
|--------|--------|
| <img width="580" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/2062a404-b1ec-4bd2-bed4-de27a8d2d4ef"> | <img width="533" alt="image" src="https://github.com/cowprotocol/cowswap/assets/7122625/658829cf-e239-47ab-8027-8e7352ea74bd"> | 
Each fix has a separate commit
> fix(widget): widget displaying and expanded colors panel

- apps/cowswap-frontend/src/legacy/state/orders/middleware/pendingOrderPopup.tsx
Fixes sell amount in the place order notification
1. Place SELL SWAP with zeroFee flag on
* Notification sell amount should match what's signed
2. Repeat for BUY order
* Same result
3. Repeat 1 and 2 with zeroFee flag off
* Same result
> fix: place order notification sell amount

- libs/widget-react/src/lib/CowSwapWidget.tsx
The widget connection became broken. When connecting, it was not showing 
Currently in https://dev.widget.cow.fi if you disconnect from the widget:
And then connect:
It will connect for the host app, but not the widget:
- Open configurator
- Connect,
> fix: connect wallet not working in widget mode

- apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/styled.tsx
- apps/cowswap-frontend/src/common/pure/CurrencyAmountPreview/styled.tsx
- apps/cowswap-frontend/src/common/pure/TransactionErrorContent/index.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/styled.tsx
- apps/cowswap-frontend/src/legacy/components/OrderProgressBar/styled.ts
- apps/cowswap-frontend/src/legacy/components/Popups/index.tsx
- apps/cowswap-frontend/src/legacy/components/Popups/styled.ts
- apps/cowswap-frontend/src/legacy/components/TransactionExecutedContent/index.tsx
- apps/cowswap-frontend/src/legacy/components/TransactionExecutedContent/styled.ts
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/Step.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/Row/styled.ts
- libs/snackbars/src/containers/SnackbarsWidget/index.tsx
- libs/snackbars/src/pure/SnackbarPopup/index.tsx
- Addresses: 
- https://github.com/cowprotocol/cowswap/issues/3858
- https://github.com/cowprotocol/cowswap/issues/3788
- And others
- On order progress show the Cow Runner Game button in less prominent colors (secondary button). When finished show the CLOSE button in addition.
- Made sure the Toast/Popup components (they are different components doing the same...) use the same styles. In the future this should be re-factored to use a single component.
> Misc. style fixes

- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersReceiptModal/hooks.ts
- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersReceiptModal/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
Follow up to https://github.com/cowprotocol/cowswap/pull/3845 and #3889 
Add a VERY pretty button to closed LIMIT orders receipt modal
1. Same as #3845 , except that you should trigger the modal from a LIMIT order receipt
2. Should NOT be visible for TWAP orders
> feat(limit): add recreate button to limit receipt modal

- apps/cowswap-frontend/src/legacy/components/SideMenu/index.tsx
1. Faq, policies, account page - the scrollbar should not be displayed
2. Terms and conditions - the scrollbar should be displayed
> chore: don't display scrollbar on side menu when it's short

- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTablePagination/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTablePagination/styled.tsx
Fixes https://github.com/cowprotocol/cowswap/issues/3683
Since the component became bigger it makes sense to move styled elements into separate files.
No need testing, just safe refactoring
> refactor(orders-table): move styled elements from OrdersTablePagination

- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTablePagination.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTablePagination/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTablePagination/styled.tsx
Fixes #3683
I mainly copied the solution from https://taiga-ui.dev/navigation/pagination.
I'm limited pagination up to 14 pages because it matches max width of the orders table.
There is also one PR on top of this with small refactoring: https://github.com/cowprotocol/cowswap/pull/3896
https://github.com/cowprotocol/cowswap/assets/7122625/b50bec23-c9cf-46a5-bb1e-cc765cd932d4
Safe with a huge TWAP order: https://app.safe.global/apps/open?safe=sep:0xF568A3a2dfFd73C000E8E475B2D335A4A3818EBa&appUrl=https://swap-dev-git-fix-3683-cowswap.vercel.app/
1. When an order contains <= 14 pages there should not be additional controls
2. For orders with > 14 pages we add trimming and arrows
> feat(orders-table): trim pagination up to 14 pages

- apps/cowswap-frontend/src/modules/swap/hooks/useSetupSwapAmountsFromUrl.ts
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Fixes #3768
1. `useSetupSwapAmountsFromUrl()` was overriding URL when it's not needed
2. In the previous refactoring (#3848) I was moved provider network processing to the callback `onProviderNetworkChanges` which also contains `rememberedUrlState` processing. Along with it I should have removed the remembered state resetting from "On URL parameter changes" hook.
3. As a part of refactoring changed `rememberedUrlState` from `useState()` to `useRef()` to avoid confusion. In the future we should change other parts of the logic to avoid using `react-hooks/exhaustive-deps`.
1. Connect the app to the Mainnet
2. Modify the link swap.cow.fi/#/100/swap/dai/cow?recipient=vitalik.eth&sellAmount=100
3. Paste the link to the browser's tab
> fix(trade): restore state from URL after provider network changes

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1708939359762889
Since the last confirmation screen refactoring we got a bug.
"Price Updated" is displayed in Limit orders confirmation screen, but it should not.
1. Initiate a limit order creation (better to use volatile assets)
> fix(limit-orders): price updated warning should not be displayed

- apps/cowswap-frontend/src/common/updaters/FeesUpdater.ts
- apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1708361093191469
Just up the refresh interval from 10 to 30 sec.
1. Swap page should fetch quote not more often than 30 sec
2. TWAP page should fetch quote not more often than 30 sec
3. The "Quote refresh in ..." on the confirmation modal should tick from 30 sec
> fix: increase quote refresh interval for Swap and TWAP

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useRateImpact.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/AlternativeLimitOrderUpdater.ts
Follow up to https://github.com/cowprotocol/cowswap/pull/3845
[Thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1708944696384479?thread_ts=1708711157.372369&cid=C0361CDG8GP) where it was reported.
Price impact is "stuck" on first load of recreate form.
This PR clears it on load.
1. Recreate an existing limit order
* Price impact should not start filled
* Price impact should be filled in after quote is loaded
> feat(limit): fix price impact on load

- apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
- apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
- apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- libs/widget-lib/src/cowSwapWidget.ts
- libs/widget-lib/src/types.ts
- libs/widget-lib/src/urlUtils.ts
- libs/widget-react/src/lib/CowSwapWidget.tsx
Okay, i've been trying to fix #3899 and as a result I did a few improves in the widget while I was trying things out. 
So this changes don't improve the connect/disconnect, but improves a few things and prepares the ground to fix the issue in a future PR.
It was not really benefiting from the new typed messages from the improvements in the widget communication.
`processEvent` was receiving an `any` object instead of the well typed payloads. This PR improes that.
https://github.com/cowprotocol/cowswap/pull/3909/files#diff-7cc2f0fdbe38430b866ecaabc2d6994287cf16cbcf476d53a1d048b5c966edd1L47
Additionally, this updater had an issue with the hooks. It was not updating the `useCallback` even if their dependencies changed.
The provider was never part of the params that travel through the iframe …
> [widget] improve updater and params

- apps/cowswap-frontend/src/legacy/components/TransactionSettings/TransactionSettingsMod.tsx
- apps/cowswap-frontend/src/legacy/state/user/reducer.ts
- apps/cowswap-frontend/src/legacy/utils/prices.ts
- apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts
- apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
- apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
- apps/explorer/src/explorer/pages/AppData/config.tsx
- apps/widget-configurator/src/app/embedDialog/const.ts
- libs/common-const/src/common.ts
- libs/common-const/src/misc.ts
- libs/common-utils/src/misc.ts
- libs/widget-lib/docs/README.md
- libs/widget-lib/src/types.ts
- package.json
- yarn.lock
This PR updates the app-data to `v2.0` which includes the partner fee.
This change is a breaking change, and required to change the type of `slippageBips` to a number.
It also updates the widget params, so they can provide the two pieces of information that are needed. The `bps` and `recipient`
It has to adapt a bunch of places where we were referring to `interfaceFeeBips` and now calls it `partnerFee`.
Last but not least, I renamed where I could BIPS to BPS except `slippageBips` to keep it close to the actual field.
> feat: Introduce partner fee

- apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
- apps/cowswap-frontend/src/legacy/theme/baseTheme.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/styled.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
- apps/cowswap-frontend/src/modules/swap/pure/Row/types.ts
- apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
- libs/ui/src/enum.ts
Adds basic accordion to show the sum of all fees:
When expanded, it shows the details:
Future PRs will include some changes to make this production ready, and the review of tooltips, labels and all flows. 
This is the figma, and future PRs will add for example the Network fee:
https://www.figma.com/file/iPRnzK11XUvcaW6uBti7BE/Fee-display?type=design&node-id=160%3A2112&mode=design&t=spV2KT0KREOVkfaX-1
> Fee display style

- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
This PR introduces in the configuration the new setting to run the widget in dapp mode, or standalone mode
Dapp mode:
Standalone mode:
> feat: add dapp mode to widget

- apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
- apps/cowswap-frontend/src/legacy/state/swap/extension.ts
- apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
- apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeSummary/index.tsx
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.tsx
- libs/common-utils/src/misc.ts
Continuation on https://github.com/cowprotocol/cowswap/pull/3920 (thanks @shoom3301 for your last 2 commits!)
Fetch the partner fee from the widget params and display it.
Tooltip shows the BPS (and percentage)
1. Place an order
2. Observe the mocked data (please, for now don't test in production, as we have mocked data)
Computation of the fee is not done
> Show parner fee

- apps/explorer/src/explorer/pages/Home/index.tsx
Fixes #3947 
No tokens table for gchain
1. Open explorer
* Should have tokens take on Mainnet landing page
2. Switch to gchain
* Should NOT have tokens table
> fix(explorer): do not show tokens table on gchain

- apps/cowswap-frontend/src/legacy/state/price/hooks.ts
- apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
- apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
- apps/cowswap-frontend/src/modules/tradeQuote/utils/isQuoteExpired.ts
- libs/common-utils/src/sentry.ts
Fixes #3954 
Check quote expiration before order being placed in 2 ways:
1. Disable the swap/twap button when the quote has less than 5s validity or is expired
2. Abort the ethflow with an error modal if the quote expiration matches the rule above
When that happens, it'll [trigger a sentry error](https://cowprotocol.sentry.io/issues/5027703076/?project=5905822&query=errorType%3AplaceOrderWithExpiredQuote&statsPeriod=90d&stream_index=0)
1. Limit order button should not show this, as it doesn't really need an active quote AFAICT
2. Only aborting the ethflow as it's the only flow where we don't call the API directly. When we do, backend won't allow to place orders with expired quotes.
See test steps on #3954
Addtionaly, to test ethflow abortion:
1. Place the first ethflow order
2. Go back to …
> fix(eth-flow): prevent orders with expired quotes

- apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
Fixes #3984
Fixes this bug:
1. Place non-ethflow SWAP (just because it's faster)
2. Close modals to get to the empty order form
3. Go to a different tab/window and wait 2+ min
4. Go back to the tab
* Should NOT show `quote expired` message
5. Repeat but this time on step `2`, fill in the exact same sell amount before moving to another tab/window
* Should show `quote expired` message, even if briefly
> fix(swap): no quote expired when there's no input

- apps/cowswap-frontend/src/pages/LimitOrders/AlternativeLimitOrder.tsx
Fixes #3960 
Right now just hard-coding the order type to the modal, as only LIMIT orders can be recreated
When this is added to more order types we can make it dynamic.
1. Open recreate modal
* Title should be: Recreate limit order
> fix(recreate): add limit to recreate limit order modal title

- libs/wallet/src/web3-react/connectors/TrezorConnector/index.ts
Contexts:
https://cowservices.slack.com/archives/C03NXGFJA2U/p1709619078116629
https://cowservices.slack.com/archives/C0361CDD1FZ/p1709351188180749
The key of the problem in the wrong error message.
Before the fix we displayed "Current Trezor account index is out of bounds." error message in case when we can't connect to Trezor and it confuses people.
Technically, they key of the problem in `getCurrentAccount()` method, it didn't consider a case when `accounts` is an empty array.
After the fix we should display this error:
1. Open CowSwap, don't even connect Trezor device to your computer
2. Try to connect Trezor from the wallets list
3. Close the newly opened tab
> fix(trezor): display correct message for connection error

- apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
- libs/common-const/src/common.ts
Fixes #3997
There was a bug in `useHighFeeWarning()` calculations.
We don't need to multiply fee percent to -1 for buy orders and we should multiply the percent before converting it to fraction.
1. Compare the warning values with Barn
> chore: fix fee warning calculations

- apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
- apps/cowswap-frontend/src/legacy/state/application/hooks.ts
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- libs/widget-lib/src/types.ts
This PR is just a small improvement on the params to reflect more clearly the two modes of execution. `standalone` and `dapp` 
Before, this was decided with a flag that would "hide" the connect button. Before we release the new version of the widget, I preferred to change this to projects choose one of these two methods
> feat: add standalone/dapp mode to params

- apps/cowswap-frontend/src/common/pure/OrderExecutionStatusList/RateTooltipHeader.tsx
- apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmountInfo/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/styled.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/SwapPriceDifferenceWarning.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/tooltips.tsx
- apps/cowswap-frontend/src/pages/Faq/TradingFaq.tsx
- libs/ui/src/pure/InlineBanner/banners.tsx
Rebrand all the fee concepts as described in #3974
Adapt labels, values and tooltips for
It will show 2 concepts:
- Fee: which should always be FREE as there's not protocol fee
- Total costs (the fee used for settlement) --> depending on the flow will show different information. See the TEST instructions
It will show 2 concepts:
- Total fee (the partner fee, if it has one)
- Total costs (the fee used for settlement) --> depending on the flow will show different information. See the TEST instructions
To review the label and tooltips in the following flows:
- ETH Flow: Just sell ETH or xDAI - [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Presign Flow: Use the Safe App- [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Normal Flow: Sell …
> Rebrand labels and improve tooltips

- apps/explorer/src/hooks/useErc20.ts
- apps/explorer/src/hooks/useTokenList.ts
Fixes #4000
Use token lists on explorer for loading tokens and only fetch from chain if not found in any list.
1. Load something with lots of different tokens like this `0x9008D19f58AAbD9eD0D60971565AA8510560ab41`
* Tokens should load fine
2. Browse different pages
* Most tokens should load super fast as well
3. Compare with prod version
* Should be faster
1. This does not fixes all the pending issues with tokens that we have
2. This does not fixes all the token images
3. This does not make tokens loading from onchain efficient (using multicall for example)
> feat(explorer): use token lists on explorer

- libs/tokens/src/state/tokens/allTokensAtom.ts
- libs/tokens/src/state/tokens/userAddedTokensAtom.ts
- libs/tokens/src/utils/tokenMapToListWithLogo.ts
Fixes #3841 
There are no clear steps to reproduce AFAICT.
Probably load the shared localStorage into the app and load the app.
Should NOT show tokens from a different chain.
> fix(tokens): don't list tokens from other chains

- apps/cowswap-frontend/src/modules/limitOrders/updaters/AlternativeLimitOrderUpdater.ts
Fixes #4017
1. Place a limit order with 5min duration
2. Cancel, let it expire or execute
3. Recreate it
* Should have 5min duration
4. Repeat with all predefined durations
* Should match the original duration
> fix(recreate): fix 1h duration orders

- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/UnsupportedWalletWarning.tsx
In the past week, we had 2 cases of users trying to use TWAP with Safes, but not being able to because their Safes were not yet deployed!
This change does not add support for it, since we can't really support that use case.
It does however inform the users that deploying the Safe is required.
1. Open TWAP with an unsupported wallet
* Should show the message like above
> fix: add on TWAP wallet requirements note about Safe not deployed

- apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater.tsx
- apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
Fixes #4071
1. For cancellation events always display a link to Explorer
Removed `transactionHash` from `emitCancelledOrderEvent()`call.
2. For on-chain transaction in Safe display correct link in "View on Safe"
Use `safeTransactionHash` in `emitOnchainTransactionEvent` call.
1. Cancel an order using on-chain tx
2. Do wrap/unwrap in Safe
> fix: display correct links for on-chain notifications

- apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater.tsx
- apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
- apps/cowswap-frontend/src/modules/orders/containers/TransactionContentWithLink/index.tsx
- apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
"Order submitted" popup should contain link to Safe instead of Etherscan.
> fix: show link to Explorer for twap orders

- apps/cowswap-frontend/src/modules/tokensList/pure/ModalHeader/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
Fixes # 4098
The issue comes from https://github.com/cowprotocol/cowswap/pull/4079
1. Manage tokens modal
2. Import token modal
3. Trade menu (mobile view)
> chore: fix trade widget links menu style

- libs/tokens/src/const/tokensList.json
- libs/tokens/src/const/tokensLists.ts
Should fix https://github.com/cowprotocol/cowswap/issues/4106
1. With geoblock on, load the app
2. Token list should be loaded
> fix: replace dpaste lists with a version stored on github

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- apps/cowswap-frontend/src/modules/trade/pure/UnlockWidgetScreen/index.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1711698714785519?thread_ts=1711649246.114269&cid=C036G0J90BU
When feature-flag is disabled, then:
1. The banner with zero balance orders feature should not be displayed
2. The limit orders form should not allow creating orders without balance
> fix(limit-orders): use ff for zero balance orders

- release-please-config.json
We lose some commits in the changelog because release-please is not configured for many libs
> ci: add release-please config for all libs

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
Fixes #4027 
Close receipt modal after recreate order is placed
1. Go to limit orders history
2. Open a order receipt modal
3. Click on `recreate` order
4. Place new order
* After order placement, should be returned to active limit orders table
* Receipt modal should have been closed
5. Repeat but triggering the recreate from the context menu
* Same result
6. Place a new limit order
* Same result
> fix(recreate): close receipt modal after placing order

- apps/cowswap-frontend/src/modules/limitOrders/updaters/AlternativeLimitOrderUpdater.ts
- libs/common-utils/src/fractionUtils.ts
Fixes #4040 
Changing the amounts for recreating limit order with tokens of different decimal precision should work now.
1. Place a limit order between a pair with different decimal precision (e.g.: WETH/USDC mainnet)
2. Have the order execute/cancel/expire
3. Go to history and recreate it
4. Change the sell or buy amounts
* Opposite amount should be equal to the current amount times/divided by (depends on the field changed and the price display notation) the current price
> fix(recreate): fix recreate buy amount for pairs with different decimal precision

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
- apps/cowswap-frontend/src/modules/trade/state/alternativeOrder/hooks.ts
- libs/analytics/src/events/transactionEvents.ts
Closes #4096 
Add analytics events for clicking on recreate and placing recreate orders.
Edit orders are not enabled but the events are already prepared for that.
1. Click on recreate
* Analytics event `Recreate order: clicked` should be fired
2. Place recreate order
* Analytics event `Recreate order: placed` should be fired
> feat(recreate): add analytics events for recreate modal

- apps/widget-configurator/package.json
- apps/widget-configurator/vite.config.ts
After adding [the fix](https://github.com/cowprotocol/cowswap/pull/4123), widget-configurator stopped working locally.
Just added `server.fs.allow` value similarly with other apps.
> chore: fix widget-cfg vite config

- apps/cowswap-frontend/src/modules/application/containers/WithLDProvider.tsx
- apps/explorer/src/explorer/components/common/WithLDProvider/index.tsx
Fix lint warning
1. This change impacts Launch Darkly. So, check any feature that uses a feature flag still works as before
> fix: fix lint warning

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- apps/cowswap-frontend/src/modules/trade/pure/UnlockWidgetScreen/index.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
This reverts commit 28c60bda7b8817ff7156e9e24f253f57da427b36.
No balance limit orders have been enabled.
No need for feature flag.
1. Limit orders should work as usual
2. Limit orders banner should be displayed
3. Should be possible to place `partial fills` and `fill or kill` orders without enough balance
> fix(limit-orders): revert use ff for zero balance orders

- apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormButtonContext.ts
- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1712239854250149
1. Clean localStorage in CowSwap
2. Open widget-cfg and disconnect wallet
> fix(widget): disable connect wallet button in dapp mode

- libs/widget-lib/src/types.ts
Since we have [references to the types](https://github.com/cowprotocol/docs/pull/350) in the params table, we should export them from the library
> docs(widget): split interfaces to fit docs

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/widget-configurator/src/app/configurator/index.tsx
- libs/widget-lib/src/types.ts
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1712267092933019
2. Switch to standalone mode (or dapp-mode with connected Safe via WC)
3. Connect to Safe via WC
4. Setup sell ETH trade
5. Open browser console and execute `window.cowSwapWidgetParams = {banners: {hideSafeWebAppBanner: true}}`
6. Change some value in the configurator UI, for example: sell amount
7. Setup sell ETH trade again (if needed)
> feat(widget): option to hide safe banner

- libs/widget-lib/src/cowSwapWidget.ts
Fixes #3952 
Fix issue causing widget to duplicate events every time the network is changed when on `Dapp` mode.
2. Change to `standalone` then change back to `dapp`
3. Connect with Wagmi modal
4. Change the network in the configurator panel
5. Fill in the form and proceed placing the order until the wallet signature is requested
* There should be *only 1* signature requested
* The rest of the app should behave as usual
> fix(widget): call disconnect when destroying the widget

- libs/common-utils/src/doesTokenMatchSymbolOrAddress.ts
Fixes #4192 
Typing wise this shouldn't be possible, but it did happen quite a few times.
Although not that much recently.
Still, addressing it anyway.
No testing steps, addressing based on sentry error.
> fix: fix doesTokenMatchSymbolOrAddress app crash

- apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
Fixes #4035 
No explorer link for Native token on tokens page
1. Go to tokens page
2. Native token should have no explorer link
> feat(tokens-table): do not show explorer link for native token

- apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx
- apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
Fixes #3953 
Do not wrap fee text
1. Fill in trade details to see the fee
2. Switch to a tiny width (up to 300px wide)
* USD fee amounts shouldn't wrap, but display in the next line instead
> fix(mobile): adjust fee display for tiny widths

- apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
Since partner fee program is currently working only with swap orders, we don't even need to add the data to limit/twap orders app-data.
1. Create a swap order with partner-fee
2. Create a limit order with partner-fee
3. Create a TWAP order with partner-fee
> fix: add partner fee too app-data only for swap orders

- apps/widget-configurator/src/app/configurator/consts.ts
- apps/widget-configurator/src/app/configurator/controls/PartnerFeeControl.tsx
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/embedDialog/const.ts
Fixes #3977
1. Removed Partner fee recipient input from the widget configurator
2. Hardcoded "0x8BFE784432C91169Bdf3469B52ac589912dE21C3" as a recipient in the widget configurator
3. Added pk of the address into 1password
1. The partner fee recipient input should be removed
2. An order app-data with partner fee should contain the address above as a partner fee recipient
> fix(widget-cfg): hardcode partner fee recipient address

- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/styled.ts
- libs/widget-react/src/lib/CowSwapWidget.tsx
To show the widget, it would be nice to allow to show two version:
* Small responsive: We show it with a width of`450px`
* Big!: Will use as much space as available
For example, for limit orders, instead of:
Now it tries to use all the space:
https://github.com/cowprotocol/cowswap/assets/2352112/db090d80-3259-491f-81cc-77a248207169
It would be great to give an option on how to select Small/Big options. @fairlighteth how is best to show this control?
> feat: make widget to use all space

- apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
Fixes #4210
I was not able to reproduce it!
Looking at the code I've noticed the only one cause why it might have been happened, so, I've added the fix.
See #4210
> fix: mark order as replaced only if it's not created

- apps/cowswap-frontend/src/api/blocknative.ts
Fixes #4216 
Ignore blocknative websocket errors
1. Connect from a country blocked by blocknative
2. Switch to ethereum
3. Check the console logs contain an error message similar to
* It should not be logged to Sentry
(How to check that locally? not sure... maybe only on the sentry panel?)
> fix(blocknative): ignore websocket errors

- apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useHandleChainChange.ts
- apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useRemainingNativeTxsAndCosts.ts
- apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useSetupEthFlow.ts
- apps/cowswap-frontend/src/modules/swap/containers/EthFlow/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapModals/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
Fixes #4092 
Fix ethflow crash
New behaviour: when switching networks, ethflow modal/history is cleared.
Steps from the issue:
1. Connect to the wallet in Sepolia chain
2. Select ETH as a sell token
3. ETH amount should be > WETH balance in the wallet, WETH should not be approved
4. Expand the 'Switch to the classic mode' dropdown and press on the Wrap ETH and Swap button
5. Run the Wrap transaction
6. When it is mined, switch to the GC in the connected wallet
* Should NOT crash
* Should be returned to SWAP
> fix(eth-flow): fix classic eth flow crash

- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx
Fixes #4166
Display the banner only in widget mode, when `enabledTradeTypes` contains `TradeType.ADVANCED`
1. Open widget configurator (by default all trade types are enabled)
2. Setup a trade with high price impact (>1%) and enough amount (Sepolia >100$, GC >500$, Mainnet > 50k$)
3. Disable "advanced" trade type in the configurator
> fix(swap): show TWAP suggestion banner only in Safe app

- apps/cowswap-frontend/src/common/pure/CurrencySelectButton/styled.tsx
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1712917947184939
> chore: fix token select comp style in readonly mode

- apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetPalette.ts
- libs/widget-lib/src/urlUtils.ts
Context: https://cowservices.slack.com/archives/C05QVFJUX9R/p1713169527030309
The custom theme is resetting when you navigates in the CowSwap.
It happens because the palette params are deriving from the URL query, but when you navigates in CowSwap the URL query is getting cleaned up.
To fix that, I added a condition and reset the state only when the query param `palette` equals `null`
2. Specify a custom theme
3. Navigate to another trade widget (e.g. Limit orders)
4. Refresh the page
> fix(widget): don't reset palette state while navigating

- libs/snackbars/src/containers/SnackbarsWidget/index.tsx
Fixes https://github.com/cowprotocol/cow-fi/issues/166
This fix is only about the last case in the issue (scroll bar when snackbar is displayed in mobile view).
The first case is not relevant anymore.
Second one is "ok", we should display the scrollbar here since this is a modal and we use fixed height for that cases.
@elena-zh I remember you already have an issue for styling scrollbars for Windows in the whole CoW Swap.
1. Open the widget in mobile resolution
2. Post an order
> fix(snackbars): remove scrollbar from body when overlay is displayed

- libs/wallet/src/web3-react/updater.ts
Fixes #2366
Reset Safe info when there's no Safe data
1. Connect using Rabby wallet and an EOA address
2. Pick native as sell token
* Should show eth flow
3. Switch to a Safe address within Rabby wallet
* Should suggest eth flow bundling
4. Switch back to EOA
* Bundling banner should be gone
* Wallet interactions should work as before
> fix(wallet): reset safe info when there's no safe data

- apps/cowswap-frontend/src/common/updaters/CancelReplaceTxUpdater.tsx
Fixes #4255 
Fixes #4256 
In some cases we were passing down Safe tx hashes as well as no tx hashes to query with blocknative
1. Do a Safe tx
* Should not log blocknative related errors
> fix(blocknative): fix blocknative invalid tx hash

- apps/cowswap-frontend/src/cow-react/sentry.ts
Fixes #4251 
Ignore errors like [this](https://cowprotocol.sentry.io/issues/2741336407/?environment=production&project=5905822&sort=freq&statsPeriod=90d&stream_index=0)
[According to Sentry](https://sentry.io/answers/load-failed-javascript/), those happen when `fetch` calls fails for Apple devices.
This doesn't seem to be actionable either, so this PR ignores them.
This is more specific and filters out based on error urls seens in the last ~80 error occurrences or so (there are 5.6k in total, I'm not going through them all 😬)
1. Try to reproduce with an Apple device? (most of them happen on iOS)
* Observe `Sentry: Ignoring Apple device load failed error` is logged to the console
> fix(sentry): ignore apple devices TypeError

- apps/widget-configurator/src/app/configurator/index.tsx
Reverts the commit for testing this PR https://github.com/cowprotocol/cowswap/pull/4262
https://widget-configurator-git-revert-memory-leak-test-cowswap.vercel.app/ shouldn't have now the toggle show/hide button
> Revert "chore: add show/hide widget button to accelerate memory leaks"

- apps/explorer/src/hooks/useTokenList.ts
Fixes #4276
HOTFIX
Partially fixes the issue by:
1. Loading sepolia token list
2. Adding more tokens to the token list (https://github.com/cowprotocol/token-lists/pull/328)
Needs a bigger refactor to fix it, but this change is only stopping the bleeding.
1. Open the mentioned order in the PR link without opening another page before `0x9dc9232cc93b8644c45f6cffa731ba1ece5916bfc6046b45f613d10d00caf64705e6b5eb1d0e6aabab082057d5bb91f2ee6d11be66223eda` [direct link](https://explorer-dev-git-fix-4276explorer-sepolia-issue-cowswap.vercel.app/sepolia/orders/0x9dc9232cc93b8644c45f6cffa731ba1ece5916bfc6046b45f613d10d00caf64705e6b5eb1d0e6aabab082057d5bb91f2ee6d11be66223eda?tab=overview)
* Should load
> fix(explorer): add sepolia token list

- apps/explorer/src/hooks/useErc20.ts
Context: https://cowservices.slack.com/archives/C036JAGRQ04/p1713783667693619?thread_ts=1713783227.686239&cid=C036JAGRQ04
The bug was introduced in [the recent fix](https://github.com/cowprotocol/cowswap/pull/4245/files#diff-6e4096a863530b89050cf7a7215d5c281af6f9c62533a7ac6f9af39b8b640e63R145).
I'm not 100% sure why do we need this callback, anyway, I think we should extinguish the fire first of all.
1. Open https://explorer-dev-git-hotfix-explorer-crashing-cowswap.vercel.app/orders/0x23f2bca97398e803562db9d4631fd9769a472f8e3ec56f1e87eca2ca7a08bf8d4f9e9e757645af8a6fbe877f3f7c66c5b79854a16625d4f0?tab=overview
> fix(explorer): fix browser crashing

- apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts
- apps/cowswap-frontend/src/modules/permit/hooks/useGeneratePermitHook.ts
- apps/cowswap-frontend/src/modules/permit/hooks/useGetCachedPermit.ts
- libs/permit-utils/src/lib/generatePermitHook.ts
Fixes #4274
Permit hook generation failure wasn't properly handled, leading to [1.8k errors logged on Sentry](https://cowprotocol.sentry.io/issues/4564574974/?environment=production&project=5905822&query=is%3Aunresolved&sort=freq&statsPeriod=90d&stream_index=3)
1. Force a permit hook generation failure
2. See the exception is handled
I couldn't find a way to reproduce it, so locally I changed the code to always thrown an exception.
Did not include that in the PR, though.
* Permit should work as before
@elena-zh tagging you to double check the permit behaviour. The exception you can skip it as there are no clear reproduction steps.
> fix(sentry): fix unhandled permit failure

- apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
Fixes #4254
In widget mode, the account modal background should be transparent
> fix(widget): make account modal background transparent

- apps/cowswap-frontend/src/common/pure/Modal/index.tsx
- apps/cowswap-frontend/src/common/state/openModalState.ts
- apps/cowswap-frontend/src/modules/injectedWidget/updaters/IframeResizer.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/styled.ts
- libs/widget-lib/src/cowSwapWidget.ts
- libs/widget-lib/src/types.ts
Fixes #4279
Modals are dispalyed with `posotion: fixed`, so they don't impact on the widget height, because of that `IframeResizer` didn't react on it.
To fix that, I've added an additional trigger when modal is open.
Modals are displaying differently, depending on the screen width (`isUpToSmall`).
When widget container width > 720px, then the widget height will be set to the window height, otherwise it will be set to the defaultHeight (by default 640px).
See #4279
1. Modals displaying with different screen width
2. After merging this PR, we should update and test https://cow.fi/widget as well
> fix(widget): fix modals displaying

- libs/ui/src/pure/Tooltip/index.tsx
This PR is some feature I wanted to have for quite some time and now I have a excuse to implement :) 
Let me explain giving some context
The problem: Tooltips show up when you hover, and they hide when you move the mouse. This is OK most of the time, but sometimes there's something in the tooltip you want to copy paste, and you can't because the moment you move the mouse to the tooltip content.... IT DISSAPEARS 💨 
More importantly. Normally tooltips are created to give some additional context. They are supposed to be short, however, the user might want to read more about it, so it would be great to add links to blog posts, FAQ or external sites.
The problem is again, when you try to move your mouse away of the tooltip icon.... PUFFFFF... 💨  VANISHED!
Furthermore, when we are developing, …
> feat(tooltip): make tooltips sticky

- apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- libs/ui/src/pure/Tooltip/index.tsx
- libs/widget-lib/src/types.ts
Follow up on https://github.com/cowprotocol/cowswap/pull/4330
This PR allows users of the widget to customize the tooltip and add any content they want. 
The configuration allows you to provide a custom fee label and the markdown for the tooltip
```ts
{
content: {
// TODO: Don't merge with this. This comment should be reverted.
feeLabel: "Anxo's cut",
feeTooltipMarkdown: `\
Anxo has been working hard lately, and need to pay his bills.
Anxo is a good guy, so you should pay him.
This fee won't contribute to anything useful, but it will make Anxo happy.
Think about it
[don't read more](google.com)
`,
},
}
```
Copilot helped writing the tooltip message, so I think IA wants me to be payed more
1. Go to configurator https://widget-configurator-git-custom-fee-labels-cowswap.vercel.app/
2. Check …
> Custom fee labels

- apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
- apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.test.ts
- apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
- libs/widget-lib/src/types.ts
Fixes #4160
Since users might want or have to use different partnerFee recipient addresses depending on network, we should provide an option to this.
To keep backward compatibility, I changed the recipient type from `string` to `string | Record<SupportedChainId, string>`.
Docs update: https://github.com/cowprotocol/docs/pull/359/files
1. App data for orders with partnerFee should contain specified bps and address
2. Only swap orders should have partnerFee
How to test:
```
window.cowSwapWidgetParams = {
partnerFee: {
bps: 100,
recipient: {
1: '0x000...1',
100: '0x000...100',
11155111: '0x000...11155111',
},
},
}
```
1. Run the code above in the widget configurator console
2. Change smth in the configurator inputs (to update widget state)
3. Create an order
> feat(widget): support different partnerFee recipient for networks

- libs/ui/src/pure/Tooltip/index.tsx
This PR replaces https://github.com/cowprotocol/cowswap/pull/4337 and https://github.com/cowprotocol/cowswap/pull/4330 (so if approved, I will close these 2 PRs without merging)
I tried a couple of approaches for improving the tooltips. This PR is another simpler approach that comes from a re-iteration of https://github.com/cowprotocol/cowswap/pull/4337
It removes the STICKY behavior of https://github.com/cowprotocol/cowswap/pull/4330 and allows you to toggle the tooltip by clicking the icon.
The code should also be simpler. Check the test steps to understand the expectations on the current behavior
SPEC 2: `Tooltip works like before`
1. Over the icon shows it
2. Move away to hide it
SPEC 2: `Toggle the tooltip with the click`
1. Click to show
2. Click to hide. This is especially …
> chore: simplify ux and code

- apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Part of #4238
- Using new proxy endpoint from https://github.com/cowprotocol/bff/pull/10
- Bumping usd refresh interval from 30s to 1m
1. Open the console in the `network` tab and filter for `geckoProxy`
2. On mainnet/gchain, you should see the requests _mostly_ all 200.
* Some of them should be `cached`
3. Open the tokens page
* Should load usd prices for the ones where there's is balance
4. Open the activity modal
* Should load usd prices for the ones with surplus
in general should behave the same or better in regards to usd amounts loading.
> feat(usd-estimation): replace coingecko endpoint

- apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts
- apps/cowswap-frontend/src/cow-react/sentry.ts
- apps/cowswap-frontend/src/cow-react/sentry/beforeSend.ts
- apps/cowswap-frontend/src/cow-react/sentry/index.ts
Fixes #4260
This PR addresses 4 types of unhandled rejection errors:
All of them are not thrown as Error objects
Filter them based on breadcrumbs messages
Filter them based on additional data, as those did not have anything relevant I could find printed to the console.
Out of those, only the first was something actionable on our side.
I fixed that by NOT re-throwing a handled exception.
All others are out of our control, thrown by the wallet (Metamask, it seems), thus we are ignoring it.
1. Manually tested it locally
2. After deployed, observe those error reduce/disappear
> fix(sentry): fix sentry unhandled rejection

- apps/cowswap-frontend/public/emergency.js
Follow up of #3809
Reported:
https://cowservices.slack.com/archives/C036MD8ADMG/p1715085509788589
https://cowservices.slack.com/archives/C03DVQREAH0/p1715583745060159
In #3881 we have fixed the reason of the issue, be it's not enough, we also have to clean consequences of this problem.
In this PR I've added universal solutions for `localStorage` stores with versioning.
The fix is added into `emergency.js` because this script loads before all (we must to clean localStorage before run the app).
1. Block `emergency.js` request
2. Flood your localStorage. Create `allTokenListsInfoAtom:v2` localStorage record and put a lot of data into it
3. Reload the page
4. Unblock `emergency.js` request and reload the page
> fix: clean outdated localStorage stores

- libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
This PR is an attempt to fix the issue with counterfactual safes.
The underlying issue, is that we fail to detect that the connected wallet is a Safe, because we rely on the Safe API to get the Safe information, and it's not there yet (as the safe is not even deployed)
We will assume is a Safe if we detect the Safe provider and this one returns a valid safe address. Also, we keep the old check, as its useful for Wallet Connect.
Send TWAP:
Activating Safe onchain:
Safe activated:
TWAP created:
- The detection will fail if you check with Wallet Connect, because the API will not know this safe exists (actually doesn't), and we are also not using the Safe Web Apps connector, so we can't tell! I think is enough to fix it for Safe Web for now
- Unrelated to this PR: Even after I sent the TWAP, …
> feat: support counterfactual safes

- apps/cow-fi/components/Article.tsx
- apps/cow-fi/pages/learn/articles/[articleSlug].tsx
- apps/cow-fi/pages/learn/categories/[categorySlug].tsx
- apps/cow-fi/pages/learn/index.tsx
- apps/cow-fi/services/cms/index.ts
Adds a basic layout for an article page inside learn
Check out some articles, for example: https://cowfi-git-add-blog-page-cowswap.vercel.app/learn/articles/cow-protocol-april-2023-highlights
Although I added a few styles, the final ironing will be done by Michel, so don't focus too much on how this is presented. The goal was to show the page, basic content, cover image and format the markdown
> feat(cms): add blog page with an article

- apps/cowswap-frontend/src/modules/twap/const.ts
Context: https://cowservices.slack.com/archives/C035N0YEB6J/p1715262180866269?thread_ts=1714975213.305109&cid=C035N0YEB6J
Changed the threshold from 5k to 1k on Mainnet
1. The warning should be displayed on Mainnet only if the amount is less than 1k USD
> fix(twap): lower minimum sell amount

- apps/cow-fi/components/Article.tsx
- apps/cow-fi/components/Category.tsx
- apps/cow-fi/pages/learn/articles/[articleSlug].tsx
- apps/cow-fi/pages/learn/index.tsx
- apps/cow-fi/services/cms/index.ts
- apps/cow-fi/util/queryParams.ts
Make use of the SEO tags for the articles, with nice defaults (to use the article titles, description, etc as sane defaults
Creating the query string was a bit complicated because our CMS client library expect an object of key-value pairs, however the CMS allows a very rich nested object sintax that is very hard to do by hand in this format. 
This PR adds an utility that uses `qs` library to convert one format in the other. This makes it simpler to query the CMS. 
Probably we should move this to the CMS as it matures
https://www.opengraph.xyz/url/https%3A%2F%2Fcowfi-git-cms-seo-cowswap.vercel.app%2Flearn%2Farticles%2Fannouncing-gasless-approvals-on-cow-swap
You can try to go to the CMS admin and modify the SEO information, and make sure its reflected
> feat: add SEO image and fallback to cover image

- apps/cowswap-frontend/src/modules/usdAmount/apis/errors.ts
- apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/apis/getCowProtocolUsdPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/apis/getDefillamaUsdPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/services/fetchCurrencyUsdPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.test.tsx
- apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
- libs/wallet/src/web3-react/connectors/Injected/index.tsx
- libs/wallet/src/web3-react/connectors/TrezorConnector/index.ts
- tsconfig.base.json
Part of #4238
- Add Defillama price source as fallback
- Fix Coingecko rate limit detection
- Refactor usd price fetching
1. On mainnet/gchain, load an account that has many funds and/or many trades with surplus for different tokens
2. Open the tokens page, open the activity modal page
3. Open the console in the `network` tab
* Once there are `coingeckoProxy` requests failing with `429` errors, there should be requests for `defillama`
4. Open the console logs and filter by `UsdPricesUpdater`
* There should be logs indicating when coingecko, defillama or cowprotocol prices are being used
The console logs are noise, I know.
Will remove them before merging.
> feat(usd-estimation): add defillama price source

- apps/explorer/src/api/operator/operatorApi.ts
- apps/explorer/src/api/web3/index.ts
- package.json
- yarn.lock
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1715851334267859
SDK changes: https://github.com/cowprotocol/cow-sdk/pull/208
By default `cow-sdk` uses backoff strategy with 10 retries which makes significant delays when API is down.
For the search page it doesn't make sense to make so many retries, so I changed the value to 2. It means that sdk will make up to 2 requests. Why not 1? I'm not sure, just in case left 2 since it doesn't create significant delays.
1.  Open http://localhost:4200/search/0xc104cea97d7590bb8dd0c32b72cab147bf85b052859ca0b0f157361186a9d8c6
2. Open browser console (network tab) and reload page
3. Block barn.api.cow.fi/mainnet/api/v1/transactions/0xc104cea97d7590bb8dd0c32b72cab147bf85b052859ca0b0f157361186a9d8c6/orders request
4. Block …
> fix(explorer): reduce retries for tx orders requests

- apps/explorer/src/api/web3/index.ts
- apps/explorer/src/const.ts
We have `RPC_URLS` in `@cowprotocol/common-consts` and use them in CoW Swap.
To be consistent we should use them in Explorer as well.
@alfetopito already set `REACT_APP_NETWORK_URL_{chainId}` variables in Vercel env.
1. Explorer should use RPC endponts specified in Vercel env (nodereal)
> fix(explorer): use same RPC urls as in CoW Swap

- libs/ui/src/consts.ts
- libs/ui/src/pure/ButtonSecondaryAlt/index.tsx
- libs/ui/src/pure/Footer/footerAnimation.tsx
- libs/ui/src/pure/Footer/index.tsx
- libs/ui/src/pure/Footer/styled.ts
- libs/ui/src/pure/MenuBar/index.tsx
- libs/ui/src/pure/MenuBar/styled.ts
- libs/ui/src/pure/ProductLogo/index.tsx
- libs/ui/src/types.ts
- libs/widget-lib/src/themeUtils.ts
- libs/widget-lib/src/types.ts
No functional changes.
Fix inverted dependency.
`ui` lib was depending on `widget-lib` for a type.
I moved the type to `ui` instead.
Also removed the inner references within the `ui` lib.
Inside the same lib we should use relative imports.
> fix: remove widget-lib dep from ui lib and inner ui lib imports

- apps/cowswap-frontend/src/modules/notifications/hooks/useAccountNotifications.ts
1. Block https://cms.cow.fi/api/notification-list/* request
2. Reload page
> fix(notifications): don't fail when CMS API is down

- apps/cowswap-frontend/index.html
- apps/widget-configurator/src/app/configurator/controls/NetworkControl.tsx
- apps/widget-configurator/src/app/configurator/hooks/useSyncWidgetNetwork.ts
- apps/widget-configurator/src/app/configurator/index.tsx
Fixes #4459
Standalone mode means that widget doesn't depend on external wallet provider and works autonomously.
The "Network" field in the configurator is related only to the wallet connected in the configurator UI.
1. Open configurator
2. Choose dapp mode and connect Metamask
3. Change network in the configurator UI
4. Change mode to standalone
5. Change network in the configurator UI
> fix(widget-cfg): don't request network switching with standalone mode

- apps/cowswap-frontend/src/common/pure/ChainPrefixWarning/index.tsx
- apps/cowswap-frontend/src/legacy/components/AddressInputPanel/index.tsx
- libs/common-const/src/chainInfo.ts
- libs/common-utils/src/address.ts
- libs/common-utils/src/index.ts
Currently if you paste an ERC-3770 formatted address into the recipient list, you’ll get an error and have to delete the chain prefix.
With this change we will detect a prefix in an address and return just the address. If the address pasted was having the same address as the current chain, there won’t be any warning to the user, but if he has pasted an address for a different chain we’ll output a warning.
This improves the compatibility with the Safe app as addresses there are by default output with a prefix. 
1. Enable custom recipient
2. If you enter an address with a prefix, then the prefix will be stripped out and only the address will be left in the field.
- if the prefix was for the same chain the user is currently on - no warning will be output
- if the prefix was for a different …
> feat: add support for ERC-3770 on recipient addr

- apps/cowswap-frontend/src/common/pure/ChainPrefixWarning/index.tsx
- apps/cowswap-frontend/src/common/pure/WarningCard/WarningCard.tsx
- apps/cowswap-frontend/src/legacy/components/AddressInputPanel/index.tsx
Follow up on @elena-zh 's comments on https://github.com/cowprotocol/cowswap/pull/4418 from @compojoom
I made some small changes on the message.
Before:
After:
> feat: improve message for wrong prefix on networks

- apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
Solves the issue Den is experimenting with the history being polluted with URL changes in the widget
CTX: https://cowservices.slack.com/archives/C036G0J90BU/p1716290729183899
- Open configurator https://widget-configurator-git-fix-navigation-history-issue-cowswap.vercel.app/
- Change the colors of the PAPER a few times
- Navigate back, it should go to wherever you were before CoW Swap (or the home of your browser)
These steps would not work in here, where going back would be changing the colors back:
https://widget.cow.fi
> feat: don't pollute the history with widget changes

- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
- libs/ui/src/pure/HelpTooltip/index.tsx
> fix: fix safe read-only button tooltip

- apps/cowswap-frontend/src/cosmos.decorator.tsx
- apps/cowswap-frontend/src/legacy/components/AddressInputPanel/index.tsx
- apps/cowswap-frontend/src/modules/notifications/containers/NotificationsList/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
- apps/cowswap-frontend/src/modules/wallet/containers/WalletModal/index.tsx
- eslint.config.js
`eslint-plugin-react-hooks` stopped working after [the recent eslint upgrade](https://github.com/cowprotocol/cowswap/pull/4326).
Mainly, the problem comes from the new [eslint flat config format](https://eslint.org/docs/latest/use/configure/migration-guide).
I've tried several solutions, but only one helped me: https://stackoverflow.com/a/78369201/5151460
There should not be any functional changes, but I've changed a bit code of:
1. Wallet connection functionality
2. Marking notifications as read
3. Using addresses with network prefix (gno:0x0000...)
> ci: fix react-hooks eslint rules

- libs/wallet/src/web3-react/connectors/Injected/index.tsx
Fixes #4480
The problem was in the fact that `web3react` didn't update provider in `Web3Context`.
In the code bellow you can see `useProvider()` hook which is responsible for updating the provider.
It depends on `[loaded, enabled, isActive, chainId, network]` and when you change one eip6963 provider to another already connected one, the provider will not be updated, because we call `startActivation()` only when `this.provider?.isConnected?.()` is falsy.
To avoid the problem, now we undoubtedly call `startActivation()` in order to reset `isActive` state.
See #4480
> fix(wallets): update provider when eip6963 wallet changed

- libs/tokens/src/const/tokensList.json
Use the 2 token lists mapped for arbitrum one created on https://github.com/cowprotocol/token-lists/pull/393
1. Switch network to arbitrum one
2. Check the loaded token lists
* Should have cowswap, uniswap and coingecko
* They all should point to the token-lists repo
> chore: use mapped tokenlists for arb1

- libs/wallet/src/web3-react/connectors/Injected/index.tsx
The bug comes from https://github.com/cowprotocol/cowswap/pull/4483/files
This fix should be still relevant for both https://github.com/cowprotocol/cowswap/issues/4480 and https://github.com/cowprotocol/cowswap/pull/4493#issuecomment-2135708730
The cause of the problem that I undoubtedly called `startActivation()` even for network switching, but we must not do it for the case.
1. Connect to Metamask
2. Switch network in the CoW Swap UI
3. See #4480
> fix(wallets): don't reset wallet on network switching

- apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
- apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx
This is just some personal annoyance I have. Sometimes is super hard to find the token address of the selected token. I don't think this PR is a solution to it, we should allow the user to open a link in an explorer. 
This PR only adds it in the HTLM so nerdies can look it up. I hope we can add in the future the proper links for the final users. @fairlighteth  pls make sure we come back to this one as it will be a low effort to add, so we can have a small discussion on what we want to do exactly
Added to the token selector:
Added to the token table too:
> feat: expose the address of a token in the HTML

- libs/common-hooks/src/useAvailableChains.ts
Remove arb1 feature flag
1. Open CoW Swap
* Should have Arbitrum One enabled
2. Open Explorer
* Should have Arbitrum One enabled
3. Open widget
* Should have Arbitrum One enabled
> chore: remove isArbitrumOneEnabled feature flag

- apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
- apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
With https://github.com/cowprotocol/cowswap/pull/3742 a bug was introduced for wrapping on LIMIT.
[Described here](https://www.notion.so/cownation/Arbitrum-One-pre-launch-2024-05-29-e504c9b3f7cb4b459101b374608cb8d9?pvs=4#da3355ddfac14735addb0884a056b0e9).
This change makes sure it's no longer possible to try to wrap more than what's available.
1. Go to limit, pick native as sell, wrapped native as buy
2. Insert in the sell input more than your balance
* You should see `insufficient balance`
> fix(limit): do not allow wrap without full balance

- apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
Fixes #4289
Remove favourite tooltip for widget, as it's not possible to edit them.
| Regular/Before | Widget now |
|-|-|
| ![image](https://github.com/cowprotocol/cowswap/assets/43217/fae38056-3c2f-405d-9156-7db8ce8c107b) | ![image](https://github.com/cowprotocol/cowswap/assets/43217/1a963720-263f-458b-a24f-8fc98215a848) |
1. Open widget
2. Open token selector
* There should be no tooltip in the favorite tokens header
3. Open CoW Swap
* There should be a tooltip in the favorite tokens header
> fix(widget): remove favorite tooltip for widget

- apps/cowswap-frontend-e2e/src/support/ethereum.ts
- apps/cowswap-frontend/src/react-app-env.d.ts
- libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
Since [the last wallets refactoring](https://github.com/cowprotocol/cowswap/pull/4416), e2e tests started failing.
The cause of it is that after the refactoring we don't try connecting to injected provider automatically.
For e2e tests I've added special flag `window.ethereum.autoConnect`.
E2E tests should be green
> fix: connect wallet in e2e tests

- apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
- apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
- libs/widget-lib/src/cowSwapWidget.ts
- libs/widget-lib/src/types.ts
Fixes #4155 
This fix works only in mobile browsers (checked Chrome, Safari, Firefox on IOS) and doesn't work in Desktop:
Since deeplinks make sense only in mobile I think it's ok.
There is one problem with Firefox, it opens deeplinks twice, probably because it allows using depplinks from Iframes. I've tried adding try/catch for `window.open` but it doesn't help. Since the fix helps for Chrome and Safari I think it worth to keep it. In Firefox users will have to cancel the second deeplink request.
1. Open https://widget-configurator-git-fix-widget-deeplinks-cowswap.vercel.app/ in mobile browser
2. Switch to standalone mode
3. Try to connect via wallet connect to some wallet (e.g. Trust)
4. Wallet should be successfuly connected after connection approve
> fix(widget): allow using walletconnect in widget mobile

- apps/cowswap-frontend/src/legacy/components/TransactionSettings/TransactionSettingsMod.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Row/RowSlippage/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx
- libs/common-const/src/common.ts
Ethflow orders have a default min slippage of 2%.
It doesn't make much sense for chains with cheaper gas costs.
This change reduces the min amount required for everything else (gchain, arb1 and sepolia) to the default minimum: `0.5%`
1. Open on mainnet
2. Pick ETH as sell
3. Check the settings
* Min slippage allowed should be `2%`
4. Repeat for all other chains
* Min slippage allowed should be `0.5%`
* Regular slippage settings should not be affected
> feat: reduce ethflow slippage for non mainnet chains

- libs/common-utils/src/appzi.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1718197114575339
I haven't found what exactly wrong with Appzi, but I just disabled it in widget mode since it's not relevant here
2. Change "Current trade type" to "Limit"
> fix: disable appzi in widget mode

- apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/RecipientRow/index.tsx
- apps/cowswap-frontend/src/modules/twap/const.ts
- apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
1. When recipient is set it should be displayed on confirm screen (swap/limit/twap)
> fix(trade): display recipient on confirm screen

- apps/cowswap-frontend/src/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx
Fix ethflow slippage not being reset between network changes
1. Open app
2. Change network to arb1, gchain or sepolia
3. Change default slippage to `0`
4. Pick native as sell
* Slippage should be set to 0.5% 
* You should not be able to set it to less than that
5. Pick any other token as sell
* Slippage should be back to `0`
6. Change network to mainnet
* Slippage should remain at `0`
7. Pick native as sell
* Slippage should be set to 2% 
* You should not be able to set it to less than that
8. Pick any other token as sell
* Slippage should be back to `0`
9. Change to any other network
* Slippage should remain at `0`
10. Pick native as sell
* Slippage should be set to 0.5%
> fix(slippage): always reset ethflow slippage when changing networks

- libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
- libs/wallet/src/web3-react/connectors/Injected/index.tsx
- libs/wallet/src/web3-react/hooks/useActivateConnector.ts
Handles sentry error https://cowprotocol.sentry.io/issues/4526834066/?environment=production&project=5905822&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&statsPeriod=90d&stream_index=15
Actually, I can't trigger this anywhere (prod nor here), but these would be the test steps, I think.
1. Connect with MM
2. Disconnect
* `Failed to call "PUBLIC_disconnectSite", ignoring` should be logged to the console, instead of the exception
> fix(sentry): handle unhandled exception calling PUBLIC_disconnectSite

- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
When widget baseUrl has double slash, then cowswap crashes:
The bug can be reproduced only in dev environment.
2. In the widget preview go to Limit orders and then back to Swap
> fix(widget): don't crash on dev env

- apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useTradeQuoteStateFromLegacy.ts
- apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
- apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
Fixes #4562
In TWAP, we reset output amount every time when input amount changes, but it has a race condition with `QuoteUpdater`.
To avoid this, I added a new boolean flag `hasParamsChanged` to `tradeQuoteState` and reset output amount only when the flag is true.
The bug is reproducible on PROD as well.
1. Change input amount 
2. Wait for nose-picking cow
3. Start changing the input amount quickly (add 0 -> remove 0 -> repeat)
https://github.com/cowprotocol/cowswap/assets/7122625/39ac1d6b-056c-44a7-88b2-9faab1ad9ac1
> fix(twap): improve output amount resetting logic

- apps/explorer/src/api/operator/types.ts
- apps/explorer/src/components/orders/DetailsTable/index.tsx
- apps/explorer/src/components/orders/OrderDetails/index.tsx
Show execution time based on first tx when order is executed and (in case of partially fillable) there's a single fill.
1. Open order details page for an executed order
* `Execution time` should be displayed
2. Open order details page for a partially fillable order with a single fill
* `Execution time` should be displayed
3. Open order details page for an order not executed
* `Execution time` should not be present
4. Open order details page for a partially fillable order with multiple fills
* `Execution time` should not be present
> feat(explorer): show execution time when available

- apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
Context: https://cowservices.slack.com/archives/C03DVQREAH0/p1718977896946899
The reason: `window.top` !== `window.parent` in case when there are more than one parent windows.
In Cypress we have:
Cypress window
- Safe app window
- Windet window
In this case:
- `window.top` is Cypress window
- `window.parent` is Safe app window
No need to test
> fix(widget): fix widget usage in more than one iframe

- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
Fixes #4536
Described in the issue
So here `isDropdownVisible` prop should be false here, when `isDropdown` became false after the screen is expanded again.
> fix: reset isDropdownVisible status in large screen

- apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
- apps/cowswap-frontend/src/modules/account/hooks/useCloseAccountModalOnNavigate.ts
- apps/cowswap-frontend/src/modules/account/hooks/useToggleAccountModal.ts
Close account modal when changing the current page
1. Open account modal
2. On the header menu, select a different page (SWAP, LIMIT, TWAP, Tokens, Account, etc)
* Account modal should be closed
> fix: close account modal on navigation

- apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
- libs/common-const/src/common.ts
The FAQ link should lead to https://docs.cow.fi/cow-protocol/reference/core/tokens
> chore: update unsupported FAQ link

- apps/cowswap-frontend/src/modules/trade/pure/TradePageLayout/index.tsx
1. Create at least one limit order
2. Adjust the window width to be less than 1300px
> chore: fix limit orders table width

- apps/cowswap-frontend/src/legacy/components/OrderProgressBar/styled.ts
- libs/snackbars/src/containers/SnackbarsWidget/index.tsx
1. Fixed order progress bar style
2. Fixed scrolling issue with snackbars. When a snackbar (order created, filled, etc.) is displayed the page is not scrollable. It's expected, but only for small (mobile) screen size, because overlay is displayed in this case.
1. The order progress bar background should be lighter
2. When a snackbar is displayed not in mobile screen then page should be scrollable
> chore: fix order progress bar style

- apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
1. Set ETH as sell token in Swap
2. Open settings
> chore(swap): fix slippage button disabled style

- apps/explorer/src/components/orders/FilledProgress/index.tsx
The filled percentage has way too many decimals
Before
After
Search in the preview PR for orderId: `0x72198277f82a96d9ec2911c11f179d8605dedf5113a5194e98ac5235cdf6db709fa3c00a92ec5f96b1ad2527ab41b3932efeda58660ecabd`
> fix: reduce decimals to percentage

- apps/cowswap-frontend/src/api/cowProtocol/hooks.ts
- apps/cowswap-frontend/src/legacy/hooks/useGasPrice.ts
- apps/cowswap-frontend/src/legacy/hooks/useTokenAllowance.ts
- apps/cowswap-frontend/src/legacy/state/cowToken/hooks.ts
- apps/cowswap-frontend/src/modules/notifications/hooks/useUnreadNotifications.ts
- apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/hooks.ts
- libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
- libs/ens/src/hooks/useENSAvatar.ts
- libs/ens/src/hooks/useENSRegistrarContract.ts
- libs/ens/src/hooks/useENSResolver.ts
- libs/ens/src/hooks/useENSResolverContract.ts
- libs/ens/src/hooks/useENSResolverMethod.ts
- libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
No function changes, just refactor SWR usage.
Not sure whether it was working 100% before or not, but I noticed that we were not properly passing the arguments to the fetcher fns when using `useSwr`.
See the examples in their docs for reference https://swr.vercel.app/docs/arguments
The changes here mostly:
1. Short circuit the conditions to run the query one level above
2. Pass all the fetcher arguments as parameters
Everything should work as before...
1. Orders fetching
4. Gas price fetching
5. Allowance fetching
6. vCow balances/swappable amount
7. Everything ENS related
8. Notifications
9. Native token balance
10. Locked GNO
11. Smart contract detection (besides the Safe)
> refactor: update useSwr usage

- apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts
Fixes #4595
The header menu "Trade" uses `useTradeRouteContext()` for building links.
This hook wasn't considering the case when we navigate to not trade page (e.g. account page).
When we in Account page, then `useTradeState()` returns undefined and the links in the menu are not correct.
There are two cases:
1. We came to Account page from trade widget
2. Account page was just open (there are no items in the History API)
In the first case we should just take the previous value of the context.
In the second case we don't have previous context and we should use default one (`getDefaultTradeRawState`).
See #4595
> fix(trade): keep trade state after navigating from trade widgets

- apps/explorer/src/components/orders/DetailsTable/index.tsx
- apps/explorer/src/components/orders/OrderDetails/index.tsx
This PR is a personal suggestion of something that I didn't love of the explorer, and decided to suggest in for of a PR. 
Basically, I find it always very difficult to check the Etherscan transaction of a settlement. This is something users like to be able to easily check. Among other things, you can see the actual execution time (not displayed right now in the CoW Explorer) and also you can see the actual transfer amounts.
Before, if you wanted to go to the explorer you have to:
Alternatively, you can:
1. Copy the hash
2. Open a new tab in Etherscan
3. Search by hash
I do regularly both approaches, and I don't love the UX  😢
I just made the link to take you to Etherscan directly. I also added an additional button and shorten the labels of the buttons:
After discussing what we should do …
> feat: add easy link for Etherscan

- apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/RecipientRow/index.tsx
Swap/Limit/Twap:
When custom recipient is set, then it should be displayed on confirm screen. The recipient value should be a link to etherscan.
> feat: add a link to recipient address

- libs/widget-lib/src/cowSwapWidget.ts
> fix(widget): allow using clipboard in iframe

- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
Fixes #4596 
Remove the bit where we ask to refresh the page in the Safe signer tooltip.
Check the issue description
> fix(safe): update signer tooltip decription

- apps/explorer/src/hooks/useOperatorTrades.ts
Fixes #4417 
Invert Explorer fills table sorting order.
Newest trades are shown first.
1. Open an order with lots of fills, such as `0x403bdded2c50f727ea3c38f951d1a4f89b0f7313beeb4bd86da4ee1d06b642a6ce8c14435fe642f2af259a768e060c4e845606c3671e957a`
* Newest trades should be shown first
> fix(explorer): invert fills table order (newest first)

- libs/common-const/src/tokens.ts
No changes, just added a comment about updating the docs when `GNOSIS_CHAIN_STABLECOINS` change.
Nothing changed
> chore: add note about stable coins and docs fees

- apps/cowswap-frontend/vercel.json
To properly configure redirects due to the usage of the HashRouter on https://github.com/cowprotocol/cowswap/pull/4643, the use of vercel.json for cowswap-frontend app was introduced.
To make it work though, the build settings needed to be updated, as well as the app's root directory.
Based on [this answer](https://github.com/orgs/vercel/discussions/2074).
In this PR, I'm adding the build settings to vercel.json, to more easily visualize and version control the settings changes.
The [vercel.json settings available](https://vercel.com/docs/projects/project-configuration) do not include however the root directory. That can be configured in the UI only.
Not testable.
> chore: add custom build settings

- libs/widget-lib/src/cowSwapWidget.ts
The bug was reported by @compojoom 
When we navigate to some external link inside of widget iframe and go back, we don't "ACTIVATE" event and hence don't send "UPDATE_APP_DATA".
The case might be tested only after releasing a new `@cowprotocol/widget-react` version and upping it in Safe app.
1. Open https://feat_swaps_fees--walletweb.review.5afe.dev/
2. Go to Swap page
3. Setup some trade
4. Open "Widget Fee (0.35%)" tooltip
5. Click to "tiered widget fee" link
6. Navigate back using history API
7. Create an order
8. AR:order appData contains "CoW Swap-SafeApp" code
9. ER: order appData contains "Safe Wallet Swaps" code
> fix(widget): always listen activation event

- libs/widget-lib/src/cowSwapWidget.ts
Cherry-picked fix(widget): always listen activation event (#4670)
> fix(widget): always listen activation event (#4670)

- apps/cowswap-frontend/src/modules/injectedWidget/index.ts
- apps/cowswap-frontend/src/modules/injectedWidget/pure/WidgetMarkdownContent/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
In Widget we provide an option to customize some texts using Markdown.
Markdown might contain links.
Due to widget links policy, we have to open any of them in a new tab.
1. Open https://feat_swaps_fees--walletweb.review.5afe.dev/
2. Go to Swap page
3. Setup some trade
4. Open "Widget Fee (0.35%)" tooltip
5. Click to "tiered widget fee" link
6. ER: the link should be open in a new tab
> fix(widget): always open links from widget markdown in a new tab

- libs/widget-lib/src/flexibleConfig.ts
- libs/widget-lib/src/types.ts
Initially, the problem was with Next.js apps. They were crashing due to using `window`.
The problem was introduced in [this change](https://github.com/cowprotocol/cowswap/pull/4407/files#diff-381419bc0262706d9ab2bb2d885a8e794804ad54bf71dffe5d7a029d835eaf9fR3).
And then I also strengthened it [here](https://github.com/cowprotocol/cowswap/pull/4546/files#diff-92467ccfefe8743e757f1b45dac0986badce93e645f43416e4da35abdc28ad76R1).
So, the problem in the fact that cow-sdk was included in the widget-lib.
Before
```
[vite:dts] Start generate declaration files...
computing gzip size (0)...[vite:dts] Declaration files built in 391ms.
../../dist/libs/widget-lib/index.mjs  1,620.88 kB │ gzip: 328.53 kB
../../dist/libs/widget-lib/index.js  960.58 kB │ gzip: 286.46 kB …
```
> fix(widget-lib): exclude cow-sdk from the bundle

- apps/cowswap-frontend/src/assets/icon/caret.svg
- apps/cowswap-frontend/src/assets/icon/carret.svg
- apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/containers/TradeButtons/index.tsx
- apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater.ts
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts
- apps/cowswap-frontend/src/modules/trade/updaters/RecipientAddressUpdater.tsx
- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
Follow up to https://github.com/cowprotocol/cowswap/pull/4672 and/or https://github.com/cowprotocol/cowswap/pull/4678 (not sure which introduced the bug or not).
Show `enter a price` when LIMIT price is missing, even when approval is required.
1. On LIMIT with an EOA, select a buy token and a sell token that needs approval (and is not permittable)
* Approval button should be displayed
2. Clear out the price
* Approval button should NOT be displayed
* Button should be disabled and display `Enter a price`
3. Repeat with Safe app
* Bundling button should be displayed and enabled
4. Clear out the price
* Button should be disabled and display `Enter a price`
5. LIMIT, SWAP and TWAP should work as before
> fix(limit): missing price error takes precedence over missing approval

- apps/cowswap-frontend/src/common/constants/routes.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useTradeTypeInfoFromUrl.tsx
Fixes #4662 (only points 1 and 2)
>When I specify a hook first (pre or post, or both), then try selecting a buy token, the buy token can't be picked. Same for a sell token if I'd like to change it.
>When I change a chain in the app, additional chain indicator appears in the URL  ?chain=gnosis_chain. And this looks a bit weird to have 2 different chain indicators in the URL. And when I navigate between pages, the app asks to change the chain according to the numeric indicator in the URL
1. Changed the URL path from `/hooks` to `/swap/hooks` because it's more specific
2. Adjusted trade type detection for Hooks page
1. Open hooks page
2. Try changing sell/buy tokens
> fix(hooks): link hooks page to swap trade state

- apps/explorer/src/components/orders/DetailsTable/index.tsx
Fixes the issue with broken links for gnosis chain
You can see staging broken for GC if you click here: https://staging.explorer.cow.fi/gc/orders/0x0520043f5c8f642ddeefaa2648239b5681413686c5c1c11f9b3ec4241441b84179063d9173c09887d536924e2f6eadbabac099f566867f85?tab=overview 
But works in staging mainnet:
https://staging.explorer.cow.fi/orders/0x22fe1a6ac14870eb6784d61ee3f06821b342f6b9a4526255edd5f7ebd0d2aecc79063d9173c09887d536924e2f6eadbabac099f5668d635d?tab=overview
Test those links for all networks
> fix: fix broken links in gnosis chain

- apps/cow-fi/pages/learn/[article].tsx
- apps/explorer/src/components/orders/DetailsTable/index.tsx
- Right now new pages to the CMS aren't directly available as (url) paths on cow.fi. By changing the `fallback` setting in `getStaticPaths` from `false` to `blocking` as per https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#fallback-blocking it should fix that
> fix: cow-fi - generate non existing paths

- apps/cowswap-frontend/src/modules/appData/index.ts
- apps/cowswap-frontend/src/modules/appData/types.ts
- apps/cowswap-frontend/src/modules/appData/utils/appDataFilter.ts
- apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
- apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
- apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
- libs/permit-utils/src/const.ts
The permit hook address suddenly has tens of approvals starting today https://revoke.cash/address/0x4ed18E9489d82784F98118d5A6aB3AD4340802fb?chainId=1
The error linked in this sentry notification seems to match this order https://explorer.cow.fi/orders/0x78f14fa6fc379d2029ba467b97d25506efc0af5af8e806eb6736c999090d5f55488b99c4a94bb0027791e8e0eeb421187ec9a48766952228?tab=overview
The appData contains 2 hooks:
- 1 approving the permit
- 1 approving the user's trade
~While I have not been able to reproduce the issue, this change should prevent the order from ever including the permit signer hook.~
It's easily reproducible, every order should contain and log when the faulty permit is present.
1. Pick a permittable sell token with no approvals
2. Proceed until the after the confirmation modal
* …
> fix(permit): filter out permit signer and rotate it

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts
- apps/cowswap-frontend/src/modules/limitOrders/state/limitRateAtom.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/useSetupTradeAmountsFromUrl.ts
Fixes #4666
In limit orders we have initial price which is a value derrived from `/native_price` API.
Recently I added `SetupLimitOrderAmountsFromUrlUpdater` which fills limit-orders state with amounts from URL.
Those two mechanisms were conflicting and it caused from price values.
After this fix:
- if state was filled from URL
- then don't updated it with an initial price
1. Open Swap, set Sell 4000 WETH
2. Remember the output amount 
3. Navigate to Limit orders
4. ER: the form contains exactly the same sell/buy amounts as in Swap page
5. ER: the limit price = buyAmount / selAmount
> fix(limit-orders): don't override price from URL with initial value

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/types.ts
- libs/widget-lib/src/types.ts
Add option to disable progress bar completely:
Once disabled, this is what will be shown after order placement:
⚠️ Note: backend not yet working. Progress bar displayed will not move ⚠️ 
1. In the widget configurator, keep the progress bar enabled
2. Place order
* Should see progress bar (even though not moving)
3. In the widget configurator, disable the progress bar
4. Place order
* Should NOT see the progress bar
5. On regular CoW Swap, place order
* Should see progress bar (even though not moving)
> feat(progress-bar-v2): add widget setting to disable progress bar

- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
Show Safe info after order is placed in the confirmation modal until it's executed.
Once executed, show progress bar.
Same logic applies for any other SC wallet, except the safe signers.
⚠️ Styling not included
⚠️ Progress bar will not move, pending backend changes
1. With a 2/n Safe, place an order via Safe app
* After the first signature, the UI should show the number of signatures left
* Progress bar should not be shown
2. Finish signing but without executing
* Signatures count should update and should say it needs execution
* Progress bar should not be shown
3. Execute
* After tx is mined, progress bar should be displayed
4. Repeat with Safe via WC
* Should have the same result
5. Repeat with non-Safe based SC wallet (is there any?)
* Should not show Safe signatures
* Should not show …
> feat(progress-bar-v2): show safe info when pending

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/progressBarV2StateMachine.md
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
Fix items `5` and `7` from https://github.com/cowprotocol/cowswap/pull/4748#pullrequestreview-2215924014
Out of market should not take precedence over expired, cancelled and so on.
1. Place order
2. Somehow make it be out of market
3. Cancel it
* Screen should switch to cancelled screen
4. Set a short expiration time, repeat 1 and 2
5. Wait for it to expire
* Screen should switch to expired screen
> fix(progress-bar-v2): deprioritize out of market stats

- apps/cowswap-frontend/src/legacy/utils/priceLegacy.ts
- apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
Remove `0x` price source
Remove `paraswap` (was already disabled but some code was still there)
Remove legacy `gp` price source (same as paraswap)
1. Place order with short expiration
2. Let it expire
3. Observe the console network tab
* When `quote` endpoint fails, there should be no `0x` api calls
> chore: remove outdated legacy price sources

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/common/pure/CancelButton/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
Wire up cancellation
Pipes into https://github.com/cowprotocol/cowswap/pull/4033
1. Place regular order
2. Click on `cancel` from top right
* Should trigger cancellation
3. Place Ethflow order
4. Click on `cancel` from top right
* Should trigger cancellation
5. Place order and make it out of market
* Should show out of market screen and offer cancellation button
6. Click cancellation button
* Should trigger cancellation
> feat(progress-bar-v2): wire up cancellation

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
Fix item `9` from https://github.com/cowprotocol/cowswap/pull/4748#pullrequestreview-2215924014
Disable progress bar when creating or presign pending.
Once order is created/signed, it'll start querying the status.
If in the mean time (from creation/signature) it might already have moved on from the initial state.
1. Place eth flow order
* Progress bar should start only after order is created
> fix(progress-bar-v2): disable progress bar when creating or presign pending

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapModals/index.tsx
- Update surplus logic
- Refactor some local formats to use `<TokenAmount/>` component
- Disable previous surplus modal 
- ⚠️ now surplus is only visible while the progress bar modal is open! ⚠️ 
- TODO: Use the new styles for the former surplus modal
- Updated the amount displayed at the bottom to show the surplus amount instead of USD twice
- Pop up new modal when progress bar is closed
- `Share this win` button action
1. Place order with high slippage
* Once traded, surplus will be shown
> feat(progress-bar-v2): wire up surplus

- apps/cowswap-frontend/src/common/pure/CoWAMMBanner/index.tsx
- apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
- Adds a banner for CoW AMM on CoW Swap
- On click of X should close and remember this (localStorage) using existing closable banner component
- On click of CTA button shoudl track GA event
https://github.com/user-attachments/assets/4b15a886-801c-494a-838e-7173b2317130
> feat: add cow amm banner

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
Use global rather than local state for the countdown
1. Place order
2. While the countdown is running, open the activity modal
* Countdown should continue from where it was rather than start at 15s
> fix(progress-bar-v2): use global state countdown

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/utils/orderUtils/getIsCustomRecipient.ts
Add recipient address (including ENS name) to finished screen, if any
1. Place a swap with a custom recipient
* Should be mentioned in the success screen
2. Place a swap without custom recipient
* Should look like before, and not have the recipient
> feat(progress-bar-v2): custom recipient

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/swap/containers/EthFlowStepper/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
Add [`disableProgressBar` feature flag](https://app.launchdarkly.com/projects/default/flags/disableProgressBar/targeting?env=production&env=barn&env=staging&env=test&env=develop)
1. Turn `disableProgressBar` feature flag on
2. Place SWAP order
* There should be no progress bar displayed
3. Turn it off
* Progress bar should be displayed
4. Check also ethflow & Safe flows for regression
> feat(progress-bar-v2): add disableProgressBar feature flag

- apps/explorer/.env.example
- apps/explorer/src/const.ts
- libs/common-utils/src/environments.test.ts
- libs/common-utils/src/uriToHttp.test.ts
- libs/common-utils/src/uriToHttp.ts
cloudflare-ipfs.com domain is being removed
1. Open the cowswap and exploerer and make sure it works as usual
2. Token lists should load
> fix: replace cloudflare-ipfs.com with ipfs.io

- apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
- apps/cowswap-frontend/src/modules/analytics/events.ts
- apps/cowswap-frontend/src/modules/notifications/containers/NotificationBell.tsx
- apps/cowswap-frontend/src/modules/notifications/containers/NotificationsList/index.tsx
Add analytics events for notifications. Tracks how effective are the notifications, and verify they have the desired effect
Before you start, activate debugging for the analytic events
1- Create a notification in the CMS: I can help with this too 
2- Click on the bell --> make sure the event 
3. Click on the event itself to open the link --> `click-notification-card` should be triggered. Also, as value should go the id and the label the title of the notification
5. Once the notification is read. Click again in the bell to see the event now is different (because the bell don't have the red dot any more)
> feat: add analytics for notifications

- apps/cowswap-frontend/src/common/pure/CoWAMMBanner/index.tsx
Adds a new event to the closing of the banner
- Enable debug for analytics
- Click on the close button for the cow amm banner
- Inspect the event
> feat: add analytics event for closing CoW AMM banner

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/atoms.ts
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
Fix enforcement of min 5s display time for any screen
1. Place order
2. Observe screen switching
* Any screen should be displayed for at least 5s
* No hard reproduction steps, but very likely after the countdown reaches 0 the next screen should be displayed for 5s now, which before was just a blink
> fix(progress-bar-v2): fix min display time

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
- libs/core/src/cms/hooks/index.ts
- libs/core/src/cms/hooks/useCmsSolversInfo.ts
- libs/core/src/cms/hooks/useSolversInfo.ts
- libs/core/src/cms/index.ts
- libs/core/src/cms/state/index.ts
- libs/core/src/cms/types.ts
- libs/core/src/cms/updaters/SolversInfoUpdater.ts
- libs/core/src/cms/updaters/index.ts
- libs/core/src/cms/utils/getCmsClient.ts
- libs/core/src/cms/utils/getSolversInfo.ts
- libs/core/src/cms/utils/index.ts
- libs/core/src/cms/utils/mapCmsSolversInfoToSolversInfo.ts
- package.json
- yarn.lock
Load solvers info from CMS
- Solver display name
- Solver image
- Total number of solvers
- Fixed solver ranking sorting (it was inverted)
1. Place order
2. Wait for order to execute
* Total number of solvers should match the chain (mainnet: 24, gchain: 11, arb1: 13, sepolia: 3)
* Depending on the solver, there might be custom images
> feat(progress-bar-v2): load solvers info from cms

- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
Safe signing added on https://github.com/cowprotocol/cowswap/pull/4755 got lost during a merge.
Adding it back:
1. Place order with Safe
* Signing steps should be displayed when needed.
> fix(progress-bar-v2): add Safe signing back

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- Increase min display time from 2s to 5s
- Override state immediately when finished
1. Easier to observe on arb1, place order
* Immediately after getting the traded notification it should jump to the finished screen, regardless of how long the screen was displayed before
> feat(progress-bar-v2): increase min display to 5s and override on finished

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
Follow up to https://github.com/cowprotocol/cowswap/pull/4804
Allow all finished states to override minimum display time of 5s per screen.
1. Place order
2. Cancel/expire it
* Should change to final screen right away instead of waiting for 5s
> feat: allow all final states to override minimum display time

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
- Changes the order of showing solver ranking table and sell/buy/surplus amounts
> feat: reorder ranking and order

- apps/cowswap-frontend/src/common/pure/CancelButton/index.tsx
- apps/cowswap-frontend/src/common/pure/Modal/styled.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/SurplusModal.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.cosmos.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/styled.tsx
- apps/cowswap-frontend/src/legacy/components/TopLevelModals/index.tsx
- apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts
- apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/StatusDetails.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/styled.ts
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SurplusModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapModals/index.tsx
- apps/cowswap-frontend/src/theme/components.tsx
- Re-enable surplus modal pop-up when progress bar is closed
- Remove progress bar from activity modal
- Add button to bring progress bar back/focus on running progress bar
1. Place order, don't close modal
2. Open activity modal
* There should be an ugly `show progress` button
3. Click on `show progress`
* Should close the activity modal and existing progress bar should be running
4. Close progress bar
5. Open activity modal
6. Click on `show progress`
* Should close activity modal and show progress bar in another pop-up modal
* Everything in this modal should work like regular modal (cancel button, expired link, etc)
7. Place order with high slippage (50%) for making sure there'll be surplus
8. Close progress bar and wait for it to trade
* When traded, progress bar should pop-up in a …
> feat: re-enable surplus modal pop up

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
To avoid situations where countdown reaches 0 only once and follow up cycles end up going straight away to `delayed` step, this change resets it every time the backend state is not `active`.
1. No recipe for triggering this as it's dependant on failure states (failed to execute, failed to solve)
> fix(progress-bar-v2): reset countdown every time not in 'active' state

- apps/cowswap-frontend/src/legacy/components/Header/styled.tsx
Fixes https://github.com/cowprotocol/cowswap/pull/4811#issuecomment-2299206850
Now you _must_ close it in order to see the rest of the info, like on desktop view
1. On mobile, place order
2. Close progress bar
3. Open account modal
4. Click on `show progress`
* Progress bar is displayed
* Pending button is hidden
> fix: do not show header controls when progress bar is shown

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
- libs/core/src/cms/types.ts
- libs/core/src/cms/utils/getSolversInfo.ts
- libs/core/src/cms/utils/mapCmsSolversInfoToSolversInfo.ts
Show solver description from CMS on a tooltip
In this example, all the `<name> API` were set to `Operated by GnosisDAO`
1. Place order on arb1/mainnet
2. Wait for it to trade
3. Hover over the solvers (if present): 0x, 1inch, Paraswap and Balancer
* Should contain `Operated by GnosisDAO` tooltip
> feat(progress-bar-v2): show solver description if set

- apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
- apps/cowswap-frontend/src/modules/account/containers/Transaction/StatusDetails.tsx
Do not show button `show progress` when progress bar is disabled
1. Using the widget, place an order
2. Disable progress bar
3. Open activity modal
* Should not have `show progress` for the pending order
> fix: hide 'show progress' when progress bar is disabled

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
1. Place order and observe finished screen
* Should not have amounts at the top like previous screens
> feat: do not show amounts on finished step

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
If we previously have a state that was NOT initial, and attempt to get back to it, move to delayed instead
1. Tricky. Place several orders on arb1 and hope for the best, I guess.
> feat: once moved out of initial, do not go back to it

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/atoms.ts
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts
- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
To accommodate potential race condition issues, this change stores previous backend api status in the state and uses it when checking for the state change leading to `submissionFailure`.
1. Place order better on arb1 as block times are super short there
2. Wait for an order in `executing` stage go back to `solving`
* It should go to `submissionFailure` step after `executing` and before `solving`
> fix(progress-bar-v2): previous backend status

- apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
- apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater.ts
- libs/common-utils/src/tooltips.ts
Changes the text for the smart slippage and adds a tooltip
This PR will use BFF for estimating the slippage tolerance. Specifically uses this: https://github.com/cowprotocol/bff/pull/84
This implementation has been deployed to BARN, so it should have #84 applied:
https://bff.barn.cow.fi/1/markets/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-0x2260fac5e5542a773aa44fbcfedf7c193bc2c599/slippageTolerance
Select different markets, and check how it change the default slippage suggested by the app.
Make sure the trades go trough even for illiquid markets.
It might be helpful to check coingecko to understand why sometimes is the number higher, like in AAVE token (1.84%)
> feat: add tooltip and change message

- apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts
- apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
Fix css on cancellation failed banner when combined with ethflow
With banner
Without banner
1. Place ethflow order
2. Cancel it 
3. Hope cancellation fails
* Cancellation failed banner should be displayed
> fix(progress-bar-v2): adjust cancellation failed banner when combined with ethflow

- libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
Fixes #4753
`useEagerlyConnect()` hook is supposed to be called only once on app start.
But, due to `selectedWallet` dependency it is called again after disconnect+connect.
To prevent this I added a boolean reference.
See #4753
> fix(wallet): connect eagerly only once

- apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx
- apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
Fixes #4799
There was a bug with displaying the price protection value (introduced after adding partner fee).
See #4799
> fix(twap): display relevant price after slippage

- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
- apps/cowswap-frontend/src/modules/twap/utils/twapOrderToStruct.ts
- libs/common-utils/src/fractionUtils.ts
Fixes #4830
When price protection is 100% in TWAP we can't calculate the limit price (because we can't divide on zero).
To avoid crashing, we have to check buyAmount after slippage and if it equals zero, then don't calculate and display the limit price.
See #4830
> fix(twap): don't crash when slippage is 100

- libs/events/package.json
- libs/events/src/types/orders.ts
- libs/events/vite.config.ts
- libs/types/package.json
- libs/types/src/hooks.ts
- libs/types/vite.config.ts
- libs/widget-lib/package.json
- libs/widget-lib/vite.config.ts
- libs/widget-react/package.json
- libs/widget-react/src/lib/CowSwapWidget.tsx
- libs/widget-react/vite.config.ts
Fixes https://github.com/cowprotocol/cowswap/issues/4833
Short summary: this change, among other things, makes use of `https://www.npmjs.com/package/vite-plugin-dts` property `pathsToAliases` to disable the local path aliasing for given libs.
Before this change, the paths were converted to local path in the exported libs, resulting in errors when those were consumed.
Additionally, added missing dependencies to the individual lib package.json files and imported/exported types with the `type` keyword.
1. Test the app and the widget
* Should work as before
> fix(libs): fix import error on multiple libs

- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts
- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useTradeStateFromUrl.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts
- apps/cowswap-frontend/src/modules/trade/state/tradeStateFromUrlAtom.ts
Fixes #4879
Due to a race condition between parent widget props and inner app state, the tokens endup flickering non-stop.
This change makes sure on the first load, the app refrain from sending the state update event.
The side effect is that the state previously set in the widget will be always cleared in favor of the param coming from the parent widget - but only if they listen to the widget events.
1. Use this PR's deployment URL into Safe UI. Might require running a local version of the Safe
> fix(widget): widget tokens flickering

- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Since the recent fix about widget flickering, `tradeStateFromUrl` became nullable (it is null at the very beginning).
Because of that, the value of `currentChainId` sets to `SupportedChainId.MAINNET` and it triggers network switching.
1. Connect Metamask with Sepolia
2. Refresh page
3. AR: it requests network switching to Mainnet
4. ER: no network switching request
> fix: don't request network switching at page load

- libs/common-utils/src/amountFormat/index.test.ts
- libs/common-utils/src/amountFormat/utils.ts
Now it'll show up to 18 decimals, if the value is small enough.
Side effect is that the UI might break a little (see pic).
1. Place order with huuuuuuuge price difference
* Observe the amounts being properly visible
> fix(amounts-display): increase precision for small amounts

- libs/tokens/src/utils/validateTokenList.ts
Context: https://cowservices.slack.com/archives/C05QVFJUX9R/p1726893122604539
We currently use [Uniswap token lists validation schema](https://github.com/Uniswap/token-lists/blob/main/src/tokenlist.schema.json) and it's strct enough.
In order to support new requirements I changed the validation schema:
- TokenInfo.symbol max length not 80 and pattern is `^[\w\d\-\+_\.\s]+$`
- TokenInfo.name max length not 100 and pattern is `^[\w\d\-\+_\.\s]+$`
https://raw.githubusercontent.com/cowmarketing/cowidget-custom-token-lists/refs/heads/main/pendle_pt.json - should be added into CoW Swap with no valdiation errors
> fix(token-list): increase token symbol validation length

- apps/explorer/src/components/common/TokenDisplay/index.tsx
- apps/explorer/src/components/common/TokenImg.tsx
Context: https://cowservices.slack.com/archives/C04DV3TL1MH/p1727332936250749
The code which is responsible for token logos displaying is super legacy.
It mainly gets logos for Trust wallet repo.
But in Explorer we already have many token lists loaded (CoWSwap, Coingecko, etc.) and it's obvious we should rely on them first.
1. Open http://localhost:4200/orders/0xfa41f84ccd12b6d0fddc52a82090554101502f4586e86ad4a4d3050f67e34c8a42d9e44eed903a0ee477c9c04d1d1730c5e8727266f4937f?tab=overview (with the corresponding domain of course)
> fix(explorer): get token logo url from known token lists

- apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddCustomHookDapp.ts
- apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
- apps/cowswap-frontend/src/modules/hooksStore/updaters/iframeDappsManifestUpdater.tsx
- apps/cowswap-frontend/src/modules/hooksStore/validateHookDappManifest.tsx
In [this PR](https://github.com/cowprotocol/cowswap/pull/4910), I added a functionality to import custom hook-dapps using iframes.
This mechanism fetches manifest.json and save it content into localStorage.
As @yvesfracari noticed, the saved info never gets updated.
To fix that I added `IframeDappsManifestUpdater` which tries to update all custom hook-dapps, but not often than 6 hours.
1. Add a custom hook-dapp (see the mentioned PR above)
2. Change something in its manifest (for example image)
3. Remove `HOOK_DAPPS_UPDATE_TIME` from localStorage
4. Update the page
> feat(hooks-store): update custom hook-dapps manifests periodically

- libs/tokens/src/const/tokensList.json
To have more tokens available on arb1, this change adds Balancer token list.
It's disabled by default to reduce performance impact.
1. Connect to arb1
2. Check the loaded token lists
* It should have balancer
3. Check other chains
* It should not have balancer
> feat(token-lists): add balancer token list to arb1

- apps/explorer/src/components/orders/OrderHooksDetails/index.tsx
Order example: https://explorer.cow.fi/orders/0x1fc821545e8df229e80418060afbe15d01d1ab1c5dc2b7337c3016a6869aaf31aad621bfbb284bb82c47d77429585baf986e98bb670d2593?tab=overview
> fix(explorer): do not crash when appData is not parsed

- apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
- apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/index.ts
- libs/common-const/src/misc.ts
Follow up to https://github.com/cowprotocol/cowswap/pull/4934, addressing these comments https://github.com/cowprotocol/cowswap/pull/4934#issuecomment-2405122518 from @MindyCoW 
Additionally, makes sure the `High slippage amount selected` in the settings tab is only displayed if user picks a value above the suggested slippage - if any. Otherwise sticks to the default of 1%.
1. Check the texts with and without smart slippage selected match https://github.com/cowprotocol/cowswap/pull/4934#issuecomment-2405122518
* Should match
2. In the settings modal, set a slippage amount higher than the suggested slippage
* Should show `High slippage amount selected`
3. When suggested amount is > 1%, set a slippage amount > 1% and smaller than suggested slippage
* Should not show `High slippage amount …
> feat(smart-slippage): update smart slippage text

- apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetupHooksStoreOrderParams.ts
- libs/hook-dapp-lib/src/types.ts
Just extended the hook-dapp context with order sell/buy amounts
No need to test
> feat(hooks-store): add sell/buy amounts to hook-dapp context

- apps/explorer/src/components/orders/OrderHooksDetails/HookItem/index.tsx
Fixes #4979
Example: http://localhost:4200/gc/orders/0x1a8188e91fc0c2a6b27e8e124b140303b9c106e97fab262a0b26732b6cde921bfb3c7eb936caa12b5a884d612393969a557d430767069044?tab=overview
> fix(explorer): display hook details of unknown hook-dapp

- apps/cowswap-frontend/src/legacy/components/NetworkAlert/NetworkAlert.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/types.ts
- libs/widget-lib/src/types.ts
Part of https://github.com/cowprotocol/cowswap/issues/4321
Follow up to https://github.com/cowprotocol/cowswap/pull/4991
Add widget param to hide bridge info
1. Open the widget configurator
2. Change to GC
* Bridge info should be visible at the bottom
3. Select the option `Hide bridge info`
* Bridge info should be hidden
> feat(widget): hide bridge info

- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
- libs/ui/src/pure/Badge/index.tsx
- libs/ui/src/pure/MenuBar/index.tsx
- Apply different badge style for 'new'
- Fix linter warning
> feat: style enhancements for badge

- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
- apps/cowswap-frontend/src/pages/LimitOrders/RegularLimitOrders.tsx
- apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
- apps/widget-configurator/src/app/configurator/index.tsx
- apps/widget-configurator/src/app/configurator/types.ts
- libs/widget-lib/src/types.ts
Part of https://github.com/cowprotocol/cowswap/issues/4321
Follow up to https://github.com/cowprotocol/cowswap/pull/4992
Add widget param to hide orders table
2. Check limit and twap forms
* Orders table should be visible
3. Toggle `Hide orders table`
* There shouldn't be a orders table on limit nor twap form
* The regular app should work as usual
> feat(widget): hide orders table

- apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
- apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/calculateBpsFromFeeMultiplier.ts
- apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/useSmartSlippageFromFeeMultiplier.ts
Fixes #5001
Show non-dynamic slippage tooltips when feature flag is off.
This also helped me identify an issue with the feature flag that was essentially never turning off.
1. With the flag on, check the tooltips
* Should be the dynamic version
2. With the flag off (set to 0 OR having lauchdarkly requests blocked), check the tooltips
* Should be the non-dynamic version
* There should be no suggested slippage
> fix(smart-slippage): fix smart slip tooltip and feature flag

- apps/cowswap-frontend/src/cow-react/index.tsx
- libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
- libs/wallet/src/web3-react/Web3Provider/index.tsx
Fixes #5006
THe problem in the fact that we remember eip6963 provider in CoW Swap and give it more prio than widget provider.
For dapp mode in widget we should always use widget provider.
1. Open CoW Swap, connect to some eip6963 wallet
2. Open widget-configurator, use dapp mode and connect to a wallet
3. Change network in the wallet that was connected to widget-configurator
If you instead of the 1st step disconnect a wallet in CoW Swap, then everything should work well
> fix(widget): ignore selected eip6963 provider when in widget

- apps/cowswap-frontend/src/modules/trade/const/common.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
- apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
With the recent refactoring I changed false to true:
https://github.com/cowprotocol/cowswap/blob/99c4c42aec60a734a37926935be5dca6cd4cf11c/apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts#L184
Market orders should always be fill or kill
> fix(swap): disable partial fills

- apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
- Fixed and double checked sound logic across all scenarios:
**Widget Mode:**
- ✅ Custom sounds when provided
- ✅ Null -> EMPTY_SOUND
- ✅ Undefined -> Default sounds
**Normal Mode:**
- 🎄 Christmas: themed winter sounds (if available)
- 🎃 Halloween: themed sounds (dark mode only)
- 🔄 Fallback to default sounds
**Edge Cases:**
- 🎯 Widget mode always takes precedence over themes
- 🔒 No theme conflicts possible (mutually exclusive)
- 💾 Sound caching works consistently
- 🌗 Halloween properly respects dark mode
All paths have proper fallbacks, no conflicting scenarios possible.
> fix: sound widget logic

- apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
Remove `isNotificationsFeedEnabled` feature flag.
It has been enabled for awhile, we won't turn it off.
Notifications feed should be enabled
> chore(feature-flags): remove isNotificationsFeedEnabled

- apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
- apps/cowswap-frontend/src/common/state/featureFlagsState.ts
- apps/cowswap-frontend/src/modules/volumeFee/state/cowswapFeeAtom.ts
- libs/common-const/src/tokens.ts
Adds support for enabling Arb1 protocol fees for non-stable coins, based on % from feature flag.
This allows for gradual rollout, based on connected account.
Similar to Gchain fees, it's set to 0.1% on non stable to stable trades.
1. Connect on arb1,
2. Make sure the feature flag `arb1CowSwapFeePercentage` is set to a value > 0.
3. Pick a non stable pair
* Fee should be set for whatever percentage of accounts (default is 50%)
4. Pick a stable pair (any of USDC,DAI,USDT,USDE,USDM,FRAX,MIM)
* Fee should not be displayed
5. Change the percentage on launch darkly to 100% 
* Fee should be displayed for all accounts
6. Check Gnosis chain
* Fee should be displayed for all accounts (except on stable pairs)
7. Check Mainnet
* There should be no fee for any account or pair
> feat(protocol-fees): arb1 protocol fee

- apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
Fixes #4879
`derivedTradeStateAtom` initially returns a default state (DEFAULT_TRADE_DERIVED_STATE) which may cause race condition.
How it works:
1. You set some assets in Swap (/1/swap/COW/USDC)
2. You navigate from Swap to Limit orders (/1/limit/COW/USDC)
3. By default `limitOrdersDerivedStateAtom` is empty (has DEFAULT_TRADE_DERIVED_STATE value)
4. `useNotifyWidgetTrade()` sends this empty state to the integrator side
5. At the same time, `useFillLimitOrdersDerivedState()` fills `limitOrdersDerivedStateAtom` with values (COW/USDC)
6. Integrator received (ON_CHANGE_TRADE_PARAMS) an empty state from step 3, and updates widget params with them (navigate to /1/limit/_/_)
7. `useNotifyWidgetTrade()` reacts on changes from step 5 and here we go in a loop
**To avoid that I added skipping of …
> fix(widget): remove irrelevant change trade params events

- apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
- apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
- apps/cowswap-frontend/src/modules/tradeFlow/types/TradeFlowContext.ts
Fixes #5066
Did a mistake in the recent refactoring (#4950).
`const inputAmount = receiveAmountInfo?.afterNetworkCosts.sellAmount` -> `const inputAmount = receiveAmountInfo?.afterSlippage.sellAmount`
See #5066.
Please, check ETH-flow as well.
> fix(swap): take slippage into account for buy orders

- apps/explorer/src/explorer/pages/TransactionDetails.tsx
Make sure txHash on transaction view always has the 0x prefix
1. Search for a transaction hash without the `0x` prefix
* Should load as usual
* Link to etherscan should work
> fix(explorer): make sure txHash always has the 0x prefix

- apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/useRescueFundsFromProxy.ts
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
- libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
Fixes #5034
1. Send some ETH to your Shed proxy
2. Rescue the funds from Proxy using CoWSwap UI
> fix(hooks): support native currency rescuing from proxy

- apps/cowswap-frontend/src/common/constants/routes.ts
- apps/cowswap-frontend/src/common/hooks/useMenuItems.ts
- apps/cowswap-frontend/src/legacy/state/user/hooks.tsx
- apps/cowswap-frontend/src/legacy/state/user/reducer.ts
- apps/cowswap-frontend/src/modules/analytics/events.ts
- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/SettingsTab/index.tsx
- apps/cowswap-frontend/src/modules/yield/containers/YieldWidget/index.tsx
This PR allows to enable the hooks using a user setting
For simplicity I only added it in SWAP tab's setting. I think is enough for this transitory state while is not enabled by default. 
go to SWAP
See the new setting
and the tooltip
Enable it and check that you see the new tab:
> feat: enable hooks using settings

- apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/index.tsx
- apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/styled.tsx
- apps/cowswap-frontend/src/common/containers/OrderHooksDetails/index.tsx
- apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
- apps/cowswap-frontend/src/modules/combinedBalances/hooks/useTokensBalancesCombined.ts
- apps/cowswap-frontend/src/modules/combinedBalances/state/balanceCombinedAtom.ts
- apps/cowswap-frontend/src/modules/combinedBalances/updater/BalancesCombinedUpdater.tsx
- apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
- apps/cowswap-frontend/src/modules/tenderly/hooks/useSimulationData.ts
- apps/cowswap-frontend/src/modules/tenderly/hooks/useTenderlyBundleSimulation.ts
On the current implementation of the `combinedBalances` module the swap widget on the Hook tab is slow / stuck. This is happening because the `applyBalanceDiffs` to add the token amount changes from pre-hooks is slow and is being triggered more times than it should be.
This PR resolves these two issues by:
- Refactoring the `combinedBalances` from memory to a state;
- Using an Updater strategy to only update the state once per parameter change;
- Optimize the `applyBalanceDiffs` function knowing that the `currentBalances` object is larger than the `balanceDiff` object.
1. Open the Hook tab
2. Add a pre-hook that would add tokens to you (I usually use the Claim Airdrop on Sepolia or Withdraw CoW AMM on any chain)
3. Test the swap widget if it the UX is smooth or not.
Also, this …
> fix(combinedBalances): Optimize balance diff calculations

- apps/cowswap-frontend/src/common/hooks/useNavigate.ts
- apps/cowswap-frontend/src/modules/application/containers/App/RoutesApp.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/styled.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/cowswap-frontend/src/pages/Hooks/cowShed.tsx
This PR removes ther recue funds link from the top and move it to a banner on the top. It also hides the bridging banner that SWAP has (for bridging tokens in Gnosis Chain for example)
It also moves the content of cow-shed to a new page.
This page tries to give more context to the user on what cow-shed is, what his address, why would they want to need to rescue funds, and how do they do it
> fix: add cow-shed page

- apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
- libs/hook-dapp-lib/src/hookDappsRegistry.json
- libs/hook-dapp-lib/src/utils.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1731578583848349
Explorer in dev will not detect hook dapps for orders created in this PR! It will display "Unknown hook dap".
But Explorer from this PR should display all fine.
Just make sure that `dappId` in appData is readable now.
> refactor(hooks-store): use readable string as hook-dapp id

- libs/hook-dapp-lib/src/index.ts
`hookDappsRegistry` was imported as JS module and had `default` property
> chore: fix hooks store registry import

- apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx
- apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/styled.ts
- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/styled.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
- libs/ui/src/pure/FiatAmount/index.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/5084
> feat: refactor trade container styles

- apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/index.tsx
- apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/styled.tsx
- apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/5078
- Partly addresses https://github.com/cowprotocol/cowswap/issues/5116 (doesn't change the message)
https://github.com/user-attachments/assets/80a2d418-c771-4e0f-ab2c-14fb95c50390
- Add custom post hook
- Paste url `https://cow-hooks-dapps-create-vesting.vercel.app/`
- Should automatically trim the last '/' from the url to `https://cow-hooks-dapps-create-vesting.vercel.app`
> feat: fix custom hook alert title and trim slash from url

- apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/PostHookButton/index.tsx
- apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/PriceUpdatedBanner/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/5098 
https://github.com/user-attachments/assets/b153cb33-a6aa-4257-9f62-3fa9201a5929
> feat: add loading logo for hook

- libs/common-const/src/tokens.ts
Fixes #5114
Added USDC.e (https://arbiscan.io/address/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8) to the stablecoins list on Arbitrum (stablecoins are not taxed by volume-fee)
Docs update: https://github.com/cowprotocol/docs/pull/431
1. Set USDC.e/USDT swap on Arbitrum
2. Expand price details
> fix(volume-fee): do not add fee for USDC.e on arb

- apps/cowswap-frontend/src/legacy/components/NumericalInput/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
Fixes #5110
1. Added a condition in order to avoid price calculation when sell amount is enormuosly big to avoid app crashing
2. Limited amount input with 32 chars (it was 79 since 2020)
See #5110
> fix(limit-orders): do not crash when sell amount is giant

- apps/widget-configurator/src/app/configurator/index.tsx
- libs/widget-lib/package.json
- libs/widget-lib/src/cowSwapWidget.ts
- libs/widget-lib/src/types.ts
https://www.titanxhub.com/swap - if you click "connect wallet" in the widget here, you will see that the modal is displayed not correctly.
It happens because we always take `document.body.offsetHeight` as a max height for the widget.
In order to handle that, I've added a new parameter - `maxHeight`.
1. Scroll widget configurator settings to the bottom (see the pic bellow)
2. Input `{"maxHeight": 200}` in "Raw JSON params" field
3. Click "Update widget"
> feat(widget): add maxHeight parameter for the widget

- apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
- apps/cowswap-frontend/src/modules/hooksStore/state/hookDetailsAtom.ts
- apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
- apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts
- apps/cowswap-frontend/src/modules/usdAmount/services/fetchCurrencyUsdPrice.ts
- apps/explorer/src/api/tenderly/tenderlyApi.ts
- apps/explorer/src/state/erc20/atoms.ts
- libs/balances-and-allowances/src/state/balancesAtom.ts
- libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
- libs/tokens/src/hooks/tokens/unsupported/useUnsupportedTokens.ts
- libs/tokens/src/state/tokenLists/tokenListsActionsAtom.ts
- libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
- libs/tokens/src/state/tokens/allTokensAtom.ts
- libs/tokens/src/state/tokens/unsupportedTokensAtom.ts
- libs/tokens/src/state/tokens/userAddedTokensAtom.ts
- libs/tokens/src/types.ts
- libs/tokens/src/updaters/TokensListsUpdater/index.ts
- libs/types/src/common.ts
Make CoW Swap more resilient for run-time errors when we introduce new networks.
Every addition of a new chain makes us increase the version all the local storages that have some state per network.
This is because a lot of state is model as `Record<SupportedChainId, MyState>>`, because `SupportedChainId` type is changes with the addition of a network, we need to version the local storage key.
This makes all users to loose their state or settings.
What is worse is that, updating the version is something super easy to forget to do, and if you forget to do it for one of the states it will easily lead to a hard crash of the app that is:
- hard to debug
- hard to notice (only users with old states will have the issue)
The error comes from assuming the type of the deserialised state is the one …
> feat: allow adding networks without invalidating local-storage

- apps/explorer/src/explorer/pages/Order.tsx
- apps/explorer/src/explorer/pages/TransactionDetails.tsx
- apps/explorer/src/explorer/pages/UserDetails.tsx
- apps/explorer/src/explorer/pages/styled.tsx
Adding a search bar in order view s.t. users don't have to go back to homepage to look up other orders!
I used `max-width: 60rem`, `padding: 1.6rem` & styled component for consistency with this repo's convention and compatibility.
- Full-screen view
- Mobile view
- When order id doesn't exist
1. UI components are responsive in different views
2. The search bar can work/search 
3.  The search bar won't show up when there's already a search bar at `Search not found` page
> feat(explorer): add search bar in order view

- apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
- apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
Fixes #5128 and #1412 
Since "Change wallet" functionality add more troubles than value, we decided to get rid of it.
> fix(wallet): remove change wallet feature

- apps/cowswap-frontend/src/modules/usdAmount/state/usdTokenPricesAtom.ts
USD value is not displayed for TITANX (address 0xf19308f923582a6f7c465e5ce7a9dc1bec6665b1) token because it's USD price value is too small.
@alfetopito [added](https://github.com/cowprotocol/cowswap/pull/3111) a threshold in this case, I just increased it from 1000000 up to 1000000000.
1. Setup WETH/TITANX(0xf19308f923582a6f7c465e5ce7a9dc1bec6665b1) trade in Mainnet
> fix: display usd value for tokens with small prices

- apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
- apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFeeTooltip.ts
- apps/cowswap-frontend/src/modules/volumeFee/index.ts
- apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
- apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
- libs/ui/src/pure/InfoTooltip/index.tsx
- libs/ui/src/pure/Tooltip/index.tsx
- libs/wallet/src/api/state.ts
- libs/wallet/src/api/types.ts
- libs/wallet/src/web3-react/updater.ts
Reference: https://help.safe.global/en/articles/178530-how-does-the-widget-fee-work-for-native-swaps
Basically, CoW Swap should work the same with https://app.safe.global/swap when it is open in Safe Apps.
I literally copy-pasted the logic from Safe frontend.
The only thing that might be different is stablecoins list. We have [our own list](https://github.com/cowprotocol/cowswap/blob/4cf0c91a300d6fcdc026364e74c45e5b2f729f2b/libs/common-const/src/tokens.ts#L488), our list at least matches mainnet (USDC/USDT/DAI).
Volume fee should work exactly the same with https://app.safe.global/swap
> feat(volumeFee): add volume fee for Safe

- apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useResetStateWithSymbolDuplication.ts
By default we use token symbols in URL.
But in some cases we can have more than one token with the same symbol.
In this case if we meet a symbol of that token we do:
- Display "There is more than one token in the list of tokens with the symbol..." alert
- Reset the widget state to default assets
It works perfectly with everything but WETH :) Because WETH is a default asset and here we go in a trouble.
To avoid that now we check if the token with duplicated symbol is WETH, then we completely clean up the widget assets state.
Fixes #4323 
1. Open /11155111/swap/WTH (Sepolia)
2. Add 0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9 (symbol=WETH) as a custom token and choose it as buy token
3. You should see "There is more than one token in the list of tokens with the symbol..." alert
> fix: reset trade completely if default token is duplicated

- libs/tokens/src/const/tokensList.json
Follow up on https://github.com/cowprotocol/token-lists/pull/756
This PR adds a new default list for Base chain with the top 500 tokens
- Connect to safe
- Check there's plenty of tokens now
- Check that coinbase and coswap list are enabled
> feat: add default list for tokens in base

- apps/cowswap-frontend/src/api/cowProtocol/hooks.ts
Since the recent update of React to v19 we started getting app freezing.
It's reproducible only on prod/staging enviroment! (because of the `useSWRProdOrders()` logic hook, it depends on `isBarnBackendEnv`).
The main cause of the problem is in `useOrdersFromOrderBook()` hook. It was returning a new istance of array every time which causes infinite re-renderings.
It actually was a problem even before React version update, it has been worsening app performance but didn't cause app freezing.
**I also checked other parts of the code-base and haven't found similar problems.**
You can test it only on staging.
You just need to open twap page with no connected wallet.
> fix(twap): fix orders fetching

- apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
- apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx
- apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
- apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFeeTooltip.ts
- apps/cowswap-frontend/src/modules/volumeFee/index.ts
Context: https://cowservices.slack.com/archives/C035E32LCLF/p1733333921018979?thread_ts=1732722697.486239&cid=C035E32LCLF
Make sure that `isSafeAppFeeEnabled` feature-flag is enabled.
1. The tooltip label should be `Safe App License Fee`
> fix: update safe fee tooltip label

- apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
Due to some misunderstanding we didn't add Safe Apps fee in Base intentionally, but it should be there. 
1. Safe Apps fee should be applied in Base like everywhere else
> fix: add safe apps fee in Base network

- libs/ui/src/pure/MenuBar/index.tsx
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1733749781104509
The "MEV Blocker" menu item in header should have utm_content=menubar-dao-nav-mevblocker
> fix(cow-fi): add utm content to mevblocker menu item

- apps/cow-fi/data/cow-protocol/const.tsx
Add `Base` to the list of supported networks on CoW Protocol FAQ on cow.fi
1. Open cow.fi
2. Go to CoW Protocol's FAQ
3. Look for `What chains does CoW Protocol currently support?`
* Should include `Base`
> fix: add Base to CoW Protocol FAQ on cow.fi

- apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
- libs/common-const/src/tokens.ts
When `isSafeAppStableCoinsFeeEnabled` featureflag is off, then Safe Apps fee for stable-stable trades should not be added, otherwise should work as in #5139
> fix(volume-fee): control safe app fees for stablecoins with ff

- apps/cow-fi/next.config.js
- apps/cow-fi/services/cms/index.ts
Marketing needs the articles to be updated faster.
> fix(cowfi): reduce cms requests cache time to 5 min

- apps/cowswap-frontend/src/modules/twap/services/verifyExtensibleFallback.ts
- apps/cowswap-frontend/src/modules/twap/updaters/FallbackHandlerVerificationUpdater.tsx
Related to #2949 
Since Safe fallback handler might be changed any time, we should not cache the fb verification result for ever.
In this PR I added cache life time - 10 minutes.
1. Open a Safe with no CowSwapFallbackHandler
2. Create a TWAP along with changing FB
> fix(twap): cache fb handler verification for 10min

- apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx
- apps/cow-fi/app/(main)/tokens/[tokenId]/page.tsx
- apps/cow-fi/services/tokens/index.ts
Continuing the cow.fi costs issue investigation I got a responce from Vercel support where they siad that there are some errors which may cause costs increases.
I don't think this s a key of the problem, because there are very few of the errors.
Anyway, we should fix there errors, there are two of them:
1. /learn/articles/tally-recipe-for-cow-swaps
2. /tokens/metaverse-index
Some people open links which are invalid (/learn/articles/tally-recipe-for-cow-swaps -> /learn/tally-recipe-for-cow-swaps) and (/tokens/metaverse-index doesn't even exist) which causes the app errors.
1. Open /learn/articles/tally-recipe-for-cow-swaps
3. Open /tokens/metaverse-index
> fix(cowfi): fix pages crashes

- apps/cowswap-frontend/src/modules/twap/containers/SetupFallbackHandlerWarning/index.tsx
- apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
> feat: style TWAP warning banner

- apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
- apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
- apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
- apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx
- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/BundleTxWrapBanner/index.tsx
Fixes #4662 (case 2)
Selling ETH [doesn't work well with hooks](https://cowservices.slack.com/archives/C0361CDG8GP/p1733992678141039), so we decided to disable it (similarly to limit orders).
See #4662 (case 2)
> fix(hooks-store): disable selling eth

- apps/explorer/src/components/orders/DetailsTable/index.tsx
- apps/explorer/src/components/orders/OrdersUserDetailsTable/ToggleFilter.tsx
- apps/explorer/src/components/orders/OrdersUserDetailsTable/index.tsx
- apps/explorer/src/components/orders/UnsignedOrderWarning/index.tsx
This PR tries to address several issues related to the explorer. Primarily its displaying a warning for unsigned orders, so users know that the owner can be faked and anyone could have placed the order. Also, it makes some improvements to make the order table result more relevant for users.
Some accounts have a lot of expired and canceled orders.  When you go over your history, these orders are usually not super relevant to you. 
Because for now the API don't allow any filtering by the status of the order, I applied a filter in the client.
Test with `0x79063d9173C09887d536924E2F6eADbaBAc099f5` account: https://explorer-dev-git-hide-canceled-expired-cowswap.vercel.app/address/0x79063d9173C09887d536924E2F6eADbaBAc099f5
You should only be able to see the relevant orders:
Notice the filter on …
> feat: warn about unsigned orders, and hide not relevant orders

- apps/explorer/src/components/orders/OrdersUserDetailsTable/index.tsx
Apply a nitpick that I forgor to push when I merged #5214: https://github.com/cowprotocol/cowswap/pull/5214#discussion_r1888530386
> Apply nitpick

- apps/widget-configurator/src/app/configurator/consts.ts
- libs/tokens/src/const/tokensList.json
- libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1734421577955559
Before:
```
allTokenListsInfoAtom:v4 5279.48046875 KB
```
After:
```
allTokenListsInfoAtom:v5 2361.544921875 KB
```
Change network many times, the app should not crash
> fix: remove Kleros token list because it's too big

- apps/cowswap-frontend/src/common/constants/common.ts
- apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
Before this PR, we allowed a maximum deadline of 6 month for limit orders
This PR increases it to 1 year:
Place orders of more than 6 months deadline, up to a year
> feat: allow 1 year max deadline

- apps/explorer/src/components/common/Tabs/Tabs.tsx
- apps/explorer/src/components/orders/OrdersUserDetailsTable/index.tsx
- apps/explorer/src/explorer/components/OrdersTableWidget/OrdersTableWithData.tsx
- apps/explorer/src/explorer/components/OrdersTableWidget/index.tsx
- apps/explorer/src/explorer/components/common/ExplorerTabs/ExplorerTabs.tsx
This PR adds 2 things:
- Another pagination control in the bottom of the table. After all, makes sense to not scroll up to go to next page
- Makes it more cleat that the page is complete, and there's more pages later
It is not very clear in this table that 19 orders are hidden and I can navigate to next pages. Basically, it looks like there's no more than 1 order.
This PR shows the same account like this:
You can unhide orders, and the message will update
You can click on next page to navigate.
In last page, you don't see the next page link
Search for your orders in the explorer, for example for the account `0x5be9a4959308A0D0c7bC0870E319314d8D957dBB`
- Notice the two paginators
- Check the cases described above
> feat: improve orders table when hidden orders

- apps/explorer/src/components/orders/OrdersUserDetailsTable/index.tsx
- libs/tokens/src/const/tokensList.json
- libs/tokens/src/const/tokensLists.ts
- libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
New token lists for Uniswap and Coingecko in all chains (where applicable)
1. Load the app (make sure browser cache is disabled)
2. Manage the token lists
* You should see something similar to this on every chain
* Except on Sepolia, since it's Sepolia and mainnet, that doesn't have a Uniswap subset and it's not enabled by default
> feat: use new uni and coingecko token lists

- apps/cowswap-frontend/src/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx
Fixes #5165
`InitialPriceUpdater` has been resetting `isTypedValue` flag time to time because it was relying only on the local flag - `isInitialPriceSet`.
To avoid the resetting, I've bound the `isInitialPriceSet` to `isTypedValue` so now if a user entered a value, then the updater will never override it.
See #5165
> fix(limit-orders): do not override user entered price

- libs/wallet/src/web3-react/connection/safe.tsx
Context: https://cowservices.slack.com/archives/C03DVQREAH0/p1734609531567519
This is a revert of https://github.com/cowprotocol/cowswap/pull/4931
Need to run Safe app locally and specify `baseUrl` to this PR preview link, so I will test it by myself
> fix: allow any safe-like apps

- apps/explorer/src/components/orders/OrderDetails/FillsTableWithData.tsx
- apps/explorer/src/components/orders/OrderDetails/context/FillsTableContext.tsx
- apps/explorer/src/components/orders/OrderDetails/index.tsx
Fixes the pagination for fills
Before 
https://explorer-dev-git-add-double-pagination-cowswap.vercel.app/orders/0xc0688a39e9ce5ee01c49786867357811c3fcf86e27eefb072e80c9417d731bf3a53a13a80d72a855481de5211e7654fabdfe352664fd9408?tab=fills
After
test for order `0xc0688a39e9ce5ee01c49786867357811c3fcf86e27eefb072e80c9417d731bf3a53a13a80d72a855481de5211e7654fabdfe352664fd9408`
> feat: fix pagination for fills

- apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
Explicitly sets chainId when sending EthFlow tx
Despite us having already introduced some checks to try to prevent users from sending EthFlow txs to the wrong chain (#4629), it still happened again.
It can be then that somehow the wallet has a wrong network and sends the tx from the wrong one.
This change attempts to force the chain upon the wallet so that doesn't happen.
1. Extensively test ethflow orders
> fix(eth-flow): set chainId explicitly when sending ethFlow tx

- apps/widget-configurator/src/app/configurator/consts.ts
- libs/tokens/src/const/tokensList.json
Remove outdated token lists
All of the lists being removed haven't been updated in years. Probably where never updated.
1. Open app on mainnet
2. Check loaded lists
* Should contain only: CoW Swap, Coingecko (500) and Curve (disabled by default)
1. Open the widget configurator
2. Check the suggested lists
* Should contain less options
> feat: remove outdated token lists

- apps/cowswap-frontend/src/common/constants/common.ts
- apps/cowswap-frontend/src/cow-react/index.tsx
- apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
- apps/cowswap-frontend/src/modules/application/containers/App/styled.ts
- libs/snackbars/src/containers/SnackbarsWidget/index.tsx
- libs/snackbars/src/hooks/useAnchorPosition.ts
- libs/ui/src/pure/MenuBar/index.tsx
Fixes #5247, #5242
After adding Christmas theme we have broken the widget background in small resolutions.
1. Open a widget configurator
2. Make your window size smaller
> fix(widget): do not display Christmas background

- apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.ts
The bug was introduced in #5207
In the code we have a comment:
```
// If the order has been filled at least once, we should not consider the permit amount
```
But the code didn't satisfy it
Check this account with impersonator: https://explorer.cow.fi/base/orders/0xb5ada1af24500813ff0f7956c0b80d52354c790d811fd1acbc8a38006c2db74f958b275d4d2132da3d651df4d6e446e307544c5767727b30?tab=overview
> fix: fix order filled condition for permit check

- apps/cowswap-frontend-e2e/src/e2e/swap.test.ts
The case on the picture bellow is always failed.
It's actually has wrong URL setup. If you want to specify only `buyAmount` you have to set `orderKind` parameter as well. 
All e2e tests should be green
> chore: fix failed e2e test

- apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
Address [comments](https://github.com/cowprotocol/cowswap/pull/5244#pullrequestreview-2518116438) from PR #5244 
No functional changes
1. EthFlow should work as before
> chore: address pr5244 comments

- README.md
- tools/scripts/ignore-build-step.js
Since this repo includes multiple apps, we do not want to build all of them on each PR because it causes long build queues in Vercel.  
Some apps (see the list bellow) are not required to be built on each PR so we run them only a PR is labeled with a specific label.  
This label is defined in the project settings on Vercel in `Settings`/`Git`/`Ignored Build Step` script.  
For example, the label for the widget-configurator is `preview-widget-cfg`:
```
node tools/scripts/ignore-build-step.js --app=preview-widget-cfg
```
List of applications and their labels:
- widget-configurator: `preview-widget-cfg`
- cosmos: `preview-cosmos`
- sdk-tools: `preview-sdk-tools`
In addition, I expanded the list of branches that should not be deployed in preview.
Before this fix only `configuration` branch …
> ci: deploy some apps preview only when PR has label

- apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
- apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
Only preventing the flags from being loaded from Launch Darkly.
All the functionality is still there.
1. Turn flags on and off
* Should not have any effect
> chore: remove xmas/halowren feature flags

- apps/cowswap-frontend/public/emergency.js
This PR removes old token lists from localStorage with the key `allTokenListsInfoAtom:v5`
1. Load into your localStorage the above key from staging/prod
2. Open the page console and filter by `service`
3. Reload the page
* Should print logs like these:
4. Check the loaded token lists
* Should only contain the new lists from [here](https://github.com/cowprotocol/cowswap/blob/fix/remove-old-token-lists-from-cache/libs/tokens/src/const/tokensList.json) and whatever else you had loaded previously, that's not in the exclusion list:
> fix(token-lists): remove old token lists from cache

- apps/cowswap-frontend/src/common/hooks/useConvertUsdToTokenValue.ts
- apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
- apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
- libs/common-utils/src/amountFormat/index.ts
- Fix max precision bug with USD amounts
- Attempt fixing issues with precision
1. On limit, turn on global USD
2. On a sell token which you have balance, click on max
3. Place a `fill or kill` order
* Should NOT show insufficient balance
* Should use ALL available balance
* USD amounts should be a bit less finicky (better with rounding)
> feat: limit UI upgrade 2 - USD precision

- apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
- apps/cowswap-frontend/src/legacy/state/orders/consts.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useGetInitialPrice.ts
- apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdPrice.ts
Use UsdPriceUpdater instead of triggering new requests from here
I realized that there was still duplication and I could re-use the same method of fetching USD values we already have instead of triggering new requests every where
In this change, I added `useUsdPrices`, that adds the required currency to the UsdPriceUpdater queue and used it on SpotPriceUpdater
1. Market prices should load as usual in Limit/Twap forms and come from BFF
> feat(usd): further refactor SpotPrice updater

- apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
Depends on https://github.com/cowprotocol/cowswap/pull/5297
Using spot price (from BFF USD estimations) to populate the `market price` button in the limit orders form.
It's easier to see in the new design, but since it's independent from the changes there I'm piping into develop to add there later.
- Before this change, we were adding a 0.1% slippage to the current market price to make it more likely to match
This is being removed to match _exactly_ what's shown in the table
- The previous value was size dependent, based on the result from the quote. Now this is _purely_ the spot price
- As a bonus, the market price loading is back! (Don't know since when, but it was not being set at all)
1. Open LIMIT
2. Pick pair of tokens
3. Place order (out of market just to have it pending)
4. For …
> feat(market-price): use spot price for LIMIT market price button

- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/styled.tsx
- apps/cowswap-frontend/src/modules/twap/utils/getTwapOrderStatus.ts
- clear order selection on change tabs
- TWAP order statuses
> feat: clear order selection on change tabs

- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/styled.tsx
> Feat/limit UI upgrade 9

- apps/cowswap-frontend/src/modules/tokensList/pure/FavoriteTokensList/styled.ts
- Fixes a broken layout on mobile/responsive when having the tokenselector opened
> feat: fix mobile viewport layout

- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrderStatusBox/getOrderStatusTitleAndColor.ts
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- LIMIT: Add to unfillable only if pending, unfillable, and not in signing state
- LIMIT: Show the warning only for pending and scheduled orders, but not for presignature pending
- LIMIT: Add empty cell for signing orders - only for TWAP
> Feat/limit UI upgrade 11

- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
- apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
fix: auto-switch to 'all orders' tab when signing/unfillable tabs become empty
When an order transitions out of the 'signing' or 'unfillable' state, and there are no more orders in that state, the UI now automatically switches to the 'all orders' tab. This behavior is consistent for both LIMIT and TWAP orders.
> Feat/limit UI upgrade 12

- apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts
- apps/cowswap-frontend/src/modules/limitOrders/state/limitOrdersSettingsAtom.ts
- Fixes buy amount behaviour on limit form for locked/unlocked price
- Sets price locking ON by default (same as prod currently)
Sell behaviour should also work as usual, as well as limit price changes.
In summary:
- Edit sell amount:
- Price locked (default, same as prod): update buy amount
- Price unlocked: update price
- Edit buy amount:
- Price locked (default, same as prod): update sell amount
- Price unlocked: update price
- Edit price:
- Price locked or unlocked: update the field opposite to the last edited one
1. Test all 6 scenarios defined above
> fix: amount locking

- apps/cowswap-frontend/src/modules/trade/pure/TradePageLayout/index.tsx
- apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
- apps/cowswap-frontend/src/pages/LimitOrders/RegularLimitOrders.tsx
Improved how we handle the `hideOrdersTable` parameter in widget mode to ensure proper hiding of the orders table in both Limit Orders and TWAP pages:
1. Added conditional rendering of `SecondaryWrapper` based on `hideOrdersTable` parameter
2. Updated `PageWrapper` grid template areas to adjust layout when table is hidden:
- Simplified grid areas to only show "primary" when table is hidden
This change ensures the orders table is properly hidden in widget mode while maintaining a clean layout structure.
> feat: hide orders table widget

- apps/cowswap-frontend/src/common/hooks/useSafeMemo.ts
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- Invert distance to market percentage when price display is inverted
- Be more explicit in the tooltip, by adding the mentioned market price and execution prices
- Reduce re-renderings by memoizing Price instances
1. On limit orders table, observe `fills at/distance to market` column
> fix: distance to market

- apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useGetInitialPrice.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
Fix issue when sometimes spot/market prices are not loaded
1. Load the app in the Safe https://app.safe.global/apps/open?safe=sep:0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531
2. Check limit orders
* Market prices should load
> fix: spot prices display edge cases

- apps/cow-fi/data/descriptions/cow-protocol.md
Fixes #4391 
1. Open [/tokens/cow-protocol](https://cowfi-git-elena-zh-patch-1-cowswap.vercel.app/tokens/cow-protocol) page
2. Check CoW Swap link in 'Where can you swap or trade CoW Protocol (COW)?' section
> chore: fix typo on CoW protocol token page

- apps/cow-fi/app/(main)/widget/page.tsx
- apps/cow-fi/components/DaosPageComponent.tsx
- apps/cow-fi/components/LazySVG.tsx
- apps/cow-fi/styles/styled.ts
Fixes #5065
This PR resolves the loading effect issues on the `/widgets` and `/daos` pages under cowfi. The primary issue was the line height of the loading text, which caused it to appear cramped. 
Additionally, I noticed that the icons in the “trusted by” section on the cow.fi/daos page were missing, and I have included a fix for that as well. (Please check here: https://tinyurl.com/2avu2hyy)
Attached below are the screenshots showing the fixes. 
I opted for a minimal approach to implement these changes without modifying the widely used LazySVG component.
> fix: loading effect fixes for widget and daos page

- apps/cowswap-frontend/src/modules/tokensList/containers/ManageLists/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/containers/ManageLists/styled.ts
- apps/cowswap-frontend/src/modules/tokensList/containers/ManageListsAndTokens/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/containers/ManageListsAndTokens/styled.ts
- libs/tokens/src/hooks/lists/useSearchList.ts
Fixes #4915 
The popup currently does not display an error message when a user enters a token list URL that fails to load.
This PR resolves the issue by managing the error within the `ManageLists` component through the introduction of a new prop, `isListUrlValid`.
The solution is intentionally designed to minimize changes to the existing business logic and component structure, so it might not fully align with the requested UI (an error message without a top border).
Screenshots and a video demonstrating the changes are attached.
https://github.com/user-attachments/assets/9a6cc5ec-1540-401d-85ce-1ef79780ebf7
> Failed to import token list error message handled

- apps/cowswap-frontend/src/modules/limitOrders/state/limitOrdersRawStateAtom.ts
- apps/cowswap-frontend/src/modules/trade/hooks/useSetupTradeAmountsFromUrl.ts
- apps/cowswap-frontend/src/modules/trade/types/TradeRawState.ts
1 unit of token should be default amount for sell token in Limit orders / Twap / Yield widgets
> feat: default limit sell input

- libs/ui/src/pure/HelpTooltip/index.tsx
Fixes a part of https://www.notion.so/cownation/Flickering-1778da5f04ca8060b4d2cd7b87de2ba1
It fixes only help tooltip icons (you can see them in settings)
1. Open limit orders
2. Setup some trade
3. Open settings
4. Wait till the next price update
> fix(ui): get rid of flickering in HelpTooltip

- libs/common-utils/src/fractionUtils.test.ts
- libs/common-utils/src/fractionUtils.ts
Fix for several crashes happening recently when dealing with prices
The underlying fraction numerator/denominator can become quite large numbers due to the decimals padding.
That leads to the fraction operations crashing behind the scenes.
However, fractions can be simplified and still maintain the same precision.
This PR does that: add a `FractionUtils.simplify` static method
1. Play around with prices, orders etc
* Should not crash
Also, added unit tests for the new method
> feat: add FractionUtils.simplify

- apps/cowswap-frontend/src/common/hooks/useSafeMemo.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx
Fixes issue https://www.notion.so/cownation/Recalculate-price-when-change-a-network-1828da5f04ca80069c9bdf01e8e0b483?pvs=4
Price is now recalculated when network changes but tokens are the same
1. Load LIMIT on mainnet
2. Change to sepolia
* Price should be updated
> fix: rate loading on chain change

- apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
- apps/cowswap-frontend/src/legacy/state/orders/utils.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/ExecutionPriceUpdater/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- libs/common-utils/src/fractionUtils.test.ts
- libs/common-utils/src/fractionUtils.ts
Add a simple error handling for SpotPrice and ExecutionPrice updaters
Depends on https://github.com/cowprotocol/cowswap/pull/5326 (merged)
~Shouldn't be needed after the changes above, but great to have anyway just to prevent app crashes.~
Edit: There are important fixes now in the addition to the error handling
1. Play around with prices, mostly on LIMIT orders
* Should not crash
* Should show market prices as expected
> fix: price error handling

- apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
- apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts
- apps/cowswap-frontend/src/legacy/state/orders/utils.ts
- apps/cowswap-frontend/src/modules/limitOrders/updaters/ExecutionPriceUpdater/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
- apps/cowswap-frontend/src/utils/orderUtils/calculateExecutionPrice.ts
- libs/common-utils/src/fractionUtils.test.ts
- libs/common-utils/src/fractionUtils.ts
Overhaul estimated fill price in the form (and a bit in the table)
- Unified calculation in the single method
Overloaded `getEstimatedExecutionPrice` to be used in the `ExecutionPriceUpdater`
It now can also take order parameters without having an existing order
- Taking into account order flag `partially fillable`
Now it'll use a fixed sell amount to make estimation stable regardless of order size
The amount is currently set to ~50x~ 1000x `feeAmount`
From there, we use the chosen limit price (already discounted for potential fees) to derive the buy amount
Lastly, the `feeAmount` is deduced from the calculated sell amount, to give us the new estimated price
If the order is fill or kill OR the amount calculated above is bigger than actual sell amount, use the old way considering the whole …
> fix: estimated execution price

- apps/cowswap-frontend/src/common/pure/ArrowBackground/index.tsx
- apps/cowswap-frontend/src/common/pure/LimitOrdersPromoBanner/index.tsx
- apps/cowswap-frontend/src/common/pure/LimitOrdersPromoBanner/styled.ts
- apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
Fixed the arrow background animation in the Limit Orders promo banner to ensure smooth transitions and prevent "stuck" arrows on initialization. Also added customizable opacity control.
https://github.com/user-attachments/assets/9b0d0b65-c02d-4567-aae4-d4bddd71970a
https://github.com/user-attachments/assets/63f301aa-e22f-4446-adfd-1237fc403010
* Refactored animation initialization to ensure arrows are moving before becoming visible
* Added `maxOpacity` prop to `ArrowBackground` component for customizable visibility
* Improved transition timing using CSS classes instead of direct style manipulation
* Extended animation delay to ensure proper initialization
* Added smoother transition curve for opacity changes (1s ease-in-out)
1. Open the app and verify the Limit Orders promo banner appears …
> Fix Arrow Background Animation & Add Opacity Control

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts
- apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.test.ts
- apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts
Fixes #5310
Sometimes `activeRate` is a `Price` and because of that output amount (for sell order) calculates wrongly.
I don't know why it is Price, in the most of cases it is a `Fraction`.
1. Open Swap widget on Mainnet and set selling 1 WETH for USDC
2. Go to Limit orders an wait till amount are calculates
3. Changes sell amount to 2
> fix: convert active rate to fraction to calculate opposite amount

- apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx
Inverting the price keeps the display mode (USD/token)
1. On limit orders form, select the USD display mode
2. Click on switch price display
* Should keep the USD display mode
> fix: toggle usd mode

- apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts
- apps/cowswap-frontend/src/utils/orderUtils/calculateRateForAmount.ts
Price locking/unlocking should work again as expected
I broke the unlocking in this PR https://github.com/cowprotocol/cowswap/pull/5304, although I could swear it was working when I tested...
Well, I was mistaken.
1. Play around with prices and amounts while the price is locked
* Should behave like prod
2. Play around with prices and amounts while the price is unlocked
* Price should be updated when amounts are changed
* Opposite amount should be updated when price is edited
> fix: price lock

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
Simply removes the limit orders banner:
1. Open limit orders
* Banner should not be there
> chore: remove limit banner

- apps/cowswap-frontend/src/common/utils/assertProviderNetwork.ts
- apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
- apps/cowswap-frontend/src/react-app-env.d.ts
- libs/common-utils/src/getChainIdImmediately.ts
- libs/wallet/src/web3-react/connectors/TrezorConnector/index.ts
- libs/wallet/src/web3-react/connectors/TrezorConnector/sendTransactionHandler.ts
Added a type guard to make sure provider is a JsonRpcProvider.
No functional changes expected.
1. Wrap, unwrap and place ethflow
* All should work
> fix: type guard to make sure provider is a JsonRpcProvider

- apps/cowswap-frontend-e2e/src/e2e/limit-orders.test.ts
- apps/cowswap-frontend-e2e/src/e2e/swapMod.test.ts
Just fixed failed tests after the recent changes:
1. Now default buy token is USDC
2. Now default sell amount is 1
> chore: fix e2e tests after limit orders upgrade

- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/hooks/useHighFeeWarning.ts
Fixes #5367
In very specific cases `targetAmount` might be zero, and we cannot divide on zero.
See #5367
> fix: do not crash in high fee warning

- apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/MetamaskTransactionWarning/index.tsx
- apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
- libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts
- libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts
- libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts
- libs/iframe-transport/src/iframeRpcProvider/utils.ts
- libs/iframe-transport/src/types.ts
- libs/types/src/eip6963-types.ts
- libs/types/src/index.ts
- libs/wallet/src/api/hooks.ts
- libs/wallet/src/api/state/multiInjectedProvidersAtom.ts
- libs/wallet/src/api/types.ts
- libs/wallet/src/web3-react/connection/injectedOptions.tsx
- libs/wallet/src/web3-react/connectors/Injected/index.tsx
Fixes #5369
1. Do not display the banner for wallets who expose `isMetamask = true` and only display it for Metamask browser extension
2. Display the wallet for Metamask mobile wallet via WC (tested only with IOS wallet)
See above
> fix: display Metamask warning only for extension/mobile wallets

- apps/cowswap-frontend/src/modules/limitOrders/updaters/SetupLimitOrderAmountsFromUrlUpdater.tsx
Fixes https://www.notion.so/cownation/Price-is-wrong-when-change-a-token-using-token-selector-1858da5f04ca802c99e1caa36375b7d5
This problem more likely comes from #4668 fix. At least I can reproduce it on prod now.
In useUpdateActiveRate() we have a logic which depends on `isRateFromUrl` flag.
Mainly, it serves for keeping amounts static after coming from another trade widget.
But we should not prevent amounts and price update when we change tokens.
So, we reset `isRateFromUrl` flag when at least one of the tokens is changed.
1. Open swap widget in Sepolia, setup selling WETH to USDC
2. Go to limit orders
3. Change one of the tokens. You can do it in 3 ways: a) using token selector b) switching tokens places c) changing tokens in URL
> fix(limit-orders): update price and amounts when tokens changed

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
Fixes #5384 
Rate input should not be displayed when wrap/unwrap
> fix(limit-orders): do not display rate input when wrap/unwrap

- apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/atoms.ts
- apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx
- apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
Fixes #5386 
1. On limit orders form, toggle the USD input mode
2. Change currencies
* Selection should remain
3. Pick as sell a token that needs approval and it's not permittable (like WETH)
4. Approve token
* Selection should remain
> fix(usd-rate-input): keep track of usd toggle in the rate input on limit form

- apps/cowswap-frontend/src/modules/trade/containers/TradeWarnings/index.tsx
- libs/widget-lib/src/types.ts
Remove bundling recommendation for approval+order placement
1. Connect with Safe via WC
2. On SWAP, Pick as sell a token that needs approval
* Should no longer see the banner
3. Repeat with LIMIT orders
* Same result
4. Repeat with Safe app and EOA/another wallet
* Should not show any banner, as before
> fix(safe-app): remove approval+order placement bundling recommendation

- apps/cowswap-frontend/src/common/hooks/useCancelOrder/useGetOnChainCancellation.ts
- apps/cowswap-frontend/src/common/hooks/useCancelOrder/useSendOnChainCancellation.test.tsx
- apps/cowswap-frontend/src/common/hooks/useContract.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useCheckEthFlowOrderExists.ts
- apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
- apps/cowswap-frontend/src/modules/swap/services/types.ts
- libs/common-const/src/common.ts
This PR is in preparation for the ETH FLOW migration. We will replace BARN and PROD eth flow contracts with some new version deployed in deterministic address (same address to all networks).
This is done to minimize the risk of sending ETH to the wrong address in case of a Dapp or Wallet bug. 
Tracker for the changes https://www.notion.so/cownation/tracker-ETH-Flow-Contract-Replacements-1828da5f04ca8023af57e76cf6d064d9?pvs=4
See the new deployment and more context:
https://github.com/cowprotocol/ethflowcontract/pull/59
With he feature flag off, make sure it uses the old barn contracts:
```json
{
"1": "0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93",
"100": "0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93",
"11155111": "0x2671994c7D224ac4799ac2cf6Ef9EF187d42C69f",
"42161": …
```
> feat: use new deterministic ethflow contracts

- apps/cowswap-frontend/src/modules/ordersTable/pure/OrderStatusBox/index.tsx
- apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/styled.tsx
Addresses https://github.com/cowprotocol/cowswap/issues/5403
This PR addresses layout issues in the orders table, specifically focusing on the status box component and overall column widths. The changes ensure better visual consistency and prevent text wrapping issues in the status indicators.
1. **Status Box Improvements**
- Added `white-space: nowrap` to prevent status text from breaking into multiple lines
- This ensures status indicators remain on a single line for better readability. Specifically for the 'partially filled' status.
2. **Table Column Width Adjustments**
- Fine-tuned column widths in both history tab and default layouts
- Standardized status column width to `minmax(106px,112px)` (previously `minmax(80px, 0.8fr)`)
- Adjusted adjacent columns for better overall table …
> Fix Orders Table Status Box Layout

- apps/cowswap-frontend/src/modules/trade/types/TradeRawState.ts
- libs/common-const/src/tokens.ts
Attempt to fix bug reported by Chim9 on Discord.
Changes the local token name from USDC to USDC.e
1. On arb1, load `0xff970a61a04b1ca14834a43f5de4533ebddb5cc8` and `0xaf88d065e77c8cC2239327C5EDb3A432268e5831` tokens
* Both should load
> fix: add '.e' to USDC.e on Arb1

- apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
Address https://github.com/cowprotocol/cowswap/pull/5334#discussion_r1944939650
No need to test.
> feat: relax the last mile check for ethflow and improve message

- apps/explorer/src/components/orders/DetailsTable/index.tsx
- apps/explorer/src/components/orders/UnsignedOrderWarning/index.tsx
- apps/explorer/src/explorer/styled.ts
Fixes #5452 
Moves CSS variable for alert text color to global scope
This PR moves the `--cow-color-alert-text` CSS variable from the component level to the global application level, ensuring consistent styling across all components that use this variable. This change improves maintainability by centralizing the color definition.
1. Navigate to any order details page with an unsigned order
A TODO comment was also added to indicate that this approach is temporary until we have a proper way to set global CSS variables for all apps in the monorepo.
> refactor(explorer): update color system and styling for order components

- apps/cowswap-frontend/src/common/pure/GlobalWarning/index.tsx
This PR improves the styling and responsiveness of the GlobalWarning component, enhancing its appearance and usability across different screen sizes.
Key improvements:
- Improved hover effects on the close button with opacity transition
- Fixed potential layout issues by preventing icon shrinking
- Improved text readability with appropriate line-height values
1. View the GlobalWarning component in desktop view
2. Test the component in mobile view
> refactor(ui): improve GlobalWarning component styling and responsiveness

- apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx
Appzi stopped working today.
It seems like they changed css selectors and those changes are not compatible with out styles.
More specificaly, before they were adding 'appzi-f-w-open-' class but now they don't.
1. Appzi feedback widget should open when needed
2. Appzi NPS should open when needed
> fix(appzi): remove open state styles

- apps/cowswap-frontend/src/modules/swap/containers/TradeButtons/index.tsx
- apps/cowswap-frontend/src/modules/swap/containers/TradeButtons/swapTradeButtonsMap.tsx
- apps/cowswap-frontend/src/modules/swap/containers/Warnings/index.tsx
Swap button should be disabled when "Costs exceed..." warning checkbox is not checked.
1. Open Cow Swap in Safe
2. Setup a trade selling ETH and input small enough value (0.2$ in Sepolia)
> fix(swap): disable button when costs warning is not accepted

- libs/common-utils/src/getIsNativeToken.ts
Fixes the crash when pick a token from a different chain
1. isBridgingEnabled flag is ON
2. open the app
3. pick a token from a different chain in the Buy field
> chore: fix app crash in getIsNativeToken

- apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
New Safe app fee recipient address
1. Open app inside the Safe
2. Place an order
* Recipient fee address should be `0x8025BAcF968aa82BDfE51B513123b55BFb0060D3`
> fix(safe-app-fee): replace Safe App Fee recipient address

- apps/cowswap-frontend/src/modules/account/containers/AccountDetails/SurplusCard.tsx
- apps/cowswap-frontend/src/modules/twap/const.ts
Currently, there are links that navigate to articles on an external resource. 
This PR changes the navigation links to eponymous articles on cow.fi
**1. Surplus card**
- Connect to a wallet
- Open Account modal
-  Check the link on the Surplus card
**AR**: should navigate to https://cow.fi/learn/announcing-cow-swap-surplus-notifications
**2. TWAP: unsupported wallet**
- Open TWAP page
- connect to any EOA wallet
- Check 'click here' link
**AR**: should navigate to https://cow.fi/learn/how-to-use-cow-swap-twap-orders-via-safe-wallet
**3. TWAP: Fallback handler is not installed**
- Create a new Safe, fund it
- Open TWAP page
- specify a TWAP order
- Check 'Learn more' link on the warning 
**AR**: should navigate to https://cow.fi/learn/all-you-need-to-know-about-cow-swap-new-safe-fallback-ha …
> fix: change links on suplus card and twap form

- apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
- apps/cowswap-frontend/src/modules/limitOrders/pure/InfoBanner/index.tsx
Open [Limit orders](https://swap-dev-git-link-update-on-limit-orders-unl-79c937-cowswap-dev.vercel.app/#/1/limit/) page 
Check 'partially fillable orders' link
**AR**: should navigate to 
https://cow.fi/learn/cow-swap-improves-the-limit-order-experience-with-partially-fillable-limit-orders
Check the link on the 'Your order may not fill exactly when the market price reaches your limit price' info banner
**AR**: I've proposed to navigate a user to the https://docs.cow.fi/cow-protocol/tutorials/cow-swap/limit#track-a-limit-order page where it is explained how the executes at works.
> fix: update links on limit orders page

- apps/cowswap-frontend/src/modules/trade/hooks/useSetupTradeAmountsFromUrl.ts
Fixes https://cowservices.slack.com/archives/C0361CDG8GP/p1747215937525659
`useSetupTradeAmountsFromUrl()` was resetting output amount instead of skipping it to be updated from URL for widgets that don't support buy orders.
Sorry, the only way to test with Safe is run it locally. I've tested that:
https://github.com/user-attachments/assets/9f0afbf4-32dc-4da9-b1bd-9ed5bab0beaf
Anway, can you please test CoW Swap:
1. Navigation between widgets
2. Setting amounts from URL
> fix(twap): do not reset output amount

- apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
Fixes #5710
When we try to send a transaction of order presign, Safe doesn't really send a transaction, it only sign it.
In that case, `signer.sendTransaction()` throws an error with `error.transactionHash` which is a signature hash.
See  #5710
> fix: handle presign tx signature for Safe via Rabby

- apps/cowswap-frontend/src/legacy/utils/trade.ts
- apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
- apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
- apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
Fixes https://cowservices.slack.com/archives/C0361CDG8GP/p1747392016614809
This bug came with TradingSDK integration. Before we've been doing this:
And now:
Which looks similar, but under the hood `settlementContract.setPreSignature` uses `UncheckedSigner` instead of just `Signer`.
1. Safe+WC
2. Run any TX
3. Then place an order (as a 2nd TX), and sign the TX
4. The UI hangs in the 'Confirm TX' state --> no order submitted modal
https://github.com/cowprotocol/cowswap/pull/5711 please recheck this case as well.
> fix: fix order presign flow

- apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
Fixes https://www.notion.so/cownation/Confirm-with-your-wallet-appears-when-swap-is-not-yet-sent-to-a-wallet-2118da5f04ca80df8348cccd43228e4a
See https://www.notion.so/cownation/Confirm-with-your-wallet-appears-when-swap-is-not-yet-sent-to-a-wallet-2118da5f04ca80df8348cccd43228e4a
> fix(trade): reset loading state when confirm wasn't happen

- apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
- package.json
- yarn.lock
Using: https://github.com/cowprotocol/cow-sdk/pull/361
Fixes: https://www.notion.so/cownation/edge-no-routes-display-nicer-2108da5f04ca80a99d4dfa96b67eafcb?source=copy_link
There is a set of possible errors fro bridge quote:
```
export enum BridgeQuoteErrors {
NO_INTERMEDIATE_TOKENS = 'NO_INTERMEDIATE_TOKENS',
API_ERROR = 'API_ERROR',
INVALID_API_JSON_RESPONSE = 'INVALID_API_JSON_RESPONSE',
ONLY_SELL_ORDER_SUPPORTED = 'ONLY_SELL_ORDER_SUPPORTED',
TX_BUILD_ERROR = 'TX_BUILD_ERROR',
QUOTE_ERROR = 'QUOTE_ERROR',
NO_ROUTES = 'NO_ROUTES',
INVALID_BRIDGE = 'INVALID_BRIDGE',
}
```
The errors should be mapped as:
```
const DEFAULT_QUOTE_ERROR = 'Error loading price. Try again later.'
const bridgeQuoteErrorTexts: Record<BridgeQuoteErrors, string> = {
[BridgeQuoteErrors.API_ERROR]: …
```
> fix(bridge): display quote errors

- apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
- apps/cowswap-frontend/src/modules/combinedBalances/state/balanceCombinedAtom.ts
- apps/cowswap-frontend/src/modules/combinedBalances/updater/BalancesCombinedUpdater.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
- libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
- libs/balances-and-allowances/src/hooks/useSwrConfigWithPauseForNetwork.ts
- libs/balances-and-allowances/src/index.ts
- libs/balances-and-allowances/src/state/balancesAtom.ts
- libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
- libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
- libs/balances-and-allowances/src/updaters/BalancesResetUpdater.ts
Fixes #5939
There was a race condition between `BalancesResetUpdater` and `BalancesCacheUpdater`.
It was resetting balances just after restoring them from cache, which created a situation with "Couldn't load balances".
To fix that I added `fromCache` flag to balances state which prevents state resetting.
I extracted `BalancesResetUpdater` from `usePersistBalancesAndAllowances` because:
- the hook is used in three different places, but the resetting logic should be applied once
- to reduce the hook complexity
See #5939
> fix(balances): update balances after network switching

- apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/hooks/useAddTokenImportCallback.ts
- apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
- apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItemContainer/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokenSearchContent/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokensContent/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
- apps/cowswap-frontend/src/modules/tokensList/types.ts
- libs/tokens/src/hooks/tokens/useSearchToken.ts
Fixes https://www.notion.so/cownation/Swap-weth-in-mainnet-for-Cow-in-base-2398da5f04ca80f691a1ed471c40be8e?v=1c38da5f04ca812b9489000c81197879&source=copy_link
and https://www.notion.so/cownation/Search-for-dst-token-not-found-message-mentions-source-chain-2328da5f04ca803cb6f6f405a93841fb
We should not search tokens in token lists, API, etc when bridge output tokens selector is open. We should only filter list of bridge supported tokens.
Please review this PR commit by commit, because I did some refactoring without functional changes, the actual fix is [in the last commit](https://github.com/cowprotocol/cowswap/commit/63b6be9021a70b3a7c81525e16d012c6703453ed).
See https://www.notion.so/cownation/Swap-weth-in-mainnet-for-Cow-in-base-2398da5f04ca80f691a1ed471c40be8e?v=1c38da5f04ca812b9489000 …
> feat(bridge): do not search output tokens in selector

- apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/StackedProtocolIcons.tsx
- apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/index.tsx
Quick fix to swap the protocol icon colors that were missing from PR #6056
- Background: `UI.COLOR_PURPLE_800_PRIMARY` (dark purple)
- Icon: `UI.COLOR_PURPLE_200_PRIMARY` (light purple)
This provides better contrast and uses consistent theme-aware UI enums.
Visual check that CoW Protocol icons now show dark purple background with light purple icon.
> fix(bridge): swap protocol icon colors for better contrast

- apps/cow-fi/app/(learn)/learn/[article]/page.tsx
- apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx
- apps/cow-fi/app/(learn)/learn/page.tsx
- apps/cow-fi/app/(learn)/learn/topic/[topicSlug]/page.tsx
- apps/cow-fi/app/(learn)/learn/topics/page.tsx
Fixes ISR cache-busting issues in learn pages by eliminating non-deterministic patterns and adding proper revalidation.
- Replace random article selection with deterministic approach
- Add revalidate exports to all learn routes
- Limit static generation to first 10 pages with dynamic fallback
- Improve type safety and code organization
1. Navigate all learn pages - `/learn`, `/learn/articles`, `/learn/[article]`, `/learn/topics`
2. Verify consistent "Read more" articles (not random)
3. Check pagination works correctly
4. Confirm fast page loads from cache
> fix(cow-fi): ISR optimization to prevent cache-busting in learn pages

- libs/common-const/src/common.ts
- libs/tokens/src/const/defaultFavoriteTokens.ts
Removing `CoW` token from Polygon's favorite tokens and Account page, as there's no liquidity at the moment.
1. Switch Wallet to Polygon and open token selector
2. CoW token should not be in the favorite token list
3. Navigate to `Account` page
4. CoW token balance shouldn't be displayed, and a message is shown that the token is not available
> chore: remove Cow token from Polygon's favorite tokens and Account page

- apps/cowswap-frontend/src/tradingSdk/bridgingSdk.ts
- apps/explorer/src/sdk/cowSdk.ts
Use Bungee public endpoint `https://public-backend.bungee.exchange/api/v1/bungee` if Swap or Explorer aren't running locally.
1. Perform a Bridge transaction
2. In the dev tools, any request's header to `https://public-backend.bungee.exchange` should have an `Affiliate` key 
This is necessary as we're using a custom header to send the `affiliate` field
> fix: call bungee public endpoint when using custom header

- apps/cowswap-frontend/src/modules/swap/pure/CrossChainUnlockScreen/index.tsx
As per marketing's request, replace the unlock screen banner header from
> Swaps just got smarter
To
> Cross-chain swaps are here
1. Open CoW Swap
* Swap page text should be shown as above
> fix(swap): replace swap unlock screen banner header

- apps/cowswap-frontend/src/modules/swap/pure/CrossChainUnlockScreen/styled.tsx
Tiny change to adjust font size.
From 
To
1. Open SWAP
* Text should NOT wrap in 3 rows, should fit into 2 rows instead
> fix(swap): adjust swap banner header font size

- apps/cow-fi/next.config.ts
Redirect `/mev-blocker` page to external site `https://mevblocker.io`
1. Navigate to `/mev-blocker` on cow-fi app
MEV Blocker is now hosted externally. Added redirect in Next.js config
following existing pattern used for `/report-scam` redirect.
> feat(cow-fi): add redirect for MEV blocker to external site

- libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
Remove Ondo token list from curated list (aka geoblocked countried) 
1. Connect via VPN to a country that requires a curated list (for example, USA)
2. Open Token selector
3. Search for an Ondo token (for example, AAPLon). It shouldn't show up
4. Open `Manage Token Lists`
5. The list `Ondo Tokenized Stocks List` shouldn't show up
> feat: remove Ondo tokens from curated token list
