cowprotocol/cowswap

.github/workflows/cla.yml
- Add myself to the allowlist for the CLAssistent.
=> Add to allow list.

src/custom/components/CowBalanceButton/index.tsx
Fixes #382
- fixes rounding issue mentioned in the linked ticket
=> Fix for COW balance button rounding issue

src/custom/state/cowToken/middleware.ts
Fixes #370
- fixes the MOOOO sound when transaction fails
=> Fix moo sound for failed transactions

.github/scripts/prepare_production_deployment.sh, .github/workflows/ci.yml
Changes scritps and github actions in preparation for the change from `master` branch being called `main`
Also, changes the slug for the bucket name.
cc/ @giacomolicari
=> Change branch and bucket name

src/custom/components/Version/index.tsx, src/custom/constants/index.ts
Fixes #375
- updates the github links in the footer
=> Updated git repos in the footer

src/custom/pages/App/index.tsx
Fixes issue https://github.com/cowprotocol/cowswap/issues/449
=> Fix popup position.

src/custom/constants/index.ts, src/custom/constants/tokens/index.ts, src/custom/pages/Profile/LockedGnoVesting/hooks.ts, src/custom/pages/Profile/LockedGnoVesting/index.tsx, src/custom/pages/Profile/index.tsx, src/custom/state/claim/hooks/index.ts, src/custom/state/cowToken/hooks.ts
Fixes few issues
- convert COW button confirmation issue mentioned here https://github.com/cowprotocol/cowswap/pull/405#issuecomment-1109847525, now the button will be enabled after 2 new blocks are mined
- issue where after you disconnect the vested GNO card stays
- some issues mentioned in code review
=> Locked gno claim fixes

src/custom/components/SideBanner/index.tsx, src/custom/pages/App/index.tsx, src/index.tsx
Moves the banner up in the DOM tree, right above the Appzi button.
=> Reposition banner in tree

.github/workflows/ci.yml, cypress-custom/support/events.js, cypress/support/commands.js, src/custom/components/NetworkAlert/NetworkAlert/NetworkAlert.tsx, src/custom/state/swap/hooks.tsx
Attempts to fix #451 
To be clear, I could not reproduce, but this additional check should prevent the reported issue from happening
EDIT: Updated text to fix issue reported and to better reflect why swap can't happen
EDIT: Updated text to make it shorter. Now it reads `Couldn't load balances`
1. See #451
=> When balance isn't loaded, show insufficient balance message

src/custom/pages/Profile/index.tsx, src/custom/pages/Profile/styled.tsx
Fix for a small issue mentioned here https://github.com/cowprotocol/cowswap/pull/405#issuecomment-1112323500
=> Fix for governance card link

src/index.tsx
Fixes the current develop build job failing by removing the unused import
=> Removed unused import

src/index.tsx
Closes #516 
Notifications were removed by accident due to a bad merge on https://github.com/cowprotocol/cowswap/pull/484/commits/7c016a67ea69bb5fb390ab8b6ec6eaff69019b6d
1. Place an order
* You should see the notification pop up
=> Adding back popup notifications :)

src/custom/state/swap/hooks.tsx
=> Fix for incorrect msg in swap

src/custom/components/Popups/FailedNetworkSwitchPopupMod.tsx
Fixing 1 small bug https://github.com/cowprotocol/cowswap/pull/530
=> Release 1.14-RC.1

package.json, yarn.lock
Updates the NPM package for the cow game
Uses our own @cowprotcol organization. The code of the game should be the same.
=> Change cow runner game

src/custom/components/SideMenu/index.tsx, src/custom/pages/Account/Menu.tsx, src/custom/pages/Account/styled.tsx, src/custom/pages/Faq/Menu.tsx, src/custom/pages/Faq/styled.tsx
Part of the 571/account-page-layout
This PR moves Menu component used in Account and FAQ to a separate component file
=> Move SideMenu to a separate component

src/custom/api/gnosisProtocol/api.ts
Part of #624 and dependent on #640
- check networks tab for this:
Networks tab (in development - red because this is not the configutation base branch)
=> [624] Update config URL to update against changed config branch file structure

src/components/TokenWarningModal/index.tsx
Closes #644 
Screenshot:
1. gnosis chain
2. selct as buy: ADAI
3. click "Read more about unsupported tokens"
=> [644] Unsupported token recenter

src/custom/components/Footer/index.tsx
- Add footer margin for small/medium resolutions
=> Add footer margin on small and medium resolutions.

src/custom/pages/Faq/styled.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/486
=> FAQ adjust margin

src/custom/pages/Profile/LockedGnoVesting/index.tsx
Closes #646 
Fixes the error message for locked GNO COW claiming tx rejection
Also adds analytics for locked GNO COW claiming
Screenshots
=> add locked gno cow claim anayltics

src/custom/components/Header/index.tsx, src/custom/components/MenuDropdown/index.tsx, src/custom/components/MenuDropdown/styled.ts, src/custom/constants/mainMenu.ts, src/custom/constants/routes.ts, src/custom/pages/App/index.tsx, src/custom/pages/Faq/Menu.tsx
Addresses feedback points 1 to 4 from @elena-zh https://github.com/cowprotocol/cowswap/pull/607#issuecomment-1148544685
=> Improve header 1 elena feedback

src/custom/state/orders/middleware.ts
Adds events for order execution.
Adds the following action that were not tracked:
- Post Order
- Executed Swap
- Cancel Order
- Expired Order
2. Verify the events trading (success/error/cancel)
=> [analytics] Order execution

src/custom/pages/Swap/SwapMod.tsx
Improves the events for token approvals.  As part of addressing these comments https://github.com/cowprotocol/cowswap/pull/655#issuecomment-1149771629
Also, it shows a modal with the error if there's one, or if the user rejects the transaction (there wasn't one).
2. Verify the events for token approvals
=> Improve token approval

src/custom/constants/mainMenu.ts
- Add terms and conditions menu link
=> add terms conditions

src/custom/api/coingecko/index.ts, src/custom/hooks/useUSDCPrice/index.ts, src/custom/pages/Swap/SwapMod.tsx
- fixes USD estimation when you are trading ETH issue currently in happening in production
=> [Hotfix :fire: ] - 1.15.1 Fix USD estimation issue

.env, .env.production, .github/workflows/ipfs.yml, README.md, src/custom/connectors/index.ts, src/custom/utils/switchToNetwork.ts
Update the RPC endoints for Gnosis Chain
1. Test with any Wallet Connect wallet. Loading the balance should be enough test. Breaks in production, should be fixed here
=> hotfix/1.15.4: Update xDAI endpoints

src/custom/theme/baseTheme.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/724
=> fix appzi scroll

package.json, src/custom/components/Header/MobileMenuIcon/index.tsx, src/custom/components/Header/index.tsx, src/custom/theme/baseTheme.tsx
Fixes these issues found by @elena-zh 
- https://github.com/cowprotocol/cowswap/issues/724
- https://github.com/cowprotocol/cowswap/issues/728
0b84541a Replace ontouch with onclick (#729)
eca32f59 fix appzi scroll (#730)
=> [RELEASE 1.16.0] FIX 

src/custom/state/swap/trade.test.ts
Cleans up `trade.test.ts` to be easier to read and in proper order
=> Fix trade.test.ts

src/custom/hooks/useUSDCPrice/index.ts, src/custom/utils/price.ts
Bug in the USD fetching validTo time was using stale constant caching 10min in future based on compile time
Now using fn to update value
@elena-zh you were right! even after the fix it was not correct, good 👁️ 
1. open PR link
2. let sit 10 minutes
3. check networks tab
4. should be no error
=> [USD - Fix] Don't use stale USD time const

src/custom/theme/baseTheme.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/165
=> Fix appzi modal on mobile

src/custom/state/price/reducer.ts, src/custom/utils/analytics/swapEvents.ts
Part of #665 
- this PR adds a initial quote load GA event
=> Added initial order load GA event

src/custom/state/price/reducer.ts, src/custom/utils/analytics/index.ts, src/custom/utils/analytics/listEvents.ts, src/custom/utils/analytics/settingsEvents.ts, src/custom/utils/analytics/swapEvents.ts, src/custom/utils/analytics/themeEvents.ts, src/custom/utils/analytics/transactionEvents.ts, src/custom/utils/analytics/walletEvents.ts, src/state/swap/hooks.tsx
Part of the 665
This PR adds GA events for
- input/output currency select change
- input/output token amount change
- switch input/output tokens
Also moves set max balance event to swap events file
=> GA events part 2

package.json, yarn.lock
Simple RC version bump https://github.com/cowprotocol/cow-sdk/pull/43
No significant changes. Only removed optional fields from `quote` metadata
Metadata flow should remain the same
=> Bumping cow-sdk to v0.0.15-RC.1

package.json, src/custom/components/AccountDetails/index.tsx, src/custom/components/Header/index.tsx, src/custom/components/Version/index.tsx, src/custom/components/analytics/GoogleAnalyticsReporter.tsx, src/custom/hooks/useAddTokenToMetamask.ts, src/custom/pages/games/CowRunner/index.tsx, src/custom/pages/games/MevSlicer/index.tsx, src/custom/theme/baseTheme.tsx, src/custom/theme/components.tsx, src/custom/theme/cowSwapTheme.tsx, src/custom/theme/index.tsx, src/custom/utils/analytics/index.ts, src/custom/utils/analytics/otherEvents.ts, src/custom/utils/analytics/walletEvents.ts, src/custom/utils/explorer.ts, src/hooks/useAddTokenToMetamask.ts, src/theme/components.tsx, yarn.lock
=> 🐦 Release - 1.17.0 - RC.2

src/custom/components/AccountDetails/Transaction/CancelationModal.tsx
Fixes #802 (broken FAQ link in cancellation modal)
follow issue instructions
=> 802 - fix faq url

src/custom/tokens/goerli-token-list.json
Fixes #416
- this adds the goerli token list json file
- the code expects this file to be on the main branch so this is why the PR is for main branch also
- tokens can be found here https://explorer.bitquery.io/goerli/tokens
=> Added goerli-token-list.json file

src/custom/components/AccountDetails/Transaction/CancelationModal.tsx, src/custom/pages/Swap/SwapMod.tsx
- Fix USD estimations on the opposite token #809 
- Fix FAQ url #https://github.com/cowprotocol/cowswap/pull/803
- a5e4e4a24dcd7b8b2a0d1b75bbdc8c5131c4ead9
- https://github.com/cowprotocol/cowswap/pull/810/commits/f50b47160663bb24c799cb3fa172cca18ffb6021
=> Hotfix 1.18.1 RC.0

src/custom/components/Popups/PopupsMod.tsx
Fixes #812
Steps:
1. Place an order
2. Close Order Submitted confirmation modal
3. Check the tooltip displaying in different screen resolutions
=> Toast notification position

package.json
**`package.json`** version bump to `v1.19.0`
=> Bump Version to 1.19.0

src/custom/tokens/goerli-token-list.json
GNO: https://goerli.etherscan.io/address/0x02ABBDbAaa7b1BB64B5c878f7ac17f8DDa169532
0x: https://goerli.etherscan.io/address/0xe4E81Fa6B16327D4B78CFEB83AAdE04bA7075165
BAT: https://goerli.etherscan.io/address/0x70cBa46d2e933030E2f274AE58c951C800548AeF
DAI: https://goerli.etherscan.io/address/0xdc31Ee1784292379Fbb2964b3B9C4124D8F89C60
POLY: https://goerli.etherscan.io/address/0x9e32c0EfF886B6Ccae99350Fd5e7002dCED55F15
USDC: https://goerli.etherscan.io/address/0xD87Ba7A50B2E7E660f678A895E4B72E7CB4CCd9C
=> goerli: adding tokens with liquidity

src/custom/components/Header/index.tsx, src/custom/theme/baseTheme.tsx, src/custom/utils/appzi.ts
WIP
- Tries to address https://github.com/cowprotocol/cowswap/issues/862
Todo/need help:
- Could use some help with adding the unique class. We need to make sure the NPS widget is added. Haven't checked if the Appzi init function provide a function callback. Otherwise we'd need an async alternative. The goal is to add a unique (css) class with the NPS key to target with the override CSS styles.
=> Appzi nps style override 1

src/custom/utils/appzi.ts, src/utils/userAgent.ts
Follow up on https://github.com/cowprotocol/cowswap/pull/884
This PR disables appZI in imtoken
Make sure imtoken browswer doesn't show appzi feedback button or NPS form
=> Disable appzi imtoken

cypress-custom/integration/fee.test.ts, cypress-custom/integration/landing.test.ts, cypress-custom/integration/lists.test.ts, cypress-custom/integration/send.test.ts, cypress-custom/integration/swap.test.ts, cypress-custom/integration/swapMod.ts, cypress-custom/support/e2e.ts, cypress-custom/support/ethereum.ts, cypress-custom/support/index.js, src/custom/constants/lists.ts, src/custom/constants/tokens/tokensMod.ts, src/custom/tokens/goerli-token-list.json, src/custom/utils/goerli/constants.ts
Cypress testing switch to Goerli
=> Switch to Goerli network with cypress

.editorconfig, .eslintrc.json, src/cosmos.decorator.tsx, src/custom/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx, src/custom/components/CurrencyInputPanel/__fixtures__/CurrencyInputPanel.tsx
Example of fixture for CurrencyInputPanel component
=> Cosmos fixture for CurrencyInputPanel component

src/components/SearchModal/styleds.tsx, src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx, src/custom/components/SearchModal/CommonBases/index.ts, src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx, src/custom/components/Tokens/FiatBalanceCell.tsx, src/custom/components/Tokens/TokensTableRow.tsx, src/custom/constants/mainMenu.ts, src/custom/pages/Account/Affiliate.tsx, src/custom/pages/Account/Tokens/TokensOverview.tsx, src/custom/pages/Account/index.tsx
This PR adds Header dropdown for Account and also optimizes a performance by not creating a usd request if there is no balance
=> Added Account header dropdown

src/custom/components/WalletModal/index.tsx
Fixes the issue mentioned here #875
=> Fix for ToC link

src/custom/hooks/useWalletInfo.ts, src/custom/state/gnosisSafe/updater.tsx
Fixes the issue described in #989
=> Fix for safe transaction details

src/custom/components/AccountDetails/index.tsx, src/custom/hooks/useCowBalanceAndSubsidy.ts, src/custom/pages/Swap/SwapMod.tsx, src/custom/state/swap/hooks.tsx
Minor fixes pulled from https://github.com/cowprotocol/cowswap/pull/978
1. No longer defaults to wrapped native -> USDC
2. Show cow discount 0% when on unsupported network
3. Only show activities count if > 0
4. Do not show price estimation for wraps
5. Show `connect wallet` when wrapping and wallet is not connected
=> Misc fixes

.github/workflows/ipfs.yml, package.json
=> Release 1.21.0-RC.2

src/custom/pages/Account/styled.tsx
Fixes this bad boy #979, I think.
=> Fix IOS issue on account page

src/custom/pages/Account/styled.tsx
Release!
- Fixing iOS issue with the account page
=> Release 1.21.0-RC.3

README.md, public/index.html, src/custom/pages/Claim/ClaimingStatus.tsx
Part of #582 
Updating discord link
1. Make sure the discord link points to https://discord.com/invite/cowprotocol
=> Update discord link

src/custom/components/AccountDetails/styled.ts, src/custom/components/swap/EthFlow/WrapCard.tsx, src/custom/components/swap/EthFlow/helpers.ts, src/custom/components/swap/EthFlow/index.tsx, src/custom/hooks/useSwapCallback.ts, src/custom/pages/Swap/SwapMod.tsx
Addresses comments by @elena-zh here: https://docs.google.com/document/d/1brzImR3f5_YVm3FUU3XZ-rl-nFpubg3yfe7RQ_wN4yg/edit?pli=1
1. [styles for gnosis safe](https://github.com/cowprotocol/cowswap/issues/1055)
2. wrap/unwrap eth modals
3. [creeping border-radius in wrap cards](https://github.com/cowprotocol/cowswap/issues/818#issuecomment-1239389351)
=> [ETH-FLOW] Address comments

src/custom/utils/appzi.ts
Follow up on https://github.com/cowprotocol/cowswap/pull/878#discussion_r937475045
Test is minimal. NPS should work as before
=> Remove unnecesary check

src/custom/constants/index.ts, src/custom/utils/environments.test.ts
This PR updates the barn links from `barn.swap.cow.fi` to `barn.cow.fi` 
1. Go to the FAQ -> Affiliate
2. Make sure that barn links are correct
=> Update barn links

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts, src/cow-react/modules/limitOrders/services/tradeFlow/index.ts
Signing and sending an order to the server without any checks and modals
=> [Limit orders] Sign and send limit order

src/cow-react/modules/limitOrders/const/trade.ts, src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/cow-react/modules/limitOrders/containers/QuoteResolver/hooks/useQuoteRequestParams.ts, src/cow-react/modules/limitOrders/containers/QuoteResolver/index.tsx, src/cow-react/modules/limitOrders/hooks/useLimitOrdersStateFromUrl.ts, src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts, src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts, src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts, src/cow-react/modules/limitOrders/state/limitOrdersQuoteAtom.ts, src/cow-react/pages/LimitOrders/index.tsx
To place a limit order we need to calculate a fee amount.
Currently, we get a fee amount from the quote request.
=> [Limit orders] Request quote for limit orders and use fee amount from quote

.env.production, src/cow-react/modules/swap/containers/NewSwapWidget/propsChecker.ts, src/cow-react/modules/swap/containers/SwapButtons/index.tsx, src/cow-react/modules/swap/helpers/getSwapButtonState.ts, src/custom/state/swap/hooks.tsx
**Release v1.23.0-RC.1**
---
:red_circle: DON'T SQUASH :red_circle:
- https://github.com/cowprotocol/cowswap/pull/1141
- https://github.com/cowprotocol/cowswap/pull/1143
=> Release/1.23 RC.1

config/emergency.json
It's time to enable Service worker again
=> Set resetCacheInCaseOfEmergency to false

src/cow-react/modules/swap/hooks/useSwapFlowContext.ts
=> [1.23] Display ens-name in the pop-up then it's possible

src/custom/utils/trade.ts
=> [1.23] Fix waiting pop-up text for ETH-flow

src/cow-react/modules/swap/containers/ConfirmSwapModalSetup/index.tsx, src/cow-react/modules/swap/hooks/useSwapConfirmManager.ts
=> [1.23] Fix Pending tx modal for wrap/unwrap/approve

src/cow-react/modules/swap/pure/ReceiveAmountInfo/index.tsx, src/cow-react/modules/swap/pure/ReceiveAmountInfo/styled.tsx
=> [1.23] Fix fee discount color in ReceiveAmountInfo tooltip

src/cow-react/modules/swap/hooks/useSetupSwapState.ts
Fixes #1162
Reset Swap form state on wallet disconnection
=> [1.23] Reset Swap form state when wallet disconnected

src/custom/components/Popups/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx
Tiny change fixes an incorrect text string in the notification of transactions
=> Release 1.23 - Fix text

src/cow-react/modules/swap/containers/EthFlow/EthFlowBanner.tsx, src/cow-react/modules/swap/containers/EthFlow/index.tsx, src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.cosmos.tsx, src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx, src/cow-react/pages/Swap/SwapMod.tsx
=> Eth flow v2/banner pt 2

src/cow-react/modules/swap/state/EthFlow/updater.tsx
Closes #1242 
1. Select WETH -> DAI trade
2. Change a slippage to 1% (as an example)
3. Refresh the page
4. See slippage is saved/updated properly
=> [ETH-FLOW-V2] - 1242 - Fix slippage updating

.github/workflows/ci.yml, package.json
Follow up to a comment https://github.com/cowprotocol/cowswap/pull/1267#discussion_r1009316805
- Created env var NODE_VERSION
- Set node version to the v16 lts name: `lts/gallium`
- Updated package.json engine to >= 16
1. Check build steps
* Should build as usual
=> Update node version

.github/workflows/vercel.yml
RELEASE
Fixing one issue with Vercel deploy
No actual code changes other than CI
=> Hotfix 1.23.3-RC.1

.env, .env.production
RELEASE!
One last minor change before the final release tag: https://github.com/cowprotocol/cowswap/pull/1285
Updated env vars with domain regex to account for
- New staging and dev endpoints
- New preview URLs
- New temporary Vercel endpoints until our own are migrated
No changes observable in this PR.
Should only affect vercel related domains. See #1285 for more details
=> Release 1.23.3

src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx, src/cow-react/common/pure/CurrencyInputPanel/CurrencyPreview.tsx, src/cow-react/common/pure/CurrencyInputPanel/styled.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/types.ts, src/cow-react/modules/swap/pure/SwapForm/index.cosmos.tsx, src/cow-react/modules/swap/pure/SwapForm/index.tsx, src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, src/cow-react/modules/trade/hooks/useTradeNavigate.ts, src/custom/state/lists/hooks/hooksMod.ts
=> [1.24] Fix app crash when network was switch to unsupported one

cypress-custom/integration/send.test.ts, src/cow-react/modules/application/containers/App/RoutesApp.tsx, src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, src/cow-react/modules/trade/hooks/useTradeNavigate.ts, src/cow-react/pages/NewSwap/index.tsx
=> [1.24] Fix navigation to account page when open link with referral address

src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts
=> [1.24] Search token by symbol or address with taking into account favourite tokens

src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx, src/cow-react/modules/swap/pure/TradeRates/index.cosmos.tsx, src/cow-react/modules/swap/pure/TradeRates/index.tsx
=> [1.24] Hide fee discount when wrap/unwrap mode is enabled

src/cow-react/modules/trade/hooks/setupTradeState/useResetStateWithSymbolDuplication.ts, src/cow-react/modules/trade/hooks/useTradeNavigate.ts, src/cow-react/modules/trade/hooks/useTradeTypeInfo.ts
=> [1.24] Fix glitch with transparent Import token modal during alert

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Fixes part of #1323
- This pr fixes the issue when the user contains some invalid chain id it will update to current chain id
=> Fix part of the issue with invalid chain id

src/custom/tokens/goerli-token-list.json
Fixes #1380
Updates to correct address of COW on Goerli network
Note: the correct address will be there once this is merged to main branch because the token list is fetched from that branch
=> Update COW address in Goerli token list

src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
=> [1.24] Use only the input token for approve

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, src/cow-react/modules/trade/hooks/setupTradeState/useTradeStateFromUrl.ts, src/cow-react/modules/trade/hooks/useTradeNavigate.ts, src/cow-react/modules/trade/hooks/useTradeState.ts
=> [1.24] Fix trade state update for not-connected wallet state

src/cow-react/modules/application/pure/Widget/index.tsx, src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx, src/cow-react/modules/limitOrders/pure/DeadlineSelector/styled.tsx, src/cow-react/modules/limitOrders/pure/InfoPopup/index.tsx, src/cow-react/modules/limitOrders/pure/InfoPopup/styled.ts, src/cow-react/modules/swap/containers/NewSwapWidget/styled.tsx, src/cow-react/pages/LimitOrders/index.tsx, src/cow-react/pages/LimitOrders/styled.ts, src/custom/assets/cow-swap/alert-circle.svg, src/custom/theme/baseTheme.tsx, src/custom/theme/styled.d.ts
After merging the previous bigger design update PR, I try to do quick and small PR's to keep it going as quick and efficient as possible.
- Appzi button > make more visible/less opacity
- Limit order UI layout
- Arrow separator pass a prop to toggle a horizontal line display
- Limit order UI banner styling (InfoPopup)
=>  🆕🎨 Misc styling II

src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
=> Set proper kind for limit-order

src/cow-react/common/pure/ApproveButton/index.tsx, src/cow-react/common/pure/CurrencyArrowSeparator/styled.tsx, src/cow-react/common/pure/CurrencyInputPanel/styled.tsx, src/cow-react/modules/limitOrders/containers/SettingsWidget/styled.tsx, src/cow-react/modules/swap/containers/FeesDiscount/index.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx, src/cow-react/modules/swap/pure/CurrencySelectButton/styled.tsx, src/cow-react/modules/swap/pure/Price/index.tsx, src/cow-react/modules/swap/pure/ReceiveAmount/styled.tsx, src/cow-react/modules/swap/pure/Row/RowDeadline/index.tsx, src/cow-react/modules/swap/pure/Row/RowFeeContent/index.tsx, src/cow-react/modules/swap/pure/Row/RowReceivedAfterSlippageContent/index.tsx, src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx, src/cow-react/modules/swap/pure/Row/styled.ts, src/cow-react/modules/swap/pure/TradeRates/styled.tsx, src/cow-react/modules/swap/pure/styled.tsx, src/cow-react/modules/swap/pure/warnings.tsx, src/custom/assets/svg/question.svg, src/custom/components/Button/index.tsx, src/custom/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx, src/custom/components/CurrencyLogo/CurrencyLogoMod.tsx, src/custom/components/InfoIcon/index.tsx, src/custom/components/Popover/index.tsx, src/custom/components/Popups/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx, src/custom/components/SwapWarnings/index.tsx, src/custom/components/TransactionSettings/TransactionSettingsMod.tsx, src/custom/components/TransactionSettings/index.tsx, src/custom/components/swap/UnsupportedCurrencyFooter/index.tsx, src/custom/theme/baseTheme.tsx, src/custom/theme/styled.d.ts
Misc. styling updates:
- Addresses some items from https://github.com/cowprotocol/cowswap/issues/1408
=> 🆕🎨 Misc styling III

src/cow-react/modules/swap/containers/NewSwapModals/index.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/propsChecker.ts, src/cow-react/modules/swap/hooks/useTradePricesUpdate.ts, src/cow-react/modules/swap/pure/SwapButtons/index.tsx, src/cow-react/modules/swap/pure/TradeRates/index.tsx, src/cow-react/modules/swap/pure/warnings.tsx, src/cow-react/utils/genericPropsChecker.ts
=> Show nose picking cow on every quote update and display "Price updated" correctly

.github/workflows/ci.yml, package.json
=> Fix cosmos:export build in Vercel

craco.config.js, package.json
=> Vercel build fix

package.json, src/cow-react/modules/swap/containers/NewSwapModals/index.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/propsChecker.ts, src/cow-react/modules/swap/hooks/useTradePricesUpdate.ts, src/cow-react/modules/swap/pure/SwapButtons/index.tsx, src/cow-react/modules/swap/pure/TradeRates/index.tsx, src/cow-react/modules/swap/pure/warnings.tsx, src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, src/cow-react/utils/genericPropsChecker.ts, src/cow-react/utils/request.ts, src/custom/hooks/useIsOnline.ts
**DO NOT SQUASH**
Fixes:
- #1439
- #1442
- #1410
- #1451 
- #1454
=> Hotfix 1.24.3

src/custom/components/Header/index.tsx
=> Use current provider's chainId for trade context in the main menu

src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts, src/custom/state/swap/hooks.tsx
=> Fix app crashing when user switch to an unsupported network

src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts, src/cow-react/pages/NewSwap/index.tsx
Handle Unknown WETH for current network (#1466)
=> Hotfix 1.24.5

config/announcements/announcements-1.md, config/announcements/announcements-100.md, config/announcements/announcements-4.md, config/announcements/announcements-5.md
Removes announcements as requested here https://cowservices.slack.com/archives/C03GH01MR09/p1669145737710959?thread_ts=1669131448.052839&cid=C03GH01MR09
=> Remove announcements

package.json
=> 1.24.6-rc.0

package.json
=> Release 1.24.6

package.json
=> Main -> develop

src/cow-react/modules/limitOrders/pure/RateImpactIndicator/index.tsx
=> Always display tooltip of RateImpactIndicator

src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx, src/cow-react/common/pure/CurrencyInputPanel/defaultCurrencyInputProps.ts, src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/cow-react/modules/swap/pure/SwapForm/index.tsx
=> Disable CurrencyInputPanel when network is unsupported

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
=> Hide "Add a recipient" after clicking on it

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx, src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
=> Improve limit orders trade button states

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
=> Changed text for FeeExceedsFrom error

src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/theme/components.tsx
This PR fixes the issue with limit-orders submit modal
**Before**
**After**
=> Limit orders/submit modal fix

config/announcements/announcements-100.md
Banner because of Gnosis Chain network issues.
1. 🙏 
<https://cowservices.slack.com/archives/C035N0YEB6J/p1669835595056869>
=> Add Outage Banner

src/cow-react/modules/limitOrders/containers/RateInput/index.tsx, src/cow-react/modules/limitOrders/pure/InfoPopup/index.tsx, src/cow-react/modules/limitOrders/pure/InfoPopup/styled.ts, src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx, src/cow-react/modules/limitOrders/pure/Orders/index.tsx, src/cow-react/modules/limitOrders/pure/RateImpactIndicator/index.cosmos.tsx, src/cow-react/modules/limitOrders/pure/RateImpactIndicator/index.tsx, src/cow-react/modules/limitOrders/pure/RateImpactWarning/index.tsx, src/cow-react/modules/limitOrders/pure/RateInput/HeadingText.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/FieldLabel.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx, src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
Fixes #1462
Source of texts: https://docs.google.com/document/d/1au3_QDBkzo4CgW9TlmHcQWMEnsQUaH7m0UItgnFEke0/edit#
=> Limit orders texts improvements

src/cow-react/modules/application/containers/TradeWidgetLinks/index.tsx, src/cow-react/modules/mainMenu/constants/mainMenu.ts
Display limit orders on Barn by defalut (without checking feature-flag)
=> Enable limit orders for Barn

src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts, src/cow-react/modules/limitOrders/pure/ReceiptModal/FeeField.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/FilledField.tsx
Fixes the issue mentioned in #1576
=> Fixes the fee error in receipt modal

src/custom/components/ErrorBoundary/ErrorBoundaryMod.tsx
=> Fix z-index in ErrorBoundary page

src/cow-react/modules/limitOrders/pure/ReceiptModal/FieldLabel.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
=> Add blank line in the order type tooltip

src/cow-react/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
=> Set the deadline to 7 days by default

src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx, src/custom/components/Popups/FailedNetworkSwitchPopupMod.tsx, src/custom/components/WalletModal/Option.tsx
Fixes 1,2,4 from https://github.com/cowprotocol/cowswap/issues/1407
=> General layout fix 2

src/cow-react/modules/application/pure/Page/index.tsx, src/cow-react/pages/error/NotFound/index.tsx, src/cow-react/pages/games/MevSlicer/index.tsx
Fixes points 2, 4 from https://github.com/cowprotocol/cowswap/issues/1406
=> General layout style fixes

src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx, src/custom/components/SearchModal/CurrencyList/index.tsx, src/custom/components/SearchModal/ImportRow/index.tsx, src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx, src/custom/components/SearchModal/ManageLists/index.tsx
Fixes comment 2,3,4,5 on https://github.com/cowprotocol/cowswap/issues/1405
=> Token list styles fix

src/custom/state/swap/reducer.ts
=> Fix app crashing with unsupported network

src/cow-react/common/hooks/useCategorizeRecentActivity.ts
=> Fix for recent activity modal to show liquidity orders

src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/styled.ts, yarn.lock
Fixes the issue mentioned in #1589
To test
- go to limit orders page
- open receipt modal
- make sure it looks fine and can be scrolled on different device size
=> Fix for scroll in receipt modal

src/cow-react/modules/limitOrders/pure/DeadlineSelector/index.tsx, workbox.config.js
=> Fix build failing

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/cow-react/modules/limitOrders/hooks/useApplyLimitRate.ts, src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts, src/cow-react/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts, src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts, src/cow-react/modules/limitOrders/updaters/ActiveRateUpdater/index.ts
=> Store quotient value for limit-orders amount to keep precise values

package.json
Forgot I cannot push to main directly anymore :(
=> Bumped version to v1.25.0-RC.1

src/custom/state/swap/reducer.ts
Fixes #1556 
1. Select WETH as sell token, any other ERC20 as buy token. Fill in the sell amount
2. Replace WETH with ETH
* The amounts should remain as before
3. Play around WRAP/UNWRAPing, buy ETH, switch tokens around
* The only time the input should be reset is when: buy token is ETH and it's a SELL order
=> Fix WETH/ETH swap input being cleared

package.json
=> Bumping version to 1.25.0

src/constants/misc.ts, src/cow-react/modules/limitOrders/const/trade.ts, src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts, src/custom/state/swap/TradeGp.ts, src/utils/calculateSlippageAmount.ts
This PR addresses the comments from #1640
The result is the same
=> Address comments from 1640 pr

.github/auto-merge.yml
This PR adds auto-merge functionality for PRs.
https://github.com/bobvanderlinden/probot-auto-merge
I tried to add comments to make it self-explanatory. I haven't tested this, I guess we can merge and try it out :)
=> Add auto-merge config

src/cow-react/common/pure/RateInfo/index.tsx, src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
=> Fixes for some small issues

src/cow-react/modules/limitOrders/pure/DeadlineSelector/deadlines.ts, src/cow-react/modules/limitOrders/pure/DeadlineSelector/index.tsx
Bring back the deadline options. 
Reverts  3fc3ecf1f0cc1d38a6aad3457428fccc162fbcba from #1625
Please, let's only merge once @nlordell has approved is fine to do so. 
Also, @MindyCoW what do you think should be the default? Currently 7 days
=> Revert deadline reduction

src/cow-react/constants/featureFlags.ts, src/cow-react/modules/application/containers/TradeWidgetLinks/index.tsx, src/cow-react/modules/mainMenu/constants/mainMenu.ts
=> Enable limit-orders by default everywhere

src/cow-react/modules/limitOrders/pure/InfoPopup/index.tsx
Fixes #1622
- Commented out code because we might want to use it again
=> Update message and remove close button

package.json
#Summary
Version bump to 1.26.0
=> Bump version 1.26.0 in package.json

src/cow-react/pages/LimitOrders/styled.ts
- Optimizes the media query to fix https://github.com/cowprotocol/cowswap/issues/1551
=> orders table improve media query

src/cow-react/abis/types/index.ts, src/cow-react/modules/swap/pure/Row/RowDeadline/index.tsx
=> Fix tooltip

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
=> Fix user input handling in limit-orders (amount parsing)

package.json, src/custom/constants/index.ts, yarn.lock
Using latest ethflowcontract from https://github.com/cowprotocol/ethflowcontract/releases/tag/v1.0.0-artifacts
1. Once backend is ready, place one ethflow order on each network
* All of them should work as expected
=> [EthFlow] Updated ethflowcontract to 1.0.0

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
=> Add affiliate flow banners to the Limit orders page

src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
=> Don't change color of amount when price was changed

src/cow-react/modules/application/containers/TradeWidgetLinks/index.tsx, src/cow-react/modules/application/containers/TradeWidgetLinks/styled.ts
=> Remove hover effect from the Beta label

src/cow-react/modules/swap/pure/EthFlow/EthFlowModalContent/configs.ts
=> Update warning messages

src/cow-react/common/pure/CancellationModal/RequestCancellationModal.tsx, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/1750
=> 🎨  Confirmation modal fix

src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx
- Addresses https://github.com/cowprotocol/cowswap/pull/1720#issuecomment-1354434367
=> 🎨 Status label styling

src/cow-react/modules/application/containers/App/index.tsx, src/cow-react/modules/winterEdition/index.tsx
- Addresses this comment https://github.com/cowprotocol/cowswap/pull/1745#discussion_r1052451267
=> 🎅🏼 ❄️ Move winter edition into module

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx, src/cow-react/modules/limitOrders/containers/SettingsWidget/styled.tsx, src/cow-react/modules/swap/containers/NewSwapWidget/styled.tsx, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/custom/components/TransactionConfirmationModal/index.tsx, src/custom/components/swap/SwapModalHeader/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/1755 
https://user-images.githubusercontent.com/31534717/208487441-3a68386e-2472-4949-be07-8967b909e21f.mov
=> 🎨 Fix scroll styles

src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/styled.tsx, src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/styled.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx, src/cow-react/modules/limitOrders/pure/ReceiptModal/styled.ts, src/cow-react/pages/CookiePolicy/index.tsx, src/custom/components/Modal/index.ts, src/custom/components/OrdersPanel/index.tsx, src/custom/components/Popups/index.tsx, src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx, src/custom/components/SearchModal/CommonBases/index.ts, src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx, src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx, src/custom/components/Tokens/styled.ts, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/custom/components/TransactionConfirmationModal/index.tsx, src/custom/components/WalletModal/WalletModalMod.tsx, src/custom/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx, src/custom/theme/baseTheme.tsx, src/custom/theme/styled.d.ts
- Fixes https://github.com/cowprotocol/cowswap/issues/1657
- Headers on the account/order receipt are fixed on scroll
https://user-images.githubusercontent.com/31534717/208954921-47724af8-d5ef-4a81-833a-727204dd8128.mov
https://user-images.githubusercontent.com/31534717/208955011-9a9f2768-3a64-40b0-bff1-0d2f63842e6d.mov
https://user-images.githubusercontent.com/31534717/208954942-71c081bc-e048-4b7d-ac66-018e4ad4043b.mov
https://user-images.githubusercontent.com/31534717/208954969-195918d8-b38a-4991-a90d-66f03953da38.mov
- Open the account and order receipt modal, then test on different viewports.
=> 🎨 Style modals and scroll fix

src/cow-react/pages/TermsAndConditions/TermsAndConditions.md, src/custom/components/WalletModal/index.tsx
This PR updates ToC page with a new version of ToC as defined here https://docs.google.com/document/d/1xxTUoCFYnk4O0Wodqfi-WwhYGg9tTm2ayOYHuXDliLg/edit
- go to `/terms-and-conditions` page
- make sure the content is correct as defined in the doc
=> Updated ToC page

cypress-custom/integration/swap.test.ts, src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
Updating cypress with ethflow changes
Since ethflow was turned on, cypress tests have been failing as the tests did not expect ETH to be "sell-able"
1. Watch cypress GH action
* It should not fail
=> [EthFlow] Update cypress

src/cow-react/modules/swap/pure/CurrencySelectButton/index.tsx, src/cow-react/modules/swap/pure/CurrencySelectButton/styled.tsx
https://stackoverflow.com/questions/57586654/styled-component-attrs-react-does-not-recognize-prop
1. No need to test
=> Fix react warning for styled-component props

src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/custom/theme/baseTheme.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/1790
=> Fix modal overlay (full height)

src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/1800
=> Fix initiating eth refund text

src/assets/styles/styled.ts, src/cow-react/common/pure/HelpCircle/index.tsx, src/cow-react/pages/Account/Affiliate.tsx, src/cow-react/pages/Account/styled.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/1803
- Refactors the `<Txt>` component. Looks like a good candidate component to keep on re-using throughout our app and further refine.
=> Fix tooltip and <Txt> component refactor

src/cow-react/pages/Faq/styled.tsx, src/custom/components/SideMenu/index.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/486
=> Fix FAQ padding

src/cow-react/common/pure/CancellationModal/RequestCancellationModal.tsx, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
=> fix error modal footer margin

src/cow-react/common/pure/RateInfo/index.tsx, src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/styled.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx, src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/Step.tsx, src/custom/components/Modal/index.ts, src/custom/components/OrdersPanel/index.tsx, src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/custom/components/TransactionConfirmationModal/index.tsx
- Fixes #1797
https://user-images.githubusercontent.com/31534717/211568629-ddad8793-26c8-468c-bea0-53b274603e45.mov
https://user-images.githubusercontent.com/31534717/211568475-2813e659-0a05-46e0-a927-17b9e632e3bf.mov
=> Fix scroll style

src/cow-react/pages/TermsAndConditions/TermsAndConditions.md
Fixes https://github.com/cowprotocol/cowswap/issues/1825#issuecomment-1381850034
1. Open T&C page
* Last updated should NOT be italic
=> Removed italic from Terms&Conditions last updated paragraph

src/cow-react/modules/application/pure/Page/index.tsx
=> Fix for wrap mode

src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md
Fixes the issues mentioned in #1824
1. Seems to be fixed
2. Also seems to be fixed
3. Fixed
4. Fixed
5. Will leave this one open for now
=> Address comments in issue

src/custom/components/Button/index.tsx, src/custom/components/Header/styled.ts, src/custom/components/NetworkAlert/NetworkAlert/NetworkAlert.tsx, src/custom/components/Web3Status/Web3StatusMod.tsx, src/custom/components/Web3Status/index.tsx
- Fixes https://github.com/cowprotocol/cowswap/issues/1643
https://user-images.githubusercontent.com/31534717/212743085-e2f94c2c-115f-44b7-b13f-cee564fb30cd.mov
https://user-images.githubusercontent.com/31534717/212743107-4523f20f-05f9-41a2-9ae9-bb5eaa497333.mov
https://user-images.githubusercontent.com/31534717/212742810-dd600e21-c9e1-4c69-a416-ce7b10bcc223.mov
https://user-images.githubusercontent.com/31534717/212742819-6c0fea7e-0125-44d4-a9a3-26c66cda32fa.mov
https://user-images.githubusercontent.com/31534717/212742826-863cfe9d-c8b4-4847-9283-bb6c363506a6.mov
https://user-images.githubusercontent.com/31534717/212742831-ac2ab2a2-a848-4fa2-9ca7-9d77469be6db.mov
https://user-images.githubusercontent.com/31534717/212742832-8868bdad-bf45-4346-81b0-55191590ccdd.mov
=> Gnosis Banner and Connect Wallet style fix

src/cow-react/modules/application/pure/Page/index.tsx, src/cow-react/pages/CookiePolicy/CookiePolicy.md, src/cow-react/pages/CookiePolicy/index.tsx
Fixes #1825
3. Fixed
4. Fixed
5. Not sure I understand this one
6. Maybe this is fixed now
7. Should be better now
8. Should be fixed
=> Fix issues

src/cow-react/modules/swap/pure/ReceiveAmountInfo/index.tsx, src/custom/components/swap/FeeInformationTooltip.tsx
=> Remove gas cost label from ETH orders

package.json
=> Bump the version 1.29.1

config/announcements/announcements-1.md
Reverts cowprotocol/cowswap#1905
=> Revert "Mention work around to expired SSL certificate"

src/cow-react/common/pure/ApproveButton/index.tsx, src/cow-react/common/pure/CurrencyInputPanel/styled.tsx, src/cow-react/modules/swap/pure/EthFlow/EthFlowModalContent/EthFlowModalTopContent.tsx, src/custom/components/OrderProgressBar/styled.ts
- Addresses https://github.com/cowprotocol/cowswap/issues/1408
=> 🎨 Misc. Layout fixes

package.json, yarn.lock
Fixes the issue mentioned in this [comment](https://github.com/cowprotocol/cowswap/pull/1878#issuecomment-1398078118)
Solution is to downgrade the version of `@lingui/cli` because newer version have some issue parsing the variables.
=> Fix lingui bug

src/custom/components/AccountDetails/styled.ts
- Fixes https://github.com/cowprotocol/cowswap/issues/1680
=> Fix wrap modal layout

src/custom/components/Tokens/TokensTableRow.tsx
Closes #1924 
If there's a duplicate, use address
Otherwise, use token symbol
1. On mainnet, search for and add both `AURA` tokens
2. Go to tokens page and search for `aura`
* Both AURA tokens should be visible
3. Click on each in turn, taking you to the swap page
* The clicked token should be loaded as the sell token
* The url should use the token address
4. Back to the tokens page, open any other token like WETH or USDC
* The selected token should be loaded as the sell token
* The url should use the token symbol
=> #1924/Conditionally show link to swap from tokens page

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
=> Add spaces around token symbol in Insufficient balance text

.github/workflows/cla.yml
Updates the cla.yml file as mentioned in https://github.com/cowprotocol/cla
=> Update CLA file

.github/workflows/kanban-in-progress.yml, .github/workflows/kanban-review.yml
Move an issue to In Progress when a draft is open
Move an issue to Review/QA when a PR is ready for review
=> Kanban flow

config/announcements/announcements-1.md
=> Updates banner link to our latest thread

config/announcements/announcements-1.md
As discussed here: https://cowservices.slack.com/archives/C036G0J90BU/p1675878409174509?thread_ts=1675873911.084739&cid=C036G0J90BU
=> Remove Banner

.github/workflows/kanban-in-progress.yml, .github/workflows/kanban-review.yml, scripts/zenhub-automation.js
=> Zenhub kanban automation

src/cow-react/common/pure/TokenAmount/index.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
It builds and works now
Also, not a good idea to add the warning to `TokenAmount`, as it's a basic component used everywhere in the app.
Better is to create a sub component
=> Fixing circular dependency

src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
Fixes #2112
Just reverted the change: https://github.com/cowprotocol/cowswap/pull/2093/files#diff-107deb9cb5d18ad12bba3ac9809861b771e612c1aed80f0f5e4b8ca938bf2879L102
I was trying to fix some cases in the Limit orders form, but as we can see, it broke the current behavior, so, I just reverted the change.
=> Fix CurrencyInputPanel value changes

src/cow-react/modules/wallet/web3-react/connection/asyncConnector.ts, src/cow-react/modules/wallet/web3-react/connection/coinbase.tsx, src/cow-react/modules/wallet/web3-react/connection/formatic.tsx, src/cow-react/modules/wallet/web3-react/connection/safe.tsx
We accidentally lost AsyncConnector here:
https://github.com/cowprotocol/cowswap/pull/2073/files#diff-bfe491207c9919a40680fb22e39fef2e8f0f71ed1b98838d533890dda87826caL29
=> Move back AsyncConnector

src/cow-react/modules/trade/hooks/useOnCurrencySelection.ts
=> Invert tokens when user selected the same token

src/cow-react/modules/swap/helpers/getSwapButtonState.ts, src/cow-react/modules/swap/pure/SwapButtons/index.tsx, src/custom/hooks/useRefetchPriceCallback.tsx
=> UnsupportedToken state for the swap form

config/barn/strategies/strategy-4.json, config/production/strategies/strategy-4.json, config/strategies/strategy-1.json, config/strategies/strategy-100.json, config/strategies/strategy-4.json, config/strategies/strategy-5.json
This prunes the configuration branch, to remove stale files / folders.
- We no longer support Rinkeby - as such, we remove all files with `chainId` 4
- We no longer use top level strategies, as code now relies on environment specific strategy definitions. As such, we can remove top level strategies folder.
=> Remove stale configurations

src/cow-react/common/utils/markets.ts, src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx, src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.test.ts, src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.ts, src/cow-react/modules/limitOrders/utils/calculatePriceDifference.test.ts, src/cow-react/modules/limitOrders/utils/calculatePriceDifference.ts, src/cow-react/utils/fractionUtils.ts, src/cow-react/utils/rawToTokenAmount.ts, src/custom/constants/index.ts, src/custom/lib/utils/tryParseCurrencyAmount.ts
Anxo fixed most of it on https://github.com/cowprotocol/cowswap/pull/2145
Merging to parent PR
Fixing broken unit tests and broken behaviour as well
WIP, can't think anymore today
=> Fixed unit tests and behaviour

src/cow-react/abis/types/index.ts, src/cow-react/modules/wallet/web3-react/containers/WalletModal/index.tsx
Fixes the issue mentioned in #2200
=> Fix connect again wallet button

src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
Out token api source has stopped working
Commenting it out until we find a new source
1. Open the console and on the network tab filter for `tokenQuery`
2. Open the token selector an type in anything
* There should be no network calls
=> Commenting out token search

src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx, src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/styled.ts
Proposal for modifying the banner styles based on https://github.com/cowprotocol/cowswap/pull/2189:
=> Improve styles

src/cow-react/api/proxy/hooks.ts
Addresses changes requested on #2237
=> Fix MR comments

config/barn/announcements/announcements-1.md, config/barn/announcements/announcements-100.md, config/barn/announcements/announcements-5.md
Banner for staging migration downtime announcement
https://cowservices.slack.com/archives/C036PMLUPQF/p1680663173937509
=> Add barn downtime

config/production/announcements/announcements-1.md, config/production/announcements/announcements-100.md, config/production/announcements/announcements-5.md
Creating a warning for the downtime tomorrow
=> DB migration banner

src/cow-react/modules/limitOrders/pure/OrderType/index.tsx, src/cow-react/modules/limitOrders/pure/OrderType/styled.tsx
Updates Order Type dropdown from https://github.com/cowprotocol/cowswap/pull/2275
- go to limit orders
- turn on expert mode
- you should see order type option
=> Update order type dropdown UI

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx, src/cow-react/modules/wallet/web3-react/connection/trust.tsx
Fixes #2280
Changed text from 'Unhandled error' to 'Error loading price. Try again later.'
=> [Limit orders] Changed error text for UNHANDLED_ERROR

README.md
Updates README file to include information on `.env.local` file setup.
=> Add information on minimum .env.local setup

src/cow-react/modules/limitOrders/pure/OrderType/styled.tsx
- Adds additional styling for the order type dropdown on https://github.com/cowprotocol/cowswap/pull/2238
https://user-images.githubusercontent.com/31534717/231230564-42f292a1-4423-482a-bfce-7889f92faf12.mov
https://user-images.githubusercontent.com/31534717/231230577-d38a3c78-bf09-4953-ad1b-ada8ab05b336.mov
=> Order type dropdown styling

src/cow-react/abis/types/index.ts, src/cow-react/modules/limitOrders/containers/OrdersWidget/MultipleCancellationMenu.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx, src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx, src/cow-react/modules/limitOrders/pure/Orders/index.tsx, src/cow-react/modules/limitOrders/pure/Orders/styled.tsx
- This PR iterates on the great PR @shoom3301 did to implement the Figma design.
- Mainly styles the checkboxes and some other layout mods
https://user-images.githubusercontent.com/31534717/231697168-2d6e2381-a700-45b0-906e-22013048bc7f.mov
https://user-images.githubusercontent.com/31534717/231697199-ca6b4b0e-c3b1-4f3b-8ff9-c9a64e2c8960.mov
=> Multiple cancellations: Checkbox styles

src/cow-react/modules/wallet/web3-react/connection/index.tsx
Quick fix for #2340
Disabled Ledger-live wallet on mobile
=> Disable Ledger on Mobile

src/cow-react/common/pure/ExpertModeModal/index.tsx
Fixes #2342
`window.prompt()` doesn't work inside an Iframe and with some other cases.
=> feat: replace expert mode enabling prompt by UI control

config/announcements/announcements-1.md
Update the banner to reflect the current situation.
Related thread: https://cowservices.slack.com/archives/C0375NV72SC/p1682493288057339
=> Increased traffic banner

src/components/TransactionConfirmationModal/index.tsx, src/cow-react/modules/account/containers/Transaction/ActivityDetails.tsx, src/cow-react/modules/account/containers/Transaction/StatusDetails.tsx, src/cow-react/modules/wallet/api/utils/connection.ts, src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts
=> fix: rename Gnosis Safe -> Safe

src/cow-react/pages/Account/Balances.tsx
=> fix(account-page): display 0 COW as default balance in Account page

src/cow-react/common/hooks/useCancelOrder/index.ts
=> fix(cancel-order): fix order cancellation error message

src/constants/lists.ts
Fixes #2171
https://uma.xyz/uma.tokenlist.json
=> fix: remove UMA tokens list because it doesn't work

src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts, src/cow-react/modules/swap/helpers/getSwapButtonState.ts
=> fix(swap): don't display quote errors when wrap/unwrap

src/components/Header/index.tsx, src/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/components/TransactionConfirmationModal/index.tsx, src/constants/misc.ts
Shows confetti only on first transaction submitted
=> feat: show confetti on submitted transaction only

src/components/TransactionConfirmationModal/index.tsx, src/cow-react/common/pure/ApproveButton/index.tsx
Fixes #2390
During merging conflicts in https://github.com/cowprotocol/cowswap/pull/2352
The commit was lost: https://github.com/cowprotocol/cowswap/commit/a259a266f6a785be7c55a83f1345c18726b9cac1
=> chore: fix pending approve modal for Metamask

src/cow-react/common/hooks/useCancelOrder/index.ts
Fixes #2392
https://github.com/cowprotocol/cowswap/pull/2380 - here I left the code tested out
=> fix(order-cancellation): fix detection of isOffChainCancellable flag

src/components/NotificationBanner/index.tsx, src/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx, src/cow-react/common/hooks/useCancelOrder/index.ts
Fixes #2402
1. Wrong `onDismiss` callback call: https://github.com/cowprotocol/cowswap/pull/2352/files#diff-004b8fdc3c4d0627b44287b09e14c2ca8851ebe01e28328db2f42f59a65fa40aR86
2. `NotificationBanner` stack overflow: https://github.com/cowprotocol/cowswap/pull/2336/files#diff-a7ab9e05a1f39542994ad9ca4b131fd46e17b7cef9c2abe25b12976e5f16d409R67
=> fix: fix modal closing by X icon and fix notification banner stack overflow

CHANGELOG.md, src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts, src/cow-react/modules/wallet/web3-react/updater.ts, src/hooks/useAppCode.ts, src/state/enhancedTransactions/hooks/index.ts
- Removed one duplicated hook
- Renamed existing hooks to be clear what their purpose is
1. Connect with Safe via WC (desktop and mobile)
* Should work as usual
1. Connect with Safe as an app
* Should work as usual
=> chore: consistently naming safe related hooks

src/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
=> feat(tokens-search): autofocus the tokens search input

package.json
=> Add release tag 1.36.0

cypress-custom/integration/limit-orders.test.ts, cypress-custom/integration/swap.test.ts, cypress-custom/support/commands.d.ts, cypress-custom/support/commands.js, package.json, src/components/Header/index.tsx, src/cow-react/modules/application/containers/App/index.tsx, src/cow-react/modules/swap/hooks/useSwapRawState.ts, src/cow-react/modules/utm/hooks.ts, src/cow-react/modules/utm/index.ts, src/cow-react/modules/utm/state.ts, src/cow-react/modules/utm/types.ts, src/hooks/useAppData.ts, src/state/appData/AppDataInfoUpdater.tsx, src/state/swap/actions.ts, src/state/swap/hooks.tsx, src/state/swap/reducer.ts, src/utils/appData.ts, yarn.lock
Hotfix 1.36.1
Changes:
- Swap url amounts
- UTM fields on appData
- ~USDT approval work around fix~ not ready
=> Hotfix 1.36.1

config/fortunes.json
https://cowservices.slack.com/archives/C035RP0RH3P/p1684346772360569?thread_ts=1684322019.883719&cid=C035RP0RH3P
=> chore: update CoW fortunes list

package.json, src/cow-react/abis/types/index.ts, src/cow-react/common/pure/TokenAmount/index.tsx, src/cow-react/common/services/getQuoteCurrency/index.ts, src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts, src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts, src/cow-react/utils/amountFormat/index.test.ts, src/cow-react/utils/amountFormat/index.ts, src/hooks/usePriceImpact/useFallbackPriceImpact.ts, src/utils/price.ts
Fixes:
- https://github.com/cowprotocol/cowswap/pull/2501 
- https://github.com/cowprotocol/cowswap/pull/2505
=> chore: release hotfix/1.37.1

src/common/services/getQuoteCurrency/index.ts
Re-apply one change from https://github.com/cowprotocol/cowswap/pull/2485 that got lost in the merging of last release.
=> fix: bring back change after bad merge

src/modules/limitOrders/pure/OrderStatusBox/index.tsx, src/modules/limitOrders/pure/Orders/OrderRow/index.tsx
delete redundant prop for https://github.com/cowprotocol/cowswap/pull/2559/files#r1209170114
=> refactor: delete derived prop

src/utils/amountFormat/index.test.ts, src/utils/trimTrailingZeros.test.ts, src/utils/trimTrailingZeros.ts
Adds test for the fix:
https://github.com/cowprotocol/cowswap/pull/2501
This PR is done separately from the FIX because I wanted to do the changes on top of the refactor
=> Add test for formatting issue

src/legacy/components/TransactionSettings/TransactionSettingsMod.tsx, src/legacy/hooks/useRefetchPriceCallback.tsx, src/modules/swap/containers/Row/RowDeadline/index.tsx, src/modules/swap/containers/Row/RowFee/index.tsx, src/modules/swap/containers/Row/RowSlippage/index.tsx, src/modules/swap/containers/SwapWidget/index.tsx, src/modules/swap/containers/TradeBasicDetails/index.tsx, src/modules/swap/hooks/useEthFlowContext.ts, src/modules/swap/hooks/useFlowContext.ts, src/modules/swap/pure/ReceiveAmountInfo/index.tsx, src/modules/swap/pure/Row/RowDeadline/index.cosmos.tsx, src/modules/swap/pure/Row/RowDeadline/index.tsx, src/modules/swap/pure/Row/RowSlippageContent/index.cosmos.tsx, src/modules/swap/pure/Row/RowSlippageContent/index.tsx, src/modules/swap/state/EthFlow/updaters/EthFlowDeadlineUpdater.tsx, src/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx, src/modules/trade/containers/TradeWidget/index.tsx
Based on https://github.com/cowprotocol/cowswap/pull/2576#discussion_r1210561601
Rename `isEthFlow` flags where it made sense to `isEoaEthFlow`
1. Whole app should work as before
=> refactor: rename (most) isEthFlow flags to isEoaEthFlow

src/common/containers/ImportTokenModal/index.tsx, src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/modules/tradeQuote/hooks/useQuoteParams.ts, src/modules/tradeQuote/hooks/useSetTradeQuoteParams.ts, src/modules/tradeQuote/index.ts, src/modules/tradeQuote/state/tradeQuoteAtom.ts, src/modules/tradeQuote/state/tradeQuoteParamsAtom.ts, src/modules/twap/containers/TwapFormWidget/index.tsx, src/modules/twap/updaters/QuoteObserverUpdater.tsx
=> refactor: add tradeQuoteParamsAtom to be able to configure quote API requests

src/legacy/constants/routing.ts, src/legacy/constants/tokens.ts
Add EURe to list of default favourites on Gnosis Chain
- This change will only be visible on new sessions.
Users who previously visited CoW Swap will not have the token added to their default list, as this could affect previously selected tokens
- The image is being updated in the token list https://github.com/cowprotocol/token-lists/pull/211
1. Open a new browser/device/incognito mode (using this PR will already do that since it's a fresh url)
2. Change network to Gnosis chain
3. Open the token selector
* EURe should be in the list of favourite tokens at the top
=> feat(favorite-tokens): add EURe as default on Gnosis Chain

src/modules/twap/containers/TwapFormWidget/tooltips.tsx
Fixes TWAP Total time tooltip.
=> fix: tooltip time display

src/modules/twap/const.ts, src/modules/twap/containers/TwapFormWarnings/index.tsx, src/modules/twap/containers/TwapFormWarnings/warnings/SmallPartTimeWarning.tsx, src/modules/twap/containers/TwapFormWarnings/warnings/index.ts, src/modules/twap/hooks/useTwapFormState.ts, src/modules/twap/pure/PrimaryActionButton/getTwapFormState.tsx, src/modules/twap/pure/PrimaryActionButton/index.tsx, src/modules/twap/utils/isPartTimeIntervalTooShort.ts
Part of #2628 
Minimum part time duration
1. Load the app on Safe
2. Fill in a time shorter than 5 min
* Banner is displayed
3. Set more than 5 min
* No banner
=> feat(twap): validation and warnings - minimum part time

src/modules/wallet/api/pure/WalletModal/index.tsx, src/modules/wallet/web3-react/connection/index.tsx
Hiding zengo wallet
1. Open wallet modal
2. Should not show zengo wallet
=> chore: hide zengo wallet

package.json, src/modules/wallet/api/pure/WalletModal/index.tsx, src/modules/wallet/web3-react/connection/index.tsx
Hotfix: remove zengo wallet (https://github.com/cowprotocol/cowswap/pull/2748)
=> chore: release hotfix/1.40.4

src/modules/trade/hooks/useSwitchTokensPlaces.ts
=> fix(trade): switch tokens places event when one is empty

src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
=> fix(trade): display unsupported token banner

src/modules/application/containers/TradeWidgetLinks/index.tsx, src/modules/application/containers/TradeWidgetLinks/styled.ts, src/modules/trade/containers/TradeWidget/styled.tsx, src/modules/twap/containers/TwapFormWidget/styled.tsx
- Styles the container menu items
https://github.com/cowprotocol/cowswap/assets/31534717/8c38c86d-0559-4cd5-b9cc-f8bb84eae253
=> feat: container links

src/common/pure/OrderSubmittedContent/index.cosmos.tsx, src/common/pure/OrderSubmittedContent/index.tsx, src/legacy/components/EnhancedTransactionLink/index.tsx, src/modules/trade/containers/TradeConfirmModal/index.tsx, src/pages/Claim/ClaimingStatus.tsx
=> fix: display relevant link in Order Submitted modal

src/modules/ordersTable/pure/ReceiptModal/index.tsx
Closes #2706 
Update tooltip for filled field
1. Go to limit orders
2. Check the filled field tooltip
* Should not mention partial fills are not supported
=> feat(filled-tooltip): update filled tooltip

src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, src/modules/trade/pure/UnlockWidgetScreen/styled.ts
=> feat: update styles

src/pages/Account/Balances.tsx
Fixes #2821
- got to accounts page
- test with account that has 0 cow tokens
- there should be 0
- test with account that has some cow tokens
- the correct amount should be visible
- test on different chains
=> fix(account-page): cow balance issue

src/common/pure/TransactionSubmittedContent/SurplusModal.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/2790
=> feat: wrap symbol name surplus modal

src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, src/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts, src/modules/swap/containers/SwapWidget/index.tsx, src/modules/swap/state/useSwapDerivedState.ts, src/modules/trade/containers/TradeWidget/index.tsx, src/modules/trade/containers/WrapFlowActionButton/index.tsx, src/modules/tradeFormValidation/pure/TradeFormButtons/index.tsx, src/modules/tradeFormValidation/services/validateTradeForm.ts, src/pages/AdvancedOrders/index.tsx, src/pages/LimitOrders/index.tsx
Cherry pick: https://github.com/cowprotocol/cowswap/pull/2774
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1689165677430129
=> feat(trade): generalise wrap/unwrap flow for all trade widgets

src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/2849
The tooltip is to be defined. Not sure that is already fixed on `develop`.
=> feat: change label text

src/api/gnosisProtocol/api.ts, src/common/hooks/useGetSurplusFiatValue.ts, src/common/hooks/useLegacySetChainIdToUrl.ts, src/common/pure/TransactionSubmittedContent/SurplusModal.tsx, src/common/pure/TransactionSubmittedContent/index.tsx, src/legacy/components/TransactionConfirmationModal/index.tsx, src/legacy/components/analytics/pixel/constants.ts, src/legacy/components/analytics/pixel/facebook.ts, src/legacy/components/analytics/pixel/linkedin.ts, src/legacy/components/analytics/pixel/microsoft.ts, src/legacy/components/analytics/pixel/paved.ts, src/legacy/components/analytics/pixel/reddit.ts, src/legacy/components/analytics/pixel/twitter.ts, src/legacy/components/analytics/pixel/utils.ts, src/legacy/constants/index.ts, src/modules/application/containers/TradeWidgetLinks/index.tsx, src/modules/swap/containers/SurplusModalSetup/index.tsx, src/modules/swap/containers/SwapWidget/index.tsx, src/modules/swap/index.ts, src/modules/swap/updaters/SwapDerivedStateUpdater.tsx, src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx, src/pages/Swap/index.tsx, src/utils/getExecutedSummaryData.ts, src/utils/orderUtils/parseOrder.ts
> DO NOT SQUASH
Brings the changes from the fixes for 1.41 into 1.42
I just created the PR since there were a bunch of merge conflicts I had to manually fix. 
As long as it compiles and work, I will merge and then merge to `develop`
=> Merge release 1.41 into 1.42

src/legacy/components/analytics/pixel/constants.ts
Apologies, I forgot to remove the tests before the release.
Amending my error here
=> chore(pixel-resilience): remove test

src/legacy/hooks/useRefetchPriceCallback.tsx, src/legacy/state/lists/hooks.ts, src/modules/tradeFormValidation/services/validateTradeForm.ts, src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts, src/modules/tradeQuote/hooks/useQuoteParams.ts, src/modules/tradeQuote/hooks/useTradeQuotePolling.ts, src/modules/twap/hooks/useTwapWarningsContext.ts, src/utils/getDoesMessageIncludeToken.ts, src/utils/getIsMessageIncludeToken.ts, src/utils/getQuoteUnsupportedToken.ts
=> fix(trade): fix UnsupportedToken state displaying conditions

src/modules/twap/const.ts, src/modules/twap/containers/TwapFormWidget/index.tsx
=> fix(twap): increase max slippage up to 100%

src/legacy/components/FlashingLoading/index.tsx
- Styles the suspense loader
- Related issue https://github.com/cowprotocol/cowswap/issues/324
https://github.com/cowprotocol/cowswap/assets/31534717/87adbbb2-d9af-4453-bde3-8a02552df3e7
https://github.com/cowprotocol/cowswap/assets/31534717/aadadf30-35d2-42ba-9737-0dc6efccfe75
https://github.com/cowprotocol/cowswap/assets/31534717/f32a943a-5c6f-4205-890a-212a15055ce4
=> feat: style suspense loader

src/modules/swap/containers/SwapWidget/index.tsx, src/modules/trade/containers/TradeWidget/index.tsx
=> fix(trade): allow selling all native tokens from any trade widget

src/common/pure/CurrencyAmountPreview/index.tsx, src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx, src/common/pure/CurrencyInputPanel/styled.tsx, src/common/pure/CurrencySelectButton/styled.tsx
=> feat(trade): display disabled appearance for currency input panel

src/api/gnosisSafe/index.ts, src/common/pure/OrderSubmittedContent/index.tsx, src/legacy/components/ExplorerLink/index.tsx, src/legacy/components/Popups/PopupItem.tsx, src/legacy/components/Popups/TransactionPopup.tsx, src/legacy/state/application/reducer.ts, src/legacy/state/orders/helpers.tsx, src/legacy/state/orders/middleware/updateOrderPopup.ts, src/legacy/utils/index.ts, src/modules/twap/hooks/useCreateTwapOrder.ts
=> fix(twap): display a correct link to Safe tx on order creation

src/common/pure/PriceImpactIndicator/index.tsx
=> fix: change the price impact tooltip text

src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
=> feat(twap): display Creating... for Scheduled orders when it's supposed to be created already

src/common/constants/common.ts, src/common/pure/CowSwapSafeAppLink/index.tsx, src/common/pure/InlineBanner/banners.tsx, src/common/pure/Modal/index.tsx, src/common/pure/Modal/styled.tsx, src/legacy/components/NumericalInput/index.tsx, src/legacy/state/orders/updaters/utils.ts, src/modules/ordersTable/containers/OrdersTableWidget/index.tsx, src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx, src/modules/ordersTable/pure/OrdersTableContainer/index.tsx, src/modules/trade/pure/TradeNumberInput/index.tsx, src/modules/twap/const.ts, src/modules/twap/containers/TwapFormWarnings/warnings/UnsupportedWalletWarning.tsx, src/modules/twap/containers/TwapFormWidget/index.tsx, src/modules/twap/hooks/useEmulatedOrders.ts, src/modules/twap/pure/CustomDeadlineSelector/index.tsx, src/pages/AdvancedOrders/index.tsx, src/pages/LimitOrders/index.tsx
Fixes #2950 #2951
1. There was a problem in `CustomDeadlineSelector`, it set a value for `hoursValue` and `minutesValue` only once
2. In `TradeNumberInput` I've changed the triggers of calling `validateInput` in `useEffect`. I'm afraid it can affect other number inputs. @elena-zh please pay attention to other number inputs on the TWAP form
3. Fixed annoying warnings in `StyledDialogContent`
4. Additionally fixed #2951
=> fix(twap): display actual value for num of parts and custom deadline

src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/2954
- Enhances the TWAP banner content/text shown on SWAP when a high slippage is detected
=> feat: enhance twap banner

src/legacy/components/ExplorerLink/index.tsx, src/legacy/utils/index.ts, src/legacy/utils/retry.test.ts, src/modules/mainMenu/constants/mainMenu.tsx, src/modules/swap/pure/warnings.tsx
=> fix(menu): display explorer home link when wallet is not connected

package.json, src/api/gnosisProtocol/api.ts, src/api/gnosisProtocol/legacy/types.ts, src/legacy/hooks/usePriceImpact/useFallbackPriceImpact.ts, src/legacy/hooks/usePriceImpact/useQuoteAndSwap.ts, src/legacy/hooks/useRefetchPriceCallback.tsx, src/legacy/hooks/useStablecoinPrice/index.ts, src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts, src/legacy/state/price/updater.ts, src/legacy/utils/price.ts, src/legacy/utils/priceLegacy.ts, src/modules/tokens/hooks/useEnoughBalance.ts, src/modules/tokens/index.ts, src/modules/tradeQuote/hooks/useQuoteParams.ts, yarn.lock
This PR ensures the users request a `verified` quote when they have enough balance.
This will make the backend API to simulate the quote. It will be more accurate, but they need to have balance for the token. 
NOTE: They don't need to have allowance. 
Main hook helping to implement this feature. 
It will check if an account has enough balance (compared to the passed `amount`).
It will handle also the native currency (i.e. ETH), so it will check that the user has enough balance if the amount is in this currency.
Companion pure function for the hook, it allows to be used by providing all the dependencies. `useEnoughBalance` is convenient for most of the cases, because it will get the native ETH price and the tokens as part of the responsibility, however for some cases where you need to …
=> chore(solver-colocation): use verified quote

src/modules/tokens/hooks/useEnoughBalance.ts
Somehow 2 commits where lost in the merge. They were present in https://github.com/cowprotocol/cowswap/pull/2945  and its follow up, but something strange happened and they don't show up and they weren't merged to the release
=> Cherry pick lost commits

src/mocks/tradeStateMock.ts, src/modules/limitOrders/hooks/useTradeFlowContext.ts, src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx, src/modules/limitOrders/services/safeBundleFlow/index.ts, src/modules/limitOrders/services/tradeFlow/index.ts, src/modules/limitOrders/services/types.ts, src/modules/swap/hooks/useFlowContext.ts, src/modules/swap/services/ethFlow/index.ts, src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts, src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts, src/modules/swap/services/swapFlow/index.ts, src/modules/swap/services/types.ts
Removes the uploading of documents for all flows, except TWAP
Test in the consolidated branch instead
Just make sure TWAP is the only flow that uploads docs
=> chore(appData): remove unnecesary flows

.github/workflows/ci.yml, cypress-custom/integration/limit-orders.test.ts, cypress.config.ts
Fix Limit order tests
It was not waiting enough for the limit order input to be enabled. 
I refactord the tests so they are easier to read and less error prone (dryer)
Check cypress result in this PR
=> Fix cypress

src/modules/twap/pure/CustomDeadlineSelector/styled.tsx
- Fixes styles in custom deadline selector for TWAP orders
- Unused selectors cleanup
=> feat: fix styles custom deadline twap

src/modules/appData/services/index.ts
Fixes issues https://github.com/cowprotocol/cowswap/issues/3009
The document was being uploaded to the wrong environment. 
Example on my tests (i reproduced staging locally):
https://staging.explorer.cow.fi/gc/orders/0x04963b675dfac966f88c9681ffc1b59e98cc71852889b5e8d15ad19b4663156940a50cf069e992aa4536211b23f286ef88752187ffffffff?tab=overview
Unfortunately to test this for real, we need to merge into staging!
=> fix: fix issue uploading appData in STAGING

src/modules/tradeQuote/hooks/useQuoteParams.ts
Context: https://cowservices.slack.com/archives/C0375NV72SC/p1690980795844549
=> fix: pass account address along with other verified quote params

src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
Changes the text when no open orders. Addresses: https://github.com/cowprotocol/cowswap/issues/3010
=> feat: text change

src/api/gnosisProtocol/legacy/types.ts, src/legacy/utils/priceLegacy.ts, src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap, src/modules/tradeQuote/hooks/useQuoteParams.ts, src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx, src/test-utils.tsx
Unit tests for the fix: https://github.com/cowprotocol/cowswap/pull/3016
=> test: test useAddress field in useTradeQuotePolling

src/modules/twap/state/swapAmountDifferenceAtom.ts
=> fix(twap): don't crash app while the swap amount diff calculation

src/modules/trade/pure/TradeNumberInput/index.tsx, src/modules/twap/pure/CustomDeadlineSelector/index.tsx, src/modules/twap/pure/CustomDeadlineSelector/styled.tsx, src/modules/twap/state/swapAmountDifferenceAtom.ts
- Number arrows fix - on the hotfix I messed up a merge and some commits were not included
- Fix app crash when selling ETH on TWAP https://github.com/cowprotocol/cowswap/pull/3033
- [Not merged yet] Contract addresses https://github.com/cowprotocol/cowswap/pull/3031
=> chore(release): hotfix 1.44.2

apps/cowswap-frontend/index.html, apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, apps/cowswap-frontend/src/modules/application/containers/TradeWidgetLinks/index.tsx, apps/cowswap-frontend/src/modules/mainMenu/utils.ts
Context: https://cowservices.slack.com/archives/C036G0J90BU/p1692376011339719
=> fix(twap): rename advanced to TWAP

apps/cowswap-frontend/jest.config.ts, apps/cowswap-frontend/package.json, apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx, apps/cowswap-frontend/src/test-utils.tsx
=> test: fix useTradeQuotePolling test imports

apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveState.ts, apps/cowswap-frontend/src/common/hooks/useApproveState.ts, apps/cowswap-frontend/src/common/hooks/useShouldZeroApprove/index.ts, apps/cowswap-frontend/src/common/hooks/useShouldZeroApprove/shouldZeroApprove.ts, apps/cowswap-frontend/src/common/pure/ApproveButton/index.cosmos.tsx, apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx, apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx, apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx, apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/index.ts, apps/cowswap-frontend/src/modules/appData/index.ts, apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.tsx, apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useSetupEthFlow.ts, apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts, apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts, apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/InvestOption.tsx
Fixes build warnings
The issue was with some imports being re-exported and vite not being able to detect them
=> chore(tech-debt): fix build warnings

apps/cowswap-frontend/src/common/pure/CurrencyLogo/hooks/useCurrencyLogoURIs.ts
Issue: https://docs.google.com/document/d/1sIwsE9sCuEMZoNuBVXxpdxLrW-s-tF75AEnAMUX05I0/edit#heading=h.723o8oxoch1p
`EURE_GNOSIS_CHAIN` const doesn't have a logo, but the token has it in `cowprotocol/token-lists`.
However, since `EURE_GNOSIS_CHAIN` is always used first (because it's hardcoded) the token gets a logo url from `getTokenLogoURI()` and it's invalid.
After loading the tokens list we should update the cache if there is a `logoURI` and no `imageOverride`.
1. Open Gnosis Chain and select EURe token
=> fix: update token logo cache after tokens list loading

apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts, apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Release `1.47.0`
Adding one more fix (#3127) and close the release
=> chore(release): 1.47.0

apps/cowswap-frontend/src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts, apps/cowswap-frontend/src/legacy/state/price/updater.ts, apps/cowswap-frontend/src/modules/appData/index.ts, apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts, apps/cowswap-frontend/src/modules/permit/const.ts, apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts, apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts, apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts, apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts, apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts, apps/cowswap-frontend/src/modules/swap/services/types.ts, apps/cowswap-frontend/src/modules/tokens/hooks/useEnoughBalance.ts, apps/cowswap-frontend/src/modules/tradeQuote/hooks/useQuoteParams.ts
Follow up to https://github.com/cowprotocol/cowswap/pull/3067
Add allowance checks for permittable tokens
- If the token is NOT permittable, show the regular flow (everything was considered permittable in the previous PR)
- When sending the order, check the existing allowance
- If already enough allowance, do not include the permit/request permit signature
- If permittable and NOT enough allowance, do include the permit
- Check token is permittable for DAI and USDC
- Check token is permittable on Gnosis Chain
- Detect when permit is expired/invalid
- Update the permit when expired/invalid
- ✅ (this PR) ~Offer permit only when there's not enough allowance~
- Additional UI changes being worked on by Michel
- On Goerli, of the tokens that I checked, only COW seems to work as permittable
- On …
=> feat(permit): check allowance

apps/cowswap-frontend/.env.production
=> Hotfix 1.47.1 follow ups

apps/cowswap-frontend/cosmos.config.json, apps/cowswap-frontend/package.json
=> chore: fix cosmos CI

apps/cowswap-frontend/src/common/pure/ButtonSecondary/index.tsx
=> feat: update approve button color

apps/cowswap-frontend/src/common/constants/theme.ts, apps/cowswap-frontend/src/common/pure/Modal/index.tsx, apps/cowswap-frontend/src/common/pure/Modal/styled.tsx, apps/cowswap-frontend/src/common/pure/NewModal/index.tsx, apps/cowswap-frontend/src/legacy/theme/baseTheme.tsx, apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.tsx
- Fixes the new CoW Modal styles
- CloseX (X close icon) click event to close doesn't work. Clicking outside the modal (backdrop area) **does** work.
=> feat: fix new cow modal styles

libs/common-const/src/routing.ts, libs/common-const/src/tokens.ts
=> refactor: remove unused code

apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
Make it more consistent. Just drop the word "order"
- Click in Trade in the menu
- Now should show SWAP, LIMIT, TWAP
=> chore: simplify trade menu

apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts
#3147 
Refactor ugly code, no functional changes
⚠️ Does not improve the coverage of permittable tokens ⚠️ 
1. On mainnet or goerli, pick different sell tokens
2. Observe `permittableTokens:v0` key
* Permittable tokens should be marked as permittable with the respective type
* Non permittable tokens should be set to `false`
=> refactor(permit): refactor checkIsTokenPermittable

apps/cowswap-frontend/src/modules/wallet/containers/Web3Status/index.tsx, libs/common-const/src/common.ts
There was some legacy code that was not being used (`lastProvider` in local storage)
I removed it! 
should work as before.
I can see autoconnect works
=> fix: remove legacy code

apps/cowswap-frontend/src/modules/application/containers/TradeWidgetLinks/index.tsx
=> fix: display trade menu item badge

apps/cowswap-frontend/src/legacy/state/user/hooks.tsx, apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
Some people like more Dark mode, some people light mode, you can choose the one you want....
WROOOOOOOONG! You like darkmode, and that's the end of it. This PR force users to use Darkmode because is Halloween, and its cool, and spooky. 
This PR needs to be reverted after Halloween
Try to set light mode
=> chore: disable light mode

apps/cowswap-frontend/src/legacy/state/cowToken/middleware.ts, apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.ts
Continuation on https://github.com/cowprotocol/cowswap/pull/3278 
Fixes an issue that was making the spooky sounds not to sound (case where you have in your local storage the light theme setting)
Credits to @alfetopito to find the issue!
Before this PR you could reproduce by adding the following value to the local storage key `redux_localstorage_simple_user`:
```
{"selectedWalletBackfilled":true,"matchesDarkMode":true,"userDarkMode":false,"userExpertMode":false,"recipientToggleVisible":false,"userLocale":"en-US","userClientSideRouter":false,"userHideClosedPositions":false,"userSlippageTolerance":"auto","userSlippageToleranceHasBeenMigratedToAuto":true,"userDeadline":1800,"tokens":{"1":{"0x6B175474E89094C44Da98b954EedeAC495271d0F":{"chainId":1,"address":"0x6B175474E89094C44Da98b954EedeAC495 …
```
=> feat: fix issue with sounds

config/fortunes.json
Removed old fortunes, added just Haloween
=> Spooky Fortune Cookies

README.md, yarn.lock
This PR just moves arrounds some elements in the documentation to make it a bit more structured.
Additionally, documents `REACT_APP_ORDER_BOOK_URLS` env var, to make it easier to use your own API
https://cowservices.slack.com/archives/C036G0J90BU/p1695996920984219
=> docs: improve readme and add REACT_APP_ORDER_BOOK_URLS

apps/cowswap-frontend/index.html
Second attempt, now using the right tag!
=> Fix og image

libs/widget-lib/README.md
1. Updated `widget-lib` docs corresponding to the latest changes
2. Added links to the docs and configurator
=> docs: update widget lib docs

apps/cowswap-frontend/src/legacy/components/Web3Provider/index.tsx, libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts
Fixes: #3307 
I can't reproduce, trying the most obvious solution which is to ignore falsy values.
1. Load as a Safe app
* Does not crash
=> fix: fix 3307 - Safe fails to load

libs/widget-lib/demo/vanilla.html
The minimal js code with CowSwap widget demo
=> docs: vanilla js widget demo

.github/workflows/vercel.yml, libs/common-utils/.env
Friking new test to see if now GH can pick the env if its as a secret
Will test in staging
=> Add env as secret

apps/widget-configurator/src/app/configurator/index.tsx, apps/widget-configurator/src/app/configurator/styled.ts, libs/widget-lib/docs/README.md
=> feat(widget-configurator): button to show drawer

apps/widget-configurator/.env, apps/widget-configurator/.env.production, apps/widget-configurator/src/app/analytics.ts, apps/widget-configurator/src/app/configurator/index.tsx, apps/widget-configurator/src/app/embedDialog/index.tsx, apps/widget-configurator/vite.config.ts, libs/analytics/src/index.ts, libs/analytics/src/types.ts
Added `@cowprotocol/analytics` to the widget configurator.
Currently we track three events:
1. When user connect to a wallet `{category: 'Widget configurator', event: 'Connect Wallet'}`
2. When user opens Embed code modal `{category: 'Widget configurator', event: 'View Code'}`
3. When user copy embed code `{category: 'Widget configurator', event: 'Copy Code'}`
1. Open PR preview
2. Do actions from the list above
3. Check that events went out to GA
4. GA should have the same ID as at CoWSwap
=> feat(widget-configurator): google analytics events

apps/cowswap-frontend-e2e/src/e2e/swapMod.test.ts, apps/cowswap-frontend/src/common/pure/ConfirmedButton/ConfirmedButton.tsx, apps/cowswap-frontend/src/modules/permit/hooks/usePermitCompatibleTokens.ts, apps/widget-configurator/src/app/embedDialog/const.ts, apps/widget-configurator/src/app/embedDialog/utils/formatParameters.ts, apps/widget-configurator/src/app/embedDialog/utils/reactExample.ts, apps/widget-configurator/src/app/embedDialog/utils/sanitizeParameters.ts, apps/widget-configurator/src/app/embedDialog/utils/vanilaNpmExample.ts, apps/widget-configurator/src/app/embedDialog/utils/vanillaNoDepsExample.ts, libs/widget-lib/docs/README.md, libs/widget-lib/src/types.ts
=> chore: pull changes from 1.49.0 into develop

libs/tokens/src/pure/TokenLogo/index.tsx
- Fixes token currency pair logo image
=> feat: fix token symbol crop  image

apps/widget-configurator/src/app/configurator/index.tsx, apps/widget-configurator/src/app/configurator/styled.ts
Added links to the landing page and to the docs.
TODO: link to the docs should be updated after releasing the new docs
=> feat(widget): links to landing and docs

apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetMetaDataAtom.ts, apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts, apps/widget-configurator/src/app/embedDialog/const.ts, libs/widget-lib/docs/README.md, libs/widget-lib/src/types.ts, libs/widget-lib/src/urlUtils.spec.ts, libs/widget-lib/src/urlUtils.ts
This PR changes the name of the app in the configurator, so its clear where the trades come from if they trade from there
I want to avoid getting this:
https://dev.explorer.cow.fi/gc/orders/0x35c1e50674faf7d661c8a9282884fd832b832333f4cde9948783bbfc0028fabc79063d9173c09887d536924e2f6eadbabac099f5654bb459?tab=overview
This is the new value:
Despite we use now "CoW Widget: Configurator" as the appCode we use if you place an order, we override it in the snippet.
Additionally, tries to simplify a bit more the configuration so there's not so much nesting. Adds `sell` and `buy` params instead of `tradeAssets`. I did the change, also because i think is more natural to use (a dev would naturally look for properties like `sellXXX` to control the sell assets or amounts): …
=> feat: improve appCode, config and readme

apps/cowswap-frontend/src/modules/tokensList/containers/ManageTokens/index.tsx, apps/cowswap-frontend/src/modules/tokensList/containers/ManageTokens/styled.ts, apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx, apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/styled.ts, apps/cowswap-frontend/src/modules/tokensList/pure/ListItem/styled.ts, libs/tokens/src/hooks/tokens/useSearchToken.ts
The modal should not colapse
Before:
After:
The first item shouldn't be underlined by default
Before:
After:
=> fix(tokens): fix token lists styles

apps/widget-configurator/src/app/analytics.ts, apps/widget-configurator/src/app/configurator/hooks/useEmbedDialogState.ts, apps/widget-configurator/src/app/configurator/index.tsx, apps/widget-configurator/src/app/embedDialog/index.tsx, apps/widget-configurator/src/main.tsx, apps/widget-configurator/src/theme/commonTypography.ts
- Moves the embed code button to a FAB
https://github.com/cowprotocol/cowswap/assets/31534717/51a43890-c6ff-4668-9998-d275655e0db7
=> feat: move embed code button

libs/widget-lib/package.json, libs/widget-react/package.json
Update lib versions
- widget-lib
- widget-react
=> chore: update lib versions

.github/workflows/npm.yml
Follow up on https://github.com/cowprotocol/cowswap/pull/3383
=> chore: rename npm workflow

apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx, apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/index.tsx, apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/styled.ts, apps/cowswap-frontend/src/modules/mainMenu/types.ts, libs/assets/src/cow-swap/widget-icon.svg, libs/common-const/src/common.ts
=> feat(widget): add widget link to main menu

libs/widget-lib/package.json, libs/widget-react/package.json
The react widget doesn't work properly for TS projects.
This PR solves, hopefully the problem. 
I will do a NPM package with this and test it
=> Add dependencies widget react

CHANGELOG.md, libs/widget-lib/package.json, libs/widget-react/package.json, libs/widget-react/tsconfig.json, package.json
Maybe does what https://github.com/cowprotocol/cowswap/pull/3398 can't do
DO NOT SQUASH!!
=> chore: merge main develop

libs/widget-react/package.json, libs/widget-react/src/index.ts
export all, not just the types
=> fix: export all, not just types

CHANGELOG.md, apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts, apps/cowswap-frontend/src/modules/permit/state/permitCacheAtom.ts, libs/permit-utils/src/const.ts, libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts, libs/widget-react/package.json, libs/widget-react/src/index.ts, package.json
Merge main to develop
- DO NOT SQUASH
- DO NOT REBASE
=> chore: merge main to develop

apps/widget-configurator/src/app/configurator/index.tsx
Context: https://cowservices.slack.com/archives/C05QVFJUX9R/p1700643337422669
=> fix(widget-configurator): set default trade pair USDC/COW

apps/widget-configurator/src/app/embedDialog/const.ts
Add a COMING SOON comment for a potential fee
=> docs: improve comment for fee

apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedPartOrders.ts, apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedTwapOrders.ts, apps/cowswap-frontend/src/modules/twap/updaters/CreatedInOrderBookOrdersUpdater.tsx, apps/cowswap-frontend/src/modules/twap/utils/mapPartOrderToStoreOrder.ts, apps/cowswap-frontend/src/modules/twap/utils/mapTwapOrderToStoreOrder.ts
Fixes #3442 and #3441 
This is a patch, but It will need further investigation on the cause of why the tokens are missing.
=> fix: crash unknown tokens

libs/tokens/src/state/tokens/allTokensAtom.ts
Fixes #3435
See [#3435](https://github.com/cowprotocol/cowswap/issues/3435)
=> fix(tokens-selector): add native token to the top of the list if it's not there already

libs/ui/src/pure/Button/index.tsx, libs/ui/src/pure/ExternalLink/index.tsx, libs/ui/src/pure/Popover/index.tsx
PoC to kill a circular dependency
=> fix: fix issue with boundaries

libs/wallet/src/api/utils/connection.ts
Context: https://cowservices.slack.com/archives/C06002PRF37/p1701949191296759
=> chore: fix CoW Swap widget name in the account modal

apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitHasEnoughAllowance.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
Follow up on the small issues raised in https://github.com/cowprotocol/cowswap/pull/3433
=> chore: follow up 3433

apps/cowswap-frontend/src/common/containers/FeatureGuard/index.tsx, apps/cowswap-frontend/src/legacy/utils/trade.ts, apps/cowswap-frontend/src/mocks/tradeStateMock.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts, apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx, apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts, apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
[Swap fee=zero](https://github.com/cowprotocol/cowswap/pull/3469) feature is hidden under `swapZeroFee` flag
=> chore: feature flag for swap zero fee

apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/styled.tsx, apps/cowswap-frontend/src/legacy/components/Header/styled.tsx, apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/styled.ts
- Fixes color styling for the spending cap modal
=> feat: styling fix

apps/cowswap-frontend/src/modules/twap/updaters/TwapOrdersUpdater.tsx
Context: https://cowservices.slack.com/archives/C036MD8ADMG/p1702647376040919
The case:
1. Propose and execute a transaction with TWAP order creation
2. Propose another transaction with the same call data
3. Cancel/replace the proposed transaction
AR: the order from the first tx is NOT displayed in the orders table
ER: the order from the first tx is displayed in the orders table
See the case above
=> fix(twap): deduplicate safe transactions with the same order

CHANGELOG.md, apps/cowswap-frontend/src/common/containers/FeatureGuard/index.tsx, apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts, apps/cowswap-frontend/src/legacy/utils/trade.ts, apps/cowswap-frontend/src/mocks/tradeStateMock.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts, apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx, apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts, apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts, apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts, apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts, apps/cowswap-frontend/src/modules/swap/pure/EthFlow/WrappingPreview/WrapCard.tsx, apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx, apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts, apps/cowswap-frontend/src/modules/twap/updaters/TwapOrdersUpdater.tsx, libs/wallet/src/constants.ts, libs/wallet/src/web3-react/connection/walletConnectV2.tsx, libs/wallet/src/web3-react/connectors/LedgerConnector.tsx, libs/wallet/src/web3-react/hooks/useWalletMetadata.ts, package.json
=> chore: merge main 1.52.0 to develop

apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
Fixes cosmos. 
The issue, its making numbers too big 25 zeros. I just parse them as string
=> fix: fix cosmos

CHANGELOG.md, apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx, apps/cowswap-frontend/src/legacy/theme/styled.d.ts, apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx, apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx, libs/ui/src/pure/Button/index.tsx, package.json
=> chore: merge main 1.53.1

libs/wallet/src/web3-react/connection/injected.tsx
=> fix(wallets): don't request network change when connect injected wallet

CHANGELOG.md, libs/permit-utils/src/const.ts, package.json
=> Merge 1.54.1

apps/cowswap-frontend/src/common/containers/WalletUnsupportedNetworkBanner/index.tsx, apps/cowswap-frontend/src/common/hooks/useIsProviderNetworkUnsupported.ts, apps/cowswap-frontend/src/cow-react/index.tsx
`WalletUnsupportedNetworkBanner` was outside of `WithLDProvider` and the component didn't react on feature flag changes.
=> chore: fix supported network check for Sepolia

.github/workflows/ci.yml, apps/cowswap-frontend/src/api/gnosisProtocol/priceApi.ts
https://github.com/cypress-io/github-action/issues/634#issuecomment-1405967020
=> chore: fix e2e in CI

apps/cowswap-frontend/src/modules/permit/hooks/usePermitCompatibleTokens.ts, libs/tokens/src/utils/lowerCaseTokensMap.ts
See [thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1704813006396369?thread_ts=1704724619.995319&cid=C0361CDG8GP)
1. App should load (might not be a problem in this PR as there's no localStorage)
=> chore: fix app broken due to missing network info

.github/workflows/vercel.yml
There was lint error:
Tested here > https://rhysd.github.io/actionlint/
Reference: https://stackoverflow.com/questions/69759538/use-an-array-in-workflow-level-env-variable
=> chore: fix deployment action

.github/workflows/vercel.yml
The failed build:
https://github.com/cowprotocol/cowswap/actions/runs/7488552199/job/20383275913
Looks like comments are not allowed inside of the `run` with multilines.
=> chore: fix vercel build

apps/explorer/index.html
=> chore: test explorer deployment

.github/workflows/release-please.yml
Result: https://github.com/cowprotocol/cowswap/pull/3630
=> chore: fix release-please ci

apps/explorer/README.md, apps/explorer/src/components/AppData/DecodeAppData.tsx, apps/explorer/src/components/orders/DetailsTable/index.tsx, apps/explorer/src/utils/decodeFullAppData.ts, apps/explorer/src/utils/getUiOrderType.ts
Fixes #3623
During the recent migration https://github.com/cowprotocol/explorer/pull/720 was lost, added it back in this PR.
+ small improvement in README
See #3623
=> chore: add lost changes from prev repo (PR #720)

apps/explorer/README.md, apps/explorer/src/components/AppData/DecodeAppData.tsx, apps/explorer/src/components/orders/DetailsTable/index.tsx, apps/explorer/src/state/network/NetworkUpdater.tsx, apps/explorer/src/utils/decodeFullAppData.ts, apps/explorer/src/utils/getUiOrderType.ts, libs/tokens/src/hooks/tokens/useSearchToken.ts
1. fix(token-search): ignore search input case when triggering the search (#3620)
2. fix(explorer): cast string SupportedChainId to number (#3624)
3. chore(explorer): add lost changes from prev repo (PR #720) (#3635)
=> chore: add three fixes to the release

apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts, libs/tokens/src/updaters/WidgetTokensListsUpdater/index.tsx, libs/widget-lib/src/types.ts
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1705322200199129?thread_ts=1705315545.520989&cid=C0361CDG8GP
Changed widget parameter `tokenLists` type from `{ url: string }[]` to `string[]`
Changing token lists in the widget configurator should apply in the widget
=> fix(widget): simplify token lists config

apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/index.tsx, apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/styled.ts, apps/cowswap-frontend/src/modules/trade/pure/UnlockWidgetScreen/styled.ts
- Addresses https://github.com/cowprotocol/cowswap/issues/3454
https://github.com/cowprotocol/cowswap/assets/31534717/294fd59c-ea17-45d5-902c-c58ccc2f813b
=> feat: menu text underline style

apps/explorer/src/explorer/pages/AppData/styled.ts
=> fix(explorer): fix app-data encode form error displaying

libs/widget-react/package.json
Updated widget-lib version to the latest
=> feat(widget-react): update widget-lib

apps/cowswap-frontend/src/modules/permit/const.ts
Not a meaningful change in any way
=> fix: minimum change just to cowswap app to trigger the release

apps/cowswap-frontend/src/legacy/state/orders/reducer.ts, apps/cowswap-frontend/src/legacy/state/orders/utils.ts, apps/cowswap-frontend/src/modules/twap/utils/getPartOrderStatus.ts
Fix #3018 
1. Place a SWAP
2. Cancel it
* Should show `cancelling` for 1 min
3. Repeat with LIMIT
* Should show `cancelling` for 1 min
4. Repeat both with off-chain and on-chain cancellations
* Both should work as expected
=> fix: cancelling status for SWAP/LIMIT

apps/cowswap-frontend/src/cosmos.decorator.tsx
=> chore: hide app loader in Cosmos

apps/cowswap-frontend/src/common/hooks/useIsProviderNetworkUnsupported.ts, apps/cowswap-frontend/src/common/hooks/useUnsupportedNetworksText.tsx, apps/cowswap-frontend/src/common/pure/NetworksList/index.tsx, apps/cowswap-frontend/src/legacy/components/Header/NetworkSelector/index.tsx
Now that sepolia has been enabled in prod, remove the feature flag from the code.
1. Sepolia should work
2. Other networks should work
3. Unsupported networks should behave like before
=> chore: remove sepolia feature flag

apps/cowswap-frontend/public/xss/malicious.svg, apps/cowswap-frontend/public/xss/non-malicious.svg
Delete some SVGs used for testing a potential vulnerability
=> chore: delete XSS images

.release-please-manifest.json, apps/cowswap-frontend/CHANGELOG.md, apps/cowswap-frontend/package.json, apps/explorer/CHANGELOG.md, apps/explorer/package.json, libs/permit-utils/CHANGELOG.md, libs/permit-utils/package.json, libs/widget-lib/CHANGELOG.md, libs/widget-lib/package.json
Simple merge, DO NOT SQUASH!!!
=> chore: main to develop

.github/workflows/deployment.yml
Follow up to https://github.com/cowprotocol/cowswap/pull/3761
=> ci: escape app name in deployment script

apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx, apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/styled.ts, apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/styled.ts, apps/cowswap-frontend/src/modules/trade/pure/ReviewOrderModalAmountRow/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/Row/styled.ts, apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/CountDown.tsx, apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/styled.tsx, apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
- Iterates over UI styles
- Isolated component for quote count down + blink animation on reset
https://github.com/cowprotocol/cowswap/assets/31534717/36b0a188-8410-4f83-b7d0-5ebc0a444949
=> review modal style updates

.github/workflows/deployment.yml, .github/workflows/vercel.yml
Follow up to https://github.com/cowprotocol/cowswap/pull/3764
Fixed one thing, now need to fix the vercel workflow https://github.com/cowprotocol/cowswap/actions/runs/7745801136
=> ci: fix deployment again

apps/cowswap-frontend/src/modules/trade/containers/WrapNativeModal/index.tsx
Fixes #3780 
Wrap:
Unwrap
1. Wrap
2. .. then Unwrap
Check messages are OK
=> fix: fix wrap/unwrap message

libs/widget-react/src/lib/CowSwapWidget.spec.tsx
No actual changes
1. Unit tests should pass
=> fix(widget-react): minimal widget-react changes to force release-please bump

apps/cowswap-frontend/tsconfig.json, libs/events/.babelrc, libs/events/.eslintrc.json, libs/events/README.md, libs/events/jest.config.ts, libs/events/package.json, libs/events/project.json, libs/events/tsconfig.json, libs/events/tsconfig.lib.json, libs/events/tsconfig.spec.json, libs/events/vite.config.ts, tsconfig.base.json
First PR of the epic to enhance the widget based on feedback we received and just to make it more robust and customizable. 
The main topics will be:
- Provide event communication between CoW Swap and people using the widget (intra iframe communication). We will be using a new event emitter which is one of the biggest changes
- White-labeling the app further: hide parts of the app, change or disable sounds, change images
- Error handling and other improvements for the Widget creation and updating
- Cleanup and restructuring some parts so they are easier to understand and mantain
The main review should happen on top of the waterfall PRs.
However, I will try to guide you to the changes applied in a PR series. It will be simpler if you follow sequentially, and learn about the changes.  You …
=> [Widget enhancement] 01 - New module @cowprotocol/events

libs/widget-react/src/lib/CowSwapWidget.tsx
This PR adds error handling for the widget.
Before this PR, if the creation or update of the widget would have an error, it would fail silently.
Now, it shows the crash. It should not happen in production but is still nice to not hide errors, its good for development. 
Errors will be shown like this:
=> [Widget enhancement] 11 - Error handling

libs/widget-react/src/lib/CowSwapWidget.tsx
This PR just fix the issues we have updating the provider.
I tried to optimize the widget by implementing these 2 PRs:
- https://github.com/cowprotocol/cowswap/pull/3822
- https://github.com/cowprotocol/cowswap/pull/3824
Unfortunatelly, we still have a small issue to solve. Account changes are not being detected. I see the event is not being triggered, so we need to debug further. This error don't come from the enhancements of the widget, but they were already before.
This PR just fixes it by making sure that, if the provider changes, we re-render the widget. It's more inefficient but it works!
We will need to revisit this soon, so I created this issue to track it:
- https://github.com/cowprotocol/cowswap/issues/3810
=> [Widget enhancement] 13 - Fix issues changing provider / wallet / chain

apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts, apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts, apps/widget-configurator/src/app/configurator/index.tsx, libs/widget-react/src/lib/CowSwapWidget.tsx
Somewhere in the waterfall, i broke the build. So this PR is just to fix it.
=> [Widget enhancement] 14 - Fix broken build

apps/cowswap-frontend/src/cowEventEmitter.ts, apps/cowswap-frontend/src/mocks/tradeStateMock.ts, apps/cowswap-frontend/src/modules/injectedWidget/updaters/CowEventsUpdater.ts, apps/cowswap-frontend/src/modules/injectedWidget/updaters/IframeResizer.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts, apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx, apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts, apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts, apps/cowswap-frontend/src/modules/limitOrders/services/types.ts, apps/cowswap-frontend/src/modules/swap/hooks/useBaseSafeBundleFlowContext.ts, apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts, apps/cowswap-frontend/src/modules/swap/hooks/useHandleSwap.ts, apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts, apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts, apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts, apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts, apps/cowswap-frontend/src/modules/swap/services/types.ts, apps/widget-configurator/src/app/configurator/index.tsx, libs/events/src/CowEventEmitter.ts, libs/events/src/types/events.ts, libs/events/src/types/orders.ts, libs/events/src/types/toastMessages.ts, libs/widget-lib/src/IframeCowEventEmitter.ts, libs/widget-lib/src/IframeRpcProviderBridge.ts, libs/widget-lib/src/types.ts, libs/widget-react/src/lib/CowSwapWidget.tsx
This PR addresses comments in PRs `01-14`
=> [Widget enhancement] 15 - Misc address comments

libs/widget-lib/src/IframeCowEventEmitter.ts, libs/widget-lib/src/IframeRpcProviderBridge.ts, libs/widget-lib/src/cowSwapWidget.ts
=> [Widget enhancement] 19 - WIP: Follow ups

apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
Tiny PR. It must have been a bad rebase because this change was applied in one of the PRs.
=> fix: broken build

apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
Context: https://github.com/cowprotocol/cowswap/pull/3831#discussion_r1487840965
=> refactor(twap): simplify twap form callbacks

apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
During the trade screens refactoring I've overridden a part of #3758
=> chore: cherry-pick recipient fix from #3758

apps/cowswap-frontend/src/common/updaters/FeesUpdater.ts, apps/cowswap-frontend/src/common/updaters/orders/CancelledOrdersUpdater.ts, apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts, apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts, apps/cowswap-frontend/src/common/utils/fetch.test.ts, apps/cowswap-frontend/src/modules/injectedWidget/updaters/CowEventsUpdater.ts, apps/cowswap-frontend/src/utils/orderUtils/calculatePriceDifference.ts, libs/wallet/src/web3-react/connectors/Injected/WidgetEthereumProvider.ts, libs/widget-lib/src/IframeRpcProviderBridge.ts, libs/widget-lib/src/cowSwapWidget.ts, libs/widget-lib/src/messages.ts, libs/widget-lib/src/types.ts
Follow up on #3871
Deletes dead code from that PR and from our code base
=> chore: delete dead code

apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx, libs/tokens/src/updaters/TokensListsUpdater/index.ts
https://app.launchdarkly.com/default/production/features/isGeoBlockEnabled/targeting
1. When flag is on you should see a request to api.country.is in network
2. When flag is on you should NOT see a request to api.country.is in network
=> chore: feature-flag for geo-block feature

apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
Follow up on this comment https://github.com/cowprotocol/cowswap/pull/3919#discussion_r1505827369
=> chore: remove console log

apps/explorer/src/components/orders/OrderNotFound/index.tsx, apps/explorer/src/explorer/components/OrderWidget/index.tsx, apps/explorer/src/explorer/components/TransactionsTableWidget/index.tsx, apps/explorer/src/explorer/pages/AppData/EncodePage.tsx
No issue, just addressing annoying linter warnings
1. After the CI build is finished, check there are no linter warnings
=> chore: fix explorer linter warnings

apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts, libs/common-utils/src/misc.ts
Fixes #3928 
Improve approval rejection message
1. Pick as sell token one that needs approval
2. Click on approve button
3. Reject on wallet
* Should show nice error rather than garbled error text
4. Repeat with SWAP, LIMIT, via injected wallet and WC wallet
=> fix(approval): show nice approval rejection msg

apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
=> Fee display styling

apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
Quote expired should work as before https://github.com/cowprotocol/cowswap/pull/3985
=> fix: bad merge removed amount for signature

apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, libs/ui/src/pure/InlineBanner/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/3980
=> Price updated banner style fix

apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx, apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/4001 
https://github.com/cowprotocol/cowswap/assets/31534717/311e1582-ae53-4007-bf5a-010f306ca7d9
=> Banner in search results

apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
- Addresses https://github.com/cowprotocol/cowswap/issues/3995 
https://github.com/cowprotocol/cowswap/assets/31534717/7c6f3357-5668-45df-b394-9b633e19fbd8
=> Fee accordion fix

apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
Fixes #4008
Just fixed margins
See #4008
=> chore: fix new modal heading styles

apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx, apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/styled.ts, libs/ui/src/pure/InlineBanner/banners.tsx
=> fix(order-receipt): fix recreate order button style

apps/explorer/src/api/web3/index.ts
=> fix: fix lint issues

apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
Context: https://cowservices.slack.com/archives/C05N1FNP3MX/p1711015845619359
=> chore: fix surplus info text

libs/events/package.json
=> chore: up events lib version

libs/events/package.json, libs/widget-lib/package.json
=> chore: up widget-lib version

libs/widget-lib/package.json
=> feat: up events lib version

libs/widget-react/package.json
=> feat: up widget-lib version

apps/cowswap-frontend/src/common/hooks/featureFlags/useIsAprilFoolsEnabled.ts
=> fix: force release-please trigger cowswap release

apps/widget-configurator/src/app/embedDialog/const.ts, apps/widget-configurator/src/app/embedDialog/utils/formatParameters.ts, apps/widget-configurator/src/app/embedDialog/utils/htmlExample.ts, apps/widget-configurator/src/app/embedDialog/utils/jsExample.ts, apps/widget-configurator/src/app/embedDialog/utils/reactTsExample.ts, apps/widget-configurator/src/app/embedDialog/utils/tsExample.ts
=> fix(widget): update snippets corresponding to the code

apps/widget-configurator/src/app/embedDialog/const.ts, apps/widget-configurator/src/app/embedDialog/utils/jsExample.ts, apps/widget-configurator/src/app/embedDialog/utils/reactTsExample.ts, apps/widget-configurator/src/app/embedDialog/utils/tsExample.ts
Fixed `createCowSwapWidget ` imports
=> fix(widget): update widget code snippets

apps/widget-configurator/src/app/configurator/hooks/useToastsManager.tsx
Removed the toast displaying at the page loading
=> chore(widget-cfg): remove initial toast displaying

libs/common-const/src/chainInfo.ts
Update gnosis chain bridge info to https://bridge.gnosischain.com/
1. Change network to gnosis chain
2. Check bridge info
* Should be https://bridge.gnosischain.com/
=> feat(gnosis-chain): update bridge info

apps/cowswap-frontend/src/modules/sounds/utils/sound.ts, apps/widget-configurator/src/app/configurator/controls/CustomSoundsControl.tsx
When you input "null" as a value for a sound URL, then the sound should not be played.
=> feat(widget): option to disable sounds

apps/widget-configurator/src/app/embedDialog/const.ts
=> chore: fix widget snipped code

apps/widget-configurator/src/app/configurator/controls/PartnerFeeControl.tsx
Closes #4206
- Try to add negative numbers. Should not be possible to do so
=> fix: do not accept negative numbers for fee

libs/ui/src/pure/SelectDropdown/index.tsx
=> fix: style select dropdown background

apps/cowswap-frontend/src/legacy/components/MenuDropdown/styled.ts, apps/cowswap-frontend/src/legacy/components/Tokens/styled.ts, libs/tokens/src/pure/TokenLogo/SingleLetterLogo.tsx
- Fixes underline hover style, by making sure the singe letter token placeholder is not underlined
- Uses correct background/text color CSS var
https://github.com/cowprotocol/cowswap/assets/31534717/817dda1d-68d0-45fa-ad54-fbb2e4e9d780
https://github.com/cowprotocol/cowswap/assets/31534717/7dc7a773-005d-4b9f-8569-7bc31ee9874a
=> Fix hover underline style

libs/tokens/src/updaters/TokensListsUpdater/index.ts
Fixes #4249 
`Failed to fetch` and `Load failed` geoblock errors are not actionable.
Ignoring and not reporting them to Sentry
1. Blocking country.is network requests should not create any sentry logs
=> fix(sentry): ignore some sentry geoblock errors

apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/Row/RowDeadline/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
Fixes #4247 
Fix tooltips
1. Check the tooltips
* Top/bottom padding should be the same on all tooltips
=> fix(tooltips): replace tooltip <p> with <br />

apps/widget-configurator/src/app/configurator/index.tsx, libs/widget-react/src/lib/CowSwapWidget.tsx
This PR fixes a memory leak in the widget react library (the widget itself was fine)
There was no proper cleanup being done.
Reproduce the issue this PR tries to solve:
https://github.com/cowprotocol/cowswap/pull/4263
Test the same steps in https://github.com/cowprotocol/cowswap/pull/4263 but in this PR:
- https://widget-configurator-git-widget-fix-performance-issue-cowswap.vercel.app/
If all goes well, it should not freeze ♨️😎
=> Cleanup widget and fix memory leaks

libs/widget-react/package.json
=> fix: update widget-lib version

libs/tokens/src/const/tokensList.json, libs/tokens/src/updaters/TokensListsUpdater/index.ts
The list: https://raw.githubusercontent.com/cowprotocol/token-lists/main/src/public/GnosisCoingeckoTokensList.json
Also updated the token list logo: https://github.com/cowprotocol/token-lists/pull/385
The new list should be enabled in Gnosis chain by default
=> feat: add coingecko token list to Gnosis chain

apps/cowswap-frontend/src/common/pure/CurrencySelectButton/styled.tsx, apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx, apps/cowswap-frontend/src/modules/wallet/containers/AccountSelectorModal/styled.tsx, apps/cowswap-frontend/src/modules/wallet/pure/WalletModal/styled.tsx, apps/explorer/src/state/theme.ts, apps/widget-configurator/jest.config.ts, apps/widget-configurator/project.json
Google driven development (I just googled an error and found the solution):
https://github.com/styled-components/styled-components/issues/1449#issuecomment-420087359
+ migrated widget-configurator tests to jest (`@nx/vite:test` was not working)
=> chore: fix tests

libs/widget-react/package.json
Update the widget-react library to the latest version of the library
=> feat: allow to specify your own fee label and tooltip

libs/ui/CHANGELOG.md, libs/ui/jest.config.ts, libs/ui/project.json, libs/ui/src/pure/BackButton/index.tsx, libs/ui/src/pure/Button/__fixtures__/Button.tsx, libs/ui/src/pure/ButtonSecondaryAlt/index.tsx, libs/ui/src/pure/GlobalWarning/index.tsx, libs/ui/src/pure/HelpTooltip/index.tsx, libs/ui/src/pure/Icon/index.tsx, libs/ui/src/pure/InfoTooltip/index.tsx, libs/ui/src/pure/InlineBanner/banners.tsx, libs/ui/src/pure/Popover/index.tsx, libs/ui/src/pure/Popover/styled.tsx, libs/ui/src/pure/Tooltip/index.tsx, libs/ui/tsconfig.json, libs/ui/tsconfig.lib.json, libs/ui/tsconfig.spec.json
Fixed the errors: https://github.com/cowprotocol/cowswap/actions/runs/8920296417/job/24498268891?pr=4334#step:6:121
=> chore: fix ui lib lint errors

apps/cow-fi/const/menu.ts
The page is not ready and should not be visible
=> fix(cow-fi): hide link to Learn page

apps/cow-fi/components/Button.tsx
=> fix(cow-fi): fix buttons style

.github/workflows/ipfs.yml, apps/cowswap-frontend/package.json, apps/cowswap-frontend/project.json
Attempt to fix IPFS automatic deployment
=> fix: deploy to IPFS automatically

.github/workflows/ipfs.yml, package.json
3rd attempt to fix the IPFS deployment
- Attempt 1: https://github.com/cowprotocol/cowswap/pull/4397
- Attempt 2: https://github.com/cowprotocol/cowswap/pull/4400
tested and generated this link: https://gateway.pinata.cloud/ipfs/QmaD3gS2zMRbVkbkdLqabsF7b8vYvmwSbzhFqt9vfhNuBE/
https://gateway.pinata.cloud/ipfs/QmaD3gS2zMRbVkbkdLqabsF7b8vYvmwSbzhFqt9vfhNuBE/
=> Fix ipfs attempt3

apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
Added `appCode` to `PartnerFeeDiscarded` and fixed the error triggering condition
=> fix(widget): improve PartnerFeeDiscarded error

apps/cowswap-frontend/src/api/blocknative.ts, apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts, apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts, apps/cowswap-frontend/src/legacy/components/Header/URLWarning/index.tsx, apps/cowswap-frontend/src/legacy/state/orders/utils.ts, apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx, apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts, apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx, apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx, libs/wallet/src/web3-react/updater.ts
Cherry-picked a commit from https://github.com/cowprotocol/cowswap/pull/4303, + fixed [the comment](https://github.com/cowprotocol/cowswap/pull/4303#discussion_r1579166290)
=> refactor: remove noisy logs

apps/cowswap-frontend/public/emergency.js
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1715680226553699?thread_ts=1715590791.026739&cid=C0361CDG8GP
=> chore: fix regex for versioned store names

README.md, package.json
=> docs: change port and document how to run cow.fi

apps/cowswap-frontend/src/common/pure/ChainPrefixWarning/index.tsx
Fixes a double negation that is not not not not not not not good.
=> fix: fix double negation

libs/common-const/src/tokens.ts, libs/tokens/src/const/defaultFavouriteTokens.ts
Context: https://cowservices.slack.com/archives/C06G1E3AU77/p1717511145294659
=> fix(arbitrum): replace GNO with COW in fav tokens

README.md
Force release plase, to release...
=> fix: add blank line to force release please

apps/cowswap-frontend/index.html
Now is the good one. Change something so Release Please is happy and updates CoW Swap
=> fix: change something for cowswap to deploy with release please

apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
=> fix: fix lint issue

.github/workflows/vercel.yml
Fix for https://github.com/cowprotocol/cowswap/actions/runs/9399898881/job/25888303370
=> fix: fix wrong config

apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
=> chore: fix account modal close icon size

apps/explorer/index.html
PR to make sure explorer is deployed too
=> Deploy explorer

libs/common-hooks/src/useOnClickOutside.tsx, libs/ui/src/pure/MenuBar/index.tsx, libs/ui/src/pure/MenuBar/styled.ts
Fix settings menu button click
https://github.com/cowprotocol/cowswap/assets/43217/13a59608-e678-436e-b109-375971036f21
Slack [thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1718100171028039?thread_ts=1718099959.528999&cid=C0361CDG8GP)
=> fix: menu button click

apps/widget-configurator/index.html
Just making release please do its thing
=> fix: deploy widget using release please

libs/tokens/src/hooks/tokens/useSearchToken.ts
Fixes #4029
The logic of token search was a bit wrong.
1. `isTokenAlreadyFoundByAddress` was considering results only from active lists and I bound it to inactive lists results as well
2. `filterFoundTokens` is redundant since we have `isTokenAlreadyFoundByAddress`, this flag prevents searching in Blockchain and API
1. Open CoW Swap on Mainnet
2. Open token search
3. Input `0x30D20208d987713f46DFD34EF128Bb16C404D10f`
=> fix(tokens): remove duplicates from token search result

apps/cow-fi/pages/widget/terms-and-conditions.tsx, apps/cowswap-frontend/src/pages/TermsAndConditions/TermsAndConditions.md
As per Legal request (see [thread](https://cowservices.slack.com/archives/C036G0J90BU/p1718631004943109))
1. Check Terms and conditions
2. Highlighted parts should be updated (images are the old version being replaced)
=> feat: update T&C for arb1

apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/index.tsx
Context: https://github.com/cowprotocol/cowswap/pull/4502#issuecomment-2174201680
=> chore: incl fees -> incl costs

apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
Fixes #4432
For Limit orders and TWAP!
See #4432
=> chore: read only -> connect signer

apps/cow-fi/components/Layout/const.ts, apps/cow-fi/components/Layout/index.tsx, apps/cowswap-frontend/src/modules/application/containers/App/index.tsx, apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx, libs/ui/src/pure/MenuBar/index.tsx
1. Removed chainId hardcode
2. Removed cowFortuneEnabled feature-flag
3. Changed rootDomain hardcode to `window.location.host`
=> refactor: fix MenuBar usage in cowswap

apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx, apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
Just remove the game images as they need adjustment
1. Check the `More` menu
=> chore: remove mev slicer and cow runner images

apps/cow-fi/components/LazyLoadTweet.tsx, apps/cow-fi/pages/cow-swap/index.tsx, apps/explorer/src/components/orders/FilledProgress/index.tsx
- Improve loading of embedded Tweets by making sure the embed script is fully loaded.
=> feat: fix twitter loading

apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx, apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
Context: https://cowservices.slack.com/archives/C03DVQREAH0/p1719589472229209
Hotfix of https://github.com/cowprotocol/cowswap/pull/4646
=> fix(widget): use custom label and content for partner fee (#4646)

apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx, apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx, apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts, libs/balances-and-allowances/src/hooks/useNativeCurrencyAmount.ts
Fixes #4046
See steps on issue #4046
=> fix(limit): clear limit output amount when price is empty

apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx, apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts, apps/cowswap-frontend/vercel.json
Fixes #4644
See steps on #4654
=> fix: don't show active SWAP button unless trade is valid

apps/cowswap-frontend/vercel.json
Follow up to https://github.com/cowprotocol/cowswap/pull/4643 which broken sounds, some images, manifest for the Safe and so on.
This PR updates the rules so that the following prefixes and suffixes are NOT redirected:
- /#
- Anything that has an extension that's between 2 and 15 chars. E.g.: `/assets/bal.png`
1. Open CoW Swap in a private browsing window (to prevent your browser's cache)
2. Use the app as usual
* All images (favicons, etc) should load
* Sounds should be played
* App should be addable to Safe as a custom Safe app
4. For sanity's sake, `curl` OR load them in the browser, one of each category. It should load the asset and NOT say `Redirecting...` if using `curl`, or just load/download the asset on the browser.
5. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/4 …
=> fix: vercel redirects

apps/cowswap-frontend/src/modules/trade/containers/TradeTotalCostsDetails/index.tsx
=> fix(trade): display trade details when there is no usd value of costs

apps/explorer/src/components/orders/DetailsTable/index.tsx, apps/explorer/src/explorer/components/OrdersTableWidget/useSearchInAnotherNetwork.tsx, apps/explorer/src/explorer/components/common/BlockExplorerLink/index.tsx, apps/explorer/src/hooks/useOperatorOrder.ts, apps/explorer/src/hooks/usePopper.ts
Fixes linter issues in Explorer and make sure it triggers an Explorer deployment build on release-please
1. Explorer should work as usual
=> fix(explorer): fix linter issues

apps/cowswap-frontend/src/modules/appData/utils/appDataFilter.ts
No changes, just remove debug logs
=> chore: remove debug logs

apps/cow-fi/pages/learn/index.tsx
Current develop cowfi build is broken.
Left over imports
All vercel builds should succeed
=> chore(cowfi): fix build

apps/cow-fi/pages/learn/index.tsx, apps/cow-fi/pages/legal/widget-terms.tsx, apps/cowswap-frontend/src/modules/analytics/events.ts, apps/cowswap-frontend/src/modules/appData/appData-module.md, apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedTwapOrders.ts, apps/cowswap-frontend/src/modules/utm/utm-module.md, libs/permit-utils/README.md
fix some comments
Optional: Give background information for changes you've made, that might be difficult to explain via comments
=> chore: fix some comments

apps/cow-fi/components/AddRpcButton/index.tsx, apps/cow-fi/lib/hooks/useConnect.ts, apps/cow-fi/lib/hooks/useConnectAndAddToWallet.ts, apps/cow-fi/pages/mev-blocker.tsx
Adds click events around clicking the 'add rpc' also on success/error for the /mev-blocker page
=> feat: add click event add rpc

apps/cowswap-frontend/src/api/cowProtocol/api.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, package.json, yarn.lock
Update to latest cow-sdk, which contains the new order status endpoint.
This change removes the temporary local host endpoint.
This means the progress bar should work on PRs now!
1. Place order
2. Observe progress bar
* Should have states changing according to real backend info!
=> feat(progress-bar-v2): update to latest sdk

apps/cowswap-frontend/src/api/cowProtocol/api.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/atoms.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx, apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx, apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts, apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts, apps/widget-configurator/src/app/configurator/index.tsx, apps/widget-configurator/src/app/configurator/types.ts, libs/widget-lib/src/types.ts, package.json, yarn.lock
Misc changes:
[chore: always show progress bar if we can](https://github.com/cowprotocol/cowswap/pull/4743/commits/4f24efc09310d529a43dc581894a9d36430b2318)
[chore: set min display time for any screen to 5s](https://github.com/cowprotocol/cowswap/pull/4743/commits/14b920e8d6e25b5242c042934c7e2c4bbe096466)
[fix: fix solver competition changed logic](https://github.com/cowprotocol/cowswap/pull/4743/commits/fc4628560a6da08a130defd0ce7afedac1e0750f)
1. Place order and observe progress bar (not yet working as it requires backend changes in a follow up PR)
* Should work as expected
=> feat(progress-bar-v2): misc changes

apps/cow-fi/components/Layout/const.ts, apps/cow-fi/modules/analytics/events.ts, apps/cow-fi/pages/cow-amm.tsx, apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
- Switches the MEV Blocker CTA on cow-fi with a COW AMM button
- Adds tracking events
- Changes Hero CTA button on the /cow-amm page
=> feat: switch cowfi header cta button

apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
No function changes, just removed mocked data
1. Progress bar should work as before
=> fix: remove mock solvers

apps/cowswap-frontend/src/common/pure/CoWAMMBanner/index.tsx, apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
Hotfix to add a cow amm banner
includes only @fairlighteth PR https://github.com/cowprotocol/cowswap/pull/4780
=> feat: add cow amm banner (#4780)

.release-please-manifest.json, apps/cow-fi/CHANGELOG.md, apps/cow-fi/package.json, apps/cowswap-frontend/CHANGELOG.md, apps/cowswap-frontend/package.json, apps/cowswap-frontend/src/common/pure/CoWAMMBanner/index.tsx, apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
=> feat: add cow amm banner (#4780) (#4781)

apps/cowswap-frontend/src/common/pure/CancelButton/index.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts, apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx, apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
Add missing links to progress bar v2 and text related changes
1. Check `unfilled` screen
* Cancel button should be highlighted
2. Check `expired` screen
* Place a new order should be highlighted and clicking on it re-open the swap with the same parameters (network, sell/buy tokens and amount and order type)
* Contact us should be set to `help@cow.fi`.
3. Check the link on `solving`
* Learn more should lead to https://cow.fi/learn/understanding-batch-auctions
4. Check the link on `solved`/`nextBatch`
* Learn more should lead to https://cow.fi/learn/understanding-batch-auctions
=> feat(progress-bar-v2): missing link

apps/widget-configurator/src/app/configurator/consts.ts, libs/tokens/src/const/tokensLists.ts
Follow up to https://github.com/cowprotocol/cowswap/pull/4786
=> fix: replace gateway.ipfs.io with ipfs.io

libs/tokens/src/hooks/tokens/useSearchToken.ts, libs/tokens/src/services/searchTokensInApi.ts
This PR makes it possible to search for tokens not present in a the lists for other networks
- Connect to arbitrum
- Search for CRV
- See we suggest two tokens we don't have in the list
=> feat: improve finding tokens in other networks

apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
Don't review yet
Closes #4577
Check how PROD link don't work https://swap.cow.fi/#/1/widget/swap/_/_?palette=null&theme=light
Check how this PR fixes it:
https://swap-dev-git-fix-issue-label-widget-cowswap.vercel.app/#/1/widget/swap/_/_?palette=null&theme=light
=> fix: fix issue with the swap label don't showing

apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts
Attempt to solve issue where solvers info is not shown.
With this change, the `/status` endpoint will keep being polled even after finished until the solver info is retrieved.
1. Place order on arbitrum
2. Wait for it to trade
* Solvers info should be present
=> fix(progress-bar-v2): keep querying when filled and there's no solver data yet

apps/cowswap-frontend/src/common/pure/CancelButton/index.tsx, apps/cowswap-frontend/src/common/pure/Modal/styled.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts, apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/styled.tsx, apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx, apps/cowswap-frontend/src/modules/account/containers/Transaction/StatusDetails.tsx, apps/cowswap-frontend/src/modules/account/containers/Transaction/styled.ts, apps/cowswap-frontend/src/theme/components.tsx
- Addresses comments from https://github.com/cowprotocol/cowswap/pull/4808
=> feat: style safe tx + address comments

apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx, apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx, apps/cowswap-frontend/src/modules/swap/containers/SurplusModalSetup/index.tsx, jest.setup.ts
Fix unit tests
Unit tests should pass
=> fix: fix unit tests broken due to lottie-react

apps/cow-fi/pages/careers/index.tsx, apps/cow-fi/pages/careers/refer-to-earn.tsx
- Updates refer to earn page text
=> feat: update refer to earn text

apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/types.ts, apps/cowswap-frontend/src/common/hooks/orderProgressBarV2/useOrderProgressBarV2Props.ts, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.cosmos.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
Next batch is removed
1. Should work as usual, this was not easily reachable anyway
=> feat: remove nextBatch

apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts, apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/styled.tsx
=> Updated progressbar steps

apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts, apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/styled.tsx, libs/tokens/src/pure/TokenLogo/SingleLetterLogo.tsx, libs/tokens/src/pure/TokenLogo/index.tsx
- Addresses issues mentioned in https://github.com/cowprotocol/cowswap/pull/4822#issuecomment-2306978009
=> feat: fix issues / styling

apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx
Update messages to latest.
Also make sure to not suggest to switch to arbitrum when on arbitrum
1. Place order with tight slippage (0%) and little change of surplus
2. Once traded, observe the suggested message
=> feat(progress-bar-v2): update msgs

apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/styled.ts, libs/tokens/src/pure/TokenLogo/index.tsx, libs/ui/src/pure/ProductLogo/index.tsx
- Fixes these issues:
- Animations in iOS
- Token logos broken on token selector, activity modal, etc
=> fix(progress-bar): fix styling issues

apps/cow-fi/data/cow-amm/const.tsx, apps/cow-fi/pages/cow-amm.tsx, apps/cow-fi/pages/legal/cowswap-terms.tsx
- Update cowswap legal terms
- Update cowamm content
=> feat: update content

apps/cow-fi/data/cow-amm/const.tsx, apps/cow-fi/pages/cow-amm.tsx, apps/cow-fi/pages/legal/cowswap-terms.tsx
Hotfix!
Cherry picked:
- feat(cow-fi): update content (#4877)
=> chore: hotfix 2024-09-12

apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/index.tsx, apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/styled.tsx, apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/index.tsx, apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/styled.ts
=> fix: fix import list warning styles

libs/ui/src/pure/MenuBar/index.tsx, libs/ui/src/pure/MenuBar/styled.ts
- Fixes the settings dropdown menu
=> Fix settings memu

apps/cowswap-frontend/src/common/containers/OrderHooksDetails/index.tsx, apps/cowswap-frontend/src/common/containers/OrderHooksDetails/styled.tsx, apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/styled.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/styled.tsx, apps/explorer/src/components/AppData/DecodeAppData.tsx, apps/explorer/src/components/common/AppDataWrapper/index.tsx, apps/explorer/src/components/orders/DetailsTable/index.tsx, apps/explorer/src/components/orders/NumbersBreakdown/index.tsx, apps/explorer/src/components/orders/OrderHooksDetails/HookItem/index.tsx, apps/explorer/src/components/orders/OrderHooksDetails/HookItem/styled.tsx, apps/explorer/src/components/orders/OrderHooksDetails/index.tsx, apps/explorer/src/components/orders/OrderHooksDetails/styled.tsx, apps/explorer/src/explorer/pages/AppData/styled.ts
- Addresses comments from https://github.com/cowprotocol/cowswap/issues/4945
---
=> Hooks store styleimprove

apps/cowswap-frontend/public/emergency.js, apps/cowswap-frontend/src/api/cowProtocol/priceApi.ts, apps/cowswap-frontend/src/common/updaters/FeesUpdater.ts, apps/cowswap-frontend/src/legacy/state/index.ts, apps/cowswap-frontend/src/legacy/state/orders/hooks.ts, apps/cowswap-frontend/src/legacy/state/price/hooks.ts, apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, libs/analytics/src/googleAnalytics/CowAnalyticsGoogle.ts, libs/wallet/src/web3-react/updaters/HwAccountIndexUpdater.tsx
Just removed annoying logs, no functional changes
=> refactor: remove excessive console logs

apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
=> chore: update hook docs link

apps/cowswap-frontend/src/common/hooks/useMenuItems.ts, apps/cowswap-frontend/src/common/pure/CoWAMMBanner/CoWAmmBannerContent.tsx, apps/cowswap-frontend/src/common/pure/CoWAMMBanner/styled.ts, apps/cowswap-frontend/src/common/pure/OrderProgressBarV2/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/TenderlySimulate/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/dapps/AirdropHookApp/hooks/useClaimData.ts, apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/hooks/useTenderlySimulate.ts, apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx, apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx, apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx, apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts, apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/RowSlippage/index.tsx, apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/SettingsTab/index.tsx, apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TransactionSettings/index.tsx, apps/cowswap-frontend/src/modules/yield/hooks/useYieldWidgetActions.ts
Quick fix addressing linter errors and warning and the build as well due to bad imports.
1. Everything should work as before
=> chore: fix lint issues

apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
=> fix(swap): fix safe eth-flow

config/fortunes.json
- Replacing fortune cookies with halloween themed ones
Todo:
- Pending final content approval
=> feat: replace fortune cookies with halloween

apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx, apps/cowswap-frontend/src/modules/tokensList/pure/LpTokenLists/index.tsx, apps/cowswap-frontend/src/modules/yield/updaters/PoolsInfoUpdater/index.tsx, libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
Fixed linter errors breaking the build
No functional changes
=> chore: fix linter errors

config/fortunes.json
- Updates the fortune cookies
- Important: To be merged after the halloween theme is not active anymore. The Halloween theme has it's own fortune cookies (https://github.com/cowprotocol/cowswap/pull/5049) that should be replaced by this.
=> feat: replace fortune cookies

config/barn/strategies/strategy-8453.json, config/production/strategies/strategy-8453.json
=> feat: add base strategies

apps/cowswap-frontend/src/common/constants/routes.ts, apps/cowswap-frontend/src/modules/application/containers/App/RoutesApp.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx, apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/styled.tsx, apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx, apps/cowswap-frontend/src/pages/Hooks/cowShed.tsx
Add experimental badge to CoW Hooks tab
=> fix: add cow-shed page

apps/cowswap-frontend/src/common/containers/OrderHooksDetails/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
This PR Closes #5092 
Check on #5092
=> Fix: log simulation only on trade confirmation

libs/widget-react/package.json
Add changes from https://github.com/cowprotocol/cowswap/pull/5127
=> chore: bump widget-react deps

apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
Context: https://cowservices.slack.com/archives/C03GH01MR09/p1731942603687149?thread_ts=1731321549.976889&cid=C03GH01MR09
`With hooks you can add specific actions before and after your swap <>Learn more.<>` message should contain https://cow.fi/learn/cow-hooks-you-are-in-control link
=> fix(hooks-store): update hooks learn link

apps/cowswap-frontend/src/api/cowProtocol/hooks.ts, apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx, apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx, apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx, apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx, apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx, apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFeeTooltip.ts, apps/cowswap-frontend/src/modules/volumeFee/index.ts
Hotfix for TWAP page freezing
Safe Apps fee tooltip update
=> Release 2024-12-05

libs/common-const/src/tokens.ts
=> fix: add more stablecoins in fees logic

apps/cow-fi/app/(main)/legal/cowswap-terms/page.tsx
https://cowservices.slack.com/archives/C06G1E3AU77/p1734013021996129?thread_ts=1734011452.477379&cid=C06G1E3AU77
=> fix(cow-fi): add info about base launch

apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx, apps/cowswap-frontend/src/utils/orderUtils/getIsCustomRecipient.ts
Fixes #3517
Old but gold...
See #3517
=> fix: compare recipient address with no case sensitivity

apps/cowswap-frontend/src/common/pure/CoWAmmBannerContent/index.tsx
- Fixes an issue where the menubar overlaps the CoW AMM banner:
=> feat: banner position fix

libs/wallet/src/web3-react/connection/safe.tsx
https://github.com/cowprotocol/cowswap/pull/5235
=> fix: allow any safe-like apps

.release-please-manifest.json, apps/explorer/CHANGELOG.md, apps/explorer/package.json
=> chore: release main (#5240)

apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
Just fix the label name in the code, no functional changes.
Addressing this comment: https://github.com/cowprotocol/cowswap/pull/5274#discussion_r1910772018
1. Max limit order deadline should still be 1y
=> fix(deadline): fix limit order deadline label

apps/cowswap-frontend/src/modules/usdAmount/apis/getCowProtocolNativePrice.ts, apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.test.tsx, apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Attempt to fix develop. Context https://github.com/cowprotocol/cowswap/pull/5292
=> test: fix broken test develop

apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
=> feat: fix unfillable order status

apps/cowswap-frontend/src/common/constants/featureFlags.ts, apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx, apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts, apps/cowswap-frontend/src/modules/limitOrders/hooks/useIsWidgetUnlocked.ts, apps/cowswap-frontend/src/modules/trade/hooks/useLimitOrdersPromoBanner.ts
Add feature flag `isLimitOrdersUpgradeBannerEnabled`
1. Test app behaviour with flag on and off
=> feat: limit banner feature flag

apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts, apps/cowswap-frontend/src/utils/orderUtils/calculateRateForAmount.test.ts
Follow up to #5332 comments
1. Unit tests
=> chore: pr5332 follow up

apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/index.tsx, apps/cowswap-frontend/src/modules/ordersTable/pure/OrderFillsAtWithDistance/index.tsx
Fixes: https://www.notion.so/cownation/Flickering-1778da5f04ca8060b4d2cd7b87de2ba1
Only one change:
[refactor: extract OrderFillsAtWithDistance component](https://github.com/cowprotocol/cowswap/commit/2669f103b47e4a98f8ed01498eef4810e93d3cd9)
This is the final refactoring.
Basically, need to test the whole orders table.
=> refactor: extract OrderFillsAtWithDistance component

apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/index.tsx, apps/cowswap-frontend/src/modules/ordersTable/pure/OrderFillsAt/index.tsx, apps/cowswap-frontend/src/modules/ordersTable/pure/OrderFillsAtWithDistance/index.tsx
Only one change:
[refactor: extract OrderFillsAt component](https://github.com/cowprotocol/cowswap/commit/21a183ec26c4972a72ebacdfc55ba0495fcadfeb)
No need to test
=> refactor: extract OrderFillsAt component

apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx, apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/index.tsx
When click on the limit price it should invert
=> fix(orders-table): fix limit price inverting

apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
Extra guardrails when wrapping and unwrapping (less needed, but good to have anyway) to ensure the correct chainId is used.
1. Wrap and unwrap using an EOA and SC wallets
* Should work as usual
=> fix(wrap/unwrap): enforce chainId when wrapping/unwrapping

apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/MetamaskTransactionWarning/index.tsx, apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx, libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts, libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts, libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts, libs/iframe-transport/src/iframeRpcProvider/utils.ts, libs/iframe-transport/src/types.ts, libs/types/src/eip6963-types.ts, libs/types/src/index.ts, libs/wallet/src/api/state/multiInjectedProvidersAtom.ts, libs/wallet/src/api/types.ts, libs/wallet/src/web3-react/connection/injectedOptions.tsx, libs/wallet/src/web3-react/connectors/Injected/index.tsx
The banner should be displayed when the widget is connected to:
1. Metamask browser extension
2. Metamask mobile wallet
=> feat: display Metamask warning in widget

apps/cow-fi/app/(mev-blocker)/mev-blocker/page.tsx
Update mevblocker endpoint from /maxbackrun to correct one /maxbackruns. Now documentation and website will be on par
High-level description of what your changes are accomplishing
Add screenshots if applicable. Images are nice :)
Optional: Give background information for changes you've made, that might be difficult to explain via comments
=> fix(mev-blocker): fix typo on /maxbackruns endpoint

apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts
=> fix(orders-table): prevent excessive transactions on approvals

static-files/public/safary-0.1.16.js, static-files/public/test.txt
https://files.cow.fi/cow-files/safary-0.1.16.js
=> feat: add safary script for GTM

apps/cow-fi/app/(main)/legal/cowswap-terms/page.tsx
Doc: https://docs.google.com/document/d/1tjUyTK5TLLCf4uDMyJreDCfgAs4hvDHZ6rMz8MJ53HY/edit?tab=t.0
What should be updated: https://cow.fi/legal/cowswap-terms, "COW Token Giveaway, Base Launch: Terms and Conditions" should be replaced with the content of the doc
=> feat(cow-fi): update base token reward T&C

.release-please-manifest.json, apps/explorer/CHANGELOG.md, apps/explorer/package.json
=> chore: release main (#5466)

apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx, libs/tokens/src/hooks/tokens/useNetworkLogo.ts, libs/tokens/src/pure/TokenLogo/index.tsx, libs/tokens/src/state/environmentAtom.ts, libs/tokens/src/updaters/TokensListsUpdater/index.ts
High-level description of what your changes are accomplishing
Add screenshots if applicable. Images are nice :)
Optional: Give background information for changes you've made, that might be difficult to explain via comments
=> chore: pass bridgeNetworkInfo to tokens lib via TokensListsUpdater

apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersSettings/index.tsx, apps/cowswap-frontend/src/modules/advancedOrders/pure/Settings/index.tsx, apps/cowswap-frontend/src/modules/limitOrders/containers/SettingsWidget/index.tsx, apps/cowswap-frontend/src/modules/swap/hooks/useSwapSettings.ts, apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts, libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
[fix(swap): wait for a optimal quote before eth-flow](https://github.com/cowprotocol/cowswap/commit/acd0f493c28af15451b9cae0af34c80917bfb586)
[fix(trade): reset recipient when turn off settings](https://github.com/cowprotocol/cowswap/commit/0abfb94c29a5317dd2cf920a73640adbaef14063)
=> Release 2025-03-24

libs/analytics/src/widget/orderLifecycleAnalytics.ts, libs/events/src/types/orders.ts
Refactored `setupEventHandlers` in order to address https://github.com/cowprotocol/cowswap/pull/5507#discussion_r1998256693.
I did `payload: any` because couldn't beat TS
=> refactor: simplify setupEventHandlers

apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
=> fix: do not ask apporval for native sell token

apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx, libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts, libs/balances-and-allowances/src/hooks/useSwrConfigWithPauseForNetwork.ts, libs/common-const/src/networks.ts
=> fix(balances): updated balances on network changes (#5569)

apps/cow-fi/app/(learn)/learn/[article]/page.tsx, apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx, apps/cow-fi/app/api/revalidate/route.ts, apps/cow-fi/components/ArticlesPageComponents.tsx, apps/cow-fi/const/pagination.ts, apps/cow-fi/services/cms/index.ts, apps/cow-fi/util/fetchHelpers.ts, apps/cow-fi/util/paginationUtils.ts, apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, apps/cowswap-frontend/src/modules/trade/hooks/useTradeNavigate.ts, libs/common-utils/src/tokens.test.ts, libs/common-utils/src/tokens.ts
Continuing release https://github.com/cowprotocol/cowswap/pull/5634
75fb06daf4895fac03d754ebc2df5564e8fa48c5: fix(learn): fixing CMS article 404s with improved error handling and retry logic (https://github.com/cowprotocol/cowswap/pull/5632)
https://github.com/cowprotocol/cowswap/pull/5650/commits/3fa654cf465038435a880d04c063cacbab245433: fix issues on the Learn page (#5655)
https://github.com/cowprotocol/cowswap/pull/5650/commits/aa9c4c51706de3928bb46455ad8310d55be3eff4: fix chainID on twap page (#5657)
https://github.com/cowprotocol/cowswap/pull/5650/commits/368926d566e58e9558799ed7bebd4ae16f2e6ca3: fix(twap): base dai error (#5658)
=> chore(release): 2025/04/29

apps/cowswap-frontend/src/react-app-env.d.ts
=> fix: null change to trigger cowswap build

apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx, apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/BridgeRouteBreakdown.cosmos.tsx, apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/index.tsx, apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx, apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx, apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/index.tsx, apps/cowswap-frontend/src/modules/bridge/pure/StopHeader/StopHeader.tsx, apps/cowswap-frontend/src/modules/bridge/pure/SwapStopDetails/index.tsx, apps/cowswap-frontend/src/modules/bridge/styles.ts, apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx, apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts, apps/cowswap-frontend/src/modules/trade/containers/TradeTotalCostsDetails/index.tsx, apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
Given my changes in PR https://github.com/cowprotocol/cowswap/pull/5708 and @shoom3301  related work in https://github.com/cowprotocol/cowswap/pull/5716 I created this PR to take @shoom3301 's PR and make it work with mine.
=> refactor(bridge): enhance TradeDetailsAccordion and related components

libs/tokens/src/updaters/TokensListsUpdater/index.tsx
The Updater goes into infinite loop
=> fix: remove UserAddedTokensUpdater

apps/cow-fi/app/api/revalidate/route.ts
Follow up fix for https://github.com/cowprotocol/cowswap/pull/5736
=> fix(cowfi): update comment and simplify revalidation logic in route.ts

apps/cowswap-frontend/src/tradingSdk/bridgingSdk.ts
It can be tested only in *.cow.fi domains, so I merge it right now
=> feat(bridge): add bungee prod api urls

apps/cow-fi/app/(learn)/learn/[article]/page.tsx, apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx, apps/cow-fi/next.config.ts
Cherry-picked #6066 to `main` to test it on cow.fi
=> fix(cow-fi): update articles page with caching strategy and type annotations

apps/cowswap-frontend/src/common/hooks/useSwapResultsContext.ts, apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx, apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts, apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts, apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx, apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts, apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts, libs/common-utils/src/doesTokenMatchSymbolOrAddress.ts
=> Hotfix 2025-07-31

package.json, yarn.lock
=> chore: update `cow-sdk` to `v6.0.0.`

apps/cowswap-frontend/src/common/hooks/useContract.ts, apps/cowswap-frontend/src/modules/cowShed/containers/InvalidCoWShedSetup/index.tsx, apps/cowswap-frontend/src/modules/cowShed/hooks/useCurrentAccountProxy.ts, apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts, apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrdersAuthMulticall.ts, apps/cowswap-frontend/src/modules/wallet/containers/AccountSelectorModal/index.tsx, apps/cowswap-frontend/src/pages/error/AnySwapAffectedUsers/useIsAnySwapAffectedUser.ts, apps/cowswap-frontend/src/utils/orderUtils/getOrderFilledAmount.ts, apps/cowswap-frontend/src/utils/orderUtils/getOrderSurplus.ts, libs/abis/src/abis/Multicall3.json, libs/abis/src/generated/custom/Multicall3.ts, libs/balances-and-allowances/src/hooks/useIsBlockNumberRelevant.ts, libs/balances-and-allowances/src/hooks/useNativeTokensBalances.ts, libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts, libs/common-const/src/common.ts, libs/hook-dapp-lib/src/consts.ts, libs/hook-dapp-lib/src/hookDappsRegistry.ts, libs/hook-dapp-lib/src/utils.ts, libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts, libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts, libs/multicall/src/hooks/useMultipleContractSingleData.ts, libs/multicall/src/hooks/useSingleContractMultipleData.ts, libs/multicall/src/multicall.ts, libs/multicall/src/types.ts, libs/permit-utils/src/lib/generatePermitHook.ts, libs/permit-utils/src/types.ts, libs/tokens/src/state/tokens/allTokensAtom.ts, libs/tokens/src/updaters/TokensListsUpdater/index.tsx
- https://github.com/cowprotocol/cowswap/pull/6138
- https://github.com/cowprotocol/cowswap/pull/6137
- https://github.com/cowprotocol/cowswap/pull/6125
- https://github.com/cowprotocol/cowswap/pull/6124
=> Hotfix 2025-08-12

apps/cowswap-frontend/src/cowSdk.ts, apps/explorer/src/sdk/cowSdk.ts
An empty commit to trigger release-please in order to redeploy CoW Swap and Explorer in Staging
=> fix: update CoW Swap and Explorer with bungee changes

.github/workflows/release-please.yml
Update `release-please-action` to `v4.3.0`
=> chore: update `release-please-action` to `v4.3.0`

apps/cowswap-frontend/src/test-utils.tsx
No actual changes
Nothing to test
=> fix: add return type annotations (to trigger release please build)
