cowprotocol/cowswap

src/custom/components/CowBalanceButton/index.tsx
src/custom/components/Header/index.tsx
src/custom/components/Menu/index.tsx
src/custom/state/cowToken/hooks.ts

Second part of the #349
- renamed CowClaimButton to CowBalanceButton
- removed glow effect from cow balance button
- updated button link to /profile
- updated balance button to show vCow + Cow balance

Update COW balance button

---

src/custom/pages/Profile/index.tsx
src/custom/pages/Profile/styled.tsx

- Conditionally shows the 'Add Token' (to MetaMask) component vs. the 'Copy contract' based on library (MetaMask) detection.
**WalletConnect with a Safe**
https://user-images.githubusercontent.com/31534717/161952595-d812d8ed-aed5-44a5-864e-febb024a3870.mov
**MetaMask**
https://user-images.githubusercontent.com/31534717/161952672-ca29b8b4-22b6-48b3-8dd4-c8a71ec499ce.mov

Profile: Conditional 'Add Token' vs 'Copy contract address': Waterfall PR[6]

---

src/custom/components/AddToMetamask/index.tsx
src/custom/pages/Profile/index.tsx
src/custom/pages/Profile/styled.tsx

- Adds orange hover links for consistency (reported by @nenadV91 )
https://user-images.githubusercontent.com/31534717/161947167-a9bd1550-2b53-406e-9f77-aeb27ba59b0b.mov
- Added an optional `shortLabel` prop to the AddToMetamask component, which only outputs `Add token`  (inspired by @nenadV91 's comment here https://github.com/cowprotocol/cowswap/pull/371#issuecomment-1090059251)
https://user-images.githubusercontent.com/31534717/161947313-e14178ae-7cdc-4a4f-bb0a-123c54bbf67a.mov
Existing Add to Metamask modal seem fine without the optional `shortLabel` prop:

Profile: Orange link hover and shorter Add to Metamask label: Waterfall PR[5]

---

src/custom/components/AddToMetamask/index.tsx
src/custom/pages/Profile/index.tsx
src/custom/pages/Profile/styled.tsx
src/custom/utils/index.ts

- Conditionally shows the right external block explorer (Rinkeby, Ethereum Mainnet, Gnosis Chain) text label and outgoing url for the COW balance card.
- Creates a tiny util function (`getBlockExplorerUrl`) to leverage existing functions returning its respective block explorer urls (from: `getBlockscoutUrl` and `getEtherscanUrl`)

Conditional explorer external url: Waterfall PR[2]

---

src/custom/components/AddToMetamask/index.tsx
src/custom/pages/Profile/index.tsx
src/custom/pages/Profile/styled.tsx
src/custom/utils/index.ts

WIP part of waterfall PRs
- Adds styled components for card actions (profile page)

Add card actions styled components: Waterfall PR[1]

---

src/custom/components/AddToMetamask/index.tsx
src/custom/pages/Profile/index.tsx
src/custom/pages/Profile/styled.tsx

- Change `Contract ↗` label to `View Contract ↗`
- Get block explorer URL with the `token` prop instead of `address`

View contract token

---

src/custom/pages/Swap/SwapMod.tsx
src/custom/state/swap/hooks.ts

Fixes #386
- fixes the issue mentioned in the ticket by removing the url query params on the network change

Clear url params on the network change

---

src/custom/constants/lists.ts
src/custom/tokens/rinkeby-token-list.json

Fixes #363
- adds COW token to the list of Rinkeby tokens
- updates the Rinkeby list link to `cowprotocol/cowswap` and `main` branch instead of `master`
- cow token will not be visible until this is merged into `main` branch
-

Add COW to Rinkeby list and update Rinkeby list link

---

src/custom/components/CurrencyLogo/CurrencyLogoMod.tsx
src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
src/custom/constants/tokens/tokensMod.ts
src/custom/hooks/useApproveCallback/useApproveCallbackMod.ts
src/custom/hooks/useChangeNetworks.ts
src/custom/pages/App/index.tsx
src/custom/pages/Claim/ClaimsOnOtherChainsBanner.tsx

This is a 3FER!
Closes #340, closes #352, and closes #341 + 2 minor other broken things
Testing
- disconnect wallet and switch wallet to rinkeby
- using network selector connect to RINKEBY or GCHAIN
- should toggle wallet, switch to network
- check url
- switch url chain id

[uni fix] connect and switch network (network selector)

---

src/custom/components/CowBalanceButton/index.tsx
src/custom/hooks/useCowBalanceAndSubsidy.ts
src/custom/state/cowToken/hooks.ts

Fixes #409
As mentioned in the ticket this will add cow from locked GNO to the combined balance that will be shown in the header button but also included in the discount calculation.

Add cow from locked GNO to combined balance

---

src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx
src/custom/components/SearchModal/ManageLists/index.tsx

Closes #438 
1. mainnet
2. open token list
3. open manage token lists
4. scroll to bottom

[438] Fix truncated token list manager

---

src/custom/components/SideBanner/index.tsx

On hover of the `Share on Twitter` button removes the text underline
Addresses -> https://github.com/cowprotocol/cowswap/pull/477#issuecomment-1112061773

Remove underline on hover

---

src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/state/orders/updaters/utils.ts

Assorted fix on two unhandled exceptions that caused the app to crash locally.
On prod they are not an issue since they are swallowed and logged as errors.
- Unhandled exception on PendingOrdersUpdater
- Unhandled exception on UnfillableOrdersUpdater
Can't really tell how to force them. It happened while developing locally.
It seems I was having connection issues at the time and it just caused the app to crash.

Fix unhandled exception on updaters

---

cypress-custom/integration/swapMod.ts

Fixing integration tests broken on https://github.com/cowprotocol/cowswap/pull/457
*Note:* One fix I did that isn't code related was approving WETH for the integ test account `0x68D25464371F3a97691c52e40d4C1306aF0B7629`.
1. Nothing to test, just confirm intergration tests are green

Fix cypress

---

cypress-custom/integration/swapMod.ts
package.json
src/custom/components/WalletModal/WalletModalMod.tsx
src/custom/hooks/useWalletInfo.ts
src/custom/hooks/web3.ts
src/custom/utils/signatures.ts
yarn.lock

Same as https://github.com/cowprotocol/cowswap/pull/360 but updated to latest code on `develop`
Closes https://github.com/cowprotocol/cowswap/issues/351
Closes https://github.com/cowprotocol/cowswap/issues/342

Fix walletconnect double qr code updated

---

src/custom/hooks/useCowBalanceAndSubsidy.ts
src/custom/state/cowToken/hooks.ts

Fixes #497
Removes COW from locked GNO from vested calculation and also from header balance button
- we want to make sure that the COW vested from locked GNO is not included in the subsidy percentage and balance button

Remove COW from locked GNO from subsidy calculation

---

src/custom/components/NetworkAlert/NetworkAlert/NetworkAlert.tsx

Fixing network alert for gchain
1. Connect to gchain
2. Change between light/dark modes

Fix network alert (only for gchain for now)

---

src/custom/hooks/useWalletInfo.ts

"You see something, you do something" kind of fix
While testing locally the app broke because this check was unhandled
Not a through investigation of what caused it, just handling it to prevent the app from crashing
Not a problem on prod where it'll be swallowed and logged as an error
Only visible locally, no way to reproduce in the PR
Besides, no clear path for reproduction either, happened while switching to unsupported networks back and forth trying to reproduce https://github.com/cowprotocol/cowswap/issues/514
Maybe related, but unsure

Fix unhandled exception when checking whether address is SC

---

src/custom/components/Popups/FailedNetworkSwitchPopupMod.tsx

Closes https://github.com/cowprotocol/cowswap/issues/529
1. Using a wallet that doesn't support network changing from the app, such as Nifty, open the on the same network as the wallet
2. Once loaded, change the network in the URL. E.g.: from `chain=rinkeby` to `chain=mainnet`
* An error message will be displayed
3. Change between dark and light modes
* The error message should be readable in both modes

Fix network warning unreadable on dark mode

---

craco.config.js
src/custom/pages/Swap/SwapMod.tsx

Fixes #534
- The issue happens because until the `defaultTokens` are loaded the WETH will be in the `importTokensNotInDefault` and this is why the imported token widget shows up. So this will check if there are no `defaultTokens` and return an empty array.
- The first commit for Sentry should be reverted before this is merged. That is just for the review because at this point the sentry auth key is not working

Fix import token popup issue

---

src/custom/pages/Swap/SwapMod.tsx

Fixes #553
- As asked in the ticket this will move unsupported token text above Gnosis chain banner

Move unsupported token text above gc banner

---

src/custom/api/coingecko/index.ts
src/custom/constants/index.ts
src/custom/hooks/useUSDCPrice/index.ts
src/custom/state/price/updater.ts
src/custom/utils/price.ts

Attempts to SWR-ise the USD querying logic
As a bonus - stops 2 faulty calls to quote happening on initial load - app was querying "USDC" in price quote

[USD Price] SWR-ise the USD fetching logic

---

.github/workflows/cla.yml

CLA runs every time still 😢 
@anxolin @alfetopito @nenadV91 any ideas why?
the conditional in the `if` seems to be ignored even in a new PR i opened to test (CLA still runs) - could it be because it checks it anyways and sees it's already all signed by the team so it posts the comment despite the `if` check?
A better solution would be to conditionally run this at the top level (in the `on` check for example)

[CLA] Disable check on " uni-merge/** " branch name

---

src/custom/components/Header/URLWarning/URLWarningMod.tsx
src/custom/components/Header/URLWarning/index.tsx
src/custom/pages/App/AppMod.tsx

Removes the following warning element

Remove URL warning

---

src/custom/components/Header/index.tsx

Adds tracking events for changing the theme 
2. Change the theme from dark mode to light mode

[Analytics] Add dark mode analytics

---

src/custom/components/TransactionConfirmationModal/index.tsx
src/custom/hooks/useWrapCallback.ts

Adds tracking events for wrapping/unwrapping native token
Adds the following action
- Send transaction to Wallet
- Sign transaction
- Reject Signing transaction
- Error Signing transaction
2. Verify the events by wrapping/unwrapping native tokens

[analytics] Add wrap events for analytics

---

src/custom/components/SideMenu/index.tsx
src/custom/constants/index.ts
src/custom/pages/Account/Affiliate.tsx
src/custom/pages/Account/Governance.tsx
src/custom/pages/Account/Menu.tsx
src/custom/pages/Account/Tokens.tsx
src/custom/pages/Account/index.tsx
src/custom/pages/Account/styled.tsx
src/custom/pages/App/index.tsx
src/custom/pages/Faq/Menu.tsx
src/custom/pages/Faq/styled.tsx

First part of the  #571
This will add a basic layout for the account page with the sidebar menu and also sub pages
- General
- Tokens
- Governance
- Affiliate
- go to `/account?chain=mainnet`
- test menu links
- test responsive design

Added account page layout with subpages

---

src/custom/components/Footer/index.tsx
src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
src/custom/components/Header/NetworkSelector/index.tsx
src/custom/components/Header/index.tsx
src/custom/components/Header/styled.ts
src/custom/constants/mainMenu.ts
src/custom/hooks/useChangeNetworks.ts
src/custom/pages/App/index.tsx
src/custom/pages/Swap/SwapMod.tsx
src/custom/pages/Swap/styleds.tsx

This branch `improve-header-12` is the last in the waterfall PR to improve the header/menu for all viewports:
- Addresses issue #570 
- Removes decimals for the shown COW balance
- For small/mobile devices, it shows a fixed footer menu, with the COW button and the connected account.
- Introduces a drop down menu structure/component. Incl. mobile (hamburger) menu support.
https://user-images.githubusercontent.com/31534717/171024272-72bc698f-b964-4f39-8c7a-f650ed1100f4.mov
https://user-images.githubusercontent.com/31534717/171028109-03144cd2-8a5b-45ab-a4f9-9603efc02100.mov
https://user-images.githubusercontent.com/31534717/171024292-a42c5be5-d0d2-41dd-9296-e780e6d518b8.mov
https://user-images.githubusercontent.com/31534717/171024294-368cf18c-466d-40b4-a324-24c13004aad3.mov …

Header/Menu improvement (waterfall PR FINAL) 

---

config/strategies/strategy-1.json

This PR just changes the mainnet price strategy to use `COWSWAP` as the primary strategy (that is, only use backend prices) and fallback to `LEGACY` (that is, using other DexAg prices).
This should have the effect of using the 0x and ParaSwap query configurations that we have in our backend (disabling Balancer V2 liquidity because of <https://forum.balancer.fi/t/medium-severity-bug-found/3161>).

Change Mainnet Price Strategy to `COWSWAP`

---

src/custom/hooks/useUSDCPrice/index.ts

Sets the deadline to 10min in the future instead of the max value (in 84 years!)
This is just a temporary fix while this is an optional field in the backend.

Fix issue with deadline

---

config/strategies/strategy-1.json

This PR re-applies #620 (description included below).
The original PR #620 was reverted as changes to the backend made the pricing requests that were made by the FE no longer work (we were rejecting quotes with `validTo`s set too far in the future, and for pricing, the frontend was using `0xffffffff` - i.e. the maximum possible value).
It should be safe to re-apply these changes as we now have configured the backend to skip the maximum `validTo` check.
Moving forward, we should probably stop using `0xffffffff` for the `validTo` value. There are some proposed changes (https://github.com/cowprotocol/services/pull/249) that add new semantics that can be used here:
- We have a new `validFor` that can be specified instead of `validTo` for specifying validity with a duration (instead of an …

Change Mainnet Price Strategy to `COWSWAP` - Take 2

---

src/custom/components/Settings/SettingsMod.tsx

Adds tracking events for enabling expert mode
Adds the following action:
- Show Confirmation
- Confirm Enabling Expert Mode
2. Verify the events by enabling expert mode

[analytics] Enable expert mode analytics

---

src/custom/components/TransactionSettings/TransactionSettingsMod.tsx

Adds tracking events for changing the default expiration time for the orders
Adds the following action:
- Set Default Expiration Time
- Set Custom Expiration Time
2. Verify the events by changing the expiration time of the orders, or restoring the defaults

[analytics] Changing expiration date

---

src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
src/custom/constants/index.ts
src/custom/utils/misc.ts

Adds tracking events for changing the default slippage tolerance
Adds the following action:
- Set Default Slippage Tolerance
- Set Custom Slippage Tolerance
2. Verify the events by changing the expiration time of the orders, or restoring the defaults

[analytics] Add analytics for slippage

---

src/custom/constants/index.ts
src/custom/hooks/useWrapCallback.ts
src/custom/pages/Swap/SwapMod.tsx

Adds events for order signing.
Adds the following action that were not tracked:
- Send transaction to Wallet
- Reject
- Signing Error
Before this PR we were not handling the rejections of the signing differently from any other error. This was making the error message displayed to the user not very clear
Before:
This PR improves the message (I had to differentiate between errors and rejections, so I just went for this change, i hope its OK) 
after:
This PR gets rid of some weird error names, now the events that tract the success singing the order are:
- **Signed: Swap**:  Normal swap (before `Swap w/o Send`)
- **Signed: Swap and Send to Self**: Swap and send tokens to …

[Analytics] Sign flow: send to wallet & Cancel & Error

---

src/custom/pages/Swap/SwapMod.tsx
src/custom/state/price/reducer.ts

This PR address an issue where we are silently hiding error when we quote the prices.
This happens when we quote prices with a disconnected wallet (which is perfectly fine), and then we get an error.
The fix is just to give more priority to show the error than show the connect button.
Before:
After:
For doing a proper fix of this, we would need to refactor the whole component. The component is a nightmare, in this case the problem is the error handling hell: it's a series of nested ternary conditionals of dozens of lines of code.
I tried to move the button out of the error chain by trying to add it only under condition that is not connected, but I run into the conditional hook problem because of the last merge, see thread https://cowservices.slack.com/archives/C0361CDG8GP/p1653557763017379 …

Show quote errors even if disconnected

---

src/custom/components/AccountDetails/index.tsx
src/custom/components/Header/index.tsx
src/custom/components/Header/styled.ts
src/custom/components/OrdersPanel/index.tsx
src/custom/hooks/useMediaQuery.ts
src/custom/utils/toggleBodyClass.ts

- Attempt to improve iOS janky scrolling in the mobile menu overlay
- Fix race condition with adding `noScroll` class to Body. It got added then removed right away when the mobile menu overlay was open. While it should stay added. Fixed now.
- Optimize media query detection by adding `isLargeAndUp`
- Detect if a device has touch capabilities with `isTouch` and use that to have the app pick `onClick` vs `onTouchStart` event.

Fix iOS scrolling mobile menu overlay attempt and improve events

---

src/custom/components/AppziButton/index.tsx
src/custom/pages/Account/styled.tsx
src/custom/pages/App/index.tsx
src/custom/theme/baseTheme.tsx

- Reposition Appzi modal on mobile only

Re-position Appzi modal on mobile.

---

src/custom/pages/Profile/LockedGnoVesting/index.tsx

Completes David's PR https://github.com/cowprotocol/cowswap/pull/649
Add missing events that @elena-zh pointed out here:
>  Btw, there is no GA event for rejecting Convert transaction.
https://github.com/cowprotocol/cowswap/pull/655#issuecomment-1149762679
I also added the events in https://docs.google.com/spreadsheets/d/1AwcuvmPaAyIRuKayOEp1cKcVGD3MLOpfS8UWA04fBtY/edit#gid=0
1. Install and activate https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en
2. Verify the events by claiming COW

Add missing events for claiming COW

---

src/custom/hooks/useUSDCPrice/index.ts

Prices from a caching attempt via refs was causing `lastPrice` to be returned which resulted in either `undefined` or low values based on the conditional statement
removed that and added an `isNative` check to the dep array to retrigger price check when switching between native ETH and WETH (may not be necessary but let's test)
- input amounts for WETH - check price is accurate
- switch to ETH
- check amounts SHOW UP
- check amounts are similar/identical to WETH price
- check networks tab and filter with `ethereum` - to check coingecko api calls
- check that WETH address is used for ETH
- check on gchain that it works the same

[HOTFIX :fire:] 1.15.2 - remove ref to last price - FIXES ETH/WETH pricing issue!

---

src/custom/components/Tokens/TokensTable.tsx

- Fixes the issue mentioned by @elena-zh here https://github.com/cowprotocol/cowswap/pull/654#issuecomment-1152400628, and scrolls the table to left on page change.
- go to tokens page
- reduce device size to small screen until there is a horizontal scroll bar appearing 
- scroll the table to the right
- once you change the page the horizontal scroll position should move to left

Scroll left table on page change

---

package.json

Fixes these warnings when running `yarn` command which also activates `prei18n:extract` at some point, as suggested in this thread https://github.com/lingui/js-lingui/issues/433#issuecomment-454678661

Fix for lingui warnings

---

.env
.env.production

Fixes issue raised by @nlordell [here](https://cowservices.slack.com/archives/C036G0J90BU/p1655214376667189)
Regex test:

Fix swap.cow.fi appData bug

---

.gitignore
cypress-custom/integration/swapMod.ts

1. Fixes broken `SwapMod.tsx` test and small fixes to the hacky `.type({selectAll}{backspace})` workaround
The issue is that on the SwapMod "output currency output field" tests, we weren't clearing the input currency field, thus a race condition between the amount prefilled in the output (expected output) was clashing with the test instructions and failing.
This clears first the input field, then inputs in the output + returns the use of the `.clear()` method
2. Change WETH against DAI tests to use GNO. DAI (incorrect contract address) returns enormous amounts which causes (correctly) the `high fee vs amount`  to appear, blocking the swap button
- check cypress is green

FIX CYPRESS TESTS

---

.env
.env.production
.gitignore
cypress-custom/integration/swapMod.ts
src/custom/hooks/web3.ts
src/custom/pages/Swap/SwapMod.tsx
src/custom/utils/price.ts

Part of the issues with 1.15.0 and co (1.15.1, 1.15.2) - the ETH USD value, price impact, and WETH/ETH showing different USD values
What was wrong:
ETH//WETH price impact
`getGpUsdcPrice` -- (`custom/utils/price.ts`) has a bug: 
Comment on L416 is wrong, `sellAmount` returned in the response is the amount WITHOUT the `feeAmount` applied, thus `L417` should not exist. By existing it was returning a worse price as the `sellAmount` returned was then higher making the price worse.
The reason we weren't seeing it in BARN/LOCAL is that the `feeAmount` was marginal and not affecting price so much in certain cases.
We started seeing this more since the change to the `COWSWAP` strategy as the primary price feed, and probably only really saw it now. This was on me, sorry y'all 😞 
This is a bit …

[ 🔥 😮‍💨 H O T F I X ] 1.15.5 

---

src/custom/hooks/useUSDCPrice/index.ts
src/custom/utils/price.ts

Related to [this slack thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1656002311466639)
We had changed the `validTo` param and we need it to stay inside the calculating callback and NOT only the hook. Keeping it inside the hook can pass stale values to the cb and cause a "Valid To time cannot be in the past" error
1. swap any token with networks tab open
2. filter by "quote"
3. look for buy orders for USDC at 100000000 (100 in usdc atoms)
4. see that there are no errors for valid to time being in the past

[fix] Pass validTo time inside callback

---

src/custom/state/swap/TradeGp.ts
src/custom/state/swap/trade.test.ts

Slippage calculation was wrong, as pointed out by @nlordell in https://cowservices.slack.com/archives/C0369B303UN/p1655937383605559
Before we were calculating the slippage in a way more complex way (and wrong). We were using the price without fee, which is the one we show, then multiplying that by the original amount (to get what we would get if there was no fee), then we apply the slippage to the original price, and multiply it by the original amount after fee.
Now is way more simple. Just applies the slippage to the amount after fee. Similar approach was applied to buy Orders.
- Use the UI and simulate buy orders and sell order
- Pay special attention to the sell amount and buy amount used when you sign the transaction, and the displayed amounts in the confirmation window

Fix issue with Slippage calculation

---

src/custom/hooks/useUSDCPrice/index.ts
src/custom/state/sentry/updater/index.ts
src/custom/utils/logging/index.ts

As discussed in the v1.15.0 [post-mortem doc](https://docs.google.com/document/u/2/d/1SfKDvGBRQFLScEoiQ3V2aGXG9ktIIaJ3WkIm_oghG9g/edit) this is a low hanging fruit follow up for adding better detection to downed services.
Adds sentry message reporting (non-error) for USD (coingecko/cow api) price feeds returning `null`
An example [can be seen here](https://sentry.io/organizations/cowprotocol/issues/3375350787/?environment=local&project=5905822&query=is%3Aunresolved)
Open Cowswap
Change WETH to ETH token in the From field
Open Sentry, filter by PR environment --> the error should be at the top

[USD Price] Add sentry reporting to USD price feeds

---

src/custom/pages/Swap/SwapMod.tsx
src/custom/state/index.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/state/price/middleware.ts
src/custom/state/price/reducer.ts
src/custom/utils/analytics/index.ts
src/custom/utils/analytics/listEvents.ts
src/custom/utils/analytics/settingsEvents.ts
src/custom/utils/analytics/swapEvents.ts
src/custom/utils/analytics/themeEvents.ts
src/custom/utils/analytics/transactionEvents.ts
src/custom/utils/analytics/walletEvents.ts
src/state/swap/hooks.tsx

Part of the #665
Adds GA events for:
- order price out of market range
- input/output currency select change
- input/output token amount change
- switch input/output tokens
- initial order quote loading
- adds small changes such as renaming and some refactoring
- Should be self explanatory how to activate these events but for more information, refer to the `CowSwap - Analytics events / dimensions` file for and for the "price out of market range" issue, place 2 orders to swap 100 GNO -> PAX one immediately after another on Rinkeby network and the second order should give this warning and trigger and event

Added GA events for order out of market

---

src/custom/theme/components.tsx
src/custom/theme/cowSwapTheme.tsx
src/custom/theme/index.tsx
src/custom/utils/analytics/index.ts
src/custom/utils/analytics/otherEvents.ts
src/custom/utils/explorer.ts
src/hooks/useAddTokenToMetamask.ts
src/theme/components.tsx

This PR adds GA event
- when user click on external link that leads to protocol-explorer or to blockscout
- Make an successful trade and click on view on explorer link in modal or in notification popup
- Open account details and click on some external link

GA events 4

---

src/custom/components/swap/EthWethWrap/WrapCard.tsx
src/custom/theme/baseTheme.tsx

Closes #804 
1. wrap eth flow
2. check colour modes

804 - Fix ETH wrap font colour

---

src/custom/state/orders/helpers.tsx
src/custom/state/orders/updaters/utils.ts

Every swap notification had the sell amount without accounting for the fee, different than the placement notification:
| Order placed | Order traded |
| - | - |
| ![Screen Shot 2022-07-21 at 10 58 31](https://user-images.githubusercontent.com/43217/180187008-d06bd88c-9bbe-45c0-b237-c131e258a79f.png) | ![Screen Shot 2022-07-21 at 10 59 10](https://user-images.githubusercontent.com/43217/180186967-cbbf0384-47bb-47bd-8e21-8ef4e180173c.png) |
After this change:
| Order placed | Order traded |
| - | - |
|![Screen Shot 2022-07-21 at 11 01 04](https://user-images.githubusercontent.com/43217/180187624-4ba666e3-2671-432f-9bb7-1b9baa54a7e6.png) | ![Screen Shot 2022-07-21 at 11 01 51](https://user-images.githubusercontent.com/43217/180187649-353e5f67-f14b-48fe-9ccf-4ec7567ab168.png) |
1. Place order …

Fix traded amount on notifications

---

src/custom/hooks/useUSDCPrice/index.ts

Right now the capturing of empty prices from our USD endpoints: coingecko & cow-api is returning way too much noise that can't be attributed directly to our price feeds constantly failing (we would have received external reports likely) and it is much more likely that there is something wrong with the way/place where we are reporting this to sentry
For now we disable
https://sentry.io/organizations/cowprotocol/issues/3375350787/?project=5905822&query=is%3Aunresolved

[SENTRY] disable price feed empty response reporting

---

src/custom/state/lists/hooks/hooksMod.ts
src/custom/state/lists/updater/updaterMod.ts

Attempt to fix https://github.com/cowprotocol/cowswap/pull/835 compiler error.
-----
All credits of this PR should go to @alfetopito who found the issue and did the fix in the first place.
Fixes #834 - App crashes when switching to Goerli for the first time
This was not quite fixed on https://github.com/cowprotocol/cowswap/pull/805
1. Open the PR
2. Change the network to mainnet
3. Open local storage and replace the contents of `redux_localstorage_simple_lists` with https://paste.ee/p/MvQYv
4. Reload the page
5. Switch the network to Goerli
* It should not crash :)
6. Repeat the steps on https://cowswap.dev.gnosisdev.com/#/swap?chain=goerli
* It SHOULD crash since it does not contain this fix yet

Fixed #834. Bug when changing to Goerli on first time

---

package.json
src/custom/hooks/useGnosisSafeInfo.test.tsx
src/custom/hooks/useGnosisSafeInfo.ts
src/custom/pages/Swap/SwapMod.tsx
yarn.lock

Fixes #311
When Cow DAPP is opened inside Gnosis safe in Read-only mode, then we don't allow user to swap and show disabled button with text "Read Only"
https://github.com/cowprotocol/cowswap/issues/311#issuecomment-1201053615
I had to update `@gnosis.pm/safe-apps-web3-react` package up to `1.5.0` version because the old version doesn't have full typings of SafeInfo (particularly `isReadOnly` flag)

Disable swap form when Gnosis safe in readonly mode

---

src/custom/components/Header/index.tsx
src/custom/utils/appzi.ts

Experimenting to add events to appZi.
The reason is to:
* Try to help @fairlighteth  with this issue he is having re-styling appzi: https://github.com/cowprotocol/cowswap/pull/866 
* We will like to add Google Analytics events for opening and closing appzi
This PR is highly experimental, because their event handling is deprecated. Although AppZi mentioned that we should be able to use it. Maybe we will just need to check with them if they can enable it and make it official
See for context: https://docs.appzi.io/deprecations/events
This PR allows us to register to the events, so we can add arbitrary logic. 
See console: 
- I see that currently the info in the event doesn't help with adding the dynamic CSS @fairlighteth needed. 
- Also, i see they don't trigger an event when I close the …

Add event handlers for appzi events

---

src/custom/theme/baseTheme.tsx

Do not hardcode AppZi key in the CSS.
Just trade so you can see the NPS. It should be styled (so you cannot click on the links in the background)

Import key from constants

---

src/custom/utils/appzi.ts

AppZi has two modes in which it can be invoked:
1) Imperative mode. You order the NPS widget to show. This is controled by our util `openNpsAppzi()`
2) Automatic. You report to appzi that the user has traded, or has waited long enough. Appzi decides if it should open the NPS. This is controlled by our util `openNpsAppziSometimes()`
We did the test and development of the feature using  `openNpsAppzi()`, which made development/testing easier. This had the code to inject the styles.
However, and here it comes the bug, I forgot to add the code also in `openNpsAppziSometimes()`
- Additionally, makes sure we inject the styles only once
- Also removes some console logs
Trade and observe now the NPS form has the right styles

Apply the NPS restyle also in automatic mode, and only once

---

src/custom/utils/appzi.ts
src/custom/utils/userAgent.ts

This PR tries to solve a problem that happens when using appZi in Metamask IOS app.
The error is reproducible in production right now.
1. Using Metamask IOS
2. Click on the button to leave a feedback using appZi --> instead of opening the appzi modal, it only shows the X icon, and blocks the user (they cannot click on anything else). 
Although this error is solved with a refresh, we cannot deploy the NPS that would make this error way more sever, because now on your first trade you will be propted with the appZi for,
- Test the steps above for Metamask in IOS and Android. I only tested this in IOS, I would appreciate some test in android.

Disable appzi old chrome

---

src/custom/state/orders/middleware.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/utils/appzi.ts
src/custom/utils/time.ts

Further improving NPS tracking
Changed the flags based on Anxo's comment
- `traded`: true, if triggered after a trade
- `expired`: true, if triggered after a trade has been expired
- `waitedForTooLong`: true, if triggered after a trade takes more than X minutes
- `secondsSinceOpen`: number, set every time it's triggered
---
Added 3 custom fields depending on each NPS trigger:
- `traded` flag, if triggered after a trade
- `expired` flag, if triggered after a trade has been expired
- `waitedFor` field, if triggered after a trade takes more than X minutes
The last one will have as value how long, in minutes, the user waited for
Before each test, make sure the appzi key on localStorage is cleared. Refresh the browser after removing it.
All NPS instances should contain `secondsSinceOpen` with …

Improve NPS - more fields

---

public/index.html

Updating the cache flag so shared image from meta tag uses the new version
I guess it will only make sense once this is deployed to an environment where this was used before, because this PR won't have the shared imaged cached and will start with the latest

Updated meta tag for shared image to invalidate existing cache

---

src/custom/state/orders/middleware.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/utils/appzi.ts

- Removed redundant `orderId`
- Added `env` and `chainId` 
Follow up to https://github.com/cowprotocol/cowswap/pull/905
Added 2 fields to appzi NPS:
- orderId
- explorerUrl
Both are redundant, yes.
Couldn't decide which we should keep, so added both.
Let me know which is the preferred and I'll remove the other one
Same as #905, except that there are 2 new fields that should be included in all the NPS submitted

Improve nps orderid

---

src/custom/components/Header/HeaderMod.tsx
src/custom/connection/index.ts

- revert the z-index change for Header
- fixes the issue with Coinbase, where the text was Uniswap instead of CoW Swap

Revert z-index and fix for Coinbase

---

src/custom/constants/lists.ts

Sets the main branch for the url of goerli tokens list.
Fixes the failing cypress tests.

Set the right branch for goerli list

---

cypress-custom/integration/swapMod.ts

Fixing [cypress break](https://github.com/cowprotocol/cowswap/runs/8120379767?check_suite_focus=true) after behaviour changes coming from https://github.com/cowprotocol/cowswap/pull/996
1. Integration tests should pass

Fix cypress usdc not default

---

cypress-custom/integration/swapMod.ts
src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
src/custom/pages/Swap/SwapMod.tsx
src/custom/state/swap/hooks.tsx

Additional fixes on latest RC `v1.21.0-RC.0` currently deployed on barn/staging
- Fixed cypress tests
- Fixed chainId on url

Release 1.12.0 RC.1

---

.github/workflows/ipfs.yml
package.json

Latest IPFS deploy [failed](https://github.com/cowprotocol/cowswap/runs/8158132195?check_suite_focus=true), due to lack of infura credentials.
I changed it instead to Pinata as we already have the keys available in the repo
Requires the ipfs step to be triggered

Updated ipfs build to use Pinata instead of Infura

---

src/custom/components/SearchModal/ManageTokens/ManageTokensMod.tsx

Follow up to #1021 addressing [comment #2](https://github.com/cowprotocol/cowswap/pull/1021#issuecomment-1237156406)
> Custom tokens point to Etherscan in GC (reported in https://github.com/cowprotocol/cowswap/issues/249 )
Closes https://github.com/cowprotocol/cowswap/issues/249
1. On gnosis chain, open the token selector and go to manage token lists > tokens
* The external link on the right the token should take you to gnosisscan rather than etherscan

1020 & 249/Fixed link for tokens on gchain

---

package.json
src/custom/state/enhancedTransactions/reducer.ts
src/custom/state/enhancedTransactions/updater/CancelReplaceTxUpdater.tsx
src/custom/utils/blocknative.ts
yarn.lock

Close #327 
There were a few [breaking changes](https://github.com/blocknative/sdk/releases/tag/4.0.0) in the blocknative sdk regarding speedup and cancel txs, also a [websocket fix](https://github.com/blocknative/sdk/releases/tag/3.7.1) that could have affected the app usage.
This is first try to fix the current wss errors we are getting from the bn sdk.
_UPDATE 2022/09/05_
* _added more logging and also some Sentry handlers to catch any Blocknative issue_
* _bumped the blocknative sdk to the latest version_

Fix replacement hash for both speedup and cancel txs

---

src/custom/hooks/useStablecoinPrice/index.ts
src/custom/pages/Swap/SwapMod.tsx
src/custom/state/swap/hooks.tsx

Closes #1061 
[Hotfix 1.15.1](https://github.com/cowprotocol/cowswap/pull/676) for USD price fixed quickly an issue for USD price estimation/impact being incorrect. Since switching to ETH as a "tradable" (more accurately, quoteable) token in the ETH-FLOW update (only in dev) the UI needs to be aware of ETH quotes in redux, which contains quote errors (among other things). 
The change here reverts the hotfix change which after testing was irrelevant. Actually this was noted by Anxo in a review and now fixed. **THIS HAS NOT AFFECTED PROD IN ANY WAY!!** it would only affect it now, had we merged dev. So thanks @elena-zh and @anxolin !
Mainnet, SUB token showing proper error …

[ETH-FLOW] FIX hanging price: use input token for quote

---

.env

This fixes the automatic detection of the BARN environment
REGEX before this PR
REGEX after this PR

Improve barn detection

---

src/custom/pages/Account/ens/index.ts

This PR adds the ENS subgraph for Görli to support fetching all ENS names a given address could have.
1. Register a ENS for Görli in https://app.ens.domains/
2. Visit https://pr1091--cowswap.review.gnosisdev.com/#/account?chain=goerli
3. Check the ENS name is added to the dropdown in `Your referral url` section

Add goerli ens subgraph support

---

README.md
src/custom/constants/mainMenu.ts

The limit orders page development is in progress, so, it must not be displayed on production

Hide limit-orders page under feature-flag

---

src/cow-react/swap/hooks/useSetupSwapState.test.tsx
src/custom/state/swap/actions.ts
src/custom/state/swap/hooks.tsx
src/custom/state/swap/reducer.ts
src/state/swap/actions.ts
src/state/swap/hooks.tsx

On https://github.com/cowprotocol/cowswap/pull/1040 the swap page was refactored.
These files were changed by wrong way: 
`src/state/swap/actions.ts`. 
`src/state/swap/hooks.tsx`. 
`src/state/swap/reducer.ts`. 
In this PR the files were reverted and overrided by `src/custom`

Override swap state uni-files using src/custom

---

src/custom/utils/blocknative.ts

Currently we have limitations on the Blocknative SDK usage for users who are in countries affected by OFAC sanctions (such as Belarus or Russia), which cause errors during the connection to the Blocknative API. These errors are mainly websocket connection errors and they were logged not in the best way to Sentry, this PR improves that logging a bit and allow searching/filtering the logs by the error message.
Before:
After:
This PR doesn't introduce anything new, just improves logging in Sentry.

Improve blocknative sdk error reporting

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
src/cow-react/modules/limitOrders/hooks/useSetupLimitOrdersState.ts
src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts

Set recipient to limit orders store from URL and user input.
Cases:
- input a recipient in the URL: http://localhost:3000/#/1/limit-orders/WETH/WBTC?recipient=0xabc
- click to `+ Add a recipient (optional)` and input recipient from keyboard
Nothing to test

[Limit orders 2] Set recipient to limit orders store from URL and user input

---

src/custom/components/Popups/FollowPendingTxPopup/index.tsx
src/custom/components/Web3Status/Web3StatusMod.tsx
src/custom/hooks/useRecentActivity.ts
src/custom/state/application/atoms.ts
src/custom/state/application/hooks.ts

Closes #872
This proposal stores the `orderId` when closing the **popUp** that signals where to **follow** a pending order.
**This will prevent:**
1. When switching to expert mode, a previously displayed popup will not be shown.
2. That when refreshing the page it is not shown again.
1. Open an order, close the progress modal, close the popup notification. And finally switch to expert mode 
2. In expert mode put an Order, close the notification popup and finally refresh the page. 
💡 Note: The popup **should not appear again** in any of the cases

Keep last orderId on state when popup is closed

---

.env.production

#1132
There were wrong regex to detect environment 
After deploy to Barn
1. Open barn.cow.fi
2. The New swap form should be displayed by default

Fix prod and barn regex

---

src/cow-react/modules/swap/containers/NewSwapWidget/propsChecker.ts
src/cow-react/modules/swap/containers/SwapButtons/index.tsx
src/cow-react/modules/swap/helpers/getSwapButtonState.ts
src/custom/state/swap/hooks.tsx

#1142
`SwapButtons` component had the wrong props checker `isSwapButtonPropsEqual`.
This checker didn't check all props properly and therefore we had an outdated trade data on the confirmation screen.
[swap/hooks.tsx](https://github.com/cowprotocol/cowswap/pull/1143/files#diff-9f3a1b6697e3fe27f8e496a5224658fd212db2e0dbc93eb58c79b6256c966a66) - `inputError` type was changed from `ReactNode` to `string` to have an opportunity to use `genericPropsChecker`. Because `ReactNode` cannot be used in the `JSON.stringify()`

Fix SwapButtons props changes check

---

src/cow-react/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
src/cow-react/modules/swap/hooks/useSwapConfirmManager.ts

Fixes #1163
After Swap refactoring the "Order submitted" screen has been lost.

Fix 1163: Show transaction confirm screen after order signing

---

src/custom/components/Header/styled.ts

Fixes the logo position in the mobile menu, when the banner is present:
https://user-images.githubusercontent.com/31534717/194368865-ab87c3e6-f84e-42c1-abcb-80143957437a.mov

Fixed logo position on mobile menu open

---

src/custom/constants/lists.ts
src/custom/tokens/goerli-token-list.json

> Do not review yet ⛔️
Update the lists of tokens to:
* Change the logo of the list for CoW Protocol 
* Change the logo of $COW token
* Rename the CoW Protocol list to CoW Swap
* Add a new Coingecko list with the top 250 tokens from CoinGecko
1. Test now you can find and add easily stETH
2. Test CoW Swap list is enabled
3. Test Coingecko list is disabled
4. Test COW logo is OK

Update token list

---

src/custom/components/swap/EthFlow/pure/EthFlowModalContent/EthFlowModalTopContent.tsx
src/custom/components/swap/EthFlow/pure/EthFlowModalContent/configs.ts

Part of #1186 
Addresses @elena-zh 's comment on descriptions: https://github.com/cowprotocol/cowswap/pull/1187#issuecomment-1277712327
@elena-zh made the comment that the description was a little redundant, so i cleaned it up:
@elena-zh made the point that it is unclear even in expert mode why users are wrapping native currency. I opted for using the ethFlowDescription base text:

[1186 - ETH-FLOW-V2] Fix and standardise descriptions

---

src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
src/custom/components/swap/EthFlow/containers/EthFlowModal/hooks/useSetupEthFlow.ts
src/custom/components/swap/EthFlow/containers/EthFlowModal/index.tsx
src/custom/components/swap/EthFlow/pure/EthFlowModalContent/EthFlowModalBottomContent.tsx
src/custom/components/swap/EthFlow/pure/EthFlowModalContent/EthFlowModalTopContent.tsx
src/custom/components/swap/EthFlow/pure/EthFlowModalContent/configs.ts
src/custom/lib/hooks/useCurrencyLogoURIs/useCurrencyLogoURIsMod.ts
src/custom/state/swap/hooks.tsx

Closes 1-4 (core issues) of #1186 
I see that the EthFlow code is currently in `src/custom` but according to the new guidelines it should be moved into `src/cow-react` correct? In that case I will do so after this PR
I also noticed the division of the folders inside `src/cow-react/modules`. Question: should EthFlow be it's own module to keep the `hooks`, `utils` etc separate from the `swap` stuff? @anxolin 
1 & 2 & 4. Punctuation:

1186 - Eth-Flow - Fix issues

---

public/emergency.js

Redirection on the server side doesn't work if there is a cache in the service-worker

Redirect for Barn

---

src/cow-react/modules/swap/containers/ImportTokenModal/index.tsx
src/custom/tokens/goerli-token-list.json
src/custom/tokens/rinkeby-token-list.json

Import token modal is blinking on network switching
1. Connect wallet to Ethereum Mainnet
2. Switch network to Gnosis Chain from UI
**ER:** UI updated without opening the Import token modal
**AR:** Import token modal appears for ~1sec and disappears

[Hotfix] Fix Import token modal blinking on network switching

---

.github/workflows/ci.yml

Adding Cosmos build step to CI
It'll be deployed alongside the website on PRs and accessible at <pr url>/cosmos/
1. Watch this PR's build step
* Should contain `Build Cosmos` withing the `Build apps` CI workflow
2. Watch PR comments
* The same one where the app link is available should have another link pointing straight to /cosmos/ url

Cosmos ci build

---

src/custom/hooks/useWrapCallback.ts

Closes #1243
Fixes issue with NATIVE / WRAPPED balances showing insufficient when balance === wrappedBalance
Fix was switching from greaterThan to not less than (uni lib doesn't have greaterThanOrEqualTo)

[ETH-FLOW-V2] 1243 - Insufficient balance NATIVE/WRAPPED

---

src/cow-react/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/utils/signatures.ts

1. Fixes order digest in eth flow signing step
2. use wrapped address inside `UnfillableOrdersUpdater` when getting new quotes and checking out-of-market prices

[EFV2] Fix order digest

---

.github/workflows/ci.yml

We use LTS versions of node, seems like yesterday it auto updated to 18.12.0 LTS which gives us errors:
```bash
Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
```
Using 16.17.1 fixes that.
I don't have too much time to debug this more as it's not a prio, but we should revert this change after eth-flow and/or others have had time to properly investigate this.

Set pinned node 16.17.1

---

src/cow-react/modules/limitOrders/hooks/useLimitOrdersStateFromUrl.ts
src/cow-react/modules/limitOrders/hooks/useSetupLimitOrdersState.ts

https://www.loom.com/share/fda1f0e2ecdf4a5f92aa8e18aa5d3ee2
1. Open Limit orders page and don't connect wallet
2. Select `Gnosis chain` network
3. Reload page

Fix: don't reset network to mainnet after page reload

---

.github/workflows/ci.yml
.github/workflows/vercel.yml

- Added manual step to deploy to Vercel prod
Anyone can trigger it, but it'll stop before the actual deployment is started
- Added deployment environments
Right now only these accounts will be allowed to publish to production
Only after the approval is give the env var `VERCEL_PROJECT_ID_PROD` will be available.
Otherwise it's not possible to deploy to production environment
Another cool thing about environments is that we can see all deployments per environment [here](https://github.com/cowprotocol/cowswap/deployments)
1. Check the deployment steps
2. There's one step that temporarily requires my permission to deploy to `dev`
3. I also tested with Anxo's approval
Otherwise, this needs to be first added to the default branch (I guess `develop`), then we can test the manual trigger. I have …

Manual prod deployment

---

.github/workflows/vercel.yml

RELEASE!
(another RC, not intended for deployment neither changes any code other that CI)
---
This change removes the local envvar mapping that for some reason wasn't working.
Only the `dev` env var was being picked which means `barn` and `staging` steps were deploying to `dev` environment.
Now the `VERCEL_PROJECT_ID` env var is set individually in each GH environment
There is also a fix for the envvars, which need to be set at build time but were not being passed.
1. I have temporarily forced `staging` and `barn` to be deployed in this branch to check the respective projects are deployed on Vercel
2. Change will be reverted before the merge
3. Example working build https://github.com/cowprotocol/cowswap/actions/runs/3386498114
4. Staging and barn created in the previous deployment …

Fix vercel project

---

.env
.env.production

- New staging and dev endpoints
- New preview URLs
- New temporary Vercel endpoints until our own are migrated
Needs deployment to each respective environment.
For develop it should already detect itself as being on develop, but then nothing changes there as it's already the default
Tested the regexes with https://regex101.com/
Regex: `^pr\d+--cowswap\.review|^(swap-dev-git-[\w\d-]+|swap-\w{9}-)cowswap\.vercel\.app`
URLs:
```
swap-h3c4xsg7t-cowswap.vercel.app/
swap-dev-git-limit-orders-wrap-unwrap-cowswap.vercel.app/
pr1284--cowswap.review.gnosisdev.com/
```
Regex: `^(cowswap\.dev|dev\.swap\.cow\.fi|swap-develop\.vercel\.app)`
URLs:
```
cowswap.dev.gnosisdev.com/
dev.swap.cow.fi
swap-develop.vercel.app
```
Regex: `^(cowswap\.staging|staging\.swap\.cow\.fi|swap-staging\.vercel\.app)`
URLs: …

Updated env vars with domain regex

---

src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/updaters/ActiveRateUpdater/index.ts
src/custom/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx

This PR fixes some smaller UI/UX issues
- when the currency changes, the output amount is removed while the new rate is loaded
- when the currency changes, until the new rate is loaded, we hide the USD amount of output value, otherwise there will be some point where the wrong value is showed
1. go to limit orders widget
2. change the currencies
3. make sure everything looks ok

Limit orders bug fixes 1

---

src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts

Fixes #1321
- type lower-case token symbols in URL
- make sure the correct tokens are selected

Fix for lower-case letters in URL

---

README.md
src/cow-react/modules/swap/helpers/getEthFlowEnabled.ts
src/cow-react/modules/swap/helpers/getSwapButtonState.ts
src/cow-react/modules/swap/hooks/useIsEthFlow.ts
src/cow-react/modules/swap/pure/SwapButtons/index.tsx

Closes #1289 
Added feature flag for toggling Native Eth Flow
To enabled it, on the console type if: `localStorage.setItem('enableEthFlow', '1')`
To disabled it: `localStorage.setItem('enableEthFlow', 0)`
1. Load the page and try to sell ETH
2. Test a few flows with varying amounts of ETH and WETH in your wallet
* The behaviour should be identical to the one currently in dev.swap.cow.fi
3. Enable the EthFlow with `localStorage.setItem('enableEthFlow', '1')`
4. Try to sell ETH (if ETH was selected before you might need to switch the token pair to reset it)
* It should now use the native Eth Flow
**Note**: Native Eth Flow is not fully working yet. The change here is just the feature flag

[Eth flow]#1289 Feature flag

---

src/cow-react/modules/swap/services/utils/logger.ts
src/custom/utils/trade.ts

Follow up to #1239 (https://github.com/cowprotocol/cowswap/pull/1239#discussion_r1019955645)
Using sellToken.address directly, as native token sell address is already set to 0xeee at this point
1. Turn on eth flow `localStorage.setItem('enableEthFlow', '1')`
2. Select sell ETH for anything
3. Place order (no need to actually submit the tx)
* It should pop the onchain tx without issues
4. Repeat steps 2 and 3 with WETH and a different token pair
* It should show the wallet signature prompt without issues

[Eth flow] Follow up 1239 - fix selltokenaddress

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts
src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/styled.ts
src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts

This PR adds "Unlock limit orders" screen
This will be shown to a user first until he clicks on the enable button
From that point he will not see this screen
1. go to limit orders page
2. you should see this screen
3. click on the Unlock button
4. the screen should be gone and if you refresh the page it should also be gone

Added enable limit orders screen

---

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts

Fix for e2e tests.
In the Cypress environment we have a little different setup of provider, so, we have a case when the provider returns `chainId` as `undefined` and we shouldn't consider that case as network change.

Fix detection of network changes from provider

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTabs.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx

To get better UX we persist selected tab id to the URL.
- `/limit-orders/WETH/DAI?tab=open`
- `/limit-orders/WETH/DAI?tab=history`

Persist current orders tab to the URL query

---

src/cow-react/common/pure/CurrencyInputPanel/styled.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.styled.tsx
src/cow-react/modules/limitOrders/pure/Orders/styled.ts
src/cow-react/pages/LimitOrders/index.tsx
src/cow-react/pages/LimitOrders/styled.ts

1. Vertical alignment of content in the orders table:
2. Fix the currency panel layout
3. Display the orders table when Limit orders page is unlocked
4. Fix the orders list width for mobile view

DIsplay orders list and styles fixes

---

src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts
src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts

Fixes #1420
This PR
- fixes mentioned issue
- fixes the price percentage warning when you switch the tokens and for a short period of time you see really big positive or negative difference

Fix WETH/USDC issue on switch and also warning issue

---

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts

Fixes #1427
1. Open swap page and connect Metamask to Goerli
2. Change chainId in the URL to Mainnet (1)
3. Metamask opens modal with network change request
4. AR: URL contains Mainnet chainId (1)
5. ER: URL contains Goerli chainId (5)

Reset chainId to provider's value after network change request initiated by URL

---

src/cow-react/utils/request.ts
src/custom/hooks/useIsOnline.ts

Fix to the false claims we get sometimes from the browser saying is offline.
Before this PR we relied only on `window.navigator.onLine`
This PR introduces:
- A check of connectivity when the browser says is offline
- This check is basically a HEAD HTTP request
- The request has a timeout of 15s (after this time, it assumes is offline)
- It will do re-attempts to check the network state every 30s if the browser is still offline
TODO, I will add more details

Fix offline issue

---

src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/Step.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Progress1.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Progress2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step1.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
src/custom/components/ExplorerLink/index.tsx

This PR implements the pure component for the stepper. 
- Simple model for the parameters. Its easier to check in cosmos the parameters (its shown as a JSON in the fixture)
- Creates a component with the 3 steps, and 2 progress bars
- Step 1: Models the Send ETH tx state
- Step 2: Models the Order Creation state
- Step 3: Models the Receival of either the tokens or the refund
- https://www.figma.com/proto/sUwumNFlcslHzShSZJHVsS/2022_COW-Native-ETH-Flow?page-id=1201%3A382&node-id=1232%3A1702&viewport=-96%2C1616%2C0.19&scaling=min-zoom&starting-point-node-id=1204%3A674
- Designs https://www.figma.com/proto/sUwumNFlcslHzShSZJHVsS/2022_COW-Native-ETH-Flow?page-id=1201%3A382&node-id=1298%3A382&viewport=-96%2C1616%2C0.19&scaling=min-zoom&starting-point-node-id=1298%3A382&show-proto-sidebar=1 …

[ETH] Stepper pure component

---

src/cow-react/pages/NewSwap/index.tsx

Fixes #1458
Basically, the new Swap redirection was making the assumption we have defined the WETH address for all networks. 
- Reproduce the steps from Elena described in #1458
- No crash now

Handle Unknown WETH for current network

---

src/cow-react/api/gasPrices/index.ts
src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/api/gnosisProtocol/gasFeeApi.ts
src/cow-react/modules/swap/containers/EthFlow/hooks/useRemainingNativeTxsAndCosts.ts
src/custom/constants/index.ts
src/custom/state/gas/actions.ts
src/custom/state/gas/reducer.ts
src/custom/state/gas/updater.tsx

In this PR
- we change gas prices API to use **Blocknative** for **Mainnet**
- the gas state structure will now have "fast, average, slow" properties same as response from **Blockscout** for **GC**
- we map the gas price confidence levels from Blocknative to our gas state properties `fast: 99, average: 90, slow: 70,`
- the gas price should now be updated every 10 seconds (if that is ok?)

Use Blocknative as source for Mainet gas-prices and update implementation

---

src/cow-react/modules/swap/containers/Row/RowDeadline/index.tsx
src/cow-react/modules/swap/containers/Row/RowSlippage/index.tsx
src/cow-react/modules/swap/pure/Row/RowDeadline/index.cosmos.tsx
src/cow-react/modules/swap/pure/Row/RowDeadline/index.tsx
src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx
src/cow-react/modules/swap/state/EthFlow/updaters/EthFlowDeadlineUpdater.tsx
src/cow-react/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx
src/cow-react/modules/swap/state/EthFlow/updaters/types.ts
src/custom/components/TransactionSettings/TransactionSettingsMod.tsx

Closes #1379
1. Storing both Deadline and Slippage settings for EthFlow
2. Allowing Slippage to be updated for EthFlow
1. Turn on EthFlow flag with `localStorage.setItem('enableEthFlow', '1')`
2. Pick as sell token any ERC20, pick as buy token `ETH` (or xDAI, if on xDAI)
3. Open settings and set slippage to 1% and deadline to 4 minutes
4. Refresh the page
* Values should be kept
5. Click on the arrow to switch the tokens
* `ETH` should now be the sell token and the ERC20 the buy token
6. Open the settings
* The slippage should be set to `2%`
* The deadline should be set to 10min
7. Try to update slippage to a value < 2%
* You should not be able to
8. Try to update deadline to a value < 10 min
* You should not be able to
9. Update the values to slippage > 2% and deadline > 10 min
* You …

[EthFlow]#1379 Storing ethFlow deadline and slippage

---

src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/custom/components/AccountDetails/Transaction/ActivityDetails.tsx
src/custom/components/TransactionConfirmationModal/index.tsx

Closes #1293 
Adding EthFlow stepper to Activity details and Confirmation modal
**Note:** Definitely NOT pretty! Out of the scope of this task
**Note:** Expiration and cancellation NOT yet supported!
1. Turn on ethflow with `localStorage.setItem('enableEthFlow', '1')`
2. Place ETH sell order
* Confirmation modal should show stepper
* Activity details should show stepper

[EthFlow]#1293 connect stepper happy path

---

src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx

Follow up to https://github.com/cowprotocol/cowswap/pull/1465
Closes #1293 
(Partially) handling expiration
You can now see the stepper for expired orders, but there's no action possible
The refunding will never complete.
1. Turn on ethflow with localStorage.setItem('enableEthFlow', '1')
2. Place ETH sell order
3. Make it expire - not very straight forward. See notes at the bottom
* Order will be seen as expired like screenshot above
Alternatively, you can use impersonator.xyz/ to impersonate my account (check [this](https://protocol-explorer.dev.gnosisdev.com/goerli/orders/0xdfe9b9ca80c54d655ac68121c04e0bfac9bf01d3a631fa71a9e051b9d6a6071976aaf674848311c7f21fc691b0b952f016da49f3ffffffff) expired order)
1. In two browser windows, connect with the same account
2. In one window, place and …

[EthFlow]#1293 stepper expired orders

---

src/cow-react/common/hooks/usePrice.ts
src/cow-react/common/hooks/useRateInfoParams.ts
src/cow-react/common/pure/RateInfo/index.tsx

@nenadV91:
>Right now on dev in orders table I think we have an issue with price calculation because its not adjusting for the decimals. In the first order the actual price should be 1 WETH = 1125.7329 USDC
1. Create order with currencies with different decimals (for example: WETH -> USDC)
2. AR: The price on Limit orders form and in Orders table is wrong
3. ER: The price is actual

Fixed order price calculation

---

src/cow-react/common/hooks/useTokensAllowances.ts
src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useOrdersBalancesAndAllowances.ts
src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts

Post-merge review fixes: https://github.com/cowprotocol/cowswap/pull/1437
1. Added `TODO` to add batching for useTokensAllowances() 
2. Added `ListenerOptions` for useTokensAllowances()
3. Added `{ blocksPerFetch: 25 }` for allowances request in `useOrdersBalancesAndAllowances()`
4. Refactored `useTokensAllowances()` hook to simplify `useMemo()` usage
5. Added `TODO` for `useTokenBalancesWithLoadingIndicator()` refactoring
6. Refactored `OrderRow` component and extracted logic to `getOrderParams` util
1. Recheck #1354

Refactor limit orders hooks and components

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx

Show different text on the stub for open/history orders

---

src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts

Fixes #1415
The root of the problem is here: https://github.com/pmndrs/jotai/pull/1004
How it works:
1. Open a tab with the limit orders page with state: `2 WETH -> DAI`
2. Open one more tab with state: `3 WETH -> DAI`
3. After opening the second tab, the first one receives `storage` event with the state from the second tab
4. `useSetupTradeState()` hook detects changes and rewrites the state
5. Second tab receives state from the first tab and we go to the loop

Disable limit-orders state persistence between browser tabs

---

src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx

Only shows pagination when `orders.length > LIMIT_ORDERS_PAGE_SIZE`

No pagination when orders.length is lower than LIMIT_ORDERS_PAGE_SIZE

---

src/cow-react/modules/limitOrders/pure/Orders/OrdersTabs.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx
src/cow-react/pages/LimitOrders/styled.ts

Fixes: #1543
- Adds responsive styles for the limit order, orders table.
https://user-images.githubusercontent.com/31534717/204773164-5e90aa44-f1db-4846-99c7-5999dbc3e2cc.mov
- Styling the rest of the table (responsive) is a WIP (next PR)

Limit order responsive styles 1

---

src/cow-react/modules/mainMenu/constants/mainMenu.ts

This PR updates the header so if the flag `enableLimitOrders` **is set** in local storage then we show this 
if **not** then we show this

Update the header navigation for limit-orders

---

src/cow-react/common/pure/CurrencyArrowSeparator/index.tsx
src/cow-react/common/pure/CurrencyArrowSeparator/styled.tsx

Make tap area of CurrencyArrowSeparator smaller

---

src/custom/state/orders/consts.ts
src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts

Fixes #1563
1. Removed `quote` requests for limit-orders to derive "unfillable" state
2. Reduced count of `order` requests for limit-orders (before - every 2 sec, now - every 15 sec)

Fix limit orders performance issues

---

config/announcements/announcements-100.md

Reverts #1568.
The issue in Gnosis Chain has been resolved: Nethermind released a new node version which is curently stable. We update Nethermind and now can resume normal service.
Since images are nice:
Feel free to merge
Yes!
https://cowservices.slack.com/archives/C0361CDD1FZ/p1669904175134319?thread_ts=1669820120.072869&cid=C0361CDD1FZ

Remove xdai issue banner

---

src/cow-react/common/pure/CurrencyArrowSeparator/index.tsx
src/cow-react/common/pure/CurrencyArrowSeparator/styled.tsx
src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
src/cow-react/common/pure/CurrencyInputPanel/CurrencyPreview.tsx
src/cow-react/common/pure/CurrencyInputPanel/styled.tsx
src/cow-react/common/pure/RateInfo/index.tsx
src/cow-react/modules/application/containers/App/styled.ts
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
src/cow-react/modules/limitOrders/containers/RateInput/styled.ts
src/cow-react/modules/limitOrders/pure/DeadlineSelector/styled.tsx
src/cow-react/modules/swap/containers/NewSwapWidget/styled.tsx
src/cow-react/modules/swap/pure/CurrencySelectButton/styled.tsx
src/cow-react/modules/swap/pure/Row/styled.ts
src/cow-react/modules/swap/pure/Row/types.ts
src/cow-react/modules/swap/pure/Row/typings.ts
src/cow-react/modules/swap/pure/TradeRates/styled.tsx
src/cow-react/pages/Claim/styled.ts
src/custom/components/Header/styled.ts
src/custom/components/Popover/PopoverMod.tsx
src/custom/components/Popover/index.tsx

- Adds responsive styles for the swap/limit container
Left = this PR
Right = current `develop`

Fix swap/limit container responsive styles

---

src/cow-react/modules/swap/services/common/steps/analytics.ts
src/custom/components/analytics/events/transactionEvents.ts
src/custom/state/orders/middleware.ts

Fixes: #1371
Base to differentiate between some order events for limit orders and swaps. 
Adds the class into the parameters for analytics. Also modifies the middleware so they can pass the required param
This PR doesn't add any new event for limit orders. For example, there's no event for when the order is filled (is not handled in the middleware as for swaps)
The PR scope is just to parameterized the analytics, and for the post order event (which we were already sending), now it specifies if its a swap or a limit order.
Follow up PRs should handle the execution, cancelation, expiration of orders and report to analytics. 
1. Install Google Analytics Debugger
2. Make sure

[analytics] Differentiate between Post Orders for Swaps and Limit Orders

---

src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts

Fixes #1373
Included the `quoteId` we used to get the market price to the `POST /order` request.
1. Create a limit-order
2. Check `network` in the dev console
3. ER: The `quoteId` parameter must be in the `POST /order` request

Add quoteId to POST quote request

---

src/cow-react/modules/limitOrders/containers/OrdersReceiptModal/hooks.ts
src/cow-react/modules/limitOrders/containers/OrdersReceiptModal/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/state/limitOrdersReceiptAtom.ts

Fixes #1534
Modifies the implementation to keep selected order id in state
And then in another hook we get selected order with the id from the state
So when the other hook updates the orders the selected order will also be updated.
- make a limit order with short expiration and some price that probably wont execute
- open receipt for that order and don't close it
- wait until the time expired and make sure that the status in updated

Fix for receipt status

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts

There are no reasons to display too many orders, so, the limit of up to 100 orders was added.

Display up to 100 limit-orders in the table

---

src/custom/state/orders/middleware.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/utils/appzi.ts

Fixes #1602
1. Don't show Appzi NPS for limit orders that in pending for a long time (>5mins)
2. Show Appzi NPS for limit orders only if they were filled before 5 mins since creating

Show Appzi nps for limit orders only when an order was filled before 5 min since creating

---

src/custom/hooks/useWrapCallback.ts
src/custom/utils/misc.ts
workbox.config.js

1. Init tx signing for Wrap/Unwrap
2. Reject signing in the wallet
AR: The app crashes
ER: Nothing happened

Don't crash app when user rejected tx for wrap/unwrap

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/hooks/useApplyLimitRate.ts
src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts
src/cow-react/modules/limitOrders/hooks/useOnCurrencySelection.ts
src/cow-react/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts
src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts
src/cow-react/modules/limitOrders/updaters/ActiveRateUpdater/index.ts
src/cow-react/modules/limitOrders/utils/adjustDecimals.ts

Fixes #1595
1. Store amounts using precise values instead of view values (view value = 5 USDC, unit value = 5000000 USDC)
2. Adjust decimals on switch token places
3. Adjust decimals on select currency

Store amounts using precise values in limit-orders

---

package.json
src/cow-react/abis/types/index.ts

Remove `contracts:compile i18n:compile` scripts from `postinstall` because we also call them in `prepare`
This will reduce the build time

Optimize yarn script execution time

---

src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
src/custom/lib/hooks/useCurrencyLogoURIs/useCurrencyLogoURIsMod.ts

Suggestion on some small modification for #1669
It doesn't change anything fundamentally, but it:
- Deletes the `getOverriddenTokenLogoURI` which I believe we don't need anymore.
- Adapts `CommonBases` so it uses `useCurrencyLogoURIs` hook instead.
- Changes slightly the logic. Respect the precedence, but returns the full list of uris so we have fallbacks even for the overrides tokens.

Change uri logic

---

src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
src/custom/lib/hooks/useCurrencyLogoURIs/useCurrencyLogoURIsMod.ts

Currently we override the explicit tokenURL as provided in the token list by either an explicit (hardcoded) override or the Uniswap generated fallback link (https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/${networkName}/assets/${address}/logo.png).
This means we never load the URLs from the actual token list (cf. e.g. in prod right now ACX and icETH don't have a logo despite having one specified in the list.
This PR changes the logic of the override to use the following priority:
1. Explicit hardcoded overrides (this ensures that e.g. we show a nice WETH symbol)
2. Explicit URLs as specified on the token list
3. Autogenerated Uniswap link only as a fallback
Before:
After:
1. Open the token picker, type ACX
2. Select Token
Context: …

[TokenLists] Prioritise explicit logoURI over fallback path

---

package.json

1.26.0-RC.0 version bump

---

README.md
src/cow-react/modules/swap/helpers/getEthFlowEnabled.ts

Removing EthFlow feature flag
1. Open app and pick ETH as sell token
* EthFlow should show up without needing to use the feature flag

Eth flow/remove feature flag

---

src/cow-react/modules/limitOrders/containers/OrdersReceiptModal/hooks.ts
src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
src/cow-react/modules/limitOrders/pure/ReceiptModal/IdField.tsx
src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx

Show creating EthFlow orders on limit orders history
1. Place ethflow order
2. Go to limit orders history
* EthFlow order should show up there
Limit orders view receipt now hides the orderId when the ethflow order is in creating state and shows the creation transaction instead:

[EthFlow] Show `creating/cancelling` EthFlow orders on limit orders history

---

src/cow-react/common/services/getQuoteCurrency/index.ts
src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/index.tsx
src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts

Fixes #1656
1. When one of the tokens is stable-coin, then another token is `quote` (should be displayed in `Price per TOKEN`)
2. When there are no stable-coins in trade, then consider a token with the smallest amount as `quote`. (for 0.0005 WETH -> 3000 COW, WETH is quote)
https://user-images.githubusercontent.com/7122625/206747578-fff03901-0dec-4c1d-8ab6-8fecb6a147e2.mov

Apply smart quote selection to RateInput

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
src/cow-react/modules/limitOrders/pure/Settings/index.tsx
src/cow-react/modules/limitOrders/pure/Settings/styled.ts
src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/styled.ts
src/cow-react/modules/swap/containers/FeesDiscount/index.tsx
src/custom/components/Popover/index.tsx
src/custom/components/Settings/SettingsMod.tsx
src/custom/components/Settings/index.tsx
src/custom/components/SwapWarnings/index.tsx
src/custom/components/Tooltip/TooltipMod.tsx
src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
src/custom/components/swap/FeeInformationTooltip.tsx
src/custom/components/swap/SwapHeader/SwapHeaderMod.tsx

- Addresses https://github.com/cowprotocol/cowswap/issues/1637 
https://user-images.githubusercontent.com/31534717/207121569-7da440b5-8e9f-48b1-88a5-c339f02ede27.mov
- Consistent header padding on switch between SWAP and LIMIT tab
https://user-images.githubusercontent.com/31534717/207123080-8e04fc92-4adf-4d3b-8b1e-349a6e78911c.mov
- Fix the blinking issue on the limit order UNLOCK screen. The issue was related to the SVG's needing to load. In the future we need to re-consider if inline SVG is performant enough vs. just having plain IMAGE imports.
https://user-images.githubusercontent.com/31534717/207125993-6d17f885-7a8a-4786-9465-2904430d3c53.mov

Tooltip styles fix

---

src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx
src/cow-react/modules/trade/utils/tokenViewAmount.ts

Fixes #1658 #1677
In `CurrencyInputPanel` there was a wrong overriding of `typed value` for zero values (`0` or `0.` or `0.0`).

Fix input in CurrencyInputPanel when value is zero

---

src/cow-react/common/hooks/useCancelOrder/index.ts
src/cow-react/common/hooks/useCancelOrder/useEthFlowCancelOrder.ts
src/custom/hooks/useRecentActivity.ts

Follow up to https://github.com/cowprotocol/cowswap/pull/1629#issuecomment-1339999184
This PR addresses (hopefully) points 1 to 3.
As for point 4, that is correct, the UI doesn't recognize when the tx is cancelled/sped up in the wallet directly.

[EthFlow] Follow up to PR #1629 - Update cancellation state for EthFlow orders

---

src/cow-react/common/hooks/useCancelOrder/index.ts
src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Progress2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
src/custom/state/orders/utils.ts

Part of #1299 
EthFlow stepper states
1. Place orders in several contexts: expired, cancelled, cancelling
*Note*: Automatic refunds not yet supported
*Note*: Order creation/cancellation transactions not yet tracked. Will be part of next PR

[EthFlow]#1299 Stepper state changes

---

src/cow-react/common/hooks/useCancelOrder/index.ts
src/cow-react/common/hooks/useCancelOrder/useEthFlowCancelOrder.ts
src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/cow-react/modules/swap/hooks/useEthFlowContext.ts
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
src/cow-react/modules/swap/services/common/types.ts
src/cow-react/modules/swap/services/ethFlow/index.ts
src/custom/hooks/useRecentActivity.ts
src/custom/state/enhancedTransactions/actions.ts
src/custom/state/enhancedTransactions/hooks/index.ts
src/custom/state/enhancedTransactions/reducer.ts
src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx

Closes #1299 
Follow up to https://github.com/cowprotocol/cowswap/pull/1710
Keeping track of ethflow creation & cancellation txs
Also added a new sub-state to stepper on Step2: cancelled
*Note*: Automatic refund states (when the order expires) are not yet returned by the backend, thus not tracked
1. Place ethflow orders and test various states

[EthFlow]#1299 track tx states

---

src/cow-react/modules/application/containers/App/Updaters.tsx

Follow up to https://github.com/cowprotocol/cowswap/pull/1724
Fixes the issue where creation/cancellation ethflow transactions were displaying a pop-up when confirmed
1. Place one ethflow tx
2. After the tx is confirmed, there should NOT be a pop-up displayed
3. Cancel the ethflow
4. After the cancellation tx is confirmed, there should NOT be a pop-up displayed

[EthFlow]#1299 fix extra popups

---

src/custom/components/AccountDetails/Transaction/styled.ts
src/custom/constants/index.ts
src/custom/state/orders/middleware.ts

Closes #1300 
Built on top of https://github.com/cowprotocol/cowswap/pull/1732
Cancellation pop-ups are already displayed for ethflow cancellations, but there is one edge case.
When the order is not created on the backend, the notification will still point to Explorer.
That will lead nowhere as the order doesn't exist.
This PR makes the link in that case point to etherscan with the cancellation tx hash
⚠️ **Note** ⚠️ This PR is intentionally pointing to the wrong contract so the order is never created in the backend to test this behaviour. The contract change SHOULD BE REVERTED before merging this PR!!!
1. Place order
2. Cancel it
* The toast notification will show `View on Etherscan` instead of `View on Explorer`

[EthFlow]#1300 cancellation toast notifications

---

src/cow-react/modules/swap/services/ethFlow/index.ts
src/cow-react/modules/swap/services/ethFlow/steps/calculateUniqueOrderId.ts
src/cow-react/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts

Small preparation/refactor for detection of collisions.
I removed the responsibility of calculating the order id from the step that signs the transaction.
I made the new step's function signature so it could call itself in a recursive fashion to find the first orderId without collisions. 
I briefly explained in this PR's TODO which checks we could implement and how to do the recustive all.
Nothing should change in this PR behaviour. The app should work as before. You can check ETH flow is not broken :)

Refactor preparing for unique order Id checks

---

src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
src/custom/state/orders/updaters/GpOrdersUpdater.ts

Fixes issue where the cancellation pop-up was triggered twice for ethflow orders
Issue was reported here https://github.com/cowprotocol/cowswap/pull/1732#issuecomment-1353154225
1. Place ethflow order
2. Cancel it
* There should be 1 pop-up when cancellation tx is mined
3. Wait for a few minutes
* No other cancellation pop-up should be triggered

[EthFlow]follow up #1732 double cancellation toasts

---

src/cow-react/modules/swap/containers/Row/RowFee/index.tsx
src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx

Fixes #1647
- updates the Fee tooltip when ethflow
- updates the fee row when ethflow
- should the USD estimation for fee include the network gas fee?
- go to swap page
- select eth as a sell currency
- check fee row

Eth flow/1647

---

src/cow-react/modules/swap/helpers/getSwapButtonState.ts
src/cow-react/modules/swap/pure/SwapButtons/index.tsx

Closes #1747
Add expert mode for eth flow.
Test to swap with and without expert mode 
Verify the confirmation only shows for normal mode

Add expert mode for eth flow

---

src/cow-react/common/pure/RateInfo/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
src/cow-react/modules/limitOrders/containers/RateInput/styled.ts
src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/styled.tsx
src/cow-react/modules/limitOrders/pure/RateInput/HeadingText.tsx
src/cow-react/modules/swap/pure/Row/styled.ts
src/cow-react/modules/swap/pure/TradeRates/styled.tsx
src/custom/components/Tooltip/TooltipMod.tsx

- Addresses https://github.com/cowprotocol/cowswap/issues/1675
- Addresses https://github.com/cowprotocol/cowswap/issues/1528
The issue with the shifted rate impact is due to larger token symbols (e.g. FRACTION).
**BEFORE**
**AFTER**
**Example with very large token symbol/name:**
**Fixed token symbol on load**
https://user-images.githubusercontent.com/31534717/207896629-fdbec2b6-eb61-47e3-b2b2-fff5681bee0b.mov

🎨 Rate impact styles

---

src/cow-react/common/pure/RateInfo/index.tsx
src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
src/cow-react/modules/limitOrders/hooks/useRateImpact.ts
src/cow-react/modules/limitOrders/utils/getDecimals.ts

> Original PR from @nenadV91 #1771
Fixes #1759
- There was an issue in our code where we used `DEFAULT_DECIMALS` (18) when the actual token decimals is 0 and that shouldn't happen
- check if the mentioned issue is fixed
- make sure prices for other tokens are correct (for example USDC, WBTC, USDT)

Fix for zero decimal tokens

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx

- Prevents the output of an empty <div> when this condition is false:
`const isVisible = showPriceImpactWarning || rateImpact < 0`
https://user-images.githubusercontent.com/31534717/207928448-b836dbc3-ec2c-4bd6-805a-0c889f61f0b7.mov

Conditional display of the rate warning banner

---

src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/common/hooks/useCategorizeRecentActivity.ts
src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx
src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Progress1.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Progress2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step1.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step2.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
src/cow-react/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
src/custom/components/AccountDetails/Transaction/ActivityDetails.tsx
src/custom/components/AccountDetails/Transaction/StatusDetails.tsx
src/custom/components/AccountDetails/Transaction/index.tsx
src/custom/components/TransactionConfirmationModal/index.tsx
src/custom/hooks/useActivityDerivedState.ts
src/custom/hooks/useRecentActivity.ts
src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx
src/custom/state/orders/actions.ts
src/custom/state/orders/hooks.ts
src/custom/state/orders/middleware.ts
src/custom/state/orders/reducer.ts

Part of #1294 
Handle creation transaction failure
- New order state `invalid` - this will be a new state returned by the backend
- Updated stepper to display cancellation failure
1. Not tested with transaction cancellation/speed up. May or may not work (more likely won't)
2. Cancellation transaction failure not yet handled
1. Place an ETH sell order for 1 ETH
* Tx will fail
* Stepper will be updated to show the status like the picture above
2. Place regular ETH sell orders
* Should work as usual
How do you fail a tx, you ask?
I've made a temporary change so every ETH flow order will always fail when value is exactly `1 ETH` in this PR :)

[EthFlow]#1294 handle failed txs

---

src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx

- Addresses https://github.com/cowprotocol/cowswap/issues/1783
- Open the order table with some orders, make sure there's a 'Cancelling...' order.
- All the status labels should be equally aligned

🎨 Order table alignment: status labels

---

src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx
src/cow-react/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx
src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
src/custom/components/TransactionSettings/index.tsx
src/custom/constants/index.ts

Closes #1445 
More info about invalid slippage, both for regular and ethflow orders
- Regular orders have high slippage warning set to `1%`. Added the same for ethflow orders when above `10%`
- Showing error when ethflow slippage is < `2%`
**Invalid: too high**: same for both types; > `50%`
**High**: > `1%`
**Low**: < `0.05%`
**Invalid**: < `0%`
**High**: > `10%`
**Invalid**: < `2%`
1. On regular, check the slippages -1, 0, 1.1, 50, 50.1
* Make sure the behaviour matches what's described in the images above
2. On ethflow, check the slippages 1, 2, 10, 10.1, 50, 50.1
* Make sure the behaviour matches what's described in the images above

[EthFlow]#1445 highligh invalid slippage

---

src/custom/components/TransactionSettings/TransactionSettingsMod.tsx

Closes #20 
Also preventing more than 2 decimals of precision on slippage input.
E.g.: 1.99 OK; 1.999 won't be possible to type
Funny business with JS and floats
1. Try slippage inputs: 5.02 and 5.06
* Slippage should be valid and remain 5.02 and 5.06
2. Of course, try other values and make sure there's nothing funny after this tiny change

Fixed #20: JS and floats are not to be trusted

---

src/custom/components/TransactionSettings/TransactionSettingsMod.tsx

A bit more of #1445 for ethflow
- Allow slippage input to be cleared -> then replace it with minimum (`2%`)
https://user-images.githubusercontent.com/43217/209933992-e927d86f-5bed-4001-9a01-14fdf15af9cc.mov
- When Input is an error (< `2%`) and focus moves away, set value to minimum rather than last used value
https://user-images.githubusercontent.com/43217/209934013-bd41f815-aebb-4792-b5a9-5db28ff9dc3f.mov
Somewhat addressing https://github.com/cowprotocol/cowswap/issues/1806 but not quite.
Clearing the field completely for ethflow is not trivial and I don't think it's worth the effort.
1. Select eth flow order
2. Set slippage to something valid other than default and move the focus away
3. Go back to the input and remove everything
* It should be set to minimum (`2%`)
4. Insert a valid …

[EthFlow]#1445 more slippage business

---

src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step1.tsx
src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx
src/custom/state/orders/actions.ts
src/custom/state/orders/middleware.ts
src/custom/state/orders/reducer.ts

Fixes #1787
- Displaying error pop when order creation tx fails
- Displaying error pop when order cancellation tx fails
- Tiny fix also for https://github.com/cowprotocol/cowswap/issues/1798
1. Following steps on #1787 , when placing the sell ETH order, tweak the `gas limit` in a way that the tx fails right away
* The order should be displayed as failed in the activity descriptor
* The failure sound should be emitted
* The failure pop-up should be displayed
1. Place a valid ETH sell order
2. Right away request a cancellation, tweaking the `gas limit`  in a way that the tx fails right away
* The stepper should change from `eth refund initiated` etc to regular pending order flow
* The failure sound should be emitted
* The failure pop-up should be displayed

[EthFlow]#1787 failed sound on tx failure

---

src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
src/cow-react/pages/Faq/EthFlowFaq.tsx
src/custom/components/Header/styled.ts
src/custom/state/orders/actions.ts
src/custom/state/orders/reducer.ts
src/custom/state/orders/updaters/ExpiredOrdersUpdater.ts
src/custom/state/orders/updaters/GpOrdersUpdater.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts

Part of #1294 
Wiring up refund tx hash
After the order expires and the automated refunder kicks in, the refund tx hash will be displayed at the bottom of the 3rd step
Follow same test steps as https://github.com/cowprotocol/cowswap/pull/1756

[EthFlow]#1294 - updated backend return types

---

cypress-custom/integration/swap.test.ts

Our e2e tests are red, because there is Fees exceed 30% of the swap amount!  banner for the trade.
e2e test doesn't expect it

Fix e2e tests

---

.github/workflows/pr_comments.yml

New GH action workflow
It'll trigger on every issue_comment
And run only on PR comments
This first workflow is only logging the whole workflow event context.
I intend to use this to create cosmos/storybook links from Vercel deployment comments.
Still not sure what's available, so the first step is just logging stuff.
Sadly, new workflows only run after they are deployed to the default branch, which is `develop`
So, nothing to see here in this PR

New GH action workflow

---

src/custom/components/OrderProgressBar/index.tsx
src/custom/state/orders/reducer.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts

Closes #1586 
Progress bar now starts from 0 for ethflow orders
https://user-images.githubusercontent.com/43217/210795533-b50ddf5a-7d06-449d-bb0e-8ba61a07d019.mov
1. On regular mode (non-expert), place an ethflow order
2. Keep the modal open and observe
* When the order becomes pending, the progress bar should start from the very left
3. Repeat same process for non-ethflow orders, as well as smart contract wallets
* The behaviour should be the same

[EthFlow]#1586 progress bar starts not from 0

---

.github/workflows/pr_comments.yml

Playing around with workflow `issue_comments`
Merging directly as:
1. This does not impact any existing code or workflows
2. Changes in the PR have no effect. Looks like they need to be merged to `develop` in order to be updated

PR comments workflow

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useValidatePageUrlParams.ts

Closes #1841 
1. On limit orders, load token https://etherscan.io/token/0x2E2A42fbE7C7E2FfC031BAF7442dBE1F8957770a
* The app should NOT crash

#1841/Do not reset page number if there are no orders to be loaded

---

src/custom/components/WalletModal/InjectedOption.tsx
src/custom/components/WalletModal/WalletModalMod.tsx

Fixes #1332
Adds an option on mobile to open Dapp in Metamask Browser.
https://user-images.githubusercontent.com/5501872/210831517-69256270-3240-4716-be59-9bab036bd0f0.mov
1. Tap `Connect Wallet` on mobile device
2. Tap `Connect Wallet` on Metamask Browser

Add open in metamask option on mobile

---

src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx

- Fixes https://github.com/cowprotocol/cowswap/issues/1795
- Uses a media query to programmatically detect Tablet viewports and smaller, instead of using user agents. Should detect viewport changes and apply onMouseEnter/Leave (desktop/mouse) vs onClick (touch mobile/tablet) logic.
https://user-images.githubusercontent.com/31534717/211832078-55fb4fd1-1ef6-45e5-b807-fecfd971619e.mov

Detect mobile/tablet by media query instead of user agent

---

cypress-custom/integration/swap.test.ts

Prices in Goerli are not stable and sometimes we get `Fees exceed 10% of the swap amount!` warning.
In this PR I check the warning and accept it if it exists.

Make swap e2e tests more sustainable

---

src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
src/cow-react/modules/limitOrders/utils/isUnsupportedTokenInQuote.ts

Fixes #1872
`useIsTradeUnsupported()` is not appropriate to Limit orders, because it's coupled with `useRefetchQuoteCallback()` that in turn is unrelated to Limit orders.
Because of it, the unsupported check was changed and now it's based on `limitOrdersQuoteAtom`.
1. Connect to a wallet on GC
2. Open Limit orders page
3. Select WXDAI-AST token pair
4. Fill in the amount

Replace useIsTradeUnsupported() by state from limitOrdersQuoteAtom for Limit orders

---

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
src/cow-react/types.ts

Fixes #1391, #1717
`useSetupTradeState()` didn't check the case, when `chainId` was changed while changing wallet
1. Connect to Metamask on Gnosis chain
2. Click `Change wallet` in the Account modal
3. Connect via Walletconnect to a wallet that doesn't support Gnosis chain (Trust for example)

Additionally compare chainId in URL and in provider for trade state updates

---

src/cow-react/constants/format.ts
src/cow-react/modules/swap/pure/ReceiveAmountInfo/index.tsx
src/cow-react/modules/swap/pure/ReceiveAmountInfo/styled.tsx
src/cow-react/utils/number.ts
src/custom/components/QuestionHelper/QuestionHelperMod.tsx
src/custom/components/Tooltip/TooltipMod.tsx
src/custom/lib/utils/tryParseCurrencyAmount.ts
src/state/mint/v3/utils.ts

- Addresses https://github.com/cowprotocol/cowswap/issues/1794
- Currently the integer and decimals are retrieved by using `.split('.')` on the `string`. I think it would be better to pass it as a prop. Need a review here.
- The current layout will not work if the decimal count are NOT consistently the same. E.g. we need to have the same amount of decimals for all decimals. Need some assistance here.
https://user-images.githubusercontent.com/31534717/212090327-c0e849ca-f685-407b-891b-75eac0a9647b.mov

Consistent fee/numbers layout for fee tooltip

---

src/cow-react/modules/trade/utils/analytics.ts
src/custom/components/analytics/events/transactionEvents.ts

The analytic events are too complex. 
Because the type of order is included in the event name, the dashboards/funnels are harder to implement. 
This PR unifies a lot of the events
Enable analytics plugin and check the new events match the expectations on https://cowservices.slack.com/archives/C04J0438VTJ/p1673968708883919

Simplify analytics

---

src/cow-react/modules/application/pure/Page/index.tsx
src/cow-react/pages/CookiePolicy/CookiePolicy.md
src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md
src/cow-react/pages/TermsAndConditions/TermsAndConditions.md
src/cow-react/pages/TermsAndConditions/index.tsx

Fixes #1879
This PR adds "Back to top" button at the end of following pages
- Terms and conditions
- Privacy Policy
- Cookie Policy
- go to pages mentioned above
- scroll at the bottom
- test the button

Add back to top button to content pages

---

src/custom/utils/explorer.ts

Closes #874
1. Connect wallet to gchain
2. Check the explorer links
* It should point to `<<explorer>>/gc` instead of `<<explorer>>/xdai`

#874/Changed gchain explorer path from older `xdai` to current `gc`

---

config/announcements/announcements-1.md

Adds a banner explaining how to work around the expired SSL certificate on mainnet.

Mention work around to expired SSL certificate

---

src/cow-react/common/hooks/useAreThereTokensWithSameSymbol.ts

Fixes #1893 
Lowercasing token symbol when searching for existing ones in the mapping
1. On mainnet, search for `AURA` 
2. There should be 2 results. Import both
3. Select the first one (with the purple symbol)
* It should be selectable
* The url should change to the token address `0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF`
4. Select the other AURA token (with blue-ish symbol)
* It should be selectable
* The url should change to the token address `0xCdCFc0f66c522Fd086A1b725ea3c0Eeb9F9e8814`

#1893 Fixing issue with tokens with identical symbols

---

src/cow-react/api/gnosisSafe/index.ts
src/custom/components/AccountDetails/Transaction/StatusDetails.tsx
src/custom/hooks/useActivityDerivedState.ts
src/custom/hooks/useWalletInfo.ts

Updating Safe endpoints
1. Connect to the app using the Safe
2. Open the network console and filter by `safe`
3. Perform any operation (approval, order placement)
4. Open the activity modal
* It should link to the new Safe endpoints (app.safe.global)
* Open the link and make sure it loads the safe and txs properly
* The network requests should go to safe-transaction-`network name`
5. Repeat steps 1-4 for all networks
Also updated the safe link to point to the exact tx with deeplinking which was introduced recently
Example: https://app.safe.global/gor:0x5895fCf0A96a4d19E17d2dD759926d1A02781ef8/transactions/tx?id=multisig_0x5895fCf0A96a4d19E17d2dD759926d1A02781ef8_0x2f9eea9047c4d6547d7b0c883d1a4426b66f1907458d193dae5cab2fbe8d3290

Updated Safe urls to new endpoints

---

src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx

Fixes #1934
`ImportTokenModal` didn't check token existence by symbol and it was the cause of the bug

Import token from URL only when there are no tokens with same address and symbol

---

src/cow-react/api/gnosisProtocol/api.ts

For eip1271 orders, one can set a verification gas limit - the gas consumption limit - for the solidity call that verifies that an eip1271 order is valid.
The cost for ethflow orders, if quite low, as the implementation only needs to[ read one storage variable](https://github.com/cowprotocol/ethflowcontract/blob/d8cd52d3c178062ce9d2b311eb4d12f73d09837c/src/CoWSwapEthFlow.sol#L250). Hence, we said that we even allow a value of 0 in the backend - in order to also give a small subsidy.
For some more background see [here](https://cowservices.slack.com/archives/C035N0YEB6J/p1674992216205379)
Testplan:
Create ethflow orders on goerli and still see the orders going through.

Setting verificationGasLimit for ethflow orders

---

cypress-custom/integration/limit-orders.test.ts
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts

Test scenario:
1. Open limit orders page
2. Unlock the beta info screen
3. Pick sell token
4. Pick buy token
5. Input sell amount
6. Input buy amount
7. Click "Review limit order"
8. Compare entered values in the confirm screen
Also added fix to `useSetupTradeState.ts` for e2e tests. For some reason, the wallet provider for e2e tests sends irrelevant `chainId` at the beginning with empty `account`.

Limit order creating e2e test

---

src/cow-react/modules/limitOrders/containers/DeadlineInput/index.tsx
src/cow-react/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
src/cow-react/modules/limitOrders/pure/DeadlineSelector/index.tsx
src/cow-react/modules/limitOrders/pure/DeadlineSelector/utils.ts

PR on top of https://github.com/cowprotocol/cowswap/pull/1922
- Wiring up the picker with state
- Added error msgs for when:
- `< min date
- `> max date
- Unable to parse inserted date
- Deadline will only be updated if valid, even if input validation/picker is bypassed
⚠️ Error msg is in desperate need of styling. Will delegate that to Michel ;)
1. On limit orders, open the date picker and select `custom`
2. Play around with the custom date
3. Chose a date < 30min from now
4. Chose a date > 6 months from now

Wireup date picker

---

src/cow-react/modules/application/containers/App/index.tsx
src/custom/components/analytics/hooks/useAnalyticsReporter.ts

Not sure if this was my mistake or if this was excluded in some PR after this was implemented but this hook is missing and its not being called anywhere right now. 
The purpose of this hook is to set custom dimensions such as chainId and a walletName.
I've noticed today that custom dimensions are missing in google analytics dashboard so we should merge this ASAP.

Add analytics hook that will set dimensions

---

src/cow-react/modules/swap/pure/Row/RowDeadline/index.tsx
src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx
src/cow-react/modules/swap/pure/styled.tsx

Addresses feedback to change the `modified` text from being orange to a neutral (matching) color.
**NOW**
**AFTER**

change text color

---

public/index.html
src/cow-react/types.ts
src/custom/components/analytics/events/transactionEvents.ts
src/custom/components/analytics/hooks/useAnalyticsReporter.ts
src/custom/components/analytics/pixel/constants.ts
src/custom/components/analytics/pixel/facebook.ts
src/custom/components/analytics/pixel/linkedin.ts
src/custom/components/analytics/pixel/microsoft.ts
src/custom/components/analytics/pixel/paved.ts
src/custom/components/analytics/pixel/reddit.ts
src/custom/components/analytics/pixel/twitter.ts

Continues on top of https://github.com/cowprotocol/cowswap/pull/1977
Adds pixel tracking for Paved and Microsoft.
- when the page (url) is changed
- when the app is loaded
- when an account is connected
- when trade is posted
For more context [this is the document](https://docs.google.com/spreadsheets/d/1GFg-gXmBboLGLeLsTGA_7FxmuCB3P0xNbdwHhEEe7d4/edit?pli=1#gid=1015340718) where the events are defined
To test this check the requests in dev-tools Network tab
Paved
- when the app is loaded, filter by `search`
- when the account is connect, filter by `sign_up`
- when the order is placed, filter by `purchase`
Microsoft Ads
- when the app is loaded, I'm not really sure how to test this one but there should be one request with the `bat.bing.com ` filter
- when the account is connect, filter by …

Added Paved and Microsoft pixel tracking

---

public/index.html
src/cow-react/types.ts
src/custom/components/analytics/events/transactionEvents.ts
src/custom/components/analytics/hooks/useAnalyticsReporter.ts
src/custom/components/analytics/pixel/constants.ts
src/custom/components/analytics/pixel/facebook.ts
src/custom/components/analytics/pixel/linkedin.ts
src/custom/components/analytics/pixel/microsoft.ts
src/custom/components/analytics/pixel/paved.ts
src/custom/components/analytics/pixel/reddit.ts
src/custom/components/analytics/pixel/twitter.ts

Continues on top of https://github.com/cowprotocol/cowswap/pull/1976
Adds pixel tracking for Twitter and Reddit.
- when the page (url) is changed
- when the app is loaded
- when an account is connected
- when trade is posted
For more context [this is the document](https://docs.google.com/spreadsheets/d/1GFg-gXmBboLGLeLsTGA_7FxmuCB3P0xNbdwHhEEe7d4/edit?pli=1#gid=1015340718) where the events are defined
To test this check the requests in dev-tools Network tab
Twitter
- when the app is loaded, filter by `tw-oddz2-oddz8`
- when the account is connect, filter by `tw-oddz2-oddza`
- when the order is placed, filter by `tw-oddz2-oddzb`
Reddit
- when the app is loaded, filter events by `Lead`
- when the account is connect, filter by `SignUp`
- when the order is placed, filter by `Purchase`

Added Twitter and Reddit pixel tracking

---

craco.config.js
src/cow-react/index.tsx
src/cow-react/polyfills.ts

Polyfills were not included in the Cosmos build.
Actually, we use only one polyfill, for `window.Buffer`.
So I moved it to Webpack side and now it's included in Cosmos.

Fix Cosmos build

---

src/cow-react/modules/limitOrders/hooks/useGetInitialPrice.ts
src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts
src/custom/hooks/useFetchProfile.ts
src/custom/hooks/usePriceImpact/useFallbackPriceImpact.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/state/price/updater.ts

Tries to prevent to get the quotes when the tab/window is not active
It does it for:
- ABA updater
- Unfillable orders updater
- Limit Orders useFetchMarketPrice
- Limit Orders initial Price
Everything should work as before, but if you use another tab, it should stop doing quote requests

Don't update prices if not visible

---

src/components/analytics/index.ts

Fixes #1995 
Previously, GA test mode was being initialised when GA key could not have been found. Updated that to rely on NODE_ENV not being production.
https://cowservices.slack.com/archives/C0361CDG8GP/p1676378568049579

Change GA debug mode to rely on NODE_ENV

---

src/cow-react/modules/application/containers/App/Updaters.tsx
src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
src/cow-react/modules/swap/hooks/useFlowContext.ts
src/custom/hooks/useAppData.ts
src/custom/state/appData/AppDataInfoUpdater.tsx

Fixes #2019
The root of the problem is here:
https://github.com/cowprotocol/app-data/blob/main/src/utils.ts#L92
In general, the sequence of problems is long enough.
But, the `validateAppDataDoc` from `app-data` is designed to be called once.
Before the fix, we had a race condition and called it at least twice.

useAppData hook is designed for using only from an updater

---

src/cow-react/api/gnosisSafe/index.ts
src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
src/custom/state/gnosisSafe/updater.tsx

Fixes #1190
Uniswap `token.wrapped` throws an error when the network is not supported.

Check is network supported in Currency List component

---

src/cow-react/modules/account/containers/AccountDetails/index.tsx
src/cow-react/modules/wallet/api/hooks/useDisconnectWallet.ts

Abstract hook to disconnect. This hook hides the implementation details and provides a simple signature: it will return a callback `() => void`
This is used to reduce the dependencies in AccountDetails
Elena, not sure if these ones are worth testing individually. They will add work and I think is better to test in the top of the waterfall

[wallet-refactor-4] Disconnect hook

---

package.json
src/cow-react/api/coingecko/index.ts
src/cow-react/api/gasPrices/index.ts
src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/api/matcha-0x/index.ts
src/cow-react/common/utils/fetch.test.ts
src/cow-react/common/utils/fetch.ts
src/hooks/useENSAvatar.ts
yarn.lock

Adds exponential backoff to all relevant requests.
The strategy by default It will wait a maximum of ~102s maximum wait time. Wait time is 100ms * 2**(attempt), and it will do 10 attempts
The new util allows us to define another backoff strategy.
- Everything should work as before
- We should re-test the cases where before was failing. Hopefully, now, the app will backoff and wait until the problem is solved (re-attempting later)
- This means, that if the backend is returning some errors, it might take a bit more to fetch the information.

Exponential backoff

---

src/cow-react/common/utils/fetch.test.ts

It'd seem that we have used fetchWithBackoff incorrectly here, which made it so that our assumption of giving a numberOfAttempts was not being honored. This led to longer than expected execution (default being 10) and gave an obscure error.
I've fixed this via utilising fetchWithRateLimit. fetchWithBackoff is a no param singleton of fetchWithRateLimit, as such this should not make any difference.

Fixes unconfigured backoff limit parameter

---

src/cow-react/common/pure/Modal/ModalMod.tsx

https://github.com/reach/reach-ui/issues/536
After `reach-ui/modal` update we got a bug from it.
The new version of the modal disables all `focus` events inside the modal.
`dangerouslyBypassFocusLock` property allows disabling of that behavior.
1. Open wallet-connect modal
2. Use the search input

Fix focusing of search input in walletconnect modal

---

src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/hooks/useUpdateActiveRate.ts
src/cow-react/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx

Fixes #2040
The cause of the bug:
1. `InitialPriceUpdater` wrongly updated `activeRate` ([src](https://github.com/cowprotocol/cowswap/pull/2116/files#diff-5e4e0924caedfe8c669950e7c993b0e251527de25c387e98809e5aac8daccce2R40))
2. `useUpdateActiveRate` wrongly allowed updating of amounts event when the price was entered by user ([src](https://github.com/cowprotocol/cowswap/pull/2116/files#diff-2afd91a3dc661a99b1d19b819437d8a4dbf31b9d0ab25a1cf97b3d6c1829f602R36))
1. Please, pay attention on hte `set max` functionality

Don't update limit order amounts when price was entered by user

---

src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts
src/custom/state/enhancedTransactions/hooks/index.ts

Fixes #1638 #1847
`useTransactionAdder` didn't detect Gnosis when it's connected via WalletConnect and set the wrong type to transactions.
Because of it we got the wrong behaviour of pending txs monitoring

Fix detection of Gnosis transactions

---

src/cow-react/common/hooks/usePrice.ts
src/cow-react/modules/application/containers/App/Updaters.tsx
src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/hooks/useGetInitialPrice.ts
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx
src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.test.ts
src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.ts
src/cow-react/modules/orders/state/pendingOrdersPricesAtom.ts
src/cow-react/modules/orders/state/spotPricesAtom.ts
src/custom/state/orders/consts.ts
src/custom/state/orders/updaters/PendingOrdersUpdater.ts
src/custom/state/orders/updaters/SpotPricesUpdater.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/state/orders/utils.ts

Whole lot of changes
- Using spot price (non volume dependent) on table and for % difference calculations
- Added updater for fetching the spot prices, querying every 15s
- Doing a fancy calculation to get to the estimated execution price. See [here](https://www.notion.so/cownation/Execution-Price-Market-Price-90524299d1874a59bb34c658293a0316?pvs=4)
- Simplified how the % difference is calculated. Now it's based only on the estimated execution price and the spot price
Testing steps should be the same.
⚠️ Partial fills not supported!
⚠️ Still have not implemented tooltips/highlighting logic. Will be part of follow up PRs
Continuing addressing indicator status
Changes from previous:
- No longer using absolute percentage values
- When limit <= market price - use percentage as is
- When limit …

Limit UI prototype orders table 6 indicator status 2

---

src/cow-react/common/hooks/useRateInfoParams.ts
src/cow-react/common/pure/RateInfo/index.cosmos.tsx
src/cow-react/common/pure/RateInfo/index.tsx
src/cow-react/modules/account/containers/Transaction/ActivityDetails.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
src/cow-react/modules/limitOrders/hooks/useExecutionPriceFiat.ts
src/cow-react/modules/limitOrders/pure/ExecutionPrice/index.tsx
src/cow-react/modules/limitOrders/pure/ExecutionPriceTooltip/index.tsx
src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts
src/cow-react/modules/limitOrders/state/limitRateAtom.ts
src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts
src/cow-react/modules/limitOrders/utils/toFraction.ts
src/cow-react/modules/swap/pure/TradeRates/index.cosmos.tsx

Fixes issues with smart quote selection on orders table
Also fixed a typo across several files which was bothering me. Sorry about the noise 😬 
1. Place an limit order with COW/WETH, then another with WETH/COW
* Both should display in the list using COW prices in all price fields

Limit UI prototype fix smart quote on table

---

src/cow-react/common/utils/markets.ts
src/cow-react/modules/orders/state/spotPricesAtom.ts
src/custom/state/orders/updaters/SpotPricesUpdater.ts

This PR tries to make the creation of the keys for the CACHE deterministic. 
For that, I just created some convenient methods (`getCanonicalMarketKey` and `getCanonicalMarketChainKey`) in the `common` module, to create a key for a market with the commutative property. 
It will use lexicografic order to determine the first token. 
It applies this to the Market Price atom logics. So this PR in principle should reuse the price of the inverse markets. 
So if you try to store tokenA/tokenB, and you try to get the price tokenB/tokenA, it will understand that you can use the other price and invert it. 
It adapts the updater, and simplify it by extracting two custom hooks
Make sure i didn't break anything. Probably nice test is to see that if you have in the order list two orders of the same …

Make deterministic and simplify updater

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx
src/cow-react/modules/orders/state/spotPricesAtom.ts

This PR simplifies the dumb component so it doesn't need to have all the market prices. 
The components receive a "dumb function" that let the component get the market price. 
Creates a new hook next to the atoms which would expose the function to get the market price given a market. This time, it won't need to be provided with all the list of markets.
Nothing should have changed

Simplify getSpotPrice

---

src/cow-react/modules/limitOrders/utils/calculateAmountForRate.ts
src/cow-react/utils/fractionUtils.ts
src/custom/state/orders/priceUtils.ts
src/custom/state/orders/updaters/SpotPricesUpdater.ts

This PR fixes the issue with the decimals in the market price
The issue was because, the API returns the price in units (natural to the user). For example, 1.1/1 for USDC-DAI price
However, Uniswap SDK needs in the `Price` class we are using to be aware of the decimals. And they understand the ratio is in atoms, not in units.
For solving it, i created a convenient util, and reused some similar logic we were using for adapting Fractions.
Before:
After (pls ignore the light theme change 😂, just the numbers):
Trade DAI to USDC and check the issue is solved

Fix market price decimals

---

src/cow-react/common/pure/TokenAmount/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx

- Adds column 'Market price'
- Adds column 'Executes at'
- Adds column 'Filled'
- Small order warning banner + column indicator (+ tooltip)
- Tooltip hover on 'Executes at' price for open orders, indicating how close to executing the order is.
- Dot indicator for 'how close to executing' the order is.
- Explainer banner for Dot indicator functionality + column header tooltip
- Misc. style improvements on the order table layout.
- Adding back a close-able info banner below the limit order widget container.

🎨 Limit UI iteration (styles & functionality)

---

src/cow-react/common/utils/markets.ts
src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx
src/cow-react/modules/limitOrders/utils/calculateAmountForRate.ts
src/cow-react/modules/limitOrders/utils/calculateFractionLikePercentDifference.ts
src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.test.ts
src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.ts
src/cow-react/modules/limitOrders/utils/calculatePriceDifference.test.ts
src/cow-react/modules/limitOrders/utils/calculatePriceDifference.ts
src/cow-react/modules/orders/state/pendingOrdersPricesAtom.ts
src/cow-react/modules/orders/state/spotPricesAtom.ts
src/cow-react/utils/fractionUtils.ts
src/cow-react/utils/rawToTokenAmount.ts
src/custom/constants/index.ts
src/custom/lib/utils/tryParseCurrencyAmount.ts
src/custom/state/orders/updaters/SpotPricesUpdater.ts
src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
src/custom/state/orders/utils.ts

Tooltips wired up for `Executes at` column
Cases:
Shown when current display is the regular for the market
Shown when currently display is inverted
Tooptip will display `Unlikely to execute due to high fee`
Tooltip will display `Will execute soon!`
1. Play around with different pairs and amounts to trigger the messages above

Feature/limit UI update - wire up tooltips

---

src/cow-react/common/pure/TokenAmount/index.tsx

1. Check the high fee warning on a pending limit order
* Token symbol color should match the surrounding text
* It should NOT break any symbols displayed in the app

Fix white token symbol on black color text

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx

Do not show high fee warning on limit orders table for market orders
1. Place the smallest swap order that you can
2. Go to limit orders table
* The order should NOT have the high fee percentage warning displayed for limit orders
3. Place the smallest limit order that you can
* (Assuming the fee is >10% of the sell amount) the order should have the high fee percentage warning

Do not show high fee warning on limit orders table for market orders

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx

Inverting all prices on order row when any price is clicked
https://user-images.githubusercontent.com/43217/226932693-3bf83069-1b44-4516-8920-41bd2d613ee9.mov
1. On limit orders page, click on any price on a pending order
* Prices should invert when any is clicked
2. On limit orders history page, click on any price
* Prices should invert when any is clicked

Inverting all prices on order row when any price is clicked

---

cypress-custom/support/ethereum.ts
cypress.config.ts

Fixes issues with not being able to run cypress locally by adding a default private key, if nothing is found in the environment.
This seems to be the approach uniswap uses as well (without environment secret keys even).
1. Run `yarn cypress`
2. Select an E2E test
3. You should be able to see it running instead of an error.
Same file on uniswap: https://github.com/Uniswap/interface/blob/main/cypress/support/ethereum.ts

Add default test private key for local development purposes

---

src/custom/components/analytics/events/listEvents.ts
src/custom/components/analytics/events/otherEvents.ts
src/custom/components/analytics/events/settingsEvents.ts
src/custom/components/analytics/events/swapEvents.ts
src/custom/components/analytics/events/themeEvents.ts
src/custom/components/analytics/events/transactionEvents.ts
src/custom/components/analytics/events/walletEvents.ts
src/custom/components/analytics/hooks/useAnalyticsReporter.ts
src/custom/components/analytics/index.ts
src/custom/components/analytics/provider/index.ts
src/custom/components/analytics/types.ts

- adds a new GA event when user lands on swap.cow.fi any page, called `Initial landing on swap.cow.fi` and it is fired only once the app is loaded
- also adds some refactoring to make code better
- download [GA debug extension on Chrome](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)
- turn it on
- open the demo app
- open dev tools and go to Console tab
- you should be able to see `Initial landing on swap.cow.fi` event dispatched in the console

Refactor and add initial swap.cow.fi landing event

---

cypress-custom/integration/search.test.ts
src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx

Fixes #163 
Token search is now working when there are trailing spaces. The issue was due to address check failing with the space, so we are now trimming it.
1. Open swap page
2. Click on a currency name to search
3. Enter an address with a trailing or leading space. (e.g. on Goerli, this should give you DAI  0xdc31ee1784292379fbb2964b3b9c4124d8f89c60 )
4. It should show still results.

Fix trailing spaces breaking search

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/cow-react/modules/limitOrders/utils/calculatePercentageInRelationToReference.ts

Implements the fee warning banner on limit orders widget
Currently displayed when current estimated fee > 10% of selected sell amount
1. On limit orders page, select a pair
2. Pick a small sell amount (you might need to adjust for the network conditions)
* The warning will be shown when current fee is > 10% of selected sell amount

Feature/limit UI - Small sell amount/high fee warning on limit orders widget

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
src/cow-react/modules/limitOrders/utils/calculatePriceDifference.test.ts
src/cow-react/modules/limitOrders/utils/calculatePriceDifference.ts
src/cow-react/utils/amountFormat/index.ts
src/custom/state/orders/utils.ts

Fixes #2164 
Should no longer show prices with negative values
1. Place one order with a tiny sell amount
2. Wait for the fees to higher than the sell amount
* You should NOT see a negative price

Feature/limit UI update - #2164 negative price

---

src/cow-react/modules/limitOrders/containers/SettingsWidget/styled.tsx

Closes #2185 
Cow icon now aligned on both forms
https://user-images.githubusercontent.com/43217/228315098-215075f4-58c1-4e00-918d-ed52b02c7bdc.mov
1. On limit orders form, turn on expert mode
* Expert cow emoji should not over extend

Adjusting positioning of expert mode icon for limit orders

---

src/cow-react/modules/limitOrders/pure/ReceiptModal/FilledField.tsx

Fixed bought token symbol for limit orders receipt
1. On a filled BUY limit order (probably should work for SWAP, but I haven't tested), open the receipt modal
* The `filled` row should show the correct token symbols

Fixed bought token symbol on limit orders table receipt

---

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts

Minor change, updating the button with text appropriated for expert mode, as there's no review modal when it's enabled
1. Turn expert mode on
2. Fill in the form
* The button will show `Place limit order`
3. Click on `Place limit order` button
* It should trigger the wallet signature
4. Turn export mode off
* The button will show `Review limit order`
5. Click on `Review limit order` button
* It should show the review order modal

Showing a different button text when expert mode is enabled

---

src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.ts

Fixes #2215
Behavior before the fix:
The entered recipient address value persisted always.
Behavior after the fix: 
1. Recipient value resets before each limit orders page opening
2. Recipient value resets after each trade
1. Open limit orders page
2. Enter any address to the recipient field
3. Go to limit orders page
4. Go to limit orders back
1. Open limit orders
2. Enter any address to the recipient field
3. Sign and send order

[Limit orders] Reset recipient value before each page opening and after each order placement

---

src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx

| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/43217/229127607-8d30c862-e326-40ea-836c-a85ffb7b39bd.png) | ![image](https://user-images.githubusercontent.com/43217/229127225-7d93ad99-5ee2-41e4-9653-aa15498eae30.png) |
1. Place an order
2. Have it fill less than 100%
3. Cancel it
* Status on the history tab should be `cancelled` instead of `partially filled`

Cancelled status takes precedence on limit orders table

---

src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
src/custom/state/swap/hooks.tsx

Fixes  https://github.com/cowprotocol/cowswap/issues/2228
For SWAPS fix some edge case which was not enabling the button to post an order if you had not specified the Recipient (after you have specified one)
It also solves an issue for the LIMIT ORDERS which would show an error in the price estimation. The error was basically for having the Recipient empty. So I gave more prior to display the recipient error.
I change slightly the message from `Enter a recipient` to `Enter a valid recipient` when the recipient is wrong
1. SWAP/LIMIT orders. Try the issues in #2228

Improve error on empty eth address

---

src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx

Show `Avg. execution price` on receipt for partial fills
|Before|After|
|-|-|
| ![image](https://user-images.githubusercontent.com/43217/229131608-f96405bd-5556-46e1-a5f1-f1501a3c7258.png) | ![image](https://user-images.githubusercontent.com/43217/229131479-e08d7ce3-484d-486e-9205-e540527ab27b.png) |
1. Open a partial fills order receipt
* You should see the field `Avg. execution price`

Showing custom execution price label on receipt for partial fills

---

src/custom/state/orders/utils.ts

Simply allowing partial fills to get the estimated execution price
It still uses `fill or kill` estimation method, so might not be accurate
1. Place partial fill limit order
* Estimated execution price should be calculated
Same caveat applies as for fill or kill limit orders

Estimated execution price for partial fills - minimal

---

src/cow-react/modules/limitOrders/hooks/useOnCurrencySelection.ts

Fixes #2224
`@cow/modules/trade/hooks/useOnCurrencySelection` contains the special hook `useResolveCurrencyAddressOrSymbol` that helps us to avoid token symbols collisions.  
But, it was overridden by a wrong value (always currency symbol) in `useOnCurrencySelection()`

[Limit orders] Removed excessive currencyId update

---

src/cow-react/modules/application/containers/TradeWidgetLinks/index.tsx
src/cow-react/modules/swap/hooks/useDetectNativeToken.ts
src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx
src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
src/cow-react/modules/trade/hooks/useOnCurrencySelection.ts
src/cow-react/modules/trade/hooks/useTradeState.ts
src/custom/components/Header/index.tsx

Refactored `useTradeState()` to make it return type simpler

Refactor useTradeState() return type

---

src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts

Fixes #2021
The bug was introduced here: https://github.com/cowprotocol/cowswap/pull/1942/files#diff-476acfe17c5b8c2a3ba90bcccd7dc4c43ca0b62c5971b172351d2223685ec8b3R64
`chainIdFromProviderWasChanged` was not changed because of it bug, consequently, `chainId` didn't change in URL and the Swap form didn't change. 
I'm very sorry for `useSetupTradeState` hook :( We should refactor it some a day.
Important! This change shouldn't break E2E tests.

Fix network switching detection

---

src/cow-react/modules/wallet/api/pure/ConnectWalletOption/index.tsx
src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
src/cow-react/modules/wallet/api/pure/WalletModal/styled.tsx

Just a suggestion for wallet modal UI improvements

Wallet modal UI improvements

---

src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
src/cow-react/modules/wallet/api/pure/ZengoBanner/index.tsx
src/cow-react/modules/wallet/api/pure/ZengoBanner/styled.ts
src/cow-react/modules/wallet/web3-react/containers/WalletModal/index.tsx

Adds a ZenGo wallet banner to wallets modal if the user didn't connected his account.
Desktop - light
Desktop - light
Mobile
- open wallets modal
- makes sure it looks ok on all devices and screen sizes
- it should be hidden once the wallet is connected

Add ZenGo wallet banner

---

cypress-custom/integration/search.test.ts
src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx

Fixes #2181 
Before this change, we have been showing import rows as opposed to our own currency search results, especially in the case of an address search.
With this change, we will check whether or not we have our own results first - and if we do, we will show that. This fixes showing unnecessary import rows.
1. Go to swap
2. Switch to Goerli
3. Click on a currency to open currency search modal
4. Search for 0xdc31ee1784292379fbb2964b3b9c4124d8f89c60
5. This is a known currency on Goerli (DAI). It should not have an import button.
6. Search instead for 0x82f418D75F836385092eB8EaBf1608cd4b91961c
7. This is an unknown currency on Goerli (stETH). It should have an import button.

Don't show import if we have a token for you

---

src/cow-react/modules/swap/helpers/getSwapButtonState.ts
src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
src/custom/hooks/useRefetchPriceCallback.tsx

Context: https://cowservices.slack.com/archives/C036G0J90BU/p1680169031535319
Basically, there's some cases where we allow users to submit orders with a "fast" price from the quote endpoint. 
In this PR we are displaying "Hang in there. Calculating best price..." state until we get the best price.
1. Open vercel from https://github.com/cowprotocol/cowswap/pull/2255
2. Open swap page, setup a trade, run `localStorage.setItem('delayBestQuote', '200000')` in console and reload the page
3. Keep developed tools open in network tab
4. Just after page load do a swap
5. Open vercel from the current PR
6. Open swap page, setup a trade, run `localStorage.setItem('delayBestQuote', '10000')` in console and reload the page
7. Do a swap when it's possible
8. After all tests run …

Disable Swap form while loading best price

---

src/cow-react/api/gnosisProtocol/api.ts
src/cow-react/api/gnosisProtocol/hooks.ts
src/cow-react/api/gnosisProtocol/index.ts
src/cow-react/common/utils/fetch.ts
src/cow-react/modules/limitOrders/hooks/useGetInitialPrice.ts
src/cow-react/modules/wallet/web3-react/connection/trust.tsx
src/custom/utils/trade.ts

The strategy was accidentally lost after a major SDK update.
Fixes #2280
For api.cow.fi requests should work as before: https://github.com/cowprotocol/cowswap/pull/2069

Apply back-off strategy for order-book API calls

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts

Fixes #2296 
1. On limit orders page, turn on expert mode
2. While not connected, change the partial fills setting
* Order type should be updated immediately
* Same thing while connected

Added settingsState to limit orders memo component props

---

.github/workflows/ci.yml
.github/workflows/vercel.yml

Simply adding launch darkly env var to vercel build
Simple version of https://github.com/cowprotocol/cowswap/pull/2310 to fix the immediate issue
Forcefully deploying dev env for testing
1. Dev should work and use dev launch darkly's key

Fix launch darkly env var

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx

- Minor style update for the 'unfillable' label

Modify styles unfillable label

---

package.json
src/cow-react/common/utils/fetch.ts
src/cow-react/modules/limitOrders/hooks/useGetInitialPrice.ts
yarn.lock

Fixes #2311
Relies on changes made in https://github.com/cowprotocol/cow-sdk/pull/120
As retry function has the error injected (i.e. not the whole response but just the body in this case) we need the enriched version, where we can extract this information.
1. Open swap
2. Change to Goerli
3. Pick ETH/ZRX pair
4. Enter an amount
5. Low liquidity error should appear, without waiting a minute long

Add retry limitations based on rawApiError

---

cypress-custom/integration/swap.test.ts
cypress-custom/integration/swapMod.ts

Making Cypress green again
2 things:
- We were waiting 2s for the prices, but it was not enough
- Expert mode doesn't have the recipient any more
I explained in the code with some comments the changes
The 2 about fixed the issues, additionally i added a basic test for the recipient

Fix issue accepting fees and with recipient

---

src/cow-react/abis/types/index.ts
src/cow-react/modules/wallet/web3-react/connection/index.tsx
src/cow-react/modules/wallet/web3-react/connection/keystone.tsx

Small PR to hide the Tally wallet for now as requested by Biz Dev.
We might enable this wallet in the future so we want to keep the rest of the code.

Hide tally wallet for now

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx

Closes #2291 
https://user-images.githubusercontent.com/43217/233088316-0725a627-ac12-4f55-8604-5e39f84d8725.mov
1. Block `native_price` requests in the network tab
* Should not show a tooltip in that case

Only show executes at tooltip if there's a value

---

src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.test.ts
src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts

I use 5% in the original example.
Also, in the implementation I was using 0.5% instead of 0.05%
Now with the correct values:
Closes #2268 
Check there's at least 0.05% of balance/allowance to consider partial fill order with enough balance/allowance
BAT balance is 1, order unfillable
BAT balance is 731 (> 0.05% of sell amount), warning not displayed
1. Place order
2. Remove sell balance
* Warning displayed
3. Add at least 0.05% of sell amount
* Warning not displayed
4. Repeat steps with allowance

Check at least 0.05% balance/allowance for warning

---

src/cow-react/common/hooks/useCancelOrder/__snapshots__/useSendOnChainCancellation.test.ts.snap
src/cow-react/common/hooks/useCancelOrder/useSendOnChainCancellation.ts
src/custom/hooks/useRecentActivity.ts
src/custom/state/enhancedTransactions/actions.ts
src/custom/state/enhancedTransactions/reducer.ts
src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx

Fixes #2325
Following the example of `eth-flow` cancellation added conditions for on-chain cancellation transactions.

Fix on-chain cancellation tx notifications

---

src/cow-react/modules/wallet/api/pure/ZengoBanner/index.tsx
src/state/application/updater.ts

Small changes fixing eslint warnings:
```
WARNING in [eslint] 
src/cow-react/modules/wallet/api/pure/ZengoBanner/index.tsx
Line 13:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
src/state/application/updater.ts
Line 58:6:  React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

Fix eslint warnings

---

src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
src/cow-react/modules/limitOrders/pure/Orders/index.tsx

fix(limit-orders): enable orders selection only when off-chain signing is supported

---

src/constants/lists.ts

Reference: https://github.com/cowprotocol/cowswap/pull/2345/commits/5ba7bbd0e227f8f9b35ad006434f1b0c3e51ddbf
Since the `custom` folder is deleted, `goerli-token-list.json` file was moved to `src/tokens`:
https://raw.githubusercontent.com/cowprotocol/cowswap/develop/src/tokens/goerli-token-list.json
Just after the next release on prod, the previous link will become invalid and the token list on georli won't be loaded.
To avoid this, the link to the goerli tokens list is changed.

chore: change goerli tokens list url after removing custom folder

---

.github/workflows/kanban-in-progress.yml
.github/workflows/kanban-review.yml

In some cases, it's ok when a PR doesn't have linked issues and we shouldn't add a noise to the build checks.

ci: don't fail kanban actions when there are no linked issues

---

src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx

fix(limit-orders): don't display trade related warnings when wrap/unwrap

---

src/components/TransactionConfirmationModal/index.tsx

- Updates the audit URL in the token approval modal

fix: change audits url in approval modal

---

src/state/price/updater.ts

Fixes #2374
I'm not sure this is even needed because [this](https://github.com/cowprotocol/cowswap/pull/2254/files) seems to do exactly what we wanted, but just in case we can also do this, and as far as I could see this will show `Hang in there...` until the best quote is loaded

fix: show hang in there until best quote is loaded

---

src/state/orders/utils.test.ts

The test fails occasionally as it depends on Date.now() and the interval was too close to the boundary.
A more permanent solution would be to mock Date.now() but I hope this suffices for now
Unit tests should pass

test(classifyOrder): reduce time interval in tests

---

src/cow-react/modules/wallet/web3-react/connection/index.tsx

Fixes the issue found by @MindyCoW in one user session
The issue seems to be that when `window.ethereum.isCoinbaseWallet` is `true` we don't show Metamask option and we don't want that.

Fix Metamask issue

---

.prettierignore
CHANGELOG.md
src/components/Header/URLWarning/index.tsx

Depends on https://github.com/cowprotocol/cowswap-banner/pull/1
This PR changes the source from which we fetch announcements from the config branch in this repo to a separate repository to which we can give the entire team unrestricted access. This will allow us to act quickly and without occupying technical ressources (which will be busy with debugging) in the case there is an outage or issue with the product.
As a follow up I will I update the instructions in https://www.notion.so/cownation/Set-Announcement-Warning-Banner-Message-e7f71d85a1d34d29ba8a41c8c1acceba and remove the files in the configuration branch after this change is released into production (ideally we release it relatively quickly after merging this PR to reduce the amount of configuration drift between prod and barn and …

Change announcement banner source to separate repository

---

src/cow-react/modules/trade/utils/parameterizeTradeRoute.ts

Fixes #2440 
Try to use `0x5b6c539b224014a09b3388e51caaa8e354c959c8` token in mainnet

fix: fix token with special symbols

---

cypress-custom/integration/limit-orders.test.ts
cypress-custom/integration/swap.test.ts
cypress-custom/support/commands.d.ts
cypress-custom/support/commands.js
src/components/Header/index.tsx
src/cow-react/modules/swap/hooks/useSwapRawState.ts
src/state/swap/actions.ts
src/state/swap/hooks.tsx
src/state/swap/reducer.ts

Closes #2449 
Fix `sellAmount` and `buyAmount` url params for Swap
1. On Swap, make sure you have a sell token, insert in the url after the token(s): `?sellAmount=1`
* Sell amount input should be set to 1
2. On Swap, make sure you have a buy token, insert in the url after the token(s): `?buyAmount=4`
* Buy amount input should be set to 4
This change touches chainId/recipient (from URL only) related areas, so we also need regression tests for that
Added new cypress tests for both swap and limit orders to check for `sellAmount` and `buyAmount` behaviour
The issue was introduced on https://github.com/cowprotocol/cowswap/pull/2317
When the URL params are set, the state was being updated properly [here](https://github.com/cowprotocol/cowswap/blob/1df31149f10cce2e12d81e23e4f0b3e6b5f9467c/src/cow …

fix(swap-url-amounts): fix sellAmount and buyAmount url parameters for SWAP

---

package.json
src/cow-react/modules/utm/hooks.ts
src/cow-react/modules/utm/state.ts
src/hooks/useAppData.ts
src/state/appData/AppDataInfoUpdater.tsx
src/utils/appData.ts
yarn.lock

This PR it's the third an last PR from the series to add UTM codes in on-chain data.
Previous PRs:
- 1/3: cowprotocol/app-data#25 
- 2/3: https://github.com/cowprotocol/cowswap/pull/2453
This PR will include the UTM data into the document that is attached to the order. This way, its possible to attache UTM campaign codes to ochain data
There's an option now to provide some URL parameters so they can be attached to next future trades.
It will be attached as long as the user don't delete the `localStorage` from their browser.
All the parameters are optional, and we should be mindful that creating too many different variation will create more app-data codes, making things harder to track, so this should not be abused
Here is an example …

feature: Include UTM codes into onchain data

---

src/components/analytics/hooks/useAnalyticsReporter.ts
src/components/analytics/provider/index.ts
src/components/analytics/types.ts
src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md

Adds functionality to track user address as a dimension and also as user id.
The weird value ``"${account}"`` is because in google analytics it will be parsed as a number if we just pass the `account`
The way I tested this is by GA debug extension, there should be dimension4 in events once you connect your wallet
And also in the GA console

feat: add account address to ga tracking

---

src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
src/cow-react/modules/swap/hooks/useSwapButtonContext.ts

Closes #1594 
Fixed issue with approvals on SWAP for BUY tokens
1. With a sell token with a partial approval (In this case, approved `4`)
2. Input a buy amount that results in selling more than the approved amount
* You should see the approve button
3. Input a buy amount that results in selling less than the approved amount
* You should not see the approve button
For sanity, check the same for sell orders:
4. Input a sell amount > approved amount
* You should see the approve button
5. Input a sell amount <= approved amount
* You should not see the approve button
There are no changes to Limit orders flow

fix(approval-for-swap-buy-orders): use actual input amount for calculating approval needed

---

src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx

Made limit orders table warnings order type agnostic
From item 1 in https://github.com/cowprotocol/cowswap/pull/2462#issuecomment-1549553458
1. Place a swap order and open limit orders page
* Order should be visible as pending in the table
2. Remove balance
* Low balance warning should be displayed without mentioning `limit`
3. Remove approval 
* Low approval warning should be displayed without mentioning `limit`
4. Repeat steps with limit order
* Result should be the same

chore: make limit orders table warnings order type agnostic

---

src/cow-react/common/pure/WarningBanner/banners.tsx
src/cow-react/common/pure/WarningBanner/index.tsx
src/cow-react/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
src/cow-react/modules/swap/containers/SwapWidget/index.tsx
src/cow-react/modules/swap/pure/warnings.tsx

- Using the latest content from [figma](https://www.figma.com/file/pYXF21s8v1S1LfxpWvudbM/2023---TX-Bundling-v1?type=design&node-id=0-1&t=AgeIUSNIEmrgiaSv-0)
- Unified into a single component
- Improved (a bit) the looks, but could still use some help
Show (a terribly looking) warning banner on Swap and Limit
Hoping to make it so ugly it hurts, and then @fairlighteth can help out 😬 
- This PR is meant as a placeholder for where to display, and the logic to when to display it
- Text is obviously not final, happy to update
1. On Safe, load app as a Safe app
2. On Swap, pick token that needs approval
* Should see the (horrible) banner
3. On Limit, pick token that needs approval
* Should see the (horrible) banner
4. Repeat on Expert mode
* Should have the same result
5. Non bundle txs should …

feature(tx-bundling): warning banner

---

README.md
docs/architecture-overview.drawio.svg
docs/architecture-overview.md

Moves the diagram from:
https://github.com/cowprotocol/cowswap-diagrams/pull/1
The idea is to have it closer to the code. This way we can maintain easily the module diagrams, and the overall. 
https://github.com/cowprotocol/cowswap-diagrams will contain broader diagrams or initiatives and RFCs.
- Review diagram 
- Review readme (let me have some TODOs there, as I will want to do more PRs soon)
https://github.com/cowprotocol/cowswap/blob/overall-architecture/docs/architecture-overview.md

docs: create overall architecture

---

src/legacy/components/swap/ConfirmSwapModal/index.tsx
src/modules/swap/hooks/useFlowContext.ts

Closes #2483 
Fixes approval for tx bundling buy orders 
1. Load as Safe app
2. On Swap, pick sell token which is partially approved
3. Input buy token amount in a way that: 
1. the sell amount is less than the approved amount
2. the max amount is more than the approved amount
* You should see the bundling label
4. Moving forward with the tx, Safe modal should appear
* It should be a bundle tx
* Sell orders should work as before
* Non bundling txs should work as before
- Limit orders are not affected as they don't have slippage

fix(tx-bundling): fix tx bundling buy order approval

---

src/cow-react/common/pure/TokenAmount/index.tsx
src/cow-react/utils/amountFormat/index.test.ts
src/cow-react/utils/amountFormat/index.ts

> Related to https://github.com/cowprotocol/cowswap/pull/2502
This PR fixes the issue reported by @MindyCoW regarding a wrong price when selling WETH.
The issue was on the formatting logic. It had a broken logic on what to do when there is a carry over of the remainder. 
For example, for `18,499.99999999` as in the example, the rounding for 6 decimals will be `18,500.000000`.
In the logic, it handles separately the quotient and reminder. 
The remainder is expressed in a decimal format, i.e. 0.99999999 in this case
When rounding UP --> 1.00000000
Then we arrive to the broken logic! we where returning this value (this is why we saw a price of 1).
Detect when there's a carry over, and add it to the quotient. 
Before:
First fix (did the trick, but apparently we had an issue with clearing …

fix: formatting issue breaking when reminder carries over

---

src/cow-react/abis/types/index.ts
src/cow-react/common/services/getQuoteCurrency/index.ts
src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts
src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts
src/hooks/usePriceImpact/useFallbackPriceImpact.ts
src/utils/price.ts

Fixes #2467, #2510
The function `calculateFallbackPriceImpact` throws an error when `initialValue` equals `"0"` (because of the division on zero).
Since the function is called only from `useFallbackPriceImpact` hook, the check for `!== "0"` is added here.
I was able to reproduce it only when applied the issue reporters `localStorage` snapshot.
My assumption is:
- the reporter has cached some `wrong values` in his `localStorage`
- those `wrong values` influence on price impact calculations and cause calling `useFallbackPriceImpact` (normally it shouldn't be called, since it's a fallback)
- `calculateFallbackPriceImpact` didn't consider a case when `initialValue` is zero as string
UPD:
Elena found one more issue related to `"0"` value: …

fix: fix app crashing while calculating price impact

---

src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts

Fixes #2478
Before the fix `useSetupTradeState` hook didn't consider the case when a user initiated a network change and not finished it.
Related to: #2317

fix(trade): ignore only chainId in URL changes when network change in progress

---

src/common/pure/InlineBanner/banners.tsx
src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
src/modules/swap/containers/SwapWidget/index.tsx
src/modules/swap/pure/warnings.tsx
src/modules/wallet/web3-react/hooks/useWalletMetadata.ts

Adding a banner for Safe wallets connected via WC when doing approvals
| swap | limit |
|-|-|
| ![Screenshot 2023-05-19 at 13 54 44](https://github.com/cowprotocol/cowswap/assets/43217/38e6038e-d5fb-4bca-9c8e-80f2ca38d436) | <img width="486" alt="image" src="https://github.com/cowprotocol/cowswap/assets/43217/ebcf451e-be46-4cc5-98b5-50d2432d58e6"> |
1. Connect to Safe via WC (desktop, mobile, etc)
2. Pick as sell token one that needs approval
* The info banner like in the imgs above should be displayed
* The link should open in a new page
* The link should lead to Safe App display page
* Should behave the same with Swap and Limit
* Should NOT show the banner when approval is not needed
* Should NOT show the banner when connected via any other mean/wallet

feat(tx-bundling): add banner when approving for Save via WC

---

src/common/hooks/useShouldZeroApproveLimit.ts
src/common/hooks/useShouldZeroApproveSwap.ts
src/common/pure/ZeroApprovalWarning/ZeroApprovalWarning.tsx
src/common/state/useZeroApprovalState.ts
src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx

Fixes #2506 
Adds zero approval flow to limit orders.
1. Go to CoW Swap on Goerli,
2. Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Open Limit orders page
6. You should have the two step approval flow
7. This flow should not be shown if it is not necessary (i.e. most other tokens, if you have enough USDT allowance to begin with etc.)

feat(usdt-approval): :sparkles: add zero approval flow to limit orders

---

src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
src/modules/advancedOrders/hooks/useAdvancedOrdersRawState.ts
src/modules/advancedOrders/state/advancedOrdersAtom.ts
src/modules/limitOrders/state/limitOrdersRawStateAtom.ts
src/modules/trade/hooks/useBuildTradeDerivedState.ts
src/modules/trade/types/TradeDerivedState.ts
src/modules/trade/types/TradeRawState.ts
src/modules/tradeQuote/hooks/useQuoteParams.ts

Removes `typedValue`
Updates `useQuoteParams` to use `inputCurrencyAmount` or `outputCurrencyAmount` instead of `typedValue`

feat(twap-orders): refactor of quote (2)

---

src/common/hooks/useShouldZeroApproveSwap.ts

Fixes #2521
Swap specific zero approval checker was not relying on slippage adjusted amounts. Updated that part of the logic to make it work for both sides of the flow.
1. Go to CoW Swap on Goerli
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Go to swap
5. Specify a Buy order: Enter an amount into the Buy field that makes USDT amount higher than the approval amount (for example 10 USDT)
6. You should see zero approval warning and flow

fix(usdt-approval): :bug: fix swap zero approvals ignoring buy flow

---

src/common/hooks/useShouldZeroApprove/shouldZeroApprove.ts
src/common/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
src/modules/limitOrders/services/safeBundleFlow/index.ts
src/modules/operations/bundle/buildZeroApproveTx.ts
src/modules/swap/services/safeBundleFlow/index.ts

Fixes #2508
This refactors parts of should zero approve logic and adds a zero approve transaction to the bundled transactions when using safe, as needed.
As bundled transactions don't prompt user twice, we show the warning but not the modal.
1. Open the CoW Swap app inside a Goerli safe
2. Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Open Swap orders page
6. Press on the Approve and Swap button
7. You should expect to see in the bundle two approvals and a warning beforehand.

feat(usdt-approval): ✨ add zero approval flow to safe bundles

---

src/common/containers/ZeroApprovalModal/ZeroApprovalModal.tsx

Fixes #2522
Missing explicit modal close logic. Added a state variable to also check for to not show modal when not desired.
1. Go to CoW Swap on Goerli,
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Open Swap orders page
6. Press on the Approve button
7. Try closing the Reset modal
8. It should be possible.

fix(usdt-approval): :bug: fix modal not dismissing when close is clicked

---

src/common/hooks/useApproveCallback.ts

Fixes #2534 
1. Go to CoW Swap on Goerli,
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Open Swap orders page
6. Press on the Approve button
7. Sign the reset approval TX in the wallet and wait till the TX is executed

Fix message for revoke

---

src/common/hooks/useZeroApprove.ts
src/common/utils/pollUntil.ts
src/common/utils/wait.ts

Fixes #2532
Safe has an issue with wallet connect where when we send two transactions back to back, they repeat the nonce, causing transaction to fail.
This change introduces a fix by;
* Check if we are dealing with a safe wallet in wallet connect
* If so, poll for safe transaction execution every second
* Proceed only when this happens
1. Open CoW Swap
2. Connect to the Safe using WC option
3. Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Approve or trade to have some left over approvals (for example 5 USDT)
6. Press on the Approve button and run TX
7. Second tx should not fail.
https://github.com/safe-global/safe-wallet-web/issues/2034 …

fix(usdt-approval): 🐛 fix wallet connect with safe causing same nonce to appear twice

---

src/common/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
src/lib/hooks/swap/useSwapApproval.ts
src/lib/hooks/useApproval.ts

Fixes #2538
It was a bit hard to debug this one, but here are the conclusions of what was happening:
- The check for the `shouldZeroApprove` was dependant on `approvalState` 
- When the user modifies the approval to set a number below the trade side, we actually don't change state. We where `NOT_APPROVED` when we where 0, we are still when we are 5 (cause we try to sell 20)
- This don't trigger the `useEffect` that would recompute the need of resetting the allowance
Consecuence:
- The app thinks we didn't approve, but we don't need to reset
- Next approval will be a failed transaction
Fix
- i just made the hook to return both the allowance and the state
- This way, the hook will return a new object when the user changes its allowance
1. Go to CoW Swap on Goerli,
2. Use USDT …

fix: fix approval edge case

---

src/common/hooks/useShouldZeroApprove/shouldZeroApprove.ts

Fixes #2548
Issue was caused by `toExact` method having some decimals left at the end, even though we multiply the `amountToApprove` with `10 ** decimals`.
Replacing that with `toFixed(0)` solves this issue.
1. Open cow swap
2. Partially approve a token (any, not USDT). F.e. approve 1 WETH
3. Select WETH as a sell token
4. Select a but token, an amount to BUY --> value in the Sell field should be >1
5. Check the Swap form
6. Check the same steps for the Limit orders form

fix(usdt-approval): :bug: fix amountToApprove having a non bigint number

---

src/modules/limitOrders/services/tradeFlow/index.ts
src/modules/swap/services/safeBundleFlow/index.ts
src/modules/swap/services/swapFlow/index.ts

Continuation of https://github.com/cowprotocol/cowswap/pull/2462
Applying the same hiding logic to:
- Safe bundle flow for SWAP
- Regular SWAP presign
- Regular LIMIT presign
1. Load app as Safe app, 
2. Configure a short expiration time (5min)
3. Pick sell token that needs approval
4. Go all the way until Safe confirmation modal is displayed
5. Cancel tx
* There should not be a pop up nor COW sound
* Order should not be pending in presign state
6. Open Explorer and look for you account
* There should be a pending presign tx
7. Wait for the order to expire on Swap page
* There should not be a expiration pop up nor sound
8. Back at the Swap, go all the way and this time place the tx/sign execute it
* There should be a pop up and sound
* Order should be pending in the corresponding state …

feat(smart-contract-orders): hide sc presign orders on start

---

src/modules/limitOrders/pure/OrderStatusBox/index.tsx
src/modules/limitOrders/pure/Orders/OrderRow/index.tsx
src/modules/limitOrders/pure/Orders/OrderRow/styled.tsx

This pull request enhances the user interface experience by making the STATUS label and the content under the FILLED column clickable, which upon interaction will open the Order Receipt.
**To verify the changes implemented in this PR, follow the steps:**
1. Either place an order or navigate to the order history.
2. Interact by clicking on the FILLED column content or the STATUS label.
3. The expected behavior is that the click should trigger the opening of the associated Order Receipt.
https://github.com/cowprotocol/cowswap/assets/31534717/ca95ed88-0e93-4309-9627-08ddf7536ab9
Please take note that, if there is a yellow warning triangle icon displayed next to the status label, this specific element has been excluded from the clickable interaction.
For future iterations, I would like to …

feat: clickable fill+status label for order receipt

---

src/modules/twap/containers/TwapFormWidget/index.tsx
src/modules/twap/containers/TwapFormWidget/styled.tsx

Adds rate info to TWAP orders widget.
- go to advanced orders
- select token pair
- there should be a rate info

feat: add rate info

---

src/utils/amountFormat/index.test.ts

This PR just add a commit that i forgot to push for this PR https://github.com/cowprotocol/cowswap/pull/2502
Basically adding some scenarios that were not covered by the test
Test should pass

Add test for formatting issue

---

src/modules/tradeQuote/hooks/useQuoteParams.ts
src/modules/tradeQuote/hooks/useTradeQuotePolling.ts

The bug was introduced [here](https://github.com/cowprotocol/cowswap/pull/2426/commits/67a3e404fa11c29c830d4836c9c767d5dee3b756#diff-e6788f9d60b35818ed567f0344b90b82785850cc9febfeae0280043cecc61ca7R20)
How it have been working before: [ref](https://github.com/cowprotocol/cowswap/blob/main/src/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useQuoteRequestParams.ts#L32)

fix(limit-orders): fix quoting for buy flow

---

src/modules/account/containers/AccountDetails/styled.ts

Part of https://github.com/cowprotocol/cowswap/pull/2578
Fix for this issue
https://github.com/cowprotocol/cowswap/assets/43217/25542df0-cb2b-4e80-9c33-c3c7362862dc
Now it looks like this
https://github.com/cowprotocol/cowswap/assets/43217/46d93d1f-58d8-4d25-a041-b5e313fefbcc
1. Connect with Trust wallet via WC as a non-expert user
2. Perform any operation that adds a modal (approve, order placement)
* The spinning image at the top should be rounded
3. Repeat steps with other wallets
* The same result

fix: make (Trust) wallet icon round on modals

---

src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
src/legacy/hooks/useWrapCallback.ts
src/legacy/utils/maxAmountSpend.ts
src/modules/swap/containers/SwapWidget/index.tsx
src/modules/swap/hooks/useSwapButtonContext.ts
src/modules/trade/containers/TradeWidget/index.tsx

Based on [this thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1686042726399249)
Allow to sell/wrap the exact full Native token amount when using Safe
Swap
https://github.com/cowprotocol/cowswap/assets/43217/5fe9e3bb-a67e-4232-8a1f-e6651ff17f35
Wrap
https://github.com/cowprotocol/cowswap/assets/43217/2417c096-54fb-41c2-ac5f-33b7d4048924
1. Using the Safe connect as a Safe app
2. Pick native token as sell
3. Click on `max` button
* Exact full amount should be used
4. Repeat 1-3 using Safe via WC
* Same result
5. Repeat 1-3 with EOA
* Not all amount should be used
https://github.com/cowprotocol/cowswap/assets/43217/b4611a66-914f-4d83-ba29-c91b52577c7d
6. Repeat 1-3 with other SC wallet (such as Pillar, Argent...)
* Not all amount should be used

feat(safe): allow to sell all native

---

src/modules/trade/hooks/useSwitchTokensPlaces.ts

Reported while testing 1.40.0 release https://github.com/cowprotocol/cowswap/pull/2602#issuecomment-1579076559
Already fixed in another PR, which was not included in the release: https://github.com/cowprotocol/cowswap/pull/2591/commits/486611b8c79d2c16f27f6f18ef00671a833f5e54#diff-893ba8596fd34f05c70e2e8bd8da0fa895da4495b11a2fb3d4c042592dba5f92R38
1. Go to limit orders, pick native and wrapped native as sell/buy tokens
2. Click on the middle arrow
* Tokens should swap
3. Pick a different pair and click on the arrow
* Tokens should swap
4. Repeat on swap
* Tokens should swap

fix: limit wrap/unwrap switch arrow

---

src/modules/twap/containers/ActionButtons/index.tsx

We should display local form validation before the global, because otherwise we can display a state "Approve and TWAP" when current wallet is not a Safe.
No need to test

fix(twap): display local form validation first

---

src/modules/trade/pure/ConfirmDetailsItem/index.tsx
src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
src/modules/twap/containers/TwapConfirmModal/index.tsx
src/modules/twap/utils/deadlinePartsDisplay.ts

- Unhide Start time and hard code it to `now`
To be explained via tool tip
Follow up to https://github.com/cowprotocol/cowswap/pull/2631
Implements part of https://github.com/cowprotocol/cowswap/issues/2577
Address PR comments from https://github.com/cowprotocol/cowswap/pull/2629
Calculating:
- Part time
- Total time
Hiding:
- Start time
1. On a Gnosis Safe with the handler already updated, go to advanced
2. Fill in the form
3. Click on review
* You should see the fields above properly filled and calculated
1. Styling definitely not ready

feat(twap): twap review order - pt4 - duration fields

---

src/lib/hooks/useNativeCurrency.ts
src/modules/trade/hooks/useIsNativeInOrOut.ts
src/modules/trade/hooks/useIsWrappedInOrOut.ts

Fixes the issue mentioned in #2675
- connect metamask wallet
- change to unsupported network
- there should be no app crash

fix: unsupported chain app crash

---

jest.config.app.ts
project.json
src/libs/ui-utils/package.json
src/libs/widget-lib/.eslintrc.json
src/libs/widget-lib/README.md
src/libs/widget-lib/jest.config.ts
src/libs/widget-lib/package.json
src/libs/widget-lib/project.json
src/libs/widget-lib/src/JsonRpcManager.ts
src/libs/widget-lib/src/consts.ts
src/libs/widget-lib/src/cowSwapWidget.ts
src/libs/widget-lib/src/index.ts
src/libs/widget-lib/src/lib/widget.spec.ts
src/libs/widget-lib/src/lib/widget.ts
src/libs/widget-lib/src/types.ts
src/libs/widget-lib/src/utils.spec.ts
src/libs/widget-lib/src/utils.ts
src/libs/widget-lib/tsconfig.json
src/libs/widget-lib/tsconfig.lib.json
src/libs/widget-lib/tsconfig.spec.json
src/libs/widget-lib/vite.config.ts
tools/scripts/publish.mjs
tsconfig.base.json

This PR adds the widget library to the monorepo (credits to @shoom3301 for implementing the main widget in https://shoom3301.github.io/cow-widget/)
This PR creates a publishable lib (meaning we can push it to NPM). We will also be able to use it in another monorepo project, which will make development easier.
The library has its own tests (i created tests just for the param to URL mapping (we could add more coverage if desired):
Last but not least, it adds a way to publish this into production, for that read the lib README for instructions.
For that is uses a custom script that will: copy the README, write the version in the package.json, and publish into NPM
Just run:
`nx test widget-lib`
To build:
`nx build widget-lib`, you will see the artifacts in `dist/widget-lib`

chore: Add `widget-lib` and publish to NPM

---

src/libs/widget-lib/docs/README.md
src/libs/widget-lib/src/cowSwapWidget.ts
src/libs/widget-lib/src/demo/index.ts
src/libs/widget-lib/src/types.ts
src/modules/appData/hooks.ts
src/modules/appData/updater/useAppDataUpdater.ts
src/modules/injectedWidget/state/injectedWidgetMetaDataAtom.ts
src/modules/injectedWidget/updaters/InjectedWidgetUpdater.ts

To distinguish orders related to an app that has the widget integrated, we pass `CowSwapWidgetMetaData` in the Widget and use it for `app-data`

feat(injected-widget): set app-data appCode from integrator

---

src/legacy/components/AmplitudeAnalytics/index.ts

Restores a change that was lost in this PR https://github.com/cowprotocol/cowswap/pull/2707/files#r1238279108
The change was making amplitude env optional. If it is not present, the app breaks
- https://cowservices.slack.com/archives/C0361CDG8GP/p1687870587361509
- 
Check cypress e2e result

fix: fix e2e

---

.github/workflows/ci.yml
.github/workflows/release-please.yml
package.json

Previous release https://github.com/cowprotocol/cowswap/releases/tag/v1.40.2 introduced a change to the workflows for enabling release-please: https://github.com/cowprotocol/cowswap/commit/013915f8f4f729270ad55b857e567aa5b1ca69f8
Unfortunately, the workflow is broken https://github.com/cowprotocol/cowswap/actions/runs/5401847014
Since we are short on time, I'll just revert the change and delegate the fix to another time

chore: hotfix/1.40.3

---

package.json
src/api/gnosisProtocol/api.ts
src/api/gnosisProtocol/hooks.ts
src/modules/account/containers/AccountDetails/SurplusCard.tsx
src/modules/account/containers/AccountDetails/index.tsx
src/utils/amountFormat/index.ts
yarn.lock

First part of hackathon surplus project.
Using backend's new api: https://barn.api.cow.fi/xdai/api/v1/users/0x4CBc3B6B16Ac4218169078aDd37947B76127E10B/total_surplus
Add surplus data to activity details 
Figma: https://www.figma.com/file/FrpBXkN4ZNuVhfXp4RJtI4/2023-Account-Modal?type=design&node-id=0-1&mode=design
- Styling not included
- API fn should be moved to SDK, will do so in an upcoming PR
- Right now only queries barn
- Tooltip missing
- Real link missing
1. Connect wallet
2. Open activity details
* Surplus card should be displayed

feat(hackathon-surplus): add surplus data to activity details

---

src/common/pure/TransactionSubmittedContent/SurplusModal.tsx
src/common/pure/TransactionSubmittedContent/index.tsx
src/legacy/components/TransactionConfirmationModal/index.tsx

Continuing hackathon surplus project
Follow up to https://github.com/cowprotocol/cowswap/pull/2751
Display the new surplus modal when the order is filled
As you can see, it's very close to the design, only some minor stylings missing
|This|Design|
|-|-|
| ![Screenshot 2023-06-29 at 16 58 56](https://github.com/cowprotocol/cowswap/assets/43217/2b04e575-d6ef-4237-9ed3-6bcbf0ee153b) | ![image](https://github.com/cowprotocol/cowswap/assets/43217/01337017-2f35-4baa-b7b3-d21cb0264a69) |
- Styling not included
- Share button has no data
- Link to `learn more` is missing
- Modal must be open after order placement to see it
1. Place order
2. Keep order confirmation modal open
* Once order is filled, the new modal should be displayed

feat(hackathon-surplus): add new surplus modal when order filled

---

src/modules/twap/pure/DeadlineSelector/index.tsx

Fixes #2683
- go to advanced orders
- insert in custom deadline 64 min
- it should show `1h 4m` instead

fix: display total time nicer

---

src/api/gnosisProtocol/hooks.ts
src/common/state/totalSurplusState.ts
src/common/state/totalSurplusState/atoms.ts
src/common/state/totalSurplusState/hooks.ts
src/common/state/totalSurplusState/index.ts
src/common/state/totalSurplusState/types.ts
src/common/state/totalSurplusState/updaters.ts
src/legacy/state/orders/updaters/PendingOrdersUpdater.ts
src/modules/account/containers/AccountDetails/SurplusCard.tsx
src/modules/application/containers/App/Updaters.tsx

Build on top of https://github.com/cowprotocol/cowswap/pull/2773
This change is based on this comment https://github.com/cowprotocol/cowswap/pull/2751#discussion_r1248046192
Re-fetch data when there's a trade
Also moved data into jotai state so there's no re-fetch when activity modal is opened
1. Connect wallet
2. Place order
3. Open activity details
4. Keep notice of the surplus amount
* When order trades, surplus amount should be updated

feat(hackathon-surplus): refresh surplus on swap trade

---

src/modules/trade/pure/TradeNumberInput/index.tsx
src/modules/twap/const.ts
src/modules/twap/containers/TwapFormWidget/index.tsx
src/modules/twap/state/partsStateAtom.ts
src/modules/twap/state/twapOrdersSettingsAtom.ts

- Minimum number of parts set to 2
- Don't allow to set less than that
- When 1, 0 or empty inserted, switch back to 2
1. Open advanced orders tab
* Default parts should be 2
2. Remove `2`
* Value should be reset to `2`
3. Insert 1 or 0
* Value should be reset to `2`
* It should be possible to change to values > 2

feat(twap): order defaults

---

src/modules/twap/const.ts

Fixes #2766
1. go to advanced orders widget
2. open total time dropdown
3. the values should reflect expected result

fix: total time values dropdown

---

src/common/pure/ExecutionPrice/index.tsx
src/common/pure/RateInfo/index.tsx
src/modules/trade/pure/TradeNumberInput/index.tsx
src/modules/trade/pure/TradeWidgetField/index.tsx
src/modules/trade/pure/TradeWidgetField/styled.tsx
src/modules/twap/containers/TwapFormWidget/index.tsx
src/modules/twap/containers/TwapFormWidget/tooltips.tsx
src/modules/twap/state/twapOrderAtom.ts

On top of https://github.com/cowprotocol/cowswap/pull/2785
https://github.com/cowprotocol/cowswap/assets/43217/ddf31f0d-e6a5-467d-bf88-77d63aa02daf
1. On TWAP tab, fill in order params
* Price protection should show the price minus slippage
* Clicking on price row should invert both prices

feat(twap): refactor and wire price protection

---

src/modules/twap/containers/TwapConfirmModal/index.tsx
src/modules/twap/containers/TwapFormWarnings/index.tsx

Fixes #2772 
Disable confirm button in the modal when any form validation fails
⚠️ I was not able to reproduce the amount too small in the confirm button ⚠️ 
1. Fill in twap form with a sell amount/#parts very little above the minimum
2. Proceed to confirmation modal
3. Wait until market price/USD price changes and sell amount per parts becomes < than minimum
* Confirm button should be disabled
* Warning should be displayed

feat(twap): disable confirm button when form validation fails

---

src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
src/modules/limitOrders/containers/TradeButtons/index.tsx
src/modules/trade/pure/TradeConfirmation/index.tsx
src/modules/twap/containers/TwapConfirmModal/index.tsx

Closes #2697 
- Changed default review button label for regular and expert mode
- Bonus: renamed confirm modal text for limit from `Confirm` to `Place limit order`
Regular form
Expert form
Non approval expert form
Regular confirmation modal
1. Limit order for regular user needing approval
* Button text should be `Review limit order`
2. Same for expert mode
* Button text should be `Place limit order`
Please also check different combinations of regular/expert on SWAP, LIMIT and ADVANCED

feat(twap): review button label on limit

---

src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
src/legacy/state/orders/utils.ts
src/modules/orders/state/pendingOrdersPricesAtom.ts
src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx

(Partially) Fixed #2713 
Do not show estimated execution price for twap parent orders
As for the children, it uses the exact same logic as limit fill or kill orders AFAICT.
If not working for limit, shouldn't work twap and vice versa.
Which means, both are broken 😓 
1. Place TWAP order
* Parent twap order shouldn't have estimated exec. price

feat(twap): do not show est. exec. price for twap parent orders

---

src/utils/orderUtils/getOrderSurplus.ts

Closes #2702 
Fix surplus receipt for pending swap buy orders
1. Place a SWAP buy order
2. Go to limit orders table
3. Open the pending order receipt
* Surplus should be `-`
Repeat for other order types. Result should be the same.

fix(surplus-pending-swap-buy-receipt): fix receipt for pending buy swap orders

---

src/modules/ordersTable/pure/ReceiptModal/index.tsx

Quick fix, adding order id field to twap part orders on receipt modal
TWAP part order now has it
TWAP parent remains without
1. On orders table, open a twap part order
* Order id filed should be present and link to explorer

feat(twap): display order id on receipt for twap part orders

---

src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
src/modules/trade/pure/UnlockWidgetScreen/index.tsx
src/modules/trade/pure/UnlockWidgetScreen/styled.ts

Hides learn more text from Unlock screen on advanced orders
Source https://cowservices.slack.com/archives/C0361CDG8GP/p1688740674594089
- go to advanced orders
- make sure there is no learn more link in Unlock screen

fix(twap): hide learn more link

---

src/legacy/theme/baseTheme.tsx
src/legacy/theme/styled.d.ts
src/modules/account/containers/AccountDetails/SurplusCard.tsx

- Styles the surplus card in the account modal
- Add text for tooltip
- Decide on 2nd card

Surplus account styling 1

---

src/modules/account/containers/AccountDetails/SurplusCard.tsx
src/modules/account/containers/AccountDetails/styled.ts

I created this PR because I saw in the surplus component we were defining the surplus styled component inside the `render` function of the component. This is inefficient, because it will define it over and over in each rendering. 
On top of this, i just moved the styles close to the other styles (`./styled`)
Nothing should change, you should see the surplus as before

chore(surplus): move styles from surplus to styled

---

src/common/hooks/useNeedsZeroApproval.ts
src/modules/twap/containers/TwapFormWarnings/index.tsx
src/modules/twap/hooks/useTwapOrderCreationContext.ts
src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
src/modules/twap/services/createTwapOrderTxs.test.ts
src/modules/twap/services/createTwapOrderTxs.ts

Closes #2801 
Applying same logic as SWAP and LIMIT to TWAP in regards to tokens that don't allow the allowance to be changed.
Adding warnings to TWAP form
- Not certain whether it makes sense to have `token approval` bundle info for TWAP. After all, several operations here will be bundled, such as:
1. Approval and order placement
2. Update Safe handler and order placement
3. Cancellation
1. Pick a token which is affected, such as USDT
2. Approve less than infinite
3. Sell it in a TWAP order
* Warning banner should be displayed in the form
* Safe tx should show both approvals in sequence
Remaining TWAP operations should remain as is

feat(twap): reset USDT allowance

---

src/common/pure/OrderSubmittedContent/index.tsx
src/legacy/components/AddressInputPanel/index.tsx
src/legacy/components/ExplorerLink/index.tsx
src/legacy/components/Popups/TransactionPopupMod.tsx
src/legacy/components/SearchModal/ImportToken/index.tsx
src/legacy/components/SearchModal/ManageTokens/ManageTokensMod.tsx
src/legacy/components/SearchModal/TokenImportCard/TokenImportCardMod.tsx
src/legacy/components/Tokens/TokensTableRow.tsx
src/legacy/components/TransactionConfirmationModal/DisplayLink.tsx
src/legacy/components/Version/index.tsx
src/legacy/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx
src/legacy/hooks/useActivityDerivedState.ts
src/legacy/utils/index.ts
src/modules/account/containers/AccountDetails/index.tsx
src/modules/mainMenu/constants/mainMenu.tsx
src/modules/mainMenu/pure/MenuTree/index.tsx
src/modules/mainMenu/types.ts
src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
src/modules/ordersTable/pure/ReceiptModal/IdField.tsx
src/pages/Account/Balances.tsx
src/pages/Account/LockedGnoVesting/index.tsx

Address the issue we didn't have a explorer link in the header
TBH i thought this would be a 5min thing, and it turned out I had to implement a few features in order to make it work. 
Let me drive you through the thinking process.
1. Our links are created by configuration of some const here https://github.com/cowprotocol/cowswap/blob/b383642deb7826f20c8525fe30133a73a3be4703/src/modules/mainMenu/constants/mainMenu.tsx#L108 
2. The link to the explorer can't be added as a static type, because the URL changes for example between different networks 
3. I decided to make a new type of Menu Item with an arbitrary component, this way we can make any dynamic logic. This new type is:
* https://github.com/cowprotocol/cowswap/blob/9f462640f2d779922963825e4794d8df213b1e37/src/modules/mainMenu/types.ts …

chore: refactor explorer links and menu, add explorer in menu

---

.env
.env.production
.github/workflows/vercel.yml
README.md
src/modules/wallet/web3-react/connection/walletConnect.tsx

Allows to modify the wallet connect bridge from an environment variable 
1. Go to https://swap-dev-git-add-env-for-wallet-connect-v1-cowswap.vercel.app/#/1/swap/WETH
2. Click to connect with wallet connect
3. Copy the  code
4. Inspect the URL, it should have the right bridge in the params. I've modified the envs so, just  heck it matches:
You should see

feat(wallet-connect): add env for specifying the WC v1 bridge

---

src/modules/twap/containers/TwapFormWidget/index.tsx
src/modules/twap/state/twapOrdersSettingsAtom.ts

Closes #2832 
Fix slippage value crash
1. Open advanced orders
2. Insert a decimal value onto slippage, such as `34.34`
3. Click on another field
* The app should not crash
* Inserted value should be saved

fix(twap): fix slippage value crash

---

src/modules/account/containers/AccountDetails/SurplusCard.tsx

Closes #2829 
1. Connect with account without trades OR surplus since March 2023
2. Open activity modal
* Should show msg as above
Other accounts/networks should still display the surplus amount - if any

feat(hackathon-surplus): do not show 0 surplus

---

src/modules/account/containers/AccountDetails/SurplusCard.tsx

Closes: #2828 
Added the missing tooltip
1. Connect wallet that had any surplus since March 2023
2. Hover over question mark icon like images above
* Should show the text as above

feat(hackathon-surplus): add tooltip for activity modal surplus

---

src/common/pure/TransactionSubmittedContent/SurplusModal.tsx

Add missing link to surplus modal
1. Place order
* Once traded, surplus modal is displayed
* Surplus modal should contain link to blog post

feat(hackathon-surplus): add missing link to surplus modal

---

src/modules/ordersTable/pure/ReceiptModal/fields/SafeTxFields.tsx
src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx
src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
src/modules/trade/pure/ConfirmDetailsItem/index.tsx
src/modules/trade/pure/ReviewOrderModalAmountRow/index.tsx
src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
src/modules/twap/containers/TwapConfirmModal/index.tsx

Add missing tooltips
On TWAP review modal fields 
On order receipt modal (Safe fields)
* Check all tooltips exist.
* Check there are no missing tooltips :)

feat(twap): add missing tooltips

---

src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
src/modules/ordersTable/pure/ReceiptModal/FilledField.tsx
src/modules/ordersTable/pure/ReceiptModal/styled.ts

- Addresses https://github.com/cowprotocol/cowswap/issues/2703

feat: style progress bar

---

src/modules/swap/containers/SwapWidget/index.tsx
src/modules/swap/index.ts
src/modules/swap/state/useSwapDerivedState.ts
src/modules/swap/updaters/SwapDerivedStateUpdater.tsx
src/pages/Swap/index.tsx

`useFillSwapDerivedState` hook was initialized in `SwapWidget` because of it there was tons of updates
1. Open Swap page
2. Select a pair of assets and input amount
3. Open tokens selection modal

fix(swap): get rid of infinite updates in useFillSwapDerivedState

---

src/api/gnosisProtocol/api.ts

Avoid sending `env` as `undefined` to getOrder query
Without this, instead of the default behaviour, the SDK defaults to `barn` endpoint
1. Load the app
2. Observe network requests
* Since this is a PR env, there should be no /orders/<order id> requests to `api.cow.fi` endpoint
* Once deployed to `staging`, there should be no /orders/<order id> requests to `barn.api.cow.fi` endpoint

fix(twap): avoid sending `env` as `undefined` to getOrder query

---

src/legacy/components/Header/NetworkSelector/NetworkSelectorMod.tsx
src/legacy/components/analytics/pixel/constants.ts
src/legacy/components/analytics/pixel/facebook.ts
src/legacy/components/analytics/pixel/linkedin.ts
src/legacy/components/analytics/pixel/microsoft.ts
src/legacy/components/analytics/pixel/paved.ts
src/legacy/components/analytics/pixel/reddit.ts
src/legacy/components/analytics/pixel/twitter.ts
src/legacy/components/analytics/pixel/utils.ts

Pixels and any other analytics in the app should not break the user flow in case of an error.
This PR makes sure that if we have an error reporting Pixel (facebook, twitter, etc), we just log it and it doesn't propagate.
Additionally, this PR enables the pixel reporting for PRODUCTION and ENS (well, in the PR is enabled for testing purposes, but will be disabled before merging as stated in the code comment)
This PR tries to solve the issue reported by Elena:
@elena-zh can you check if this is fixing the issue?

chore: make pixel events more resilient

---

src/common/hooks/useGetSurplusFiatValue.ts
src/common/pure/TransactionSubmittedContent/SurplusModal.tsx
src/common/pure/TransactionSubmittedContent/index.tsx
src/legacy/components/TransactionConfirmationModal/index.tsx
src/legacy/constants/index.ts
src/modules/swap/containers/SurplusModalSetup/index.tsx
src/utils/getExecutedSummaryData.ts
src/utils/orderUtils/parseOrder.ts

Will point to the right place once ready
Fixes https://github.com/cowprotocol/cowswap/issues/2847 and https://github.com/cowprotocol/cowswap/issues/2848
Show the modal according to the rules (slightly different from the issue descriptions)
- If FIAT surplus amount estimation available, show it if amount is > 1$
- Otherwise, show if surplus amount > 0.1 units
Revert old behaviour for confirmation modal when surplus is not displayed
1. Place order which generates > 1$ surplus
2. Do not close confirmation modal
* Surplus modal is displayed inside confirmation modal
3. Repeat `1` but close the confirmation modal
* Surplus modal is displayed as a new pop up modal
4. Place order which generates < 1$ surplus
5. Do not close confirmation modal
* Surplus modal is not displayed. Instead, old …

feat(hackathon-surplus): do not show modal when too small amounts

---

src/common/utils/autofocus.ts
src/legacy/components/AddressInputPanel/index.tsx
src/legacy/components/NumericalInput/index.tsx
src/modules/trade/pure/TradeNumberInput/index.tsx
src/modules/twap/containers/TwapFormWidget/index.tsx
src/modules/twap/pure/CustomDeadlineSelector/index.tsx

- Change some input fields from `text` to `number` (TWAP slippage and number of parts)
- Use `min` & `max` html validation for the same fields
- Make all form fields select its contents on focus/click
1. On TWAP form, select the slippage field
2. With your keyboard, hit the `up` arrow
* Slippage should go it by `1`
3. Repeat with `number of parts` field
* Same result
4. Check the next on all forms (SWAP, LIMIT, ADVANCED)
5. Input a value in the input
6. Click away
7. Click on the input again
* The whole text/number should be selected

feat(form-fields): misc field forms adjustments

---

src/modules/swap/containers/Row/RowSlippage/index.tsx
src/modules/swap/pure/Row/RowSlippageContent/index.tsx
src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx
src/modules/trade/containers/TradeBasicConfirmDetails/SlippageRow.tsx
src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
src/modules/twap/containers/TwapConfirmModal/index.tsx
src/modules/twap/containers/TwapFormWidget/tooltips.tsx

- Re-apply #2843 
- Revert `limit price` to it's original name
- Change slippage label on TWAP review modal to `Price protection`
1. Check tooltips on TWAP review modal

feat(twap): tooltips try2

---

src/legacy/state/orders/actions.ts
src/legacy/state/orders/consts.ts
src/legacy/state/orders/hooks.ts
src/legacy/state/orders/reducer.ts
src/legacy/state/orders/updaters/GpOrdersUpdater.ts

Fixes #2690
When the `GpOrdersUpdater` component is unmounted this hook will "clean up" parts of the orders state saved in a local-storage, by filtering out older orders of type `['expired', 'cancelled', 'fulfilled']` and taking only top 10 sorted by `expirationTime`.
- Make sure everything works as expected
- The mentioned issue shouldn't happen anymore

fix(orders-storage): clear orders storage on unmount

---

CHANGELOG.md
package.json
src/modules/twap/state/twapOrdersListAtom.ts
src/modules/twap/state/twapPartOrdersAtom.ts

1. Open Advanced orders in Safe app
2. Create a TWAP order with 3 children
2. Open a new CowSwap tab (without Safe) in Advanced orders
3. AR: 
4. ER:

fix(twap): don't mix twap states between browser tabs

---

CHANGELOG.md
package.json
src/legacy/state/orders/updaters/GpOrdersUpdater.ts

Fixes #2906
I just forgot to fulfill `apiOrdersAtom` state (facepalm)

fix(twap): update twap orders state on Prod env

---

src/common/pure/CancellationModal/RequestCancellationModal.tsx
src/legacy/state/orders/updaters/utils.ts
src/modules/twap/utils/emulateTwapAsOrder.ts

Fixes #2887
This adds a recipient to TWAP orders cancelation modal and popups.
Cancel confirmation modal
- I've tested it in cancel confirmation modal but not in the popups since I couldn't get them.
- Test in cancel confirm modal and in popups

feat(twap): add recipient to summary in cancel modal

---

src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
src/modules/ordersTable/pure/OrdersTableContainer/types.ts
src/pages/AdvancedOrders/index.tsx
src/pages/LimitOrders/index.tsx

Fixes #2910
- Fixes the issues mentioned in the issue related by changing some order table content based on the order types.
- Also renames one type from `LimitOrderActions` to  `OrderActions` since its shared now
- Test that the scenarios mentioned in the issue are fixed

feat(TWAP): update content based on orders type

---

src/modules/twap/hooks/useCreateTwapOrder.ts
src/modules/twap/utils/parseTwapError.ts

Fixes #2670
Adds error handling for TWAP
- Shows a popup on error
- Parses invalid argument message and shows client friendly error message
**Example of error un-parsed**
```javascript
invalid address (argument="address", value="order.sellAmount.currency.address", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="sellToken", value="order.sellAmount.currency.address", code=INVALID_ARGUMENT, version=abi/5.7.0)
````
**Parsed**
- I'm not sure how, I've set invalid params in code while implementing this

feat(TWAP): handle TWAP errors

---

src/modules/twap/containers/TwapFormWarnings/index.tsx
src/modules/twap/containers/TwapFormWarnings/warnings/SmallPriceProtectionWarning.tsx
src/modules/twap/state/twapOrderAtom.ts
src/modules/twap/utils/isPriceProtectionNotEnough.ts

Fixes #2895
Spec: https://www.notion.so/cownation/FE-TWAP-Orders-c9f6bd5c23bd4c749147611dcb63daac?pvs=4#b719e9b8c73644f8919418125cb5c18e
1. One month = 30 days
2. I've replaced the word `slippage` with `price protection`
3. The design is different from the screenshot from Notion, but I think it should like it is, because recently Michel unified all warnings

feat(twap): small price protection warning

---

src/modules/ordersTable/pure/OrderStatusBox/getOrderStatusTitleAndColor.test.ts
src/modules/ordersTable/pure/OrderStatusBox/getOrderStatusTitleAndColor.ts
src/modules/ordersTable/pure/OrderStatusBox/index.tsx
src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx

Fixes #2928
There are two commits:
1. Actually the fix of the issue
2. Moving the function to a new file + tests

fix(orders-table): display partially filled status before confirmed states

---

src/modules/swap/containers/SwapWidget/index.tsx
src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
src/modules/swap/pure/warnings.tsx

Spec: https://docs.google.com/presentation/d/1ujFpnYbZ2eeaPA3v8DXRctWnDHrdlkx-63qScYrwlVk/edit#slide=id.g25b719a5370_0_55
The banner is displayed when:
1. Slippage is above 1%
2. AND the buy amount is greater than $50000
@fairlighteth I need your help with designing the banner 🙏

feat(swap): suggest using TWAP

---

src/modules/limitOrders/state/limitRateAtom.ts
src/modules/twap/hooks/useFallbackHandlerVerification.ts
src/modules/twap/services/verifyExtensibleFallback.ts
src/modules/twap/state/fallbackHandlerVerificationAtom.ts
src/modules/twap/updaters/FallbackHandlerVerificationUpdater.tsx
src/utils/jotai/atomWithPartialUpdate.ts

Fixes #2899
In `FallbackHandlerVerificationUpdater` once we detected, that fallback is set, we should:
- cache the result in `localStorage`
- don't execute `FallbackHandlerVerificationUpdater` logic again and use the cached value
I also added `atomWithPartialUpdate` helper to reduce boilerplate code
1. Set fallback handler in TWAP

refactor(twap): cache fallback handler verification result

---

src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
src/modules/ordersTable/utils/groupOrdersTable.ts
src/modules/twap/state/emulatedPartOrdersAtom.ts
src/modules/twap/state/emulatedTwapOrdersAtom.ts
src/modules/twap/state/twapOrdersListAtom.ts

Fixes #2941
Now twap order always displays as a group with all parts inside.
Only when all parts are completed (canceled/expired/filled) then the whole twap order moves to the history.

feat(twap): display order group in history tab

---

src/legacy/state/price/updater.ts
src/legacy/state/swap/hooks.tsx

Fixes #2960
The bug was introduced since the recent refactoring: https://github.com/cowprotocol/cowswap/pull/2927
There is a nuance for native tokens `useDerivedSwapInfo`. Added TODO for it

fix(swap): use symbol instead of address for native tokens

---

src/common/hooks/featureFlags/useVerifiedQuotesEnabled.ts
src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
src/legacy/state/price/updater.ts
src/modules/tradeQuote/hooks/useQuoteParams.ts

Adds 3 new feature flags for enabling the `verified` quotes. Each will control one chain. 
This feature is meant to be killed once all chains have `verified` quotes enabled.
Right now Goerly and Gnosis chain are active, and mainnet is not. 
You can check that when the user has enough balance, and is in a network that has this flag enabled, it will make requests using the verified option (see https://github.com/cowprotocol/cowswap/pull/2945 on how to check if we used the verified option)

feat(verify-quote): add feature flag

---

package.json
src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
src/mocks/tradeStateMock.ts
src/modules/appData/appData-module.md
src/modules/appData/hooks.ts
src/modules/appData/index.ts
src/modules/appData/services/index.ts
src/modules/appData/state/atoms.ts
src/modules/appData/types.tsx
src/modules/appData/updater/UploadToIpfsUpdater.ts
src/modules/application/containers/App/Updaters.tsx
src/modules/limitOrders/hooks/useTradeFlowContext.ts
src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
src/modules/limitOrders/services/safeBundleFlow/index.ts
src/modules/limitOrders/services/tradeFlow/index.ts
src/modules/limitOrders/services/types.ts
src/modules/swap/hooks/useFlowContext.ts
src/modules/swap/services/ethFlow/index.ts
src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
src/modules/swap/services/swapFlow/index.ts
src/modules/swap/services/types.ts
src/modules/twap/hooks/useCreateTwapOrder.ts
yarn.lock

This  PR brings back the logic to upload the documents to IPFS
The logic was removed because we already post the information to the backend when we post an order. 
However, for example in TWAP orders we don't invoke the API directly, so we can't post the content of the AppData document. The same could happen in the future we don't post presign orders anymore (there was some conversations about it)
Context:
https://cowservices.slack.com/archives/C0375NV72SC/p1690300421329999?thread_ts=1690297997.334099&cid=C0375NV72SC
For now, we do it for all! It doesn't harm, but is redundant, so I will do a follow-up PR to remove some flows.
This way, the come in two different PRs in case we need to revert in the future and add for example presign back.
- Make a trade in any of the flows
- Filter in the …

chore(app-data): upload app-data document

---

src/modules/appData/services/index.ts
src/modules/appData/updater/UploadToIpfsUpdater.ts

Continuation on https://github.com/cowprotocol/cowswap/pull/2933
Although previous PRs were uploading the app-data for TWAP  orders, the document was uploaded to the wrong network (always mainnet)
This PR makes sure they are in the right network, and uses production API (never barn). The reason is that now we only upload documents for on-chain orders (off-chain orders sends the document already when posting the order to the API).
On-chain orders are indexed by the `WatchTower` who will post to the API.
`WatchTower` posts to production, never to Barn.
1. Place a TWAP order
2. Make sure you can see the app-data in the explorer

fix: upload app-data to the right network

---

src/legacy/hooks/useStablecoinPrice/index.ts

Fixes #2958
The context: https://cowservices.slack.com/archives/C0361CDG8GP/p1690960269960949?thread_ts=1690570839.813469&cid=C0361CDG8GP
Important! The price impact still can be inaccurate but not so invalid as before

fix(swap): change quote amount for price impact calculation on Gnosis chain

---

package.json
yarn.lock

Update SDK to use the last closed version. Technical has the same code as RC.10, just closing the version after testing it works

chore: update sdk to last closed version

---

src/modules/appData/services/index.ts
src/modules/appData/types.tsx
src/modules/appData/updater/UploadToIpfsUpdater.ts
src/modules/appData/updater/useAppDataUpdater.ts
src/modules/swap/hooks/useFlowContext.ts
src/modules/swap/services/ethFlow/index.ts
src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
src/modules/swap/services/types.ts
src/modules/twap/hooks/useCreateTwapOrder.ts

Fixes https://github.com/cowprotocol/explorer/issues/572
Uploads the appData for ETH Flow orders.
Proof:
https://dev.explorer.cow.fi/goerli/orders/0xe0b07c25e2db3921163f048f0a75f12a2497dfa0088f5afa08473568a2ab69f6d02de8da0b71e1b59489794f423fabba2adc4d93ffffffff?tab=overview
To the API, and depending on the flow (order class) we will need to upload it to a different place. 
- TWAP --> Production, since the orders are created by WatchTower
- ETH FLOW ---> Barn/Production depending on the environment. This is because, there's a separation of the 2 contracts, and this is how we can know where the order was created. The service that creates the order will take this into account, so we need to do the same when we upload its meta-data
Place an ETH Flow order and check in Explorer its app-data …

fix: upload appData to ETH flow

---

src/legacy/utils/tooltips.ts

fix(swap): display correct value of slippage in min. price tooltip

---

src/common/hooks/useIsAdvancedOrdersEnabled.ts
src/modules/mainMenu/hooks.ts
src/pages/AdvancedOrders/index.tsx

The `Advanced orders` page redirects to `Swap page` at the first time because we initially don't have a value for a feature-flag and consider it as `false`.
After this fix we will render nothing and don't redirect while loading feature-flags info.

fix(twap): don't redirect to swap when feature-flag value is not defined

---

src/modules/application/containers/App/RoutesApp.tsx
src/modules/twap/hooks/useCreateTwapOrder.ts
src/modules/twap/utils/parseTwapError.ts

This PR fixes a nasty error in Safari where we couldn't navigate neither to TWAP nor to LIMIT_ORDERS.
This is what was happening:
The error had to do with loading Safari throwing while chunk 
After some digging, the error is related to Safari not supporting forward lookups, see https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
I found a place where we were using them, and changed the implementation. This solved the issue 🎉
here: https://github.com/cowprotocol/cowswap/pull/2918/files
I tested the new implementation also works, and IMO is simpler
I added some notes in the code with some additional changes in this PR
Load TWAP orders from an old safari

fix: solve issue in safari being broken

---

src/common/pure/CurrencyAmountPreview/index.tsx
src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
src/common/pure/CurrencyInputPanel/styled.tsx
src/legacy/components/NumericalInput/index.tsx

- Modifies the inputfield from having `disabled` to use `readonly` to prevent selection issues. Specifically on Safari.
- Needs to be tested on Safari > Update: tested and works.

feat: disabled to readonly

---

src/modules/twap/hooks/useFetchTwapOrdersFromSafe.ts
src/modules/twap/services/fetchTwapOrdersFromSafe.ts

**Important! Change the target branch before merging!**
Fixes #2642 #2993
To fetch Safe transactions we use `@safe-global/api-kit`, exactly: `safeApiKit.getAllTransactions(safeAddress)`.
By default, it returns only the last 20 transactions. Unfortunately, the limit is hardcoded on the backend, so we can't set limit=200 and fetch all at once.
Anyway, `getAllTransactions()` method returns an URL for the next batch, so we can fetch as many as we want using pagination.
How the fetching works now:
Every 15 seconds we make 10 requests by 20 transactions (total = 200).
Just in case, I've added `100ms` delay between requests.

feat(twap): fetch first 200 transactions using pagination

---

src/common/hooks/useGetSurplusFiatValue.ts

Fixes #2995
The source of problem: `Number(surplusAmount.toFixed(3)) > MIN_SURPLUS_UNITS`
`EURs` token has 2 decimals:
`invariant(decimalPlaces <= this.currency.decimals, 'DECIMALS')`

fix: use currency decimals for surplus amount calculation

---

src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts

Addresses this comment https://github.com/cowprotocol/cowswap/pull/2986#discussion_r1282902069
I explain in the comments what is wrong :) 
ETH Flow and Bundle ETH Flow (in safe app) should still work, and we should see the document in the explorer

fix: dont upload app-data in bundle-safe-flow

---

src/modules/trade/pure/TradeNumberInput/index.tsx
src/modules/twap/containers/TwapFormWidget/index.tsx

Waterfalls onto https://github.com/cowprotocol/cowswap/pull/2970
Connecting the dots with the number input arrows
- Time picker input
- ~Keyboard events (up and down arrow keys)~ added
1. On TWAP form, click on the price protection and number of parts field arrows 
* It should increase by 0.1 on price protection
* It should increase by 1 on number of parts
* It should not go over 100 on price protection
* It should not go over 100'000 on number of parts
* It should not go under 0 on price protection
* It should not go under 2 on number of parts

feat(number-input-arrow): wire up number input arrows

---

src/modules/trade/pure/TradeNumberInput/index.tsx
src/modules/twap/pure/CustomDeadlineSelector/index.tsx
src/modules/twap/pure/CustomDeadlineSelector/styled.tsx

Waterfalls onto https://github.com/cowprotocol/cowswap/pull/3001
Add and wire up arrow keys to custom deadline inputs
- Styles have been broken and need re-work. Out of the scope of this PR. @fairlighteth can you take care of it?
1. On TWAP form, open the custom deadline modal
* Both fields should have arrows
* Arrows should change the values
* Up and down keys should change the values

feat(number-input-arrow): add arrows to custom deadline input

---

src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
src/modules/swap/pure/warnings.tsx
src/modules/trade/updaters/RecipientAddressUpdater.tsx

Make the TWAP banner suggestion on SWAP orders to include the sell amount in the link
https://github.com/cowprotocol/cowswap/assets/43217/ad33428b-90c7-440e-a270-46eef2e50799
1. On SWAP fill in the sell order with significant slippage as to see the TWAP banner
2. Click on the TWAP link
* The sell amount should be kept when moving to the new tab

feat: pass sellAmount to TwapSuggestionBanner on TWAP page link

---

src/legacy/state/orders/updaters/GpOrdersUpdater.ts
src/modules/orders/hooks/useTokensForOrdersList.ts
src/modules/orders/index.ts
src/modules/orders/utils/getTokensListFromOrders.ts
src/modules/twap/hooks/useAllEmulatedOrders.ts
src/modules/twap/hooks/useEmulatedPartOrders.ts
src/modules/twap/hooks/useEmulatedTwapOrders.ts
src/modules/twap/hooks/useTwapOrdersTokens.ts
src/modules/twap/updaters/CreatedInOrderBookOrdersUpdater.tsx
src/utils/orderUtils/getTokenFromMapping.ts

Context: https://cowservices.slack.com/archives/C053B0162VD/p1691651248930029
The cause of the bug:
Twap module naively loaded orders assuming all their tokens are in the CowSwap tokens list.
`GpOrdersUpdater` already contains the logic for fetching unknown tokens info from blockchain.
1. I've extracted that logic from `GpOrdersUpdater`: https://github.com/cowprotocol/cowswap/pull/3028/commits/ed08d60e63f53c3f032e5cac41c2f4f74676c7ed
2. Added it to `TWAP` module: https://github.com/cowprotocol/cowswap/pull/3028/commits/31f66a5c092c8838cc20d35a1da0904ffcf2271a
1. Open https://app.safe.global/apps/open?safe=eth:0x35a85f7440f2be30af569ccf08adb6b0207d110c&appUrl=https://barn.cow.fi/ (replace appUrl to vercel)
2. Navigate to Advanced orders

fix(twap): load unknown tokens from blockchain

---

src/jotaiStore.ts
src/modules/advancedOrders/state/advancedOrdersAtom.ts
src/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
src/modules/limitOrders/state/limitOrdersRawStateAtom.ts
src/modules/limitOrders/state/limitOrdersSettingsAtom.ts
src/modules/twap/state/twapOrdersListAtom.ts
src/modules/twap/state/twapOrdersSettingsAtom.ts
src/modules/twap/state/twapPartOrdersAtom.ts

Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1691675128738349
The bug was introduced in the recent jotai update: https://github.com/cowprotocol/cowswap/pull/2916
Before there was a solution to prevent sync jotai storages: https://github.com/pmndrs/jotai/pull/1004/files
In the `jotai@2.x` they removed this solution and now we have to patch storage to prevent the synchronization.

fix: disable limit orders state sync between tabs

---

src/modules/twap/state/fallbackHandlerVerificationAtom.ts

We are caching the result of the compatibility check for Safes and the Composable CoW framework
I noticed that the UI was allowing me to create orders but my domain verifier was pointing to the old composable cow contract.
The issue was JOITAI caching in my browser the result of the check, from the times where I had the old contracts. At that time I was compatible, but not any more.
It surprised me that, although we CACHE, we still do the call (but ignore the result). @shoom3301 you might want to double check that (although not too urgent any more)
Full context:
https://cowservices.slack.com/archives/C053B0162VD/p1692201999694339

fix: version the storage name for the fallback handler

---

apps/cowswap-frontend/src/legacy/utils/retry.test.ts

This PR is to address this issue: https://github.com/cowprotocol/cowswap/actions/runs/5879543762/job/15944156125 
Basically this test is not deterministic
The issue is that it tries to assert the execution time is between some boundaries. I believe in this case we can assert the minimum time of execution, but the maximum is not possible, there might be some slow executions, for example, because of a Garbage Collection tasks or any other reason. 
BEcause of this, the tests can't be deterministic, so is best to only assert the minimum time is respected.
Make sure the test work

chore: remove flaky test

---

apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/getTwapFormState.test.ts
apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/getTwapFormState.tsx

The banner sometimes is displayed when the buy token is not selected.
1. Select tokens pair
2. Set sell amount less than threshold ($5000 for mainnet)
3. Change `appUrl` value in URL to `http://localhost:3000/#/100/swap/WXDAI/_` and navigate
4. Navigate to advanced orders

fix(twap): display "Minimum sell size" banner only when there is a buy amount

---

apps/cowswap-frontend/src/legacy/hooks/useENSAvatar.ts

Attempt to fix user reported error
This fix parts from the assumption that the ens NFT avatar is passing a bad value onto a BigNumber constructor.
Unsure, as I have not been able to reproduce it yet
*Update*: User confirmed it fixes the problem \o/
User's setup:
- Brave + MM + Ledger, with ens name and ERC721 set as avatar
- User also tried on Chrome + Rabby + Ledger and faced the same issue
User's avatar is set to `http://eip155:1/erc721:0xed5af388653567af2f388e6224dc7c4b3241c544/0000` (replaced the actual id with `0000` to preserve user's identity)
The hooks that processes the avatar URL is not expecting an url in this format https://github.com/cowprotocol/cowswap/blob/76c1c7c9d1c41934eb8b9762d00389b4917616b4/apps/cowswap-frontend/src/legacy/hooks/useENSAvatar.ts#L78C1-L78C1
When …

fix: handle error in case erc1155 id cannot be converted to BigNumber

---

.github/workflows/ci.yml
.github/workflows/deployment.yml

Currently, we run Cypress/Unit tests/Lint on every deployment on dev/barn/staging/prod.
It seems unreasonable, all those steps we need only for PRs.

ci: split PR ci and deployment to dev/barn/staging/prod

---

apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
apps/cowswap-frontend/src/legacy/state/orders/hooks.ts
apps/cowswap-frontend/src/legacy/state/orders/updaters/PendingOrdersUpdater.ts
apps/cowswap-frontend/src/legacy/state/orders/updaters/SpotPricesUpdater.ts

Accidentally found that we do lots of excessive `native_price` requests.
1. `useCombinedPendingOrders` didn't filter orders by the current account, so we updated orders from other accounts
2. `SpotPricesUpdater` didn't check `isWindowVisible` inside of the interval calls
Another problem was found in `PendingOrdersUpdater`.
Here we used `isUpdating` ref to prevent updating while there is another pending update.
But, we run two intervals for limit and market orders.
So, when market orders are updating in progress we can't update limit orders and the opposite.
1. Create 2 orders from account 0x00001 and keep them pending
2. Switch to account 0x00002 where no pending accounts
3. Monitor network for periodical `native_price` requests

fix: update only current account pending orders

---

apps/cowswap-frontend/src/common/hooks/useApproveState.ts
apps/cowswap-frontend/src/utils/fractionUtils.ts

Context:
https://cowservices.slack.com/archives/C0361CDG8GP/p1693391059969019
This change doesn't fix the cause of the problem, but it allows to get rid of the problem just be page refreshing.
I wasn't able to reproduce it, but most likely the frontend didn't receive an event about approval tx mining.

fix(trade): check allowance before pending tx for approval state

---

.gitignore
README.md
apps/cowswap-frontend/vite.config.ts
package.json
yarn.lock

Adds the bundle analyse tool from vite
You can run it by executing:
```
ANALYZE_BUNDLE=true ANALYZE_BUNDLE_TEMPLATE=sunburst yarn build
```
Options: "sunburst" | "treemap" | "network" | "raw-data" | "list"
Example on `sunburst`:

feat: generate the analyze bundle for vite

---

apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdAmount.ts

Just forgot to change the default isLoading value 🤦‍♂️
>one thing I noticed is that now when I pick both tokens but without inserting any amount, the price impact status is forever loading

chore: fix DEFAULT_USD_AMOUNT_STATE value

---

apps/cowswap-frontend/.env
apps/cowswap-frontend/src/cowSdk.ts

@mfw78 is going to make a `docker compose` setup with the set of services: frontend, backend, etc.
For this purpose, we need the possibility to specify custom URLs for order-book API.

chore: set order-book API urls from env file if present

---

apps/cowswap-frontend/src/cowSdk.ts

Fix for major issue #1 reported on https://github.com/cowprotocol/cowswap/issues/3105
When order book api urls are use in the constructor, it takes precedence over command overrides:
https://github.com/cowprotocol/cow-sdk/blob/28d42f0af0bdadacf05d18fa295834e2fd7657e1/src/order-book/api.ts#L399
Thus, when querying for `prod` orders (a MUST for TWAP on non-prod envs), the barn endpoint was being queried instead.
Which resulted in the parts info never being fetched.
1. Load app inside the Safe
2. Place a TWAP order
* Parts info should load/update

fix(twap): load TWAP part details

---

apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
apps/cowswap-frontend/src/modules/twap/hooks/useTwapWarningsContext.ts

Fix #3 from `Medium` section in https://github.com/cowprotocol/cowswap/issues/3105
During [the refactoring](https://github.com/cowprotocol/cowswap/pull/3074) I lost conditions for price impact warning.
Moved them back.
1. Unknown price impact warning displaying in TWAP
2. Unknown price impact warning displaying in Limit orders

fix(price-impact): display unknown price impact warning only when there is no data

---

apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
apps/cowswap-frontend/src/legacy/state/swap/reducer.ts
apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts

Fixed #5 from `Medium` section in https://github.com/cowprotocol/cowswap/issues/3105
1. On Swap page select WETH -> USDC on Mainnet
2. Change network to Goerli
The bug was introduced in https://github.com/cowprotocol/cowswap/pull/3095

fix(swap): reset state after network changes

---

apps/cowswap-frontend/src/api/gnosisProtocol/api.ts
apps/cowswap-frontend/src/api/gnosisProtocol/errors/QuoteError.ts
apps/cowswap-frontend/src/common/hooks/useNeedsApproval.ts
apps/cowswap-frontend/src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
apps/cowswap-frontend/src/legacy/state/price/updater.ts
apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/utils/getOrderParams.ts
apps/cowswap-frontend/src/modules/tokens/hooks/useEnoughBalance.ts
apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
apps/cowswap-frontend/src/modules/tradeQuote/hooks/useQuoteParams.ts
apps/cowswap-frontend/src/utils/isEnoughAmount.ts

Handle the `UNKNOWN` state for the check that verifies if the user has enough balance (used for quotes)
The app will need to know the balance of the user to decide if its using verified quotes or not. 
The balance/allowance is fetched in an async call. Meaning that we can be in a state where we don't know if we have the balance or not. 
The app was defaulting to "Yes, it has balance" if we were not sure.
See image below:
Now we handle the undefined case, so we don't use `verified` quotes:
I saw we were, in some cases making a request with the same sell token and buy token.
Its only temporal, probably due two the app being on a loading state. We will need to improve this part. 
I added a small improvement, so we just don't query the API in this case …

chore: allow enough balance check to return unknown state

---

apps/cowswap-frontend/src/legacy/state/orders/consts.ts
apps/cowswap-frontend/src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts

This PR reduces drastically the number of quotes we do. 
**Why?** 
Because the Unfillable Orders Updater was being "re-renderer" often. The re-rendering was making us to re-start the polling count (reset the timer), but also we were eagerly querying the quote!!
**Ok, but why so many re-renders**
It turns out, the updater had a `useEffect` who create the polling logic. This `useEffect` depended on a function to do the actual update. This function changes often. However, even if this function changes, we don't want to re-fetch again. 
**Soluton, proposed in this PR**
Instead of depending on the function itself, we depend on a reference to it.
This way, we don't need to re-render the `useEffect` and the polling works as expected. 
Before it would send hundreds of requests, specially in case …

Reduce queries from unfillable updater

---

apps/cowswap-frontend/src/common/pure/InlineBanner/banners.tsx

Addresses minor issue #1 from https://github.com/cowprotocol/cowswap/issues/3105
1. Load the Safe app
2. Pick native token as sell
* Banner should be displayed with spaces

fix: add html space chars before banner token symbols

---

apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts

Fixes https://github.com/cowprotocol/cowswap/issues/3105#issuecomment-1710104792
`useUsdPrice()` can be used several times on one page.
Before the fix, I removed a token from USD price queue even when one of the consumers unsubscribed.
After the fix I remove a token from queue only when there are no subscribers left.
1. Place swap (input is cleared)
2. Pick pair and insert data
3. Trade is filled
4. Price impact is not loaded until I change the inputs/refresh the page

fix(usd-amount): delete token from queue only if there are no subscribers left

---

apps/cowswap-frontend/src/common/hooks/useGetSurplusFiatValue.ts

Fixes `medium` issue #1 from https://github.com/cowprotocol/cowswap/issues/3105
Supersedes https://github.com/cowprotocol/cowswap/pull/3122
As far as I tested, it behaves ok.
It's not easy to reproduce.
1. Place order which will generate surplus (increase price impact to 50%)
2. Do NOT close the confirmation modal
3. Wait for it to match
* Modal is displayed WITHOUT flickering

fix: surplus modal flickering

---

apps/cowswap-frontend/src/utils/getCurrentChainIdFromUrl.test.ts
apps/cowswap-frontend/src/utils/getCurrentChainIdFromUrl.ts

Fixes https://cowservices.slack.com/archives/C0361CDG8GP/p1694180221933559
`getCurrentChainIdFromUrl()` wrongly assumed that `chain` query param is a number, but it's actually a string.
1. Open Account page with not connected wallet
2. Change network to Gnosis chain
3. Try to connect to Metamask
4. AR: App requests Metamask changing network to Mainnet
5. ER: App requests Metamask changing network to Gnosis chain or do nothing when Metamask is already connected to Gnosis chain

fix: fix mapping network name from URL query to chainId

---

apps/cowswap-frontend/src/legacy/components/analytics/events/transactionEvents.ts
apps/cowswap-frontend/src/legacy/components/analytics/hooks/useAnalyticsReporter.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/constants.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/facebook.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/index.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/linkedin.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/microsoft.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/paved.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/reddit.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/sendAllPixels.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/twitter.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/types.ts
apps/cowswap-frontend/src/legacy/components/analytics/pixel/utils.ts

Marketing is not using all these pixels, so we can remove them.
Before I do so, because they might come back, I did a preparatory PR to refactor, so we can easily remove them and add it back later. 
Also, makes it easier to maintain and control the pixels you want to use.
Now the pixels have a register function, which allows to register the sendPixel function for a set of events
There's common types that makes it easier to work with. 
It allows to send all the pixels for a certain events. It will delegate into all the registered pixels for that event.
The registration happens now in a single place, in the pixel initialization. This way is now the single point where we control the pixels we use.
I will remove in the next PR all the elements for the list, so the list is empty (to allow to …

chore: refactor and simplify pixel logic

---

apps/cowswap-frontend/src/legacy/hooks/useContract.ts
apps/cowswap-frontend/src/modules/swap/hooks/useCheckEthFlowOrderExists.ts
apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
apps/cowswap-frontend/src/modules/swap/hooks/useIsEthFlowOrderExists.ts
apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/calculateUniqueOrderId.ts
apps/cowswap-frontend/src/modules/swap/services/types.ts
libs/abis/src/abis/CoWSwapEthFlow.json
libs/abis/src/index.ts

Issue:
https://docs.google.com/document/d/1sIwsE9sCuEMZoNuBVXxpdxLrW-s-tF75AEnAMUX05I0/edit#heading=h.z0cmq0qselmp
I've checked the system based on `ethFlowInFlightOrderIdsAtom` and it works well.
Anyway, I've added an additional check with static call `orders[orderDigest]`.
I wasn't able to reproduce the issue because the previous solution worked well. But, I've mocked it and checked that the new approach with static call also works.

fix(eth-flow): additionally check eth-flow order id in smart-contract

---

apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts

Fixes `medium` issue #2.3 from https://github.com/cowprotocol/cowswap/issues/3105#issuecomment-1711691412
When one of the price token queries failed, all of them were reset.
This changes handles it invididualy.
1. On gnosis chain, get a shitcoin such as https://gnosisscan.io/token/0x0F1b956128aC17407C29C5600983C6CedF3B2820
2. Make sure you have a non-shitcoin with balance
3. Go to tokens page
* Shitcoint USD balance should not load
* Non-shitcoin USD balance should load
* You should see a debug log for the failed token

fix(usd-price): handle individual token price query failure

---

apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts
apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts

Adding 3 feature flags:
- `permitEnabledMainnet`
- `permitEnabledGnosis`
- `permitEnabledGoerli`
For testing in this PR and locally, the flag env used it `Test`
1. With the flag off for a given network, connect the app
2. Pick as sell token one that is permittable and has no allowance (you can reset it using revoke.cash)
3. Fill in the form
* Should request an approval tx
4. Turn the flag on
5. Refresh the app (for other flags it picks up after awhile without a refresh, but for this one it did not)
6. Pick the same sell token without approval
* Should not ask for approval and use the permit flow (assuming the token is permittable)

feat(permit): feature flag

---

apps/cowswap-frontend/src/modules/permit/const.ts
apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts

Since we do not have a precise method for estimating the gas for the quote, this PR adds 2 attempts to mitigate it:
1. Estimate the gas cost before sending the quote + 10%
2. Pick the max between default gas limit (80k) and the estimated gas + 10%
Here I list examples simulating the permit with the call data included in the quote and order, respectively.
It matters because each is signed with a different account, with impacts the final gas usage.
* Quote request call data: https://dashboard.tenderly.co/leandro/project/simulator/fb7d7317-07ab-4293-a3f7-ccbaed163e9e/gas-usage
* Order request call data: https://dashboard.tenderly.co/leandro/project/simulator/3e844725-e0f5-4036-abf9-9f4ae62f0ee1/gas-usage
* Order: https://dev.explorer.cow.fi/orders/0x7cf2225078f92f34bd87e2bb8bd2fe1a874ace9b130 …

feat(permit): better gas limit estimation

---

apps/cowswap-frontend/src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
apps/cowswap-frontend/src/modules/twap/services/createTwapOrderTxs.ts

Context: https://cowservices.slack.com/archives/C035N0YEB6J/p1695313030829809
Currently, TWAP orders are created with a limited approve amount (sell token amount). It creates some problems, so we need to make approves with "infinite" amounts.
1. Create a TWAP order with a sell token with 0 allowance amount
2. Wait until the order gets filled
Example of tx: https://goerli.etherscan.io/tx/0xbf20e4c60a56cc4ebea65a73b6c9814cfd0110354f27c9fda7c19bfcc2cd4a04

fix(twap): approve infinite amount

---

apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts
apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts
apps/cowswap-frontend/src/modules/permit/utils/getPermitDeadline.ts
apps/cowswap-frontend/src/modules/permit/utils/getPermitUtilsInstance.ts

Updates outdated permits based on permit nonce at order placement time.
Should no longer need to reset the local storage.
Not yet tested on limit orders, might not work as expected. Will do that next.
1. Load the app in goerli or mainnet (gchain not yet sorted out)
2. Pick as sell token a permittable token, for which you have no allowance set yet
3. Sell it
* Should be requested to sign the allowance msg. **Keep track of the `nonce` for later**
* Should then be prompted to sign the order
* Order should be accepted by the backend
* If executed, allowance should be set to infinite
4. Reset token allowance
5. Repeat steps 1 to 3
* Result should be the same, including being requested to sign the allowance msg
* Nonce in the signature request should be bumped
If you ever need to test again the …

feat(permit): update outdated permits

---

apps/cowswap-frontend/src/mocks/tradeStateMock.ts
apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
apps/cowswap-frontend/src/modules/permit/index.ts
apps/cowswap-frontend/src/modules/permit/types.ts
apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts

Add permit support to `fill or kill` limit orders
- Warning for out of allowance is not yet updated with permit!
- ⚠️ `Partial fills` not supported!!!
1. On LIMIT, pick a permittable token as sell
2. Disable `partial fills`
3. Select an amount for which it's not approved
* Approval button should not be displayed
4. Place limit order
* Should be prompted to sign a permit
* After signing the permit, should be prompted for the order signature as usual
* Once executed, token allowance should be set to infinite

feat(permit): limit orders

---

apps/cowswap-frontend/src/legacy/hooks/useFetchListCallback.ts

Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1695653516539379
`useFetchListCallback` works very inefficiently in terms of Infura consumption, on every page load it does requests to resolve hashes of ENS names of tokens lists.
I just hardcoded hashes to avoid excessive Infura requests.
Checked for all networks, we actually use them only for mainnet.
Before (**56 requests**):
After (**20 requests**):
1. Open dapp
2. Open dev tools with network tab

fix: don't fetch tokens list ens hashes

---

.github/workflows/vercel.yml
README.md
apps/cowswap-frontend/.env
apps/cowswap-frontend/src/legacy/constants/networks.ts

Introduce the possibility to define your own RPC nodes.
Before, you could only define your own INFURA key. So it was assumed you need to use infura for the RPC nodes.
This PR gives as an alternative, the possibility to define the RPC nodes.
It adapts also the README (it was outdated with some old env vars), and add the new ones.
You can test locally. Review I didn't mess up with the setup, and lastly check it in the preview (should use NodeReal now)
DEMO: https://swap-dev-git-allow-to-change-rpc-nodes-cowswap.vercel.app/

feat: allow to change rpc nodes

---

apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersDerivedState.ts
apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitOrdersDerivedState.ts
apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
apps/cowswap-frontend/src/modules/permit/const.ts
apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts
apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
apps/cowswap-frontend/src/modules/trade/hooks/useDerivedTradeState.ts
apps/cowswap-frontend/src/modules/trade/hooks/useTradeTypeInfo.ts
apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts
apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
apps/cowswap-frontend/src/modules/twap/services/createTwapOrderTxs.test.ts

Closes #3153
Disabling permit/quote based on order type
⚠️ This PR disables PERMIT for LIMIT (until backend is sorted) ⚠️ 
1. On SWAP, pick a token that is permittable (COW or UNI on Goerli for example)
2. Make sure you have no allowance for it (revoke.cash)
3. Fill the form with the buy token and the amount
* Should not show allowance button
4. Switch to LIMIT, with the same parameters
* Should show allowance button
5. Go back to SWAP and place the order
* Should prompt for permit signature
* Placed order should contain permit hooks data
6. Once traded, head to LIMIT with the same sell token
* Now that the token has been approved on SWAP, there should not be a allowance button
7. Place the LIMIT order
* Placed order should NOT contain permit hooks data
* TWAP should behave the same as …

feat(permit): quote by order type

---

apps/cowswap-frontend/src/common/containers/PermitModal/index.tsx
apps/cowswap-frontend/src/common/pure/Modal/index.cosmos.tsx
apps/cowswap-frontend/src/common/pure/Modal/index.tsx
apps/cowswap-frontend/src/common/pure/NewModal/index.cosmos.tsx
apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
apps/cowswap-frontend/src/common/pure/PermitModal/index.cosmos.tsx
apps/cowswap-frontend/src/common/pure/PermitModal/index.tsx
apps/cowswap-frontend/src/common/pure/Stepper/index.tsx
apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/index.tsx
apps/cowswap-frontend/src/legacy/components/swap/ConfirmSwapModal/index.tsx
apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
apps/cowswap-frontend/src/mocks/tradeStateMock.ts
apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
apps/cowswap-frontend/src/modules/permit/index.ts
apps/cowswap-frontend/src/modules/permit/types.ts
apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
apps/cowswap-frontend/src/modules/swap/hooks/useSwapConfirmManager.ts
apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
apps/cowswap-frontend/src/modules/swap/services/types.ts
apps/cowswap-frontend/src/modules/swap/state/swapConfirmAtom.ts
libs/ui/src/pure/TokenAmount/index.tsx
package.json

Fixes #3145 
Add the new permit modal to SWAP (LIMIT will come in another PR)
https://github.com/cowprotocol/cowswap/assets/43217/38f28429-459f-41d5-9825-95ef90a159b7
It even [has cosmos](https://swap-dev-git-permit-3145modals-cowswap.vercel.app/cosmos/?fixtureId=%7B%22path%22%3A%22src%2Fcommon%2Fpure%2FPermitModal%2Findex.cosmos.tsx%22%2C%22name%22%3A%22Pending+permit+signature%22%7D)!
Styles might need some work
1. Pick a permittable token to sell, make sure there's no allowance
2. Using non-expert mode, confirm the swap
* Should show the new modal in the step 1 while the permit signature is requested in the wallet
3. Sign the approval
* Should show the new modal in the step 2 while the order signature is requested in the wallet
4. Sign the order
* Should show the regular modal
5. Place …

feat(permit): modals SWAP

---

apps/cowswap-frontend/src/common/constants/theme.ts
apps/cowswap-frontend/src/common/pure/Modal/index.tsx
apps/cowswap-frontend/src/common/pure/Modal/styled.tsx
apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
apps/cowswap-frontend/src/common/pure/PermitModal/index.cosmos.tsx
apps/cowswap-frontend/src/common/pure/PermitModal/index.tsx
apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/index.tsx
apps/cowswap-frontend/src/legacy/theme/baseTheme.tsx
apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
apps/cowswap-frontend/src/modules/permit/const.ts
apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.tsx
apps/cowswap-frontend/src/modules/trade/hooks/useTradeConfirmActions.ts
apps/cowswap-frontend/src/modules/trade/state/tradeConfirmStateAtom.ts

Fixes https://github.com/cowprotocol/cowswap/issues/3145
Follow up to https://github.com/cowprotocol/cowswap/pull/3158
https://github.com/cowprotocol/cowswap/assets/43217/0e13ba7e-61e5-49f2-b77a-de7b3bd4ab73
Permit for LIMIT turned on for testing.
Partial fills might not work.
1. Pick a permittable token to sell, make sure there's no allowance
2. On LIMIT, using non-expert mode, confirm the order
* Should show the new modal in the step 1 while the permit signature is requested in the wallet
3. Sign the approval
* Should show the new modal in the step 2 while the order signature is requested in the wallet
4. Sign the order
* Should show the regular modal
5. Place an order without permit
* Should show the old modal
6. Use a non-permit token that needs approval
* Approval button should be …

feat(permit): modals LIMIT

---

apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts

Fixes #3207 
Disable permit for SC wallets
1. With a SC wallet, pick as sell a permittable token on Goerli or Mainnet
2. Make sure there's no allowance for it
3. Place a sell order
* If it's a Safe wallet, you'll be able to bundle the approval in one go
* Otherwise, you'll have to send an approval tx, then place the order
4. Open the placed order in the explorer
* It should not contain hook data in the appData field
5. Now with an EOA wallet, repeat the process (sell permittable token, no allowance etc, etc)
* Permit flow should work as usual

feat(permit): disable permit for SC wallets

---

apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts
apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/index.cosmos.tsx
libs/common-const/src/common.ts

Fixes #3218
The problem was in `ExpiredOrdersUpdater`, it was updating only orders created within the last 15 minutes, obviously, no one expired eth-flow order doesn't match this condition.
1. Create an eth-flow order that won't be filled (I created sell 0,0009 ETH for USDC on Mainnet)
2. Wait until the order become expired
3. Open activities modal

fix(eth-flow): update refund info for expired orders

---

apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx

1. Open https://dev.swap.cow.fi/#/1/swap/SLP/COW
2. TWAP suggestion banner should contain a link with proper amounts

fix(swap): don't crash app when token decimals eq 0

---

apps/cowswap-frontend/src/modules/trade/updaters/RecipientAddressUpdater.tsx

Swap page is reset when fill in the Recipient field on the Swap page with an ENS name

fix(swap): don't reset swap form on recipient ens input

---

apps/cowswap-frontend/src/modules/permit/const.ts
apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
apps/cowswap-frontend/src/modules/permit/types.ts
apps/cowswap-frontend/src/modules/permit/utils/buildPermitCallData.ts
apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts
apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts
libs/common-const/src/tokens.ts

Fixes #3148
Make USDC on mainnet permittable \o/
(And any other token that has a different `version`)
There are 3 pending issues:
1. Clear permit cache
2. Load the app with USDC already selected as sell token (https://swap-dev-git-permit-3148usdc-mainnet-cowswap.vercel.app/#/1/swap/USDC)
3. Whatever USDC token instance found, it comes with the token name as `USD//C`, different from contract's `USD Coin`
4. That leads to an invalid signature
1. Clear permit cache
2. Pick DAI as sell token
3. Not recognized as permittable
The `version` fetched  is `2` 
While the value when looking at [etherescan](https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f#readContract) is `1` 
Not sure this issue is only for DAI or for any DAI like token
Estimated fee for the quote is much lower …

fix(permit): add support for usdc mainnet

---

apps/cowswap-frontend/vite.config.ts
package.json

Bring back IPFS deployment!
We lost it:
We have it back!

Deploy to ipfs

---

apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts
apps/cowswap-frontend/src/modules/permit/hooks/useGetPermitInfo.ts
apps/cowswap-frontend/src/modules/permit/utils/buildPermitCallData.ts
apps/cowswap-frontend/src/modules/permit/utils/fixTokenName.ts

Fixes #3245
Apply the same logic used to check a token is permittable to check pending permits are still valid.
1. Make sure there's no USDC approval on mainnet
2. Place a SELL LIMIT order of USDC with a higher price than market (just so the order is not instantly matched)
3. Wait ~1min until the updater kicks in
* There should NOT be a warning about missing approval

fix(permit): usdc limit orders warning

---

apps/cowswap-frontend/src/common/updaters/FeesUpdater.ts

Reference: https://cowservices.slack.com/archives/C036MD8ADMG/p1697637629280439
The problem:
Once a token is marked as unsupported it will be in this state forever (until you clean your localStorage).
Of course, some tokens might become supported and we should handle this case.
1. Open Swap page with 1 WETH -> EURe
2. Run `addUnsupportedToken({chainId: 1, address: '0x3231Cb76718CDeF2155FC47b5286d82e6eDA273f', dateAdded: Date.now()})` in console
3. Wait ~1 minute

fix(swap): periodically refresh unsupported tokens state

---

apps/cowswap-frontend/.env
apps/cowswap-frontend/.env.production
libs/common-utils/.env

Replaces an old default infura key we don't control anymore. I think is from Gnosis.
Adds our own, which has a max number of requests, and a ratelimit. 
Just check its using the good one now (see infura key --> search for "public" one)

chore: replace rpc to rate-limited one

---

apps/cowswap-frontend/src/common/hooks/useAnalyticsReporter.ts
apps/cowswap-frontend/src/modules/appData/hooks.ts
apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetMetaData.ts
apps/cowswap-frontend/src/modules/injectedWidget/index.ts
libs/analytics/src/provider/index.ts
libs/analytics/src/types.ts

1. Put injected widget `appId` to `appData` as an app code
2. Put injected widget `appId` to google analytics dimension

feat(widget): google analytics dimension for injected widget app id

---

.github/workflows/ci.yml
.github/workflows/publish.yml

Adding a manual publish package action.
Right now, only `permit-utils` lib is publishable.
Was not able to test it manually.
Also not testable in the PR as it'll need to be merged to `develop` first.

feat(permit): add publish package action

---

apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/styled.ts

After merging the tokens refactoring, one of Michel's changes related to Widget is lost.
The list of favourite tokens should be displayed as list instead of grid.

fix(tokens): display favourite tokens as list

---

apps/cowswap-frontend/src/modules/tokensList/containers/ManageTokens/styled.ts
libs/tokens/src/state/tokens/allTokensAtom.ts
libs/tokens/src/utils/lowerCaseTokensMap.ts

There are two fixes in this PR:
1. Used added tokens may contain tokens with mixedCased addresses and it causes token duplicates.
2. When the list of user-added tokens is too long, it goes out of the container.
The state file.
[todo-1 (1).json](https://github.com/cowprotocol/cowswap/files/13201421/todo-1.1.json)
1. Open Dapp from this PR
2. Clean all browser data for this URL: Console -> Application -> Storage -> "Clear site data"
3. Copy the content of the file above and run in the console: `var state = <PUT_THE_FILE_CONTENT>`, press Enter
4. Run the code in the console: `localStorage.clear(); var stateObj = JSON.parse(state); Object.keys(stateObj).forEach(key => localStorage.setItem(key, stateObj[key]))`
5. Reload the page
6. Open user-added tokens list

fix(tokens): lowercase tokens addresses in map to avoid duplicates

---

apps/cowswap-frontend/.env
apps/cowswap-frontend/src/modules/appData/utils/fullAppData.spec.ts
apps/cowswap-frontend/src/modules/appData/utils/fullAppData.ts
libs/common-utils/src/environments.ts

Follow up on https://github.com/cowprotocol/cowswap/pull/3301#discussion_r1377406352
This PR adds some unit tests to enforce we don't forget to update the appData to the latest version, and we make sure the format is correct.
The tests will fail if its not in the right version (or they don't pass the validation)
Its easy to spot when we have an issue with the appData:
All the test pass now:

feat: ensure appData is always correct
